/**
 * Reviewed Unicorn policy.
 *
 * Unicorn's recommended preset is not a stable policy boundary: major releases
 * can add many newly recommended rules. Keep the repository's accepted policy
 * explicit so upgrading the plugin updates rule implementations without
 * silently enabling a repository-wide style migration.
 */
import unicorn from "eslint-plugin-unicorn";
import type { TSESLint } from "@typescript-eslint/utils";

export const reviewedUnicornRuleNames = [
  "catch-error-name",
  "consistent-assert",
  "consistent-date-clone",
  "consistent-empty-array-spread",
  "consistent-existence-index-check",
  "consistent-function-scoping",
  "consistent-template-literal-escape",
  "dom-node-dataset",
  "empty-brace-spaces",
  "error-message",
  "escape-case",
  "expiring-todo-comments",
  "explicit-length-check",
  "filename-case",
  "import-style",
  "isolated-functions",
  "name-replacements",
  "new-for-builtins",
  "no-abusive-eslint-disable",
  "no-accessor-recursion",
  "no-anonymous-default-export",
  "no-array-callback-reference",
  "no-array-method-this-argument",
  "no-array-reduce",
  "no-array-reverse",
  "no-array-sort",
  "no-await-expression-member",
  "no-await-in-promise-methods",
  "no-console-spaces",
  "no-document-cookie",
  "no-empty-file",
  "no-for-each",
  "no-for-loop",
  "no-immediate-mutation",
  "no-instanceof-builtins",
  "no-invalid-fetch-options",
  "no-invalid-remove-event-listener",
  "no-lonely-if",
  "no-magic-array-flat-depth",
  "no-named-default",
  "no-negated-condition",
  "no-negation-in-equality-check",
  "no-nested-ternary",
  "no-new-array",
  "no-new-buffer",
  "no-null",
  "no-object-as-default-parameter",
  "no-process-exit",
  "no-single-promise-in-promise-methods",
  "no-static-only-class",
  "no-thenable",
  "no-this-assignment",
  "no-typeof-undefined",
  "no-unnecessary-array-flat-depth",
  "no-unnecessary-array-splice-count",
  "no-unnecessary-await",
  "no-unnecessary-polyfills",
  "no-unnecessary-slice-end",
  "no-unreadable-array-destructuring",
  "no-unreadable-iife",
  "no-useless-collection-argument",
  "no-useless-error-capture-stack-trace",
  "no-useless-fallback-in-spread",
  "no-useless-iterator-to-array",
  "no-useless-length-check",
  "no-useless-promise-resolve-reject",
  "no-useless-spread",
  "no-useless-switch-case",
  "no-useless-undefined",
  "no-zero-fractions",
  "number-literal-case",
  "numeric-separators-style",
  "prefer-add-event-listener",
  "prefer-array-find",
  "prefer-array-flat",
  "prefer-array-flat-map",
  "prefer-array-index-of",
  "prefer-array-some",
  "prefer-at",
  "prefer-bigint-literals",
  "prefer-blob-reading-methods",
  "prefer-class-fields",
  "prefer-classlist-toggle",
  "prefer-code-point",
  "prefer-date-now",
  "prefer-default-parameters",
  "prefer-dom-node-append",
  "prefer-dom-node-remove",
  "prefer-dom-node-text-content",
  "prefer-event-target",
  "prefer-export-from",
  "prefer-global-this",
  "prefer-includes",
  "prefer-keyboard-event-key",
  "prefer-logical-operator-over-ternary",
  "prefer-math-min-max",
  "prefer-math-trunc",
  "prefer-modern-dom-apis",
  "prefer-modern-math-apis",
  "prefer-module",
  "prefer-native-coercion-functions",
  "prefer-negative-index",
  "prefer-node-protocol",
  "prefer-number-properties",
  "prefer-object-from-entries",
  "prefer-optional-catch-binding",
  "prefer-prototype-methods",
  "prefer-query-selector",
  "prefer-reflect-apply",
  "prefer-regexp-test",
  "prefer-response-static-json",
  "prefer-set-has",
  "prefer-set-size",
  "prefer-simple-condition-first",
  "prefer-single-call",
  "prefer-spread",
  "prefer-string-raw",
  "prefer-string-replace-all",
  "prefer-string-slice",
  "prefer-string-starts-ends-with",
  "prefer-string-trim-start-end",
  "prefer-structured-clone",
  "prefer-switch",
  "prefer-ternary",
  "prefer-top-level-await",
  "prefer-type-error",
  "prefer-unicode-code-point-escapes",
  "relative-url-style",
  "require-array-join-separator",
  "require-module-attributes",
  "require-module-specifiers",
  "require-number-to-fixed-digits-argument",
  "switch-case-braces",
  "switch-case-break-position",
  "template-indent",
  "text-encoding-identifier-case",
  "throw-new-error",
] as const;

const reviewedRules = Object.fromEntries(
  reviewedUnicornRuleNames.map((ruleName) => [`unicorn/${ruleName}`, "error"]),
);

export const reviewedUnicornConfig: TSESLint.FlatConfig.Config = {
  ...unicorn.configs["flat/recommended"],
  name: "unicorn/reviewed-recommended",
  rules: {
    // These core rules are replaced by the corresponding reviewed Unicorn
    // rules, matching the v64 preset behavior.
    "no-negated-condition": "off",
    "no-nested-ternary": "off",
    ...reviewedRules,
  },
};
