import { z } from "zod";

/**
 * A precise pick of ONE subtitle track (from `/stream subtitles`'s picker), as opposed to
 * `SubtitlePref.language` which is a ranking preference. Never carries a fetchable URL — yt-dlp's
 * enumerated subtitle URLs are signed/time-limited, so a `ytdlp` ref is re-downloaded fresh
 * (pinned to `lang`+`autoGenerated`) at apply time instead of reusing anything from enumeration.
 */
export const SubtitleTrackRefSchema = z.discriminatedUnion("kind", [
  z.strictObject({ kind: z.literal("off") }),
  z.strictObject({ kind: z.literal("sidecar"), file: z.string().min(1) }),
  z.strictObject({
    kind: z.literal("embedded"),
    subtitleIndex: z.number().int().nonnegative(),
    codec: z.string().min(1),
  }),
  z.strictObject({
    kind: z.literal("ytdlp"),
    lang: z.string().min(1),
    autoGenerated: z.boolean(),
  }),
]);
export type SubtitleTrackRef = z.infer<typeof SubtitleTrackRefSchema>;

/**
 * Per-request subtitle preference, set from the `/stream play` `subtitles`/`sublang` options (or
 * `/stream subtitles`'s track picker). `enabled`/`language` are ranking-based fallbacks:
 * `enabled === undefined` falls back to `config.subtitles.enabled`, and `language === undefined`
 * falls back to `config.subtitles.languages`. `trackRef`, when present, names an EXACT track and
 * bypasses ranking entirely (see `resolveSubtitleForFile`/`resolveSubtitleForYtdlp`).
 */
export const SubtitlePrefSchema = z.strictObject({
  enabled: z.boolean().optional(),
  language: z.string().min(1).optional(),
  trackRef: SubtitleTrackRefSchema.optional(),
});

export type SubtitlePref = z.infer<typeof SubtitlePrefSchema>;

/**
 * A requested playback source, before resolution. `file` is a concrete local path; `url` is any
 * yt-dlp-supported link; `search` is a yt-dlp search query resolved to a video at play time. Each
 * variant may carry an optional per-request subtitle preference.
 */
export const SourceSchema = z.discriminatedUnion("kind", [
  z.strictObject({
    kind: z.literal("file"),
    path: z.string().min(1),
    title: z.string().min(1),
    subtitles: SubtitlePrefSchema.optional(),
  }),
  z.strictObject({
    kind: z.literal("url"),
    url: z.url(),
    subtitles: SubtitlePrefSchema.optional(),
  }),
  z.strictObject({
    kind: z.literal("search"),
    query: z.string().min(1),
    subtitles: SubtitlePrefSchema.optional(),
  }),
]);

export type Source = z.infer<typeof SourceSchema>;

/** A short human label for a source, for queue/status embeds. */
export function sourceLabel(source: Source): string {
  switch (source.kind) {
    case "file": {
      return source.title;
    }
    case "url": {
      return source.url;
    }
    case "search": {
      return source.query;
    }
  }
}

/**
 * A stable identity string for a source, distinguishing WHICH item is playing regardless of its
 * display title. Used by `/stream subtitles` to detect that playback advanced to a *different* item
 * during the picker's (up to 2-minute) wait — a same-title-but-different-source swap that a title
 * comparison alone would miss. The `kind:` prefix keeps two variants from ever colliding (so it also
 * subsumes the source-kind check), and the concrete locator (path/url/query) distinguishes two files
 * or URLs that happen to share a title. Ignores the per-request subtitle preference on purpose: the
 * point is to identify the underlying item, not its current subtitle setting.
 */
export function sourceIdentity(source: Source): string {
  switch (source.kind) {
    case "file":
      return `file:${source.path}`;
    case "url":
      return `url:${source.url}`;
    case "search":
      return `search:${source.query}`;
  }
}

/** Attach a subtitle preference to a resolved source, preserving its discriminant. */
export function withSubtitles(
  source: Source,
  subtitles: SubtitlePref | undefined,
): Source {
  switch (source.kind) {
    case "file":
      return { ...source, subtitles };
    case "url":
      return { ...source, subtitles };
    case "search":
      return { ...source, subtitles };
  }
}
