import { z } from "zod";
import {
  MediaModeSchema,
  type MediaMode,
} from "@shepherdjerred/streambot/sources/media-kind.ts";

/**
 * A precise pick of ONE subtitle track (from `/stream subtitles`'s picker), as opposed to
 * `SubtitlePref.language` which is a ranking preference. Never carries a fetchable URL — yt-dlp's
 * enumerated subtitle URLs are signed/time-limited, so a `ytdlp` ref is re-downloaded fresh
 * (pinned to `lang`+`autoGenerated`) at apply time instead of reusing anything from enumeration.
 */
export const SubtitleTrackRefSchema = z.discriminatedUnion("kind", [
  z.strictObject({ kind: z.literal("off") }),
  z.strictObject({ kind: z.literal("sidecar"), file: z.string().min(1) }),
  z.strictObject({
    kind: z.literal("embedded"),
    subtitleIndex: z.number().int().nonnegative(),
    codec: z.string().min(1),
  }),
  z.strictObject({
    kind: z.literal("ytdlp"),
    lang: z.string().min(1),
    autoGenerated: z.boolean(),
  }),
]);
export type SubtitleTrackRef = z.infer<typeof SubtitleTrackRefSchema>;

/**
 * Per-request subtitle preference, set from the `/stream play` `subtitles`/`sublang` options (or
 * `/stream subtitles`'s track picker). `enabled`/`language` are ranking-based fallbacks:
 * `enabled === undefined` falls back to `config.subtitles.enabled`, and `language === undefined`
 * falls back to `config.subtitles.languages`. `trackRef`, when present, names an EXACT track and
 * bypasses ranking entirely (see `resolveSubtitleForFile`/`resolveSubtitleForYtdlp`).
 */
export const SubtitlePrefSchema = z.strictObject({
  enabled: z.boolean().optional(),
  language: z.string().min(1).optional(),
  trackRef: SubtitleTrackRefSchema.optional(),
});

export type SubtitlePref = z.infer<typeof SubtitlePrefSchema>;

/**
 * A requested playback source, before resolution. `file` is a concrete local path; `url` is any
 * yt-dlp-supported link; `search` is a yt-dlp search query resolved to a video at play time. Each
 * variant may carry a per-request subtitle preference and a `mode` override (music vs video) for
 * when the resolve-time classifier gets an item wrong.
 *
 * `mode` uses `.default("auto")` rather than `.optional()` deliberately. The default normalizes the
 * absent case exactly once, here, so the in-memory {@link Source} type is *total*: nothing
 * downstream ever writes `source.mode ?? "auto"`, and no consumer can forget to. The cost is that
 * every hand-written `Source` literal must now name a mode, which the compiler enforces.
 *
 * `mode` is OPTIONAL rather than defaulted. Absent and `"auto"` are indistinguishable everywhere
 * downstream — `classifyMediaKind` branches only on `"music"`/`"video"` — so a default would buy no
 * totality worth having while forcing an explicit `mode` onto every `Source` literal in `src/` and
 * `e2e/`. It also keeps `withMode` mirroring `withSubtitles` immediately below it, which takes
 * `SubtitlePref | undefined` for exactly the same reason.
 *
 * This is NOT a schema version bump. `PersistedQueuedSchema`/`PersistedCurrentSchema`
 * (`state/persistence.ts`, still `version: z.literal(2)`) and the history row's `source_json`
 * (`history/media-history.ts`) both embed this schema verbatim, so an existing v2 state file simply
 * lacks the key and parses as `undefined`. Bumping the version would instead discard every
 * in-flight resume across the deploy, for nothing.
 */
export const SourceSchema = z.discriminatedUnion("kind", [
  z.strictObject({
    kind: z.literal("file"),
    path: z.string().min(1),
    title: z.string().min(1),
    subtitles: SubtitlePrefSchema.optional(),
    mode: MediaModeSchema.optional(),
  }),
  z.strictObject({
    kind: z.literal("url"),
    url: z.url(),
    subtitles: SubtitlePrefSchema.optional(),
    mode: MediaModeSchema.optional(),
  }),
  z.strictObject({
    kind: z.literal("search"),
    query: z.string().min(1),
    subtitles: SubtitlePrefSchema.optional(),
    mode: MediaModeSchema.optional(),
  }),
]);

export type Source = z.infer<typeof SourceSchema>;

/** A short human label for a source, for queue/status embeds. */
export function sourceLabel(source: Source): string {
  switch (source.kind) {
    case "file": {
      return source.title;
    }
    case "url": {
      return source.url;
    }
    case "search": {
      return source.query;
    }
  }
}

/**
 * A stable identity string for a source, distinguishing WHICH item is playing regardless of its
 * display title. Used by `/stream subtitles` to detect that playback advanced to a *different* item
 * during the picker's (up to 2-minute) wait — a same-title-but-different-source swap that a title
 * comparison alone would miss. The `kind:` prefix keeps two variants from ever colliding (so it also
 * subsumes the source-kind check), and the concrete locator (path/url/query) distinguishes two files
 * or URLs that happen to share a title. Ignores the per-request subtitle preference on purpose: the
 * point is to identify the underlying item, not its current subtitle setting — and ignores `mode`
 * for the same reason: music-vs-video is a setting on an item, not a different item.
 */
export function sourceIdentity(source: Source): string {
  switch (source.kind) {
    case "file":
      return `file:${source.path}`;
    case "url":
      return `url:${source.url}`;
    case "search":
      return `search:${source.query}`;
  }
}

/** Attach a subtitle preference to a resolved source, preserving its discriminant. */
export function withSubtitles(
  source: Source,
  subtitles: SubtitlePref | undefined,
): Source {
  switch (source.kind) {
    case "file":
      return { ...source, subtitles };
    case "url":
      return { ...source, subtitles };
    case "search":
      return { ...source, subtitles };
  }
}

/**
 * Attach a music/video mode override to a source, preserving its discriminant. Switched on `kind`
 * rather than spread generically for the same reason {@link withSubtitles} is: TypeScript widens a
 * spread of a discriminated union to the union of all its members, which loses the narrowing every
 * consumer of {@link Source} relies on.
 */
export function withMode(source: Source, mode: MediaMode | undefined): Source {
  switch (source.kind) {
    case "file":
      return { ...source, mode };
    case "url":
      return { ...source, mode };
    case "search":
      return { ...source, mode };
  }
}
