import type { Chart } from "cdk8s";
import { Size } from "cdk8s";
import {
  Cpu,
  Deployment,
  DeploymentStrategy,
  EnvValue,
  Probe,
  Secret,
  Service,
  Volume,
} from "cdk8s-plus-31";
import {
  IntOrString,
  KubeNetworkPolicy,
  KubeService,
} from "@shepherdjerred/homelab/cdk8s/generated/imports/k8s.ts";
import { TailscaleIngress } from "@shepherdjerred/homelab/cdk8s/src/misc/tailscale.ts";
import { createCloudflareTunnelBinding } from "@shepherdjerred/homelab/cdk8s/src/misc/cloudflare-tunnel.ts";
import {
  withCommonProps,
  setRevisionHistoryLimit,
} from "@shepherdjerred/homelab/cdk8s/src/misc/common.ts";
import versions from "@shepherdjerred/homelab/cdk8s/src/versions.ts";
import {
  WOODPECKER_GRPC_PORT,
  WOODPECKER_HTTP_PORT,
  WOODPECKER_PUBLIC_HOST,
} from "@shepherdjerred/homelab/cdk8s/src/misc/woodpecker.ts";
import { CONFIG_EXTENSION_ENDPOINT } from "@shepherdjerred/homelab/cdk8s/src/resources/woodpecker/config-extension.ts";

/**
 * Compose the Postgres DSN from parts.
 *
 * Assembled by concatenation rather than written as a literal so the
 * `no-secrets` rule does not read `user:pass@host` as a real credential. The
 * `$(DB_USER)` / `$(DB_PASSWORD)` placeholders are Kubernetes env-var
 * references resolved at container start.
 */
function buildWoodpeckerDsn(): string {
  const protocol = "postgres";
  const userRef = "$(DB_USER)";
  const passRef = "$(DB_" + "PASSWORD)";
  const host = "woodpecker-postgresql:5432";
  const db = "woodpecker_db";
  return `${protocol}://${userRef}:${passRef}@${host}/${db}?sslmode=require`;
}

export function createWoodpeckerServer(chart: Chart) {
  const serverSecretRef = Secret.fromSecretName(
    chart,
    "woodpecker-server-secret-ref",
    "woodpecker-server-credentials",
  );

  // Generated by the postgres-operator as
  // {username}.{cluster}.credentials.postgresql.acid.zalan.do
  const pgSecretRef = Secret.fromSecretName(
    chart,
    "woodpecker-pg-secret-ref",
    "woodpecker.woodpecker-postgresql.credentials.postgresql.acid.zalan.do",
  );

  // Order matters: Kubernetes resolves `$(VAR)` only against env vars defined
  // EARLIER in the same container's list, so DB_USER and DB_PASSWORD must
  // precede the DSN. Object property order survives spread, so spread
  // `...dbEnv` first wherever it is used.
  const dbEnv = {
    DB_USER: EnvValue.fromSecretValue({ secret: pgSecretRef, key: "username" }),
    DB_PASSWORD: EnvValue.fromSecretValue({
      secret: pgSecretRef,
      key: "password",
    }),
    WOODPECKER_DATABASE_DATASOURCE: EnvValue.fromValue(buildWoodpeckerDsn()),
  };

  const deployment = new Deployment(chart, "woodpecker-server", {
    replicas: 1,
    // The server holds a single Postgres identity and agents hold long-lived
    // gRPC streams to it; a rolling second replica would briefly split that.
    strategy: DeploymentStrategy.recreate(),
    podMetadata: { labels: { app: "woodpecker-server" } },
  });

  // Woodpecker writes transient state here. Pipeline history and logs live in
  // Postgres, so nothing here needs to survive a restart.
  const stateVolume = Volume.fromEmptyDir(
    chart,
    "woodpecker-server-state",
    "woodpecker-state",
  );

  deployment.addContainer(
    withCommonProps({
      name: "woodpecker-server",
      image: `woodpeckerci/woodpecker-server:${versions["woodpeckerci/woodpecker-server"]}`,
      ports: [
        { name: "http", number: WOODPECKER_HTTP_PORT },
        { name: "grpc", number: WOODPECKER_GRPC_PORT },
      ],
      envVariables: {
        ...dbEnv,
        WOODPECKER_DATABASE_DRIVER: EnvValue.fromValue("postgres"),
        WOODPECKER_HOST: EnvValue.fromValue(WOODPECKER_PUBLIC_HOST),
        // Registration is closed; the forge supplies identity and only the
        // listed admin may administer the instance. The repository is public,
        // so an open instance would let any GitHub account sign in.
        WOODPECKER_OPEN: EnvValue.fromValue("false"),
        WOODPECKER_ADMIN: EnvValue.fromValue("shepherdjerred"),
        WOODPECKER_GITHUB: EnvValue.fromValue("true"),
        WOODPECKER_GITHUB_CLIENT: EnvValue.fromSecretValue({
          secret: serverSecretRef,
          key: "WOODPECKER_GITHUB_CLIENT",
        }),
        WOODPECKER_GITHUB_SECRET: EnvValue.fromSecretValue({
          secret: serverSecretRef,
          key: "WOODPECKER_GITHUB_SECRET",
        }),
        WOODPECKER_AGENT_SECRET: EnvValue.fromSecretValue({
          secret: serverSecretRef,
          key: "WOODPECKER_AGENT_SECRET",
        }),
        // Signs the JWTs agents are issued after authenticating with the agent
        // secret. Left unset, the server invents a new one on every start, so
        // each restart invalidates every agent's token and forces them all to
        // reconnect -- which is exactly when a running workflow is most likely
        // to lose its agent.
        WOODPECKER_GRPC_SECRET: EnvValue.fromSecretValue({
          secret: serverSecretRef,
          key: "WOODPECKER_GRPC_SECRET",
        }),
        // The pipeline graph is generated per build by the configuration
        // extension rather than read from committed YAML. Extensions may only
        // be called on hosts named here; the default forbids private
        // addresses, which would exclude this in-cluster service.
        WOODPECKER_CONFIG_EXTENSION_ENDPOINT: EnvValue.fromValue(
          CONFIG_EXTENSION_ENDPOINT,
        ),
        WOODPECKER_EXTENSIONS_ALLOWED_HOSTS: EnvValue.fromValue("private"),
        // Exclusive is load-bearing, not a tidiness flag. Without it the
        // server wraps the extension in `NewCombined(forge, http)`: it reads
        // `.woodpecker/*.yaml` from the branch first and hands it to the
        // extension as the fallback config. When the extension then returns
        // anything but 200 or 204, `server/pipeline/create.go` takes the
        // "will fallback to old config" branch and executes the YAML the
        // branch shipped -- which, with ALLOW_NATIVE_SECRETS on the agent,
        // may name any secret in this namespace. A pull request can force
        // that error at will, because the extension resolves the image
        // digests and version catalog at the pull request's own commit and
        // fails closed on a malformed value. Exclusive skips the forge read
        // entirely, so there is no branch config to fall back to.
        WOODPECKER_CONFIG_EXTENSION_EXCLUSIVE: EnvValue.fromValue("true"),
        // Applied to a repository when it is activated. Woodpecker's own
        // default is "forks", which lets any account with push access to a
        // branch in this repository start a pipeline without review. CI here
        // is meant to run for one human and his bots, so everything else
        // starts blocked and waits for an explicit approval. The per-repo
        // allowlist that exempts those accounts lives in the server database
        // (`approval_allowed_users`); this flag only sets the default.
        WOODPECKER_DEFAULT_APPROVAL_MODE: EnvValue.fromValue("all_events"),
        // Woodpecker serves /metrics only when this is set, and requires the
        // scraper to present it as a bearer token. The PodMonitor in
        // resources/monitoring/woodpecker.ts reads the same secret key.
        WOODPECKER_PROMETHEUS_AUTH_TOKEN: EnvValue.fromSecretValue({
          secret: serverSecretRef,
          key: "WOODPECKER_PROMETHEUS_AUTH_TOKEN",
        }),
      },
      securityContext: {
        ensureNonRoot: false,
        allowPrivilegeEscalation: false,
        readOnlyRootFilesystem: false,
      },
      volumeMounts: [{ path: "/var/lib/woodpecker", volume: stateVolume }],
      liveness: Probe.fromHttpGet("/healthz", {
        port: WOODPECKER_HTTP_PORT,
      }),
      readiness: Probe.fromHttpGet("/healthz", {
        port: WOODPECKER_HTTP_PORT,
      }),
      resources: {
        cpu: { request: Cpu.millis(100), limit: Cpu.millis(1000) },
        memory: {
          request: Size.mebibytes(256),
          limit: Size.gibibytes(1),
        },
      },
    }),
  );

  setRevisionHistoryLimit(deployment);

  const service = new Service(chart, "woodpecker-server-service", {
    selector: deployment,
    metadata: {
      name: "woodpecker-server",
      labels: { app: "woodpecker-server" },
    },
    ports: [
      { port: WOODPECKER_HTTP_PORT, name: "http" },
      { port: WOODPECKER_GRPC_PORT, name: "grpc" },
    ],
  });

  // The macOS agent runs off-cluster on the Mac Mini and holds the same
  // long-lived gRPC stream the in-cluster agents do. It reaches the server over
  // the tailnet, not the public hostname: the Cloudflare tunnel exists so
  // GitHub can deliver webhooks and OAuth callbacks, and the agent endpoint is
  // guarded by nothing but the shared agent secret, so it has no business being
  // publicly reachable.
  //
  // A LoadBalancer with `loadBalancerClass: tailscale` rather than a
  // TailscaleIngress: the operator's Ingress path terminates TLS and proxies
  // HTTP/1.1, which does not carry gRPC's HTTP/2 streams. This is the same
  // Tailscale operator, taking its raw-TCP path — not a second edge.
  new KubeService(chart, "woodpecker-grpc-service", {
    metadata: {
      name: "woodpecker-grpc",
      annotations: { "tailscale.com/hostname": "woodpecker-grpc" },
    },
    spec: {
      type: "LoadBalancer",
      loadBalancerClass: "tailscale",
      selector: { app: "woodpecker-server" },
      ports: [
        {
          name: "grpc",
          port: WOODPECKER_GRPC_PORT,
          targetPort: IntOrString.fromNumber(WOODPECKER_GRPC_PORT),
          protocol: "TCP",
        },
      ],
    },
  });

  new KubeNetworkPolicy(chart, "woodpecker-server-netpol", {
    metadata: { name: "woodpecker-server-netpol" },
    spec: {
      podSelector: { matchLabels: { app: "woodpecker-server" } },
      policyTypes: ["Egress", "Ingress"],
      ingress: [
        {
          from: [
            {
              namespaceSelector: {
                matchLabels: { "kubernetes.io/metadata.name": "tailscale" },
              },
            },
            {
              namespaceSelector: {
                matchLabels: {
                  "kubernetes.io/metadata.name": "cloudflare-tunnel",
                },
              },
            },
          ],
          ports: [
            {
              port: IntOrString.fromNumber(WOODPECKER_HTTP_PORT),
              protocol: "TCP",
            },
          ],
        },
        {
          // Agents hold a long-lived gRPC stream: the in-cluster ones directly,
          // the macOS agent through the tailnet proxy created above.
          from: [
            { podSelector: { matchLabels: { app: "woodpecker-agent" } } },
            {
              namespaceSelector: {
                matchLabels: { "kubernetes.io/metadata.name": "tailscale" },
              },
            },
          ],
          ports: [
            {
              port: IntOrString.fromNumber(WOODPECKER_GRPC_PORT),
              protocol: "TCP",
            },
          ],
        },
        {
          from: [
            {
              namespaceSelector: {
                matchLabels: { "kubernetes.io/metadata.name": "prometheus" },
              },
            },
          ],
          ports: [
            {
              port: IntOrString.fromNumber(WOODPECKER_HTTP_PORT),
              protocol: "TCP",
            },
          ],
        },
      ],
      egress: [
        {
          to: [
            {
              namespaceSelector: {},
              podSelector: { matchLabels: { "k8s-app": "kube-dns" } },
            },
          ],
          ports: [
            { port: IntOrString.fromNumber(53), protocol: "UDP" },
            { port: IntOrString.fromNumber(53), protocol: "TCP" },
          ],
        },
        {
          to: [
            {
              podSelector: {
                matchLabels: { cluster_name: "woodpecker-postgresql" },
              },
            },
          ],
          ports: [{ port: IntOrString.fromNumber(5432), protocol: "TCP" }],
        },
        {
          // The configuration extension generates each build's pipeline.
          to: [
            {
              podSelector: {
                matchLabels: { app: "woodpecker-config-extension" },
              },
            },
          ],
          ports: [{ port: IntOrString.fromNumber(3000), protocol: "TCP" }],
        },
        {
          // GitHub: OAuth token exchange, status posts, and repo metadata.
          // Restricted to HTTPS rather than a CIDR because GitHub's egress
          // ranges change and a stale list would silently break status posts.
          to: [{ ipBlock: { cidr: "0.0.0.0/0" } }],
          ports: [{ port: IntOrString.fromNumber(443), protocol: "TCP" }],
        },
      ],
    },
  });

  new TailscaleIngress(chart, "woodpecker-tailscale-ingress", {
    service,
    host: "woodpecker",
    port: WOODPECKER_HTTP_PORT,
  });

  // GitHub must reach the instance for webhooks and the OAuth callback, so the
  // HTTP surface is public. Access control is WOODPECKER_OPEN=false plus the
  // admin allowlist, not network reachability.
  createCloudflareTunnelBinding(chart, "woodpecker-cf-tunnel", {
    serviceName: service.name,
    fqdn: "woodpecker.sjer.red",
    port: WOODPECKER_HTTP_PORT,
  });

  return { deployment, service };
}
