/** Affected packages result from change detection. */
export type AffectedPackages = {
  packages: Set<string>;
  /**
   * The seed set used to compute `packages` — the top-level package dirs whose
   * own files actually changed (before transitive closure). Carried separately
   * because some downstream gates re-expand the closure with their own graph
   * (e.g. the `bun.lock` drift gate must walk **nested** workspace manifests,
   * whereas `change-detection.transitiveClosure` only reads top-level manifests
   * and would silently miss the dpp/llm-observability case from PR #1213).
   *
   * Empty when no packages were directly changed (full build, infra-only,
   * version-bump-only, etc.).
   */
  directlyChanged: Set<string>;
  buildAll: boolean;
  homelabChanged: boolean;
  /** True when a file under `packages/homelab/src/tofu/` changed. Gates the PR tofu *plan* group specifically — narrower than `homelabChanged` so cdk8s-only homelab PRs skip the plan jobs. */
  tofuChanged: boolean;
  cooklangChanged: boolean;
  resumeChanged: boolean;
  /** True when a generator input (cdk8s versions.ts, the generate/parse scripts, or the helm-types lib) changed. Gates the `helm-types-drift-check` step so its ~24-chart network fetch only runs when the generated tree can actually change. */
  helmTypesInputsChanged: boolean;
  ciImageChanged: boolean;
  hasImagePackages: Set<string>;
  hasSitePackages: Set<string>;
  hasNpmPackages: Set<string>;
  /** True when .buildkite/ci-image/VERSION changed. Non-generated commits fail fast. */
  ciImageVersionChanged: boolean;
  /** True when only version strings changed (commit-back). Skips image builds and version-commit-back. */
  versionBumpOnly: boolean;
  /** True when the current commit is a release-please merge. Triggers prod npm publishes alongside dev. */
  releasePleaseMerge: boolean;
  /** True when HEAD has an `Auto-Generated:` trailer (bot-authored). Suppresses bot-on-bot loops by skipping version-commit-back. */
  isAutoGenerated: boolean;
};

/** A single Buildkite step. */
export type BuildkiteStep = {
  label: string;
  key: string;
  command: string;
  /**
   * Per-step agent targeting. Overrides the pipeline-level `agents.queue`
   * (which is `default` — the in-cluster agent-stack-k8s agents). Set this to
   * route a single step to a non-default queue, e.g. the `macos` queue served
   * by the Mac Mini for native Swift/Xcode builds. A step with its own
   * `agents.queue` must NOT carry the `kubernetes` plugin — it runs natively on
   * that agent (default git checkout), not through the in-cluster Dagger engine.
   */
  agents?: { queue: string };
  timeout_in_minutes?: number;
  retry?: Record<string, unknown>;
  plugins?: Record<string, unknown>[];
  depends_on?: string | string[];
  if?: string;
  soft_fail?: boolean;
  env?: Record<string, string>;
  parallelism?: number;
  concurrency?: number;
  concurrency_group?: string;
  artifact_paths?: string[];
  allow_dependency_failure?: boolean;
  priority?: number;
};

/** A Buildkite step group. */
export type BuildkiteGroup = {
  group: string;
  key: string;
  steps: BuildkiteStep[];
};

/** A wait step. */
export type BuildkiteWait = {
  wait: string;
  if?: string;
};

/** Any element in a pipeline steps array. */
export type PipelineStep = BuildkiteStep | BuildkiteGroup | BuildkiteWait;

/** The full Buildkite pipeline object. */
export type BuildkitePipeline = {
  agents: { queue: string };
  steps: PipelineStep[];
};
