/**
 * Version commit-back and release-please detection.
 *
 * These predicates classify the *reason* a build was triggered (auto-generated
 * bot commits, cooklang metadata bumps, release-please merges) so the
 * orchestrator can take the appropriate fast-track path.
 */
import { execSync } from "node:child_process";
import { REPO_ROOT } from "./shared.ts";

const CI_BASE_VERSION_BUMP_BRANCH = "chore/ci-base-version-bump-pending";
const COOKLANG_VERSION_BUMP_BRANCH = "chore/cooklang-version-bump-pending";

export const COOKLANG_VERSION_COMMIT_BACK_FILES = new Set([
  "packages/cooklang-for-obsidian/manifest.json",
  "packages/cooklang-for-obsidian/versions.json",
]);

/**
 * Package directories whose source changes warrant a cooklang plugin release.
 *
 * Only the Obsidian plugin itself — `cooklang-rich-preview/` is the rich-preview
 * Astro site and is never published as part of the Obsidian plugin release, so
 * edits there must not cut a plugin version.
 */
const COOKLANG_PACKAGE_PREFIXES = ["packages/cooklang-for-obsidian/"];

/**
 * Files under {@link COOKLANG_PACKAGE_PREFIXES} that do NOT count as plugin
 * source for the release gate. Includes the auto-bump artifacts
 * (`manifest.json` / `versions.json`) plus cog-generated docs (`_summary.md`),
 * which is rewritten weekly by the `readme-refresh-weekly` Temporal schedule
 * and would otherwise trip the gate every Monday.
 *
 * Kept separate from {@link COOKLANG_VERSION_COMMIT_BACK_FILES} so that the
 * commit-back fast-track keeps its strict "only manifest/versions" meaning.
 */
const COOKLANG_NON_SOURCE_FILES = new Set([
  ...COOKLANG_VERSION_COMMIT_BACK_FILES,
  "packages/cooklang-for-obsidian/_summary.md",
]);

// ---------------------------------------------------------------------------
// Version commit-back fast-track
// ---------------------------------------------------------------------------

/** Check if the current build is a version commit-back merge (auto-generated). */
export function isVersionCommitBack(): boolean {
  const msg = Bun.env["BUILDKITE_MESSAGE"] ?? "";
  return (
    msg.startsWith("chore: bump image versions to ") ||
    /^Merge pull request #\d+ from .+\/chore\/version-bump-/.test(msg)
  );
}

/** Check if the current build is a cooklang version commit-back. */
export function isCooklangVersionCommitBack(): boolean {
  const msg = Bun.env["BUILDKITE_MESSAGE"] ?? "";
  return (
    /^chore\(cooklang\): bump to v\d+\.\d+\.\d+/.test(msg) ||
    (/^Merge pull request #\d+ from /.test(msg) &&
      msg.includes(COOKLANG_VERSION_BUMP_BRANCH))
  );
}

export function isCooklangVersionCommitBackOnly(
  changedFiles: string[],
): boolean {
  return (
    changedFiles.length > 0 &&
    changedFiles.every((file) => COOKLANG_VERSION_COMMIT_BACK_FILES.has(file))
  );
}

/**
 * True when a real cooklang *source* file changed — a file under a cooklang
 * package that is NOT one of the auto-generated / cog-generated non-source
 * artifacts (see {@link COOKLANG_NON_SOURCE_FILES}).
 *
 * The release gate keys off this rather than "any cooklang file changed" so
 * that bot-authored manifest bumps — and infra/full builds that don't touch
 * cooklang at all — never cut a new plugin release. Cooklang is still BUILT
 * and TESTED whenever any of its files change (driven by `packages`); this
 * flag governs only whether we PUBLISH.
 */
export function hasCooklangSourceChange(changedFiles: string[]): boolean {
  return changedFiles.some(
    (file) =>
      COOKLANG_PACKAGE_PREFIXES.some((prefix) => file.startsWith(prefix)) &&
      !COOKLANG_NON_SOURCE_FILES.has(file),
  );
}

/**
 * True when HEAD's commit message carries an `Auto-Generated:` trailer.
 * Bot-authored commits (e.g. version-commit-back) tag themselves with this
 * trailer so downstream pipeline steps (version-commit-back) can skip
 * themselves and avoid bot-on-bot loops.
 */
function readHeadCommitMessage(): string {
  return execSync("git log -1 --pretty=%B", {
    cwd: REPO_ROOT,
    encoding: "utf8",
  });
}

function isCiBaseVersionBumpMerge(msg: string): boolean {
  return (
    /^Merge pull request #\d+ from /m.test(msg) &&
    msg.includes(CI_BASE_VERSION_BUMP_BRANCH)
  );
}

export function isAutoGeneratedCommit(msg = readHeadCommitMessage()): boolean {
  return /^Auto-Generated:\s*\S/m.test(msg) || isCiBaseVersionBumpMerge(msg);
}

// ---------------------------------------------------------------------------
// Release-please merge detection
// ---------------------------------------------------------------------------

/** Check if the current build is a release-please merge commit. */
export function isReleasePleaseMerge(): boolean {
  const msg = Bun.env["BUILDKITE_MESSAGE"] ?? "";
  return msg === "chore: release main";
}

/** The head branch release-please pushes its release PRs to. */
const RELEASE_PLEASE_PR_BRANCH = "release-please--branches--main";

/**
 * True when this build is an *auto-triggered* (webhook) build of the
 * release-please release PR. These PRs are no-op version bumps, so we skip the
 * full CI rather than burn the whole pipeline (and the Greptile gate) on them.
 *
 * The skip is intentionally narrow: it fires *only* when BUILDKITE_SOURCE is
 * exactly "webhook" (the automatic build Buildkite starts from the GitHub PR
 * webhook). Every other source — "ui"/"api" (manual New Build / API /
 * `bk build create`), "schedule", "trigger_job" (triggered by another
 * pipeline), or an unknown/empty value — runs full CI. Defaulting unknown
 * sources to "run" is deliberate: we'd rather over-run CI than silently skip a
 * build and mistake the no-op pipeline for real coverage.
 *
 * RUN_RELEASE_CI=true also forces a full run regardless of source.
 *
 * This lets a release still be cut on demand while leaving the PR un-CI'd (and
 * therefore not mergeable) until you ask for it. Note this only matches the
 * release PR branch; the eventual `chore: release main` merge to `main` is a
 * different build and is handled by {@link isReleasePleaseMerge}.
 */
export function shouldSkipReleasePleasePrBuild(): boolean {
  const branch = Bun.env["BUILDKITE_BRANCH"] ?? "";
  if (branch !== RELEASE_PLEASE_PR_BRANCH) return false;
  const optIn = (Bun.env["RUN_RELEASE_CI"] ?? "").toLowerCase() === "true";
  if (optIn) return false;
  const source = Bun.env["BUILDKITE_SOURCE"] ?? "";
  return source === "webhook";
}

// Aliases for the test surface (same-file re-declaration exports).
export {
  isVersionCommitBack as _isVersionCommitBack,
  isCooklangVersionCommitBack as _isCooklangVersionCommitBack,
  isCooklangVersionCommitBackOnly as _isCooklangVersionCommitBackOnly,
  hasCooklangSourceChange as _hasCooklangSourceChange,
  isAutoGeneratedCommit as _isAutoGeneratedCommit,
  isReleasePleaseMerge as _isReleasePleaseMerge,
  shouldSkipReleasePleasePrBuild as _shouldSkipReleasePleasePrBuild,
};
