import type { Guild, TextChannel } from "discord.js";
import { getDiscordClient } from "@shepherdjerred/birmel/discord/index.js";
import { prisma } from "@shepherdjerred/birmel/database/index.js";
import { logger } from "@shepherdjerred/birmel/utils/index.js";

type ServerSummaryConfig = {
  guildId: string;
  channelId: string;
  enabled: boolean;
};

type EventCounts = {
  memberJoins: number;
  memberLeaves: number;
  messagesDeleted: number;
  rolesChanged: number;
  channelsCreated: number;
  channelsDeleted: number;
};

/**
 * Counts events by type from the last 24 hours
 */
async function countEventTypes(guildId: string): Promise<EventCounts> {
  const oneDayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);

  const events = await prisma.serverEvent.findMany({
    where: {
      guildId,
      createdAt: { gte: oneDayAgo },
    },
    select: { eventType: true },
  });

  const counts: EventCounts = {
    memberJoins: 0,
    memberLeaves: 0,
    messagesDeleted: 0,
    rolesChanged: 0,
    channelsCreated: 0,
    channelsDeleted: 0,
  };

  for (const event of events) {
    switch (event.eventType) {
      case "member_join":
        counts.memberJoins++;
        break;
      case "member_leave":
        counts.memberLeaves++;
        break;
      case "message_delete":
        counts.messagesDeleted++;
        break;
      case "role_create":
      case "role_update":
      case "role_delete":
        counts.rolesChanged++;
        break;
      case "channel_create":
        counts.channelsCreated++;
        break;
      case "channel_delete":
        counts.channelsDeleted++;
        break;
    }
  }

  return counts;
}

/**
 * Generates a detailed server summary message
 */
function generateServerSummary(guild: Guild, counts: EventCounts): string {
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let message = `**Server Summary - ${dateStr}**\n`;
  message += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;

  // Server stats
  message += `**Server Stats**\n`;
  message += `• Members: ${String(guild.memberCount)}\n`;
  message += `• Channels: ${String(guild.channels.cache.size)}\n`;
  message += `• Roles: ${String(guild.roles.cache.size)}\n\n`;

  // Activity summary
  message += `**24-Hour Activity**\n`;

  const hasActivity =
    counts.memberJoins > 0 ||
    counts.memberLeaves > 0 ||
    counts.messagesDeleted > 0 ||
    counts.rolesChanged > 0 ||
    counts.channelsCreated > 0 ||
    counts.channelsDeleted > 0;

  if (hasActivity) {
    if (counts.memberJoins > 0) {
      message += `• ${String(counts.memberJoins)} member${counts.memberJoins === 1 ? "" : "s"} joined\n`;
    }
    if (counts.memberLeaves > 0) {
      message += `• ${String(counts.memberLeaves)} member${counts.memberLeaves === 1 ? "" : "s"} left\n`;
    }
    if (counts.messagesDeleted > 0) {
      message += `• ${String(counts.messagesDeleted)} message${counts.messagesDeleted === 1 ? "" : "s"} deleted\n`;
    }
    if (counts.rolesChanged > 0) {
      message += `• ${String(counts.rolesChanged)} role change${counts.rolesChanged === 1 ? "" : "s"}\n`;
    }
    if (counts.channelsCreated > 0) {
      message += `• ${String(counts.channelsCreated)} channel${counts.channelsCreated === 1 ? "" : "s"} created\n`;
    }
    if (counts.channelsDeleted > 0) {
      message += `• ${String(counts.channelsDeleted)} channel${counts.channelsDeleted === 1 ? "" : "s"} deleted\n`;
    }
  } else {
    message += `No notable activity recorded.\n`;
  }

  message += `\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
  message += `*Generated by Birmel*`;

  return message;
}

/**
 * Send server summary to a specific guild
 */
async function sendServerSummary(config: ServerSummaryConfig): Promise<void> {
  try {
    const client = getDiscordClient();
    const guild = await client.guilds.fetch(config.guildId);
    const channel = await client.channels.fetch(config.channelId);

    if (channel?.isTextBased() !== true) {
      logger.warn("Summary channel not found or not text-based", {
        guildId: config.guildId,
        channelId: config.channelId,
      });
      return;
    }

    const counts = await countEventTypes(config.guildId);
    const message = generateServerSummary(guild, counts);
    await (channel as TextChannel).send(message);

    logger.info("Sent server summary", { guildId: config.guildId });
  } catch (error) {
    logger.error("Failed to send server summary", error as Error, {
      guildId: config.guildId,
    });
  }
}

/**
 * Run the server summary job for all configured guilds
 */
export async function runServerSummaryJob(): Promise<void> {
  try {
    // Query guilds with daily posts enabled (they get summaries too)
    const configs = await prisma.dailyPostConfig.findMany({
      where: { enabled: true },
      select: { guildId: true, channelId: true },
    });

    for (const config of configs) {
      await sendServerSummary({
        guildId: config.guildId,
        channelId: config.channelId,
        enabled: true,
      });
    }

    logger.info("Server summary job completed", {
      guildsProcessed: configs.length,
    });
  } catch (error) {
    logger.error("Server summary job failed", error as Error);
  }
}
