import { strict as assert } from "node:assert";
import path from "node:path";
import Ajv2020 from "ajv/dist/2020.js";
import { format } from "prettier";
import { z } from "zod";
import ThemesJsonSchema from "#tokens/themes.schema.json" with { type: "json" };

const HexColorSchema = z.string().regex(/^#[\dA-F]{6}(?:[\dA-F]{2})?$/);
const ColorsSchema = z.object({
  canvas: HexColorSchema,
  surface: HexColorSchema,
  surfaceRaised: HexColorSchema,
  text: HexColorSchema,
  textMuted: HexColorSchema,
  primary: HexColorSchema,
  primaryText: HexColorSchema,
  accent: HexColorSchema,
  accentText: HexColorSchema,
  border: HexColorSchema,
  interactiveHover: HexColorSchema,
  interactiveActive: HexColorSchema,
  interactiveDisabled: HexColorSchema,
  focus: HexColorSchema,
  success: HexColorSchema,
  successText: HexColorSchema,
  warning: HexColorSchema,
  warningText: HexColorSchema,
  danger: HexColorSchema,
  dangerText: HexColorSchema,
  info: HexColorSchema,
  infoText: HexColorSchema,
  overlay: HexColorSchema,
  chart1: HexColorSchema,
  chart2: HexColorSchema,
  chart3: HexColorSchema,
  chart4: HexColorSchema,
  chart5: HexColorSchema,
  chart6: HexColorSchema,
  chart7: HexColorSchema,
  chart8: HexColorSchema,
});
const ThemeSchema = z.object({
  colors: ColorsSchema,
  typography: z.object({
    display: z.string().min(1),
    body: z.string().min(1),
    mono: z.string().min(1),
  }),
  shape: z.object({
    radiusSmall: z.string(),
    radiusMedium: z.string(),
    radiusLarge: z.string(),
    borderWidth: z.string(),
    shadow: z.string(),
  }),
  motion: z.object({
    durationFast: z.string(),
    durationNormal: z.string(),
    easing: z.string(),
  }),
});
const ThemesSchema = z.object({
  $schema: z.string(),
  version: z.literal(1),
  themes: z.object({
    "modern-light": ThemeSchema,
    "modern-dark": ThemeSchema,
    "classic-light": ThemeSchema,
    "classic-dark": ThemeSchema,
  }),
});

const packageRoot = path.resolve(import.meta.dir, "..");
const sourcePath = path.resolve(packageRoot, "tokens/themes.json");
const tsPath = path.resolve(packageRoot, "src/generated/tokens.ts");
const cssPath = path.resolve(packageRoot, "styles/generated/tokens.css");
const source = z.json().parse(await Bun.file(sourcePath).json());
const validateJsonSchema = new Ajv2020({ allErrors: true }).compile(
  ThemesJsonSchema,
);
if (!validateJsonSchema(source)) {
  throw new Error(
    `Scout theme JSON Schema validation failed: ${JSON.stringify(validateJsonSchema.errors)}`,
  );
}
const parsed = ThemesSchema.parse(source);

function kebab(value: string): string {
  return value.replaceAll(
    /[A-Z]/g,
    (character) => `-${character.toLowerCase()}`,
  );
}

function cssForTheme(name: keyof typeof parsed.themes): string {
  const [skin, mode] = name.split("-");
  if (skin === undefined || mode === undefined) {
    throw new Error(`Invalid theme name: ${name}`);
  }
  const theme = parsed.themes[name];
  const variables = [
    ...Object.entries(theme.colors).map(
      ([key, value]) => `  --scout-color-${kebab(key)}: ${value};`,
    ),
    `  --scout-font-display: ${theme.typography.display};`,
    `  --scout-font-body: ${theme.typography.body};`,
    `  --scout-font-mono: ${theme.typography.mono};`,
    ...Object.entries(theme.shape).map(
      ([key, value]) => `  --scout-${kebab(key)}: ${value};`,
    ),
    ...Object.entries(theme.motion).map(
      ([key, value]) => `  --scout-motion-${kebab(key)}: ${value};`,
    ),
  ];
  const selector =
    name === "modern-light"
      ? `:root, [data-scout-skin="${skin}"][data-scout-mode="${mode}"]`
      : `[data-scout-skin="${skin}"][data-scout-mode="${mode}"]`;
  return `${selector} {\n${variables.join("\n")}\n}`;
}

const generatedTs = await format(
  `// Generated by scripts/generate-tokens.ts. Do not edit.\nexport const scoutThemes = ${JSON.stringify(parsed.themes, undefined, 2)} as const;\n\nexport type ScoutResolvedTheme = keyof typeof scoutThemes;\nexport type ScoutThemeTokens = (typeof scoutThemes)[ScoutResolvedTheme];\n`,
  { parser: "typescript" },
);
const generatedCss = await format(
  `/* Generated by scripts/generate-tokens.ts. Do not edit. */\n${Object.keys(
    parsed.themes,
  )
    .map((name) => {
      if (!(name in parsed.themes)) {
        throw new Error(`Missing theme ${name}`);
      }
      if (
        name !== "modern-light" &&
        name !== "modern-dark" &&
        name !== "classic-light" &&
        name !== "classic-dark"
      ) {
        throw new Error(`Unexpected theme ${name}`);
      }
      return cssForTheme(name);
    })
    .join("\n\n")}\n`,
  { parser: "css" },
);

if (Bun.argv.includes("--check")) {
  assert.equal(
    await Bun.file(tsPath).text(),
    generatedTs,
    "Generated TS drifted",
  );
  assert.equal(
    await Bun.file(cssPath).text(),
    generatedCss,
    "Generated CSS drifted",
  );
  console.log("Scout token JSON, generated TypeScript, and CSS are in sync");
} else {
  await Promise.all([
    Bun.write(tsPath, generatedTs),
    Bun.write(cssPath, generatedCss),
  ]);
  console.log("Generated Scout theme TypeScript and CSS");
}
