// Generated by scripts/generate.ts. Do not edit directly.
import generationStateJson from "#data/generation-state.json" with { type: "json" };
import loreJson from "#data/lore.json" with { type: "json" };
import peopleJson from "#data/people.json" with { type: "json" };
import relationshipsJson from "#data/relationships.json" with { type: "json" };
import aaronCard from "#data/style-cards/aaron_style.json" with { type: "json" };
import brianCard from "#data/style-cards/brian_style.json" with { type: "json" };
import caitlynCard from "#data/style-cards/caitlyn_style.json" with { type: "json" };
import colinCard from "#data/style-cards/colin_style.json" with { type: "json" };
import dannyCard from "#data/style-cards/danny_style.json" with { type: "json" };
import edwardCard from "#data/style-cards/edward_style.json" with { type: "json" };
import hirzaCard from "#data/style-cards/hirza_style.json" with { type: "json" };
import irfanCard from "#data/style-cards/irfan_style.json" with { type: "json" };
import jerredCard from "#data/style-cards/jerred_style.json" with { type: "json" };
import longCard from "#data/style-cards/long_style.json" with { type: "json" };
import richardCard from "#data/style-cards/richard_style.json" with { type: "json" };
import ryanCard from "#data/style-cards/ryan_style.json" with { type: "json" };
import virmelCard from "#data/style-cards/virmel_style.json" with { type: "json" };
import {
  GenerationStateDocumentSchema,
  LoreDocumentSchema,
  PeopleDocumentSchema,
  RelationshipsDocumentSchema,
  StyleCardsDocumentSchema,
} from "#src/schema.ts";

export const peopleDocument = PeopleDocumentSchema.parse(peopleJson);
export const relationshipsDocument =
  RelationshipsDocumentSchema.parse(relationshipsJson);
export const generationStateDocument =
  GenerationStateDocumentSchema.parse(generationStateJson);
export const loreDocument = LoreDocumentSchema.parse(loreJson);
export const styleCards = StyleCardsDocumentSchema.parse({
  aaron: aaronCard,
  brian: brianCard,
  caitlyn: caitlynCard,
  colin: colinCard,
  danny: dannyCard,
  edward: edwardCard,
  hirza: hirzaCard,
  irfan: irfanCard,
  jerred: jerredCard,
  long: longCard,
  richard: richardCard,
  ryan: ryanCard,
  virmel: virmelCard,
});
