import { test, expect } from "bun:test";
import { loadingScreenToSvg } from "#src/html/loading-screen/index.tsx";
import { LoadingScreenDataSchema } from "@scout-for-lol/data";
import { svgToPng } from "#src/html/index.tsx";

function hashSvg(svg: string): string {
  const hasher = new Bun.CryptoHasher("sha256");
  hasher.update(svg);
  return hasher.digest("hex");
}

/**
 * Check if champion loading screen images have been downloaded.
 * These are generated by `bun run update-data-dragon` in packages/data.
 */
async function hasLoadingScreenAssets(): Promise<boolean> {
  const testImage = new URL(
    "../../../dataDragon/../../../packages/data/src/data-dragon/assets/img/champion-loading/Aatrox_0.jpg",
    import.meta.url,
  );
  const file = Bun.file(testImage);
  return file.exists();
}

const currentDir = new URL(".", import.meta.url).pathname;

const FIXTURE_PATHS = [`${currentDir}testdata/ranked-flex-5v5.json`];

for (const path of FIXTURE_PATHS) {
  const fileNameOrUndefined = path.split("/").pop();
  if (!fileNameOrUndefined) {
    throw new Error("fileName is undefined");
  }
  const fileName: string = fileNameOrUndefined;
  const testName = `loading screen renders image for ${fileName}`;
  test(testName, async () => {
    // Skip if loading screen assets haven't been downloaded yet
    const assetsExist = await hasLoadingScreenAssets();
    if (!assetsExist) {
      console.warn(
        "⚠️  Skipping loading screen snapshot test: champion loading images not found. Run 'bun run update-data-dragon' in packages/data first.",
      );
      return;
    }

    // 1. Load and validate fixture
    const raw = (await Bun.file(path).json()) as unknown;
    const data = LoadingScreenDataSchema.parse(raw);

    // 2. Render to SVG
    const svg = await loadingScreenToSvg(data);

    // 3. Convert to PNG
    const png = await svgToPng(svg);

    // 4. Save artifacts for visual inspection
    const outputBase: string =
      fileName.replace(".json", "") ?? "loading-screen";
    await Bun.write(
      new URL(`__snapshots__/${outputBase}.png`, import.meta.url),
      png,
    );
    await Bun.write(
      new URL(`__snapshots__/${outputBase}.svg`, import.meta.url),
      svg,
    );

    // 5. Hash SVG for deterministic snapshot comparison
    const svgHash = hashSvg(svg);
    expect(svgHash).toMatchSnapshot();
  });
}
