import { z } from "zod";
import { defineConfig } from "@shepherdjerred/config";
import { createConfigSnapshot } from "@shepherdjerred/config/snapshot.ts";
import { createObservabilityHooks } from "@shepherdjerred/config/observability.ts";
import { createEnvSource } from "@shepherdjerred/config/sources/env.ts";
import {
  initFeatureFlags,
  shutdownFeatureFlags,
  type InitFeatureFlagsOptions,
} from "@shepherdjerred/feature-flags";
import { createFlagConfigSource } from "@shepherdjerred/feature-flags/config-source.ts";
import type { Config } from "@shepherdjerred/streambot/config/schema.ts";

/**
 * streambot's dynamically configurable values.
 *
 * ## What is deliberately NOT here
 *
 * `VOICE_ASSISTANT_ENABLED` and `VOICE_CAPTURE_ENABLED` stay in env, on
 * purpose:
 *
 * - Enabling voice today triggers *fatal* asset and model verification at
 *   startup. "Fatal" is not available at runtime, so making it a flag needs a
 *   designed degraded path — refuse to arm voice, log loudly, count an error —
 *   which is a behavior change, not a rewiring. It deserves its own change.
 * - `VOICE_CAPTURE_ENABLED` decides whether human audio is persisted to S3.
 *   Flipt runs without authentication, so moving it would let any tailnet
 *   device turn on recording. That is the sharpest instance of the accepted
 *   auth trade-off and should be a deliberate decision, not a side effect of a
 *   migration commit.
 *
 * Encoder settings are also absent, and would be misleading if present: ffmpeg
 * arguments are fixed for the process's lifetime, so flipping one changes
 * nothing until the stream restarts.
 *
 * ## What is here
 *
 * Two toggles the package's own docs describe as live-safe. Both are read
 * through a seeded snapshot because their call sites are synchronous, and both
 * fall back to the passed-in `Config` value until startup initializes the
 * snapshot — so this is a no-op until a flag exists.
 */
const DynamicBooleanSchema = z.preprocess(
  (value) =>
    typeof value === "string"
      ? value.toLowerCase() === "true"
        ? true
        : value.toLowerCase() === "false"
          ? false
          : value
      : value,
  z.boolean(),
);

const DEFINITION = {
  playerCardEnabled: {
    schema: DynamicBooleanSchema,
    sources: ["flag", "env", "default"],
    default: true,
    names: { env: "PLAYER_CARD_ENABLED" },
  },
  subtitlesEnabled: {
    schema: DynamicBooleanSchema,
    sources: ["flag", "env", "default"],
    default: true,
    names: { env: "SUBTITLES_ENABLED" },
  },
  subtitlesLanguages: {
    schema: z.union([
      z.array(z.string().min(1)),
      z.string().transform((value) =>
        value
          .split(",")
          .map((item) => item.trim())
          .filter((item) => item.length > 0),
      ),
    ]),
    sources: ["flag", "env", "default"],
    default: ["en", "eng", "en-US"],
    names: { flag: "streambot-subtitle-languages", env: "SUBTITLE_LANGUAGES" },
  },
  subtitlesIncludeAutoGenerated: {
    schema: DynamicBooleanSchema,
    sources: ["flag", "env", "default"],
    default: true,
    names: {
      flag: "streambot-subtitles-include-auto-generated",
      env: "SUBTITLES_INCLUDE_AUTO_GENERATED",
    },
  },
  reconnectEnabled: {
    schema: DynamicBooleanSchema,
    sources: ["flag", "env", "default"],
    default: true,
    names: {
      flag: "streambot-reconnect-enabled",
      env: "STREAMER_RECONNECT_ENABLED",
    },
  },
  reconnectDelaySeconds: {
    schema: z.coerce.number().int().positive(),
    sources: ["flag", "env", "default"],
    default: 5,
    names: {
      flag: "streambot-reconnect-delay-seconds",
      env: "STREAMER_RECONNECT_DELAY_SECONDS",
    },
  },
  reconnectMaxAttempts: {
    schema: z.coerce.number().int().positive(),
    sources: ["flag", "env", "default"],
    default: 3,
    names: {
      flag: "streambot-reconnect-max-attempts",
      env: "STREAMER_RECONNECT_MAX_ATTEMPTS",
    },
  },
  playerCardTickMs: {
    schema: z.coerce.number().int().nonnegative(),
    sources: ["flag", "env", "default"],
    default: 10_000,
    names: {
      flag: "streambot-player-card-tick-ms",
      env: "PLAYER_CARD_TICK_MS",
    },
  },
  playerCardRepostAfterMessages: {
    schema: z.coerce.number().int().nonnegative(),
    sources: ["flag", "env", "default"],
    default: 5,
    names: {
      flag: "streambot-player-card-repost-after-messages",
      env: "PLAYER_CARD_REPOST_AFTER_MESSAGES",
    },
  },
  idleTimeoutSeconds: {
    schema: z.coerce.number().int().positive(),
    sources: ["flag", "env", "default"],
    default: 300,
    names: {
      flag: "streambot-idle-timeout-seconds",
      env: "IDLE_TIMEOUT_SECONDS",
    },
  },
  playlistLimit: {
    schema: z.coerce.number().int().positive(),
    sources: ["flag", "env", "default"],
    default: 100,
    names: { flag: "streambot-playlist-limit", env: "PLAYLIST_LIMIT" },
  },
} as const;

const REFRESH_INTERVAL_MS = 60_000;

type Snapshot = ReturnType<typeof buildSnapshot>;

function buildSnapshot(
  environment: Readonly<Record<string, string | undefined>>,
  seed: DynamicConfigSeed,
  log: (message: string) => void,
) {
  const resolver = defineConfig({
    definition: DEFINITION,
    sources: {
      flag: createFlagConfigSource({
        targetingKey: "streambot",
        kinds: {
          playerCardEnabled: "boolean",
          subtitlesEnabled: "boolean",
          subtitlesLanguages: "string",
          subtitlesIncludeAutoGenerated: "boolean",
          reconnectEnabled: "boolean",
          reconnectDelaySeconds: "number",
          reconnectMaxAttempts: "number",
          playerCardTickMs: "number",
          playerCardRepostAfterMessages: "number",
          idleTimeoutSeconds: "number",
          playlistLimit: "number",
        },
      }),
      env: createEnvSource(environment),
    },
    hooks: createObservabilityHooks({ log }),
  });
  return createConfigSnapshot({
    resolver,
    seed,
    onRefreshError: (key, message) => {
      log(`config refresh failed for ${key}; keeping last value: ${message}`);
    },
  });
}

let snapshot: Snapshot | undefined;
let pollTimer: ReturnType<typeof setInterval> | undefined;

export type DynamicConfigSeed = {
  readonly playerCardEnabled: boolean;
  readonly subtitlesEnabled: boolean;
  readonly subtitlesLanguages?: string[];
  readonly subtitlesIncludeAutoGenerated?: boolean;
  readonly reconnectEnabled?: boolean;
  readonly reconnectDelaySeconds?: number;
  readonly reconnectMaxAttempts?: number;
  readonly playerCardTickMs?: number;
  readonly playerCardRepostAfterMessages?: number;
  readonly idleTimeoutSeconds?: number;
  readonly playlistLimit?: number;
};

function applySnapshot(config: Config): void {
  if (snapshot === undefined) return;
  config.playerCard.enabled = snapshot.get("playerCardEnabled");
  config.subtitles.enabled = snapshot.get("subtitlesEnabled");
  config.subtitles.languages = snapshot.get("subtitlesLanguages");
  config.subtitles.includeAutoGenerated = snapshot.get(
    "subtitlesIncludeAutoGenerated",
  );
  config.reconnect.enabled = snapshot.get("reconnectEnabled");
  config.reconnect.delaySeconds = snapshot.get("reconnectDelaySeconds");
  config.reconnect.maxAttempts = snapshot.get("reconnectMaxAttempts");
  config.playerCard.tickMs = snapshot.get("playerCardTickMs");
  config.playerCard.repostAfterMessages = snapshot.get(
    "playerCardRepostAfterMessages",
  );
  config.idleTimeoutSeconds = snapshot.get("idleTimeoutSeconds");
  config.playlistLimit = snapshot.get("playlistLimit");
}

async function refreshSnapshot(config: Config | undefined): Promise<void> {
  if (snapshot === undefined) return;
  await snapshot.refresh();
  if (config !== undefined) applySnapshot(config);
}

export type InitializeDynamicConfigOptions = {
  readonly environment?: InitFeatureFlagsOptions["environment"];
  readonly provider?: InitFeatureFlagsOptions["provider"];
  readonly metrics?: InitFeatureFlagsOptions["metrics"];
  readonly seed: DynamicConfigSeed;
  readonly config?: Config;
  readonly log?: (message: string) => void;
  /** Tests pass false to avoid an interval. */
  readonly startPolling?: boolean;
};

export async function initializeDynamicConfig(
  options: InitializeDynamicConfigOptions,
): Promise<void> {
  // A no-op sink keeps every call site unconditional; streambot supplies its
  // own logger from the entry point.
  const log =
    options.log ??
    (() => {
      /* discard */
    });
  await initFeatureFlags({
    ...(options.environment === undefined
      ? {}
      : { environment: options.environment }),
    ...(options.provider === undefined ? {} : { provider: options.provider }),
    ...(options.metrics === undefined ? {} : { metrics: options.metrics }),
    onInitializationFailure: log,
  });
  snapshot = buildSnapshot(options.environment ?? Bun.env, options.seed, log);
  await snapshot.refresh();
  if (options.config !== undefined) applySnapshot(options.config);
  if (options.startPolling !== false) {
    pollTimer ??= setInterval(() => {
      void refreshSnapshot(options.config);
    }, REFRESH_INTERVAL_MS);
    pollTimer.unref();
  }
}

/**
 * Reads the dynamic value, or returns the caller's current one.
 *
 * Both accessors take the value the call site already had. Before startup
 * initializes the snapshot they return it unchanged, so behavior is identical
 * to before this module existed — there is no window where a toggle flips
 * because config was not ready yet.
 */
export function playerCardEnabled(fallback: boolean): boolean {
  return snapshot === undefined ? fallback : snapshot.get("playerCardEnabled");
}

export function subtitlesEnabled(fallback: boolean): boolean {
  return snapshot === undefined ? fallback : snapshot.get("subtitlesEnabled");
}

export function isDynamicConfigReady(): boolean {
  return snapshot !== undefined;
}

export async function shutdownDynamicConfig(): Promise<void> {
  if (pollTimer !== undefined) {
    clearInterval(pollTimer);
    pollTimer = undefined;
  }
  snapshot = undefined;
  await shutdownFeatureFlags();
}
