import { recommended } from "../eslint-config/local.ts";

export default [
  ...recommended({ tsconfigRootDir: import.meta.dirname }),
  { rules: { "no-console": "off" } },
  // CDK8s infrastructure code uses heavily untyped APIs (cdk8s-plus, Helm values, etc.)
  {
    files: ["src/cdk8s/**/*.ts"],
    rules: {
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
      "@typescript-eslint/restrict-plus-operands": "off",
      // 1Password vault references and infrastructure URLs trigger false positives
      "no-secrets/no-secrets": "off",
    },
  },
  // Home Assistant workflows use @digital-alchemy/core which has untyped APIs
  {
    files: ["src/ha/**/*.ts", "src/ha/**/*.mts"],
    rules: {
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      // Zod .catch() is falsely flagged as Promise .catch()
      "custom-rules/prefer-async-await": "off",
    },
  },
  // HA workflow files interact with @digital-alchemy entities that return `any`
  {
    files: ["src/ha/src/workflows/**/*.ts"],
    rules: {
      "@typescript-eslint/strict-boolean-expressions": "off",
    },
  },
  {
    ignores: [
      "src/talos/",
      "src/*/eslint.config.ts",
      "scripts/",
      "eslint.config.ts",
      // Generated by digital-alchemy type-writer
      "src/ha/src/hass/",
    ],
  },
];
