import { recommended } from "@shepherdjerred/eslint-config";
import type { TSESLint } from "@typescript-eslint/utils";

const config: TSESLint.FlatConfig.ConfigArray = [
  ...recommended({ tsconfigRootDir: import.meta.dirname }),
  { rules: { "no-console": "off" } },
  {
    ignores: [
      "src/talos/",
      "src/*/eslint.config.ts",
      "scripts/",
      "eslint.config.ts",
      // Generated by digital-alchemy type-writer
      "src/ha/src/hass/",
      // Generated by cdk8s
      "src/cdk8s/generated/",
    ],
  },
];
export default config;
