import { recommended } from "@shepherdjerred/eslint-config";
const config = [
  ...recommended({
    tsconfigRootDir: import.meta.dirname,
    // knip (dead code/exports) + jscpd (duplication), both at warn.
    customRules: { analysisRules: true },
  }),
  { rules: { "no-console": "off" } },
  {
    ignores: [
      "src/talos/",
      "src/*/eslint.config.ts",
      "scripts/",
      "eslint.config.ts",
      // Generated by cdk8s
      "src/cdk8s/generated/",
    ],
  },
];
export default config;
