[tools]
python = "3.14.6"

[tasks.dev]
run = 'bun install'

[tasks.build-cdk8s]
dir = 'src/cdk8s/'
run = ['bun run typecheck', 'bun run lint', 'bun run build']

[tasks.build-helm-types]
dir = 'src/helm-types/'
run = ['bun run typecheck', 'bun run lint']

[tasks.build]
depends = ['build-cdk8s', 'build-helm-types']
