package com.shepherdjerred.thestorm.rwf.adapter.content;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates the shipped {@code training-yard} map: a 64x16x64 walled yard with a red base to the
 * west, a blue base to the east, one bomb in each base, a nuke on a gold pedestal in the middle,
 * cobblestone cover, and a glass lobby platform near the ceiling. Deterministic, so the committed
 * {@code blocks.schem} can be regenerated byte for byte and its hash checked by a test.
 *
 * <p>Run {@code main} with the map folder as the argument to regenerate the schematic; it prints
 * the hash to copy into {@code map.yml}.
 */
public final class TrainingYard {

  public static final int WIDTH = 64;
  public static final int HEIGHT = 16;
  public static final int LENGTH = 64;

  /** The region's lowest corner in the rwf world. */
  public static final int ORIGIN_X = 0;

  public static final int ORIGIN_Y = 64;
  public static final int ORIGIN_Z = 0;

  static final String AIR = "minecraft:air";
  static final String FLOOR = "minecraft:stone_bricks";
  static final String WALL = "minecraft:stone_bricks";
  static final String RED = "minecraft:red_concrete";
  static final String BLUE = "minecraft:blue_concrete";
  static final String COVER = "minecraft:cobblestone";
  static final String PEDESTAL = "minecraft:gold_block";
  static final String TNT = LoadedMap.TNT;
  static final String LIGHT = "minecraft:glowstone";
  static final String GLASS = "minecraft:glass";

  /** The palette, in index order; {@code AIR} first so most of the yard is index 0. */
  static final List<String> PALETTE =
      List.of(AIR, FLOOR, RED, BLUE, COVER, PEDESTAL, TNT, LIGHT, GLASS);

  /** A relative block position inside the yard. */
  public record Rel(int x, int y, int z) {}

  /** The bombs: red, blue, nuke. */
  public static final Rel RED_BOMB = new Rel(8, 1, 31);

  public static final Rel BLUE_BOMB = new Rel(55, 1, 31);
  public static final Rel NUKE = new Rel(31, 2, 31);

  /** Cover pillars (relative x, z), 2x2 and four blocks tall. */
  private static final int[][] PILLARS = {
    {20, 20}, {20, 42}, {42, 20}, {42, 42}, {31, 12}, {31, 50}, {16, 31}, {46, 31}
  };

  private TrainingYard() {}

  public static Schematic generate() {
    var indices = new int[WIDTH * HEIGHT * LENGTH];
    var yard = new Yard(indices);
    yard.fill(new Rel(0, 0, 0), new Rel(WIDTH - 1, 0, LENGTH - 1), FLOOR);
    for (var y = 1; y <= 8; y++) {
      yard.ring(y, WALL);
    }
    yard.ring(9, LIGHT);
    base(yard, 4, RED);
    base(yard, 48, BLUE);
    for (var pillar : PILLARS) {
      yard.fill(new Rel(pillar[0], 1, pillar[1]), new Rel(pillar[0] + 1, 4, pillar[1] + 1), COVER);
    }
    yard.fill(
        new Rel(NUKE.x() - 1, 1, NUKE.z() - 1), new Rel(NUKE.x() + 1, 1, NUKE.z() + 1), PEDESTAL);
    yard.set(RED_BOMB, TNT);
    yard.set(BLUE_BOMB, TNT);
    yard.set(NUKE, TNT);
    // The lobby: a glass platform at y 13 with a one-block glass rim, under the open ceiling.
    yard.fill(new Rel(27, 13, 27), new Rel(36, 13, 36), GLASS);
    yard.fill(new Rel(27, 14, 27), new Rel(36, 14, 27), GLASS);
    yard.fill(new Rel(27, 14, 36), new Rel(36, 14, 36), GLASS);
    yard.fill(new Rel(27, 14, 27), new Rel(27, 14, 36), GLASS);
    yard.fill(new Rel(36, 14, 27), new Rel(36, 14, 36), GLASS);
    return new Schematic(new Schematic.Dimensions(WIDTH, HEIGHT, LENGTH), PALETTE, indices);
  }

  /** A base: a 12x14 box of team concrete with doorways on the field side, open on top. */
  private static void base(Yard yard, int x, String block) {
    var west = x < WIDTH / 2;
    var x0 = x;
    var x1 = x + 11;
    var z0 = 24;
    var z1 = 38;
    for (var y = 1; y <= 3; y++) {
      yard.fill(new Rel(x0, y, z0), new Rel(x1, y, z0), block);
      yard.fill(new Rel(x0, y, z1), new Rel(x1, y, z1), block);
      yard.fill(new Rel(west ? x0 : x1, y, z0), new Rel(west ? x0 : x1, y, z1), block);
      var door = west ? x1 : x0;
      yard.fill(new Rel(door, y, z0), new Rel(door, y, z0 + 4), block);
      yard.fill(new Rel(door, y, z1 - 4), new Rel(door, y, z1), block);
    }
  }

  private static final class Yard {

    private final int[] indices;

    Yard(int[] indices) {
      this.indices = indices;
    }

    void set(int x, int y, int z, String block) {
      indices[(y * LENGTH + z) * WIDTH + x] = PALETTE.indexOf(block);
    }

    void set(Rel at, String block) {
      set(at.x(), at.y(), at.z(), block);
    }

    /** Fills the box between two corners, both included. */
    void fill(Rel from, Rel to, String block) {
      for (var y = from.y(); y <= to.y(); y++) {
        for (var z = from.z(); z <= to.z(); z++) {
          for (var x = from.x(); x <= to.x(); x++) {
            set(x, y, z, block);
          }
        }
      }
    }

    void ring(int y, String block) {
      fill(new Rel(0, y, 0), new Rel(WIDTH - 1, y, 0), block);
      fill(new Rel(0, y, LENGTH - 1), new Rel(WIDTH - 1, y, LENGTH - 1), block);
      fill(new Rel(0, y, 0), new Rel(0, y, LENGTH - 1), block);
      fill(new Rel(WIDTH - 1, y, 0), new Rel(WIDTH - 1, y, LENGTH - 1), block);
    }
  }

  /** Writes {@code blocks.schem} into the folder given and prints the hash for {@code map.yml}. */
  public static void main(String[] args) {
    if (args.length != 1) {
      throw new IllegalArgumentException("usage: TrainingYard <map folder>");
    }
    var schematic = generate();
    try {
      Files.write(
          Path.of(args[0]).resolve(ContentFiles.BLOCKS_FILE), SchematicWriter.write(schematic));
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
    System.out.println(schematic.sha256());
  }
}
