import { z } from "zod";
import {
  getAllChampions,
  getChampionByKey,
  normalizeChampionName,
  searchChampions,
} from "#src/model/champion-registry.ts";

/**
 * Grounded per-ability facts generated from Data Dragon (cooldowns, costs,
 * ranges) and CommunityDragon champion bins (damage numbers, scalings).
 *
 * Committed under `assets/ability-facts/{ChampionKey}.json`, one file per
 * champion, regenerated by `scripts/update-data-dragon.ts`. Rank indexing is
 * 1-based relative to the arrays: `cooldownByRank[0]`, `costByRank[0]`,
 * `rangeByRank[0]`, and `dataValues[name][0]` are all the RANK 1 values.
 */

export const AbilitySlotSchema = z.enum(["passive", "Q", "W", "E", "R"]);
export type AbilitySlot = z.infer<typeof AbilitySlotSchema>;

export const AbilityFactsSchema = z.object({
  /** Display name of the ability (e.g. "Feast"). */
  name: z.string().min(1),
  /** Number of learnable ranks. Passives are recorded as 1. */
  maxRank: z.number().int().min(1).max(6),
  /** Cooldown in seconds per rank; `[0]` = rank 1. Empty for passives. */
  cooldownByRank: z.array(z.number()),
  /** Resource cost per rank; `[0]` = rank 1. Empty for passives. */
  costByRank: z.array(z.number()),
  /** Resource the cost is paid in (e.g. "Mana", "Energy", "No Cost"). */
  costType: z.string(),
  /** Cast range per rank; `[0]` = rank 1. Empty for passives. */
  rangeByRank: z.array(z.number()),
  /**
   * Named per-rank numbers from the CommunityDragon champion bin
   * (`mSpell.DataValues`), e.g. `RBaseDamage: [300, 475, 650]`.
   * `values[0]` = rank 1; arrays are sliced to `maxRank` entries.
   */
  dataValues: z.record(z.string(), z.array(z.number())),
  /**
   * Tooltip with markup stripped and `{{ placeholder }}` tokens substituted
   * with real numbers where they could be resolved without guessing. Tokens
   * that could not be resolved remain literal `{{ token }}` text.
   */
  resolvedDescription: z.string(),
  /** Placeholder tokens left unresolved in `resolvedDescription`. */
  unresolved: z.array(z.string()),
});
export type AbilityFacts = z.infer<typeof AbilityFactsSchema>;

export const ChampionAbilityFactsSchema = z.object({
  /** Data Dragon key, also the asset filename (e.g. "Chogath", "MonkeyKing"). */
  championKey: z.string().min(1),
  /** Riot display name (e.g. "Cho'Gath", "Wukong"). */
  championName: z.string().min(1),
  abilities: z.object({
    passive: AbilityFactsSchema,
    Q: AbilityFactsSchema,
    W: AbilityFactsSchema,
    E: AbilityFactsSchema,
    R: AbilityFactsSchema,
  }),
});
export type ChampionAbilityFacts = z.infer<typeof ChampionAbilityFactsSchema>;

export type AbilityFactsLookup =
  | { status: "found"; facts: ChampionAbilityFacts }
  | {
      status: "not_found";
      /** Riot display names of the closest-matching champions. */
      suggestions: string[];
    };

const factsCache = new Map<string, ChampionAbilityFacts>();

function levenshtein(a: string, b: string): number {
  const previous = Array.from({ length: b.length + 1 }, (_, index) => index);
  for (let i = 1; i <= a.length; i++) {
    let diagonal = previous[0] ?? 0;
    previous[0] = i;
    for (let j = 1; j <= b.length; j++) {
      const above = previous[j] ?? 0;
      const left = previous[j - 1] ?? 0;
      const substitutionCost = a[i - 1] === b[j - 1] ? 0 : 1;
      previous[j] = Math.min(above + 1, left + 1, diagonal + substitutionCost);
      diagonal = above;
    }
  }
  return previous[b.length] ?? 0;
}

/**
 * Closest-match champion display names for an input that resolved to nothing.
 * Substring search first (catches partial names); edit distance as a fallback
 * (catches speech-to-text mangling like "chogarth").
 */
export function suggestChampionNames(input: string, limit = 3): string[] {
  const fromSearch = searchChampions(input, limit).map((c) => c.name);
  if (fromSearch.length > 0) {
    return fromSearch;
  }
  const query = input.toLowerCase().replaceAll(/[^a-z0-9]/g, "");
  return getAllChampions()
    .map((champion) => ({
      name: champion.name,
      distance: levenshtein(
        query,
        champion.name.toLowerCase().replaceAll(/[^a-z0-9]/g, ""),
      ),
    }))
    .toSorted(
      (left, right) =>
        left.distance - right.distance || left.name.localeCompare(right.name),
    )
    .slice(0, limit)
    .map((entry) => entry.name);
}

/**
 * Load grounded ability facts for a champion from the committed assets.
 *
 * The champion name is a user boundary (voice/Discord input): any casing,
 * spacing, punctuation, or registered spoken alias resolves. An unknown name
 * returns closest-match suggestions instead of throwing. A committed file
 * that fails schema validation throws loudly — that is a broken internal
 * contract, not user error.
 */
export async function getAbilityFacts(
  championName: string,
): Promise<AbilityFactsLookup> {
  const key = normalizeChampionName(championName);
  // Only registry-known keys touch the filesystem: an unresolved name comes
  // back verbatim from normalizeChampionName and must not become a path.
  if (getChampionByKey(key) === undefined) {
    return {
      status: "not_found",
      suggestions: suggestChampionNames(championName),
    };
  }

  const cached = factsCache.get(key);
  if (cached !== undefined) {
    return { status: "found", facts: cached };
  }

  const file = Bun.file(`${import.meta.dir}/assets/ability-facts/${key}.json`);
  if (!(await file.exists())) {
    return {
      status: "not_found",
      suggestions: suggestChampionNames(championName),
    };
  }

  const facts = ChampionAbilityFactsSchema.parse(await file.json());
  factsCache.set(key, facts);
  return { status: "found", facts };
}
