import { z } from "zod";

/**
 * Champion skin lookup functions.
 * Uses champion-skins.json generated by the update-data-dragon script.
 *
 * The JSON contains:
 * - baseSkins: champion → array of skin nums with loading screen art
 * - chromaToParent: champion → { chromaNum → parentSkinNum }
 */

const ChampionSkinsDataSchema = z.object({
  baseSkins: z.record(z.string(), z.array(z.number())),
  chromaToParent: z.record(z.string(), z.record(z.string(), z.number())),
});

type ChampionSkinsData = z.infer<typeof ChampionSkinsDataSchema>;

let skinsData: ChampionSkinsData | undefined;

async function loadSkinsData(): Promise<ChampionSkinsData> {
  if (skinsData !== undefined) {
    return skinsData;
  }

  const filePath = new URL("./assets/champion-skins.json", import.meta.url)
    .pathname;
  const file = Bun.file(filePath);
  const exists = await file.exists();

  if (!exists) {
    throw new Error(
      `champion-skins.json not found at ${filePath}. Run 'bun run update-data-dragon' in packages/data to generate it.`,
    );
  }

  const content = await file.text();
  skinsData = ChampionSkinsDataSchema.parse(JSON.parse(content));
  return skinsData;
}

/**
 * Get all available base skin numbers for a champion.
 * These are skins that have their own loading screen art (not chromas).
 * @param championName - Champion key (e.g., "Aatrox", "LeeSin")
 * @returns Array of valid skin numbers (e.g., [0, 1, 2, 3, 7, 8])
 */
export async function getAvailableSkins(
  championName: string,
): Promise<number[]> {
  const data = await loadSkinsData();
  return data.baseSkins[championName] ?? [0];
}

/**
 * Check if a specific skin number has its own loading screen art.
 * @param championName - Champion key (e.g., "Aatrox")
 * @param skinNum - Skin number to check
 * @returns true if the skin is a base skin with its own loading screen image
 */
export async function isSkinAvailable(
  championName: string,
  skinNum: number,
): Promise<boolean> {
  const skins = await getAvailableSkins(championName);
  return skins.includes(skinNum);
}

/**
 * Resolve a skin number to the correct loading screen image skin number.
 * If the skin is a chroma, returns the parent skin's number instead.
 * If the skin is a base skin, returns it unchanged.
 * If not found in either, returns 0 (default skin).
 *
 * @param championName - Champion key (e.g., "Aatrox")
 * @param skinNum - Skin number from spectator API (lastSelectedSkinIndex)
 * @returns Skin number that has a loading screen image on disk
 */
export async function resolveLoadingSkinNum(
  championName: string,
  skinNum: number,
): Promise<number> {
  const data = await loadSkinsData();

  // Check if it's a base skin with its own image
  const baseSkins = data.baseSkins[championName] ?? [0];
  if (baseSkins.includes(skinNum)) {
    return skinNum;
  }

  // Check if it's a chroma — map to parent skin
  const chromaMap = data.chromaToParent[championName];
  if (chromaMap !== undefined) {
    const parentNum = chromaMap[String(skinNum)];
    if (parentNum !== undefined) {
      return parentNum;
    }
  }

  // Unknown skin number — fall back to default
  return 0;
}
