import { z } from "zod";

/**
 * Champion skin lookup functions.
 * Uses champion-skins.json generated by the update-data-dragon script.
 * Maps champion names to arrays of valid skin numbers (excluding chromas).
 */

const ChampionSkinsMapSchema = z.record(z.string(), z.array(z.number()));

type ChampionSkinsMap = z.infer<typeof ChampionSkinsMapSchema>;

let skinsMap: ChampionSkinsMap | undefined;

async function loadSkinsMap(): Promise<ChampionSkinsMap> {
  if (skinsMap !== undefined) {
    return skinsMap;
  }

  const filePath = new URL("./assets/champion-skins.json", import.meta.url)
    .pathname;
  const file = Bun.file(filePath);
  const exists = await file.exists();

  if (!exists) {
    throw new Error(
      `champion-skins.json not found at ${filePath}. Run 'bun run update-data-dragon' in packages/data to generate it.`,
    );
  }

  const content = await file.text();
  skinsMap = ChampionSkinsMapSchema.parse(JSON.parse(content));
  return skinsMap;
}

/**
 * Get all available skin numbers for a champion.
 * @param championName - Champion key (e.g., "Aatrox", "LeeSin")
 * @returns Array of valid skin numbers (e.g., [0, 1, 2, 3])
 */
export async function getAvailableSkins(
  championName: string,
): Promise<number[]> {
  const map = await loadSkinsMap();
  return map[championName] ?? [0];
}

/**
 * Check if a specific skin is available for a champion.
 * @param championName - Champion key (e.g., "Aatrox")
 * @param skinNum - Skin number to check
 * @returns true if the skin exists in the local asset cache
 */
export async function isSkinAvailable(
  championName: string,
  skinNum: number,
): Promise<boolean> {
  const skins = await getAvailableSkins(championName);
  return skins.includes(skinNum);
}
