// AUTO-GENERATED by packages/data/scripts/update-data-dragon.ts.
// Do not edit by hand — rerun `bun run update-data-dragon` to regenerate.
//
// Maps PascalCased Twisted output (`resolveChampionKey`) to the actual
// Data Dragon filename key when they differ. Every entry means Twisted and
// Data Dragon disagree about a champion's canonical name for the current
// asset version.

export const championNameOverrides: Record<string, string> = {
  JarvanIv: "JarvanIV",
  Ksante: "KSante",
  Reksai: "RekSai",
  RenataGlasc: "Renata",
};
