import type { Lane } from "#src/model/lane.ts";
import championList from "./assets/champion.json" with { type: "json" };
import { championNameOverrides } from "./champion-name-overrides.generated.ts";
import { latestVersion } from "./version.ts";

// Case-insensitive map from any-casing champion name to the canonical
// Data Dragon key (the on-disk filename stem). Built once at module init
// from the bundled `champion.json`. Handles Riot's match-data quirks
// where `participant.championName` arrives in non-canonical casing —
// most famously `"FiddleSticks"` (capital S) when the file is
// `Fiddlesticks.png`. Any future per-champion casing surprise from
// Riot is absorbed automatically without a code change.
const canonicalChampionNames: Record<string, string> = Object.fromEntries(
  Object.keys(championList.data).map((key) => [key.toLowerCase(), key]),
);

// Numeric champion id → canonical Data Dragon key (the on-disk filename stem),
// built once at module init from the bundled `champion.json`. This is the
// authoritative, self-updating id→key source: `twisted`'s hardcoded champion
// enum lags Data Dragon by weeks (e.g. it had no entry for 805/Locke, so
// `resolveChampionKey` fell back to `Champion805` and the loading-screen image
// 404'd). Refreshing assets via `update-data-dragon` keeps this map current
// for every new champion without a code change.
const championKeyById: Record<number, string> = Object.fromEntries(
  Object.entries(championList.data).map(([key, champion]) => [
    Number(champion.key),
    key,
  ]),
);

/**
 * Resolve a numeric champion id to its canonical Data Dragon key using the
 * bundled `champion.json`. Returns `undefined` if the id is absent (the assets
 * are out of date — run `update-data-dragon`).
 */
export function getChampionKeyById(championId: number): string | undefined {
  return championKeyById[championId];
}

// Canonical Data Dragon key (lowercased) → Riot's human display name, e.g.
// "velkoz" -> "Vel'Koz", "monkeyking" -> "Wukong". Riot ships the correctly
// punctuated display name directly in `champion.json`'s `name` field, so this
// is a straight lookup table — no string transform (title-casing,
// underscore-splitting, etc.) can reconstruct apostrophes like Vel'Koz or
// renames like MonkeyKing -> Wukong.
const championDisplayNames: Record<string, string> = Object.fromEntries(
  Object.values(championList.data).map((champion) => [
    champion.id.toLowerCase(),
    champion.name,
  ]),
);

// Numeric champion id → Riot's human display name, built from the same
// `champion.json` source. Twisted-free, so unlike the twisted-enum-based
// name lookup it never lags behind newly-released champions.
const championDisplayNamesById: Record<number, string> = Object.fromEntries(
  Object.values(championList.data).map((champion) => [
    Number(champion.key),
    champion.name,
  ]),
);

/**
 * Resolve a raw/any-case champion name (e.g. Riot match-data's
 * `participant.championName`, or a Data Dragon asset key) to Riot's human
 * display name. Normalizes the lookup key first, then looks up the display
 * name in `championDisplayNames` — never derives it via string mangling.
 */
export function championNameToDisplayName(championName: string): string {
  const normalized = normalizeChampionName(championName);
  return championDisplayNames[normalized.toLowerCase()] ?? normalized;
}

/**
 * Resolve a numeric champion id directly to Riot's human display name using
 * the bundled `champion.json`. Falls back to a `Champion<id>` placeholder
 * only if the id is entirely absent from the bundled assets (stale assets —
 * run `update-data-dragon`).
 */
export function getChampionDisplayNameById(championId: number): string {
  return (
    championDisplayNamesById[championId] ?? `Champion${championId.toString()}`
  );
}

const championDisplayNameAliases: Record<string, string> = {
  "nunu & willump": "Nunu",
};

// `championNameOverrides` is auto-generated by `update-data-dragon.ts`.
// Twisted's `getChampionName(id)` returns SCREAMING_SNAKE_CASE, and
// `resolveChampionKey` PascalCases it for Data Dragon. Twisted and Data
// Dragon disagree about canonical names for some champions — e.g. Twisted
// returns `REKSAI` → `Reksai` but the on-disk file is `RekSai.png`, and
// Twisted returns `RENATA_GLASC` → `RenataGlasc` but the file is
// `Renata.png`. The generated map covers Twisted-vs-DataDragon drift; the
// case-insensitive lookup above handles Riot match-data casing quirks.

export function normalizeChampionName(championName: string): string {
  const decodedChampionName = championName.includes("%")
    ? decodeURIComponent(championName)
    : championName;
  const lowerName = decodedChampionName.toLowerCase();
  return (
    canonicalChampionNames[lowerName] ??
    championDisplayNameAliases[lowerName] ??
    championNameOverrides[decodedChampionName] ??
    decodedChampionName
  );
}

function getAbsolutePath(relativePath: string): string {
  return new URL(relativePath, import.meta.url).pathname;
}

async function validateImageExists(
  absolutePath: string,
  description: string,
): Promise<void> {
  const file = Bun.file(absolutePath);
  const exists = await file.exists();

  if (!exists) {
    throw new Error(
      `${description} not found at ${absolutePath}. Run 'bun run update-data-dragon' in packages/data to cache latest assets.`,
    );
  }
}

// Helper function to load an image as base64 data URI
async function loadImageAsBase64(
  relativePath: string,
  mimeType: string,
): Promise<string> {
  const absolutePath = getAbsolutePath(relativePath);
  const file = Bun.file(absolutePath);
  const exists = await file.exists();

  if (!exists) {
    throw new Error(
      `Image not found at ${absolutePath}. Run 'bun run update-data-dragon' in packages/data to cache latest assets.`,
    );
  }

  const buffer = await file.arrayBuffer();
  const base64 = Buffer.from(buffer).toString("base64");
  return `data:${mimeType};base64,${base64}`;
}

// Validation functions (async, for preloading/checking)
export async function validateChampionImage(
  championName: string,
): Promise<void> {
  const normalized = normalizeChampionName(championName);
  const relativePath = `./assets/img/champion/${normalized}.png`;
  const absolutePath = getAbsolutePath(relativePath);
  await validateImageExists(absolutePath, `Champion image for ${normalized}`);
}

export async function validateItemImage(itemId: number): Promise<void> {
  const relativePath = `./assets/img/item/${itemId.toString()}.png`;
  const absolutePath = getAbsolutePath(relativePath);
  await validateImageExists(
    absolutePath,
    `Item image for item ${itemId.toString()}`,
  );
}

export async function validateSpellImage(
  spellImageName: string,
): Promise<void> {
  const relativePath = `./assets/img/spell/${spellImageName}`;
  const absolutePath = getAbsolutePath(relativePath);
  await validateImageExists(
    absolutePath,
    `Summoner spell image ${spellImageName}`,
  );
}

export async function validateRuneIcon(runeIconPath: string): Promise<void> {
  const filename = runeIconPath.split("/").pop() ?? "unknown.png";
  const relativePath = `./assets/img/rune/${filename}`;
  const absolutePath = getAbsolutePath(relativePath);
  await validateImageExists(absolutePath, `Rune image ${filename}`);
}

export async function validateAugmentIcon(
  augmentIconPath: string,
): Promise<void> {
  const filename = augmentIconPath.split("/").pop() ?? "unknown.png";
  const relativePath = `./assets/img/augment/${filename}`;
  const absolutePath = getAbsolutePath(relativePath);
  await validateImageExists(absolutePath, `Augment image ${filename}`);
}

export async function validateLaneIcon(lane: Lane): Promise<void> {
  const relativePath = `./assets/img/lane/${lane}.png`;
  const absolutePath = getAbsolutePath(relativePath);
  await validateImageExists(absolutePath, `Lane icon for ${lane}`);
}

// URL getters (synchronous, for use in components)
export function getChampionImageUrl(championName: string): string {
  const normalized = normalizeChampionName(championName);
  return `https://ddragon.leagueoflegends.com/cdn/${latestVersion}/img/champion/${normalized}.png`;
}

export function getItemImageUrl(itemId: number): string {
  return `https://ddragon.leagueoflegends.com/cdn/${latestVersion}/img/item/${itemId.toString()}.png`;
}

export function getSpellImageUrl(spellImageName: string): string {
  return `https://ddragon.leagueoflegends.com/cdn/${latestVersion}/img/spell/${spellImageName}`;
}

export function getRuneIconUrl(runeIconPath: string): string {
  return `https://ddragon.leagueoflegends.com/cdn/img/${runeIconPath}`;
}

export function getAugmentIconUrl(augmentIconPath: string): string {
  return `https://raw.communitydragon.org/latest/game/${augmentIconPath}`;
}

// Base64 getters (async, for Satori/server-side rendering with local cached assets)
export async function getChampionImageBase64(
  championName: string,
): Promise<string> {
  const normalized = normalizeChampionName(championName);
  const relativePath = `./assets/img/champion/${normalized}.png`;
  return loadImageAsBase64(relativePath, "image/png");
}

export async function getItemImageBase64(itemId: number): Promise<string> {
  const relativePath = `./assets/img/item/${itemId.toString()}.png`;
  return loadImageAsBase64(relativePath, "image/png");
}

export async function getSpellImageBase64(
  spellImageName: string,
): Promise<string> {
  const relativePath = `./assets/img/spell/${spellImageName}`;
  return loadImageAsBase64(relativePath, "image/png");
}

export async function getRuneIconBase64(runeIconPath: string): Promise<string> {
  const filename = runeIconPath.split("/").pop() ?? "unknown.png";
  const relativePath = `./assets/img/rune/${filename}`;
  return loadImageAsBase64(relativePath, "image/png");
}

export async function getAugmentIconBase64(
  augmentIconPath: string,
): Promise<string> {
  const filename = augmentIconPath.split("/").pop() ?? "unknown.png";
  const relativePath = `./assets/img/augment/${filename}`;
  return loadImageAsBase64(relativePath, "image/png");
}

export async function getLaneIconBase64(lane: Lane): Promise<string> {
  const relativePath = `./assets/img/lane/${lane}.png`;
  return loadImageAsBase64(relativePath, "image/png");
}

// Champion loading screen art (tall portrait images used in LoL loading screen)

export async function validateChampionLoadingImage(
  championName: string,
  skinNum: number,
): Promise<void> {
  const normalized = normalizeChampionName(championName);
  const relativePath = `./assets/img/champion-loading/${normalized}_${skinNum.toString()}.jpg`;
  const absolutePath = getAbsolutePath(relativePath);
  await validateImageExists(
    absolutePath,
    `Champion loading image for ${normalized} skin ${skinNum.toString()}`,
  );
}

export function getChampionLoadingImageUrl(
  championName: string,
  skinNum = 0,
): string {
  const normalized = normalizeChampionName(championName);
  return `https://ddragon.leagueoflegends.com/cdn/img/champion/loading/${normalized}_${skinNum.toString()}.jpg`;
}

/**
 * Fired by `getChampionLoadingImageBase64` when the requested skin's JPG is
 * not on disk and we fall back to the base skin (skin 0). The caller is
 * expected to log/meter — this is expected (not exceptional) behaviour for
 * the small window between Riot releasing a new skin and the next
 * `update-data-dragon` run.
 */
export type SkinFallbackEvent = {
  championName: string;
  requestedSkin: number;
};

export async function getChampionLoadingImageBase64(
  championName: string,
  skinNum = 0,
  onSkinFallback?: (event: SkinFallbackEvent) => void,
): Promise<string> {
  const normalized = normalizeChampionName(championName);
  const requested = `./assets/img/champion-loading/${normalized}_${skinNum.toString()}.jpg`;
  const requestedAbs = getAbsolutePath(requested);

  if (await Bun.file(requestedAbs).exists()) {
    return loadImageAsBase64(requested, "image/jpeg");
  }

  // Defense-in-depth: with the update-data-dragon CommunityDragon fallback
  // in place this should be rare — only triggers when Riot ships a new skin
  // between asset refreshes. When it fires we still post a real image
  // (default skin) instead of the text-only fallback embed; the metric in
  // the backend tells us to refresh the asset cache.
  if (skinNum !== 0) {
    onSkinFallback?.({ championName: normalized, requestedSkin: skinNum });
    return loadImageAsBase64(
      `./assets/img/champion-loading/${normalized}_0.jpg`,
      "image/jpeg",
    );
  }

  throw new Error(
    `Image not found at ${requestedAbs}. Run 'bun run update-data-dragon' in packages/data to cache latest assets.`,
  );
}
