#!/usr/bin/env bash
# Parse the latest Bazel profile and print a performance summary.
# Profile is auto-generated by --profile in .bazelrc.
set -euo pipefail

# Ensure bazel/bazelisk is on PATH (mise shims)
export PATH="$HOME/.local/share/mise/shims:$PATH"

PROFILE="${1:-$HOME/.cache/bazel-profile.gz}"

if [ ! -f "$PROFILE" ]; then
    echo "No profile found at $PROFILE"
    echo "Run a bazel build/test first — profiling is always-on via .bazelrc"
    exit 1
fi

echo ""
echo "Bazel Build Performance ($(stat -f '%Sm' "$PROFILE" 2>/dev/null || stat -c '%y' "$PROFILE" 2>/dev/null | cut -d. -f1))"
echo "════════════════════════════════════════"
echo ""

# Find bazel binary (prefer bazelisk)
BAZEL=$(command -v bazelisk 2>/dev/null || command -v bazel 2>/dev/null) || {
    echo "Neither bazelisk nor bazel found on PATH"; exit 1
}

# Run analyze-profile and capture output
ANALYSIS=$("$BAZEL" analyze-profile "$PROFILE" 2>&1 | grep -v "^WARNING\|^INFO\|^$\|Script against")

# Print phase summary
echo "$ANALYSIS" | awk '/PHASE SUMMARY/{found=1; next} /Critical path/{exit} found'

echo ""
echo "────────────────────────────────────────"
echo ""

# Print critical path
echo "$ANALYSIS" | awk '/Critical path/{found=1} found'

echo ""
echo "────────────────────────────────────────"
echo "Profile: $PROFILE"
echo "View in browser: ui.perfetto.dev (drag & drop the .gz file)"
echo ""
