"""Repository rule that runs `bun install` to create a hermetic npm dependency repo.

Creates an external Bazel repository (@bun_modules) containing:
- node_modules/ with all installed npm packages
- package_rule.bzl: rule that wraps packages with BunInfo
- BUILD.bazel: targets for each npm package
- defs.bzl: bun_link_all_packages macro for BUILD files
"""

_PACKAGE_RULE_BZL = """\
load("@monorepo//tools/rules_bun/bun:providers.bzl", "BunInfo")

def _bun_npm_package_impl(ctx):
    all_files = ctx.attr._all_npm[DefaultInfo].files
    return [
        DefaultInfo(files = all_files),
        BunInfo(
            target = ctx.label,
            sources = depset(),
            package_json = None,
            package_name = ctx.attr.package_name,
            transitive_sources = depset(),
            npm_sources = all_files,
            workspace_deps = depset(),
        ),
    ]

bun_npm_package = rule(
    implementation = _bun_npm_package_impl,
    attrs = {
        "package_name": attr.string(),
        "_all_npm": attr.label(default = "//:_all_npm_sources"),
    },
)
"""

# Script to parse bun.lock and produce workspace deps + package list as JSON.
# bun.lock uses JSONC (trailing commas) so we use bun to parse it.
_PARSE_LOCK_SCRIPT = """\
const text = await Bun.file(process.argv[2]).text();
const clean = text.replace(/,([\\s\\n]*[}\\]])/g, '$1');
const lock = JSON.parse(clean);

const workspaces = lock.workspaces || {};
const result = { workspaceDeps: {}, allPackages: [] };

// Collect deps per workspace
for (const [wsPath, wsInfo] of Object.entries(workspaces)) {
    const deps = new Set();
    for (const name of Object.keys(wsInfo.dependencies || {})) {
        const ver = wsInfo.dependencies[name];
        if (!ver.startsWith('workspace:')) deps.add(name);
    }
    for (const name of Object.keys(wsInfo.devDependencies || {})) {
        const ver = wsInfo.devDependencies[name];
        if (!ver.startsWith('workspace:')) deps.add(name);
    }
    for (const name of Object.keys(wsInfo.peerDependencies || {})) {
        deps.add(name);
    }
    for (const name of Object.keys(wsInfo.optionalDependencies || {})) {
        const ver = wsInfo.optionalDependencies[name];
        if (!ver.startsWith('workspace:')) deps.add(name);
    }
    result.workspaceDeps[wsPath] = [...deps].sort();
}

// Extract leaf package names from lockfile packages section.
// Keys are dependency paths like '@types/bun/bun-types/@types/node/undici-types'.
// The leaf (actual package name) is the last component — or last two for scoped packages.
const allPkgs = new Set();
for (const key of Object.keys(lock.packages || {})) {
    const parts = key.split('/');
    if (parts.length >= 2 && parts[parts.length - 2].startsWith('@')) {
        allPkgs.add(parts[parts.length - 2] + '/' + parts[parts.length - 1]);
    } else {
        allPkgs.add(parts[parts.length - 1]);
    }
}
result.allPackages = [...allPkgs].sort();

console.log(JSON.stringify(result));
"""

def _sanitize_name(name):
    """Convert npm package name to valid Bazel target name."""
    return name.replace("@", "").replace("/", "+")

def _generate_build_file(packages):
    """Generate BUILD.bazel content with targets for each npm package."""
    lines = [
        'load(":package_rule.bzl", "bun_npm_package")',
        "",
        'package(default_visibility = ["//visibility:public"])',
        "",
        "filegroup(",
        '    name = "_all_npm_sources",',
        '    srcs = glob(["node_modules/**"], exclude = ["node_modules/.bun/**", "node_modules/.cache/**"]),',
        ")",
        "",
    ]

    for pkg_name in sorted(packages):
        sanitized = _sanitize_name(pkg_name)
        lines.append("bun_npm_package(")
        lines.append('    name = "%s",' % sanitized)
        lines.append('    package_name = "%s",' % pkg_name)
        lines.append(")")
        lines.append("")

    return "\n".join(lines)

def _generate_defs_bzl(all_packages):
    """Generate defs.bzl with bun_link_all_packages macro."""
    lines = [
        '"""Generated by bun_install repository rule. Do not edit."""',
        "",
        "_ALL_PACKAGES = [",
    ]

    for pkg_name in sorted(all_packages.keys()):
        lines.append('    "%s",' % pkg_name)

    lines.append("]")
    lines.append("")
    lines.append("def _sanitize_name(name):")
    lines.append('    return name.replace("@", "").replace("/", "+")')
    lines.append("")
    lines.append('def bun_link_all_packages(name = "node_modules"):')
    lines.append("    for dep_name in _ALL_PACKAGES:")
    lines.append("        native.alias(")
    lines.append('            name = "%s/%s" % (name, dep_name),')
    lines.append('            actual = "@bun_modules//:%s" % _sanitize_name(dep_name),')
    lines.append('            visibility = ["//visibility:public"],')
    lines.append("        )")
    lines.append("")

    return "\n".join(lines)

def _bun_install_impl(rctx):
    bun = rctx.which("bun")
    if not bun:
        fail("bun not found on PATH. Install bun: https://bun.sh")

    # Symlink bun.lock from workspace
    rctx.symlink(rctx.attr.bun_lock, "bun.lock")

    # Symlink package.json files
    for pkg_json in rctx.attr.package_jsons:
        # pkg_json is a Label like @//packages/birmel:package.json
        # We need to place it at the correct workspace-relative path
        pkg_path = pkg_json.package
        if pkg_path:
            rctx.symlink(pkg_json, "%s/package.json" % pkg_path)
        else:
            rctx.symlink(pkg_json, "package.json")

    # Symlink pnpm-workspace.yaml if provided (needed during transition)
    if rctx.attr.pnpm_workspace:
        rctx.symlink(rctx.attr.pnpm_workspace, "pnpm-workspace.yaml")

    # Symlink additional data files (patches, configs, etc.) at workspace-relative paths
    for f in rctx.attr.data:
        f_pkg = f.package
        if f_pkg:
            rctx.symlink(f, "%s/%s" % (f_pkg, f.name))
        else:
            rctx.symlink(f, f.name)

    # Run bun install
    # First try with --frozen-lockfile for hermeticity.
    # If that fails, fall back to --no-save (avoids lockfile mutations).
    result = rctx.execute(
        [bun, "install", "--frozen-lockfile", "--ignore-scripts"],
        timeout = 300,
        quiet = False,
    )
    if result.return_code != 0:
        # --frozen-lockfile can fail when the sandbox workspace layout
        # causes bun to see trivial lockfile diffs (e.g. missing non-JS
        # workspace members that exist on disk but aren't declared in
        # package_jsons).  Fall back to a non-frozen install that still
        # won't mutate the real lockfile (it's a symlink to a read-only
        # Bazel input, and --no-save suppresses writes).
        result = rctx.execute(
            [bun, "install", "--no-save", "--ignore-scripts"],
            timeout = 300,
            quiet = False,
        )
        if result.return_code != 0:
            fail("bun install failed (exit %d):\nstdout: %s\nstderr: %s" % (
                result.return_code,
                result.stdout,
                result.stderr,
            ))

    # Parse bun.lock to get workspace deps mapping
    parse_script = rctx.path("_parse_lock.ts")
    rctx.file("_parse_lock.ts", _PARSE_LOCK_SCRIPT)

    result = rctx.execute(
        [bun, "run", str(parse_script), "bun.lock"],
        timeout = 30,
    )
    if result.return_code != 0:
        fail("Failed to parse bun.lock:\nstdout: %s\nstderr: %s" % (
            result.stdout,
            result.stderr,
        ))

    lock_data = json.decode(result.stdout.strip())
    workspace_deps = lock_data["workspaceDeps"]

    # Use all installed packages from node_modules scan
    # This includes transitive deps that BUILD files may reference
    all_packages = {}
    for pkg in lock_data.get("allPackages", []):
        all_packages[pkg] = True

    # Also ensure workspace deps and bins are included
    for deps in workspace_deps.values():
        for dep in deps:
            all_packages[dep] = True
    for pkg_name in rctx.attr.bins.keys():
        all_packages[pkg_name] = True

    # Generate files
    rctx.file("package_rule.bzl", _PACKAGE_RULE_BZL)
    rctx.file("BUILD.bazel", _generate_build_file(all_packages))
    rctx.file("defs.bzl", _generate_defs_bzl(all_packages))

    # Clean up temp files
    rctx.delete("_parse_lock.ts")

bun_install = repository_rule(
    implementation = _bun_install_impl,
    attrs = {
        "bun_lock": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "Label for bun.lock file",
        ),
        "package_jsons": attr.label_list(
            mandatory = True,
            allow_files = ["package.json"],
            doc = "Labels for all workspace package.json files",
        ),
        "data": attr.label_list(
            default = [],
            allow_files = True,
            doc = "Additional files needed during bun install (patches, configs, etc.)",
        ),
        "pnpm_workspace": attr.label(
            allow_single_file = True,
            doc = "Label for pnpm-workspace.yaml (temporary, for transition)",
        ),
        "bins": attr.string_list_dict(
            default = {},
            doc = "Map of package name to list of bin entries (e.g. tsc=./bin/tsc)",
        ),
    },
    environ = ["HOME", "PATH", "BUN_INSTALL"],
)
