name: AdventOfCode2021
version: 0.1.0.0
github: "shepherdjerred/advent-of-code-2021"
license: "GPL-3.0"
author: "Jerred Shepherd"
maintainer: "shepherdjerred@gmail.com"
copyright: "2021 Jerred Shepherd"

extra-source-files:
  - README.md

description: My solutions to Advent of Code 2021

dependencies:
  - base >= 4.7 && < 5
  - split >= 0.2.3.4 && < 0.3
  - containers >= 0.6.5.1 && < 0.7
  - multiset >= 0.3.4.3 && < 0.4

library:
  source-dirs: src

executables:
  Day1:
    main: Main.hs
    source-dirs: Day1
  Day2:
    main: Main.hs
    source-dirs: Day2
  Day3:
    main: Main.hs
    source-dirs: Day3
  Day4:
    main: Main.hs
    source-dirs: Day4
  Day5:
    main: Main.hs
    source-dirs: Day5
  Day6:
    main: Main.hs
    source-dirs: Day6
  Day7:
    main: Main.hs
    source-dirs: Day7
