agents:
  queue: default

steps:
  - label: ":pipeline: Generate Pipeline"
    command: .buildkite/scripts/generate-pipeline.sh
    plugins:
      - kubernetes:
          checkout:
            cloneFlags: "--depth=100 --dissociate"
            fetchFlags: --depth=100
          podSpecPatch:
            serviceAccountName: buildkite-agent-stack-k8s-controller
            containers:
              - name: container-0
                image: "ghcr.io/shepherdjerred/ci-base:402"
                resources:
                  requests:
                    cpu: "1"
                    memory: "2Gi"
                  limits:
                    cpu: "1"
                    memory: "2Gi"
                envFrom:
                  - secretRef:
                      name: buildkite-ci-secrets
              - name: agent
                resources:
                  requests:
                    cpu: "100m"
                    memory: "128Mi"
                  limits:
                    cpu: "500m"
                    memory: "256Mi"
              - name: checkout
                resources:
                  requests:
                    cpu: "100m"
                    memory: "128Mi"
                  limits:
                    cpu: "500m"
                    memory: "256Mi"
              - name: copy-agent
                resources:
                  requests:
                    cpu: "100m"
                    memory: "128Mi"
                  limits:
                    cpu: "500m"
                    memory: "256Mi"
