agents:
  queue: default

steps:
  - label: ":dagger: CI"
    key: ci
    image: "oven/bun:debian"
    command: .buildkite/scripts/ci.sh
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 255
          limit: 2
    plugins:
      - kubernetes:
          checkout:
            cloneFlags: --depth=1
            fetchFlags: --depth=1
          podSpecPatch:
            serviceAccountName: buildkite-agent-stack-k8s-controller
            containers:
              - name: container-0
                envFrom:
                  - secretRef:
                      name: buildkite-ci-secrets

  - label: ":robot_face: Code Review"
    key: code-review
    if: build.pull_request.id != null
    image: "oven/bun:debian"
    command: .buildkite/scripts/code-review.sh
    timeout_in_minutes: 30
    soft_fail: true
    plugins:
      - kubernetes:
          checkout:
            cloneFlags: --depth=1
            fetchFlags: --depth=1
          podSpecPatch:
            serviceAccountName: buildkite-agent-stack-k8s-controller
            containers:
              - name: container-0
                envFrom:
                  - secretRef:
                      name: buildkite-ci-secrets

  - wait: ~
    if: build.branch == pipeline.default_branch

  - label: ":books: Update READMEs"
    key: update-readmes
    if: build.branch == pipeline.default_branch
    image: "oven/bun:debian"
    command: .buildkite/scripts/update-readmes.sh
    timeout_in_minutes: 30
    plugins:
      - kubernetes:
          checkout:
            cloneFlags: --depth=1
            fetchFlags: --depth=1
          podSpecPatch:
            serviceAccountName: buildkite-agent-stack-k8s-controller
            containers:
              - name: container-0
                envFrom:
                  - secretRef:
                      name: buildkite-ci-secrets
