// Generates packages/backend/src/game/spatial/generated/map-names.ts from
// pokeemerald-wasm's data/maps/map_groups.json.
//
//   bun scripts/generate-map-names.ts
//
// The output is checked in. The source pin is the OTTOHG_SHA in
// scripts/build-wasm.sh (Renovate advances it) — read via lib/pokeemerald-pin,
// the same pin generate-species-data.ts uses. build-wasm.sh re-runs this
// generator after every wasm build.

import { readOttohgSha } from "./lib/pokeemerald-pin.ts";

const REF = await readOttohgSha();
const RAW = `https://raw.githubusercontent.com/ottohg/pokeemerald-wasm/${REF}`;
const OUT = new URL(
  "../packages/backend/src/game/spatial/generated/map-names.ts",
  import.meta.url,
).pathname;

type MapGroupsJson = {
  group_order: string[];
  [key: string]: string[];
};

async function fetchJson<T>(path: string): Promise<T> {
  const response = await fetch(`${RAW}/${path}`);
  if (!response.ok) {
    throw new Error(`failed to fetch ${path}: ${String(response.status)}`);
  }
  return response.json() as Promise<T>;
}

// "LittlerootTown_MaysHouse_1F" → "Littleroot Town: May's House 1F".
// "PetalburgCity_Gym" → "Petalburg City: Gym".
// "Route101" → "Route 101".
function humanize(rawName: string): string {
  const segments = rawName.split("_").map((seg) => splitPascal(seg));
  if (segments.length === 1) return segments[0];
  return `${segments[0]}: ${segments.slice(1).join(" — ")}`;
}

function splitPascal(s: string): string {
  // PetalburgCity → Petalburg City; Route101 → Route 101; MaysHouse → Mays House.
  // Then post-process "Mays" → "May's" (the rival's house).
  const spaced = s
    // Insert space before each uppercase letter that follows a lowercase one.
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    // Insert space before a digit only when a lowercase letter precedes it
    // (so "Route101" → "Route 101" but "B1F" / "B2F" basement labels stay
    // glued together — uppercase + digit is treated as one unit).
    .replace(/([a-z])(\d)/g, "$1 $2");
  // Note: deliberately do NOT split between digits and trailing letters so
  // "1F" / "B1F" / "2F" floor labels stay glued together.
  // Restore possessive apostrophes that pokeemerald's map IDs strip ("MaysHouse"
  // → "May's House"). Only known character names — don't blanket-add 's-or-not
  // since plenty of unrelated names end in -s.
  const possessives = ["Mays", "Brendans", "Birchs", "Stevens", "Brineys"];
  let out = spaced;
  for (const p of possessives) {
    const re = new RegExp(`\\b${p}\\b`, "g");
    out = out.replace(re, `${p.slice(0, -1)}'s`);
  }
  return out;
}

const data = await fetchJson<MapGroupsJson>("data/maps/map_groups.json");

const lines: string[] = [];
lines.push("// Auto-generated by scripts/generate-map-names.ts. Do not edit.");
lines.push(`// Source: ottohg/pokeemerald-wasm@${REF}`);
lines.push("// (mapGroup, mapNum) → human name. Indices match pokeemerald's");
lines.push("// gMapGroup_* extern arrays.");
lines.push("");
lines.push("export const MAP_NAMES: readonly (readonly string[])[] = [");
for (const [groupIndex, groupName] of data.group_order.entries()) {
  const maps = data[groupName];
  if (!Array.isArray(maps)) {
    throw new Error(`map_groups.json missing group ${groupName}`);
  }
  lines.push(`  // ${groupName} (group ${String(groupIndex)})`);
  lines.push("  [");
  for (const mapName of maps) {
    const escaped = humanize(mapName).replace(/"/g, '\\"');
    lines.push(`    "${escaped}",`);
  }
  lines.push("  ],");
}
lines.push("] as const;");
lines.push("");
lines.push(
  "export function mapName(mapGroup: number, mapNum: number): string {",
);
lines.push(
  "  const group = mapGroup >= 0 && mapGroup < MAP_NAMES.length ? MAP_NAMES[mapGroup] : undefined;",
);
lines.push("  if (group === undefined) {");
lines.push(
  "    return `unknown map (group=${String(mapGroup)}, num=${String(mapNum)})`;",
);
lines.push("  }");
lines.push(
  "  const name = mapNum >= 0 && mapNum < group.length ? group[mapNum] : undefined;",
);
lines.push("  if (name === undefined) {");
lines.push(
  "    return `unknown map (group=${String(mapGroup)}, num=${String(mapNum)})`;",
);
lines.push("  }");
lines.push("  return name;");
lines.push("}");
lines.push("");

await Bun.write(OUT, lines.join("\n"));

// Format with Prettier (same as generate-species-data.ts) so regeneration is
// byte-stable against the committed, prettier-formatted file — without this
// the daily drift check would see permanent formatting-only phantom drift.
const fmt = Bun.spawn(["bunx", "prettier", "--write", OUT], {
  stdout: "inherit",
  stderr: "inherit",
});
const fmtExit = await fmt.exited;
if (fmtExit !== 0)
  throw new Error(`prettier exited with code ${String(fmtExit)}`);

console.log(`wrote ${OUT} (${String(data.group_order.length)} groups)`);
