// Generates packages/backend/src/game/events/data/species.generated.ts from the
// pokeemerald-wasm source headers (the exact source the wasm is built from).
//
//   bun scripts/generate-species-data.ts
//
// Run manually when the wasm is refreshed; the output is checked in. We pin a
// commit ref so the generated data matches a known source revision.
// Update REF to the exact commit SHA the pokeemerald.wasm binary was built from
// whenever the wasm is refreshed.

const REF = "ed25aa7c5ae9c3c338cc9aa57c7150fc33255ad3";
const RAW = `https://raw.githubusercontent.com/tripplyons/pokeemerald-wasm/${REF}`;

async function fetchText(path: string): Promise<string> {
  const response = await fetch(`${RAW}/${path}`);
  if (!response.ok) {
    throw new Error(`failed to fetch ${path}: ${String(response.status)}`);
  }
  return response.text();
}

// `#define SPECIES_FOO 123` -> Map FOO -> 123
function parseDefines(source: string, prefix: string): Map<string, number> {
  const out = new Map<string, number>();
  const re = new RegExp(`^#define ${prefix}(\\w+)\\s+(\\d+)`, "gm");
  for (const match of source.matchAll(re)) {
    const name = match[1];
    const value = match[2];
    if (name !== undefined && value !== undefined) {
      out.set(name, Number(value));
    }
  }
  return out;
}

// Sequential `enum { NATIONAL_DEX_NONE, NATIONAL_DEX_BULBASAUR, ... }` -> Map.
function parseEnum(source: string, prefix: string): Map<string, number> {
  const out = new Map<string, number>();
  const start = source.indexOf("enum {");
  const body = source.slice(start, source.indexOf("}", start));
  let index = 0;
  for (const line of body.split("\n")) {
    const match = new RegExp(`^\\s*${prefix}(\\w+),`).exec(line);
    if (match?.[1] !== undefined) {
      out.set(match[1], index);
      index += 1;
    }
  }
  return out;
}

// `[SPECIES_FOO] = _("NAME"),` -> Map FOO -> NAME
function parseNames(source: string): Map<string, string> {
  const out = new Map<string, string>();
  const re = /\[SPECIES_(\w+)\]\s*=\s*_\("([^"]*)"\)/g;
  for (const match of source.matchAll(re)) {
    const key = match[1];
    const name = match[2];
    if (key !== undefined && name !== undefined) out.set(key, name);
  }
  return out;
}

const [speciesSrc, namesSrc, pokedexSrc] = await Promise.all([
  fetchText("include/constants/species.h"),
  fetchText("src/data/text/species_names.h"),
  fetchText("include/constants/pokedex.h"),
]);

const speciesIds = parseDefines(speciesSrc, "SPECIES_");
const speciesNames = parseNames(namesSrc);
const nationalDex = parseEnum(pokedexSrc, "NATIONAL_DEX_");

const numSpecies = speciesIds.get("EGG");
if (numSpecies === undefined) throw new Error("SPECIES_EGG not found");

const names: string[] = new Array<string>(numSpecies + 1).fill("?");
const toNational: number[] = new Array<number>(numSpecies + 1).fill(0);
for (const [key, id] of speciesIds) {
  const name = speciesNames.get(key);
  if (name !== undefined) names[id] = name;
  const national = nationalDex.get(key);
  if (national !== undefined) toNational[id] = national;
}

// Reverse map: national dex number -> display name, for Pokédex entry events.
const nationalToName: Record<number, string> = {};
for (let id = 0; id <= numSpecies; id++) {
  const national = toNational[id];
  if (national !== undefined && national > 0) {
    nationalToName[national] = names[id] ?? "?";
  }
}

const header = `// AUTO-GENERATED by scripts/generate-species-data.ts — do not edit by hand.
// Source: tripplyons/pokeemerald-wasm@${REF}
// Names are indexed by internal species id (gPlayerParty / gBattleResults use
// internal ids). NATIONAL maps internal id -> national dex number.

export const NUM_SPECIES = ${String(numSpecies)};

export const SPECIES_NAMES: readonly string[] = ${JSON.stringify(names)};

export const SPECIES_TO_NATIONAL: readonly number[] = ${JSON.stringify(toNational)};

const NATIONAL_DEX_NAMES: Readonly<Record<number, string>> = ${JSON.stringify(nationalToName)};

export function speciesName(internalId: number): string {
  return SPECIES_NAMES[internalId] ?? \`#\${String(internalId)}\`;
}

export function nationalDexName(nationalNumber: number): string | undefined {
  return NATIONAL_DEX_NAMES[nationalNumber];
}
`;

const outPath = new URL(
  "../packages/backend/src/game/events/generated/species.ts",
  import.meta.url,
).pathname;
await Bun.write(outPath, header);

// Format with Prettier so the checked-in file always passes the art-prettier CI job.
const fmt = Bun.spawn(["bunx", "prettier", "--write", outPath], {
  stdout: "inherit",
  stderr: "inherit",
});
const fmtExit = await fmt.exited;
if (fmtExit !== 0)
  throw new Error(`prettier exited with code ${String(fmtExit)}`);

const named = names.filter((n) => n !== "?").length;
console.log(
  `wrote ${outPath}: ${String(numSpecies)} species, ${String(named)} named`,
);
