#!/bin/sh
#
# Pre-commit hook for monorepo
# Matches CI configuration
#

set -e

echo '+cargo test --all'
cargo test --all
echo '+cargo clippy --all-targets --all-features -- -D warnings'
cargo clippy --all-targets --all-features -- -D warnings
echo '+cargo fmt --all -- --check'
cargo fmt --all -- --check
