[tasks.dev]
description = "Set up development environment"
run = "bun install"


[tasks.check]
description = "Run all checks"
run = ["bun run lint", "bun run build", "bun run test"]

[tasks.lint]
description = "Run ESLint"
run = "bun run lint"

[tasks.build]
description = "Build the project"
run = "bun run build"

[tasks.test]
description = "Run tests"
run = "bun run test"
