import type { HaIntrospection } from "./introspect.ts";
import { KNOWN_EVENT_DATA } from "./known-events.ts";
import {
  fieldMetaFromSpec,
  targetDomainFromSpec,
  type FieldMeta,
} from "./selector-to-ts.ts";

export type EmitOptions = {
  schemaName: string;
  sourceHost: string;
  generatedAt: string;
};

export function emitSchemaModule(
  intro: HaIntrospection,
  options: EmitOptions,
): string {
  const entitiesLiteral = emitEntities(intro);
  const servicesLiteral = emitServices(intro);
  const eventsLiteral = emitEvents(intro);
  const eventDataLiteral = emitEventData(intro);
  return [
    header(options),
    entitiesLiteral,
    "",
    servicesLiteral,
    "",
    eventsLiteral,
    "",
    eventDataLiteral,
    "",
    emitSchemaType(options.schemaName),
    "",
  ].join("\n");
}

function header(options: EmitOptions): string {
  return [
    `// AUTO-GENERATED by @shepherdjerred/home-assistant ha-codegen — do not edit, do not commit.`,
    `// Source host: ${options.sourceHost}`,
    `// Generated at: ${options.generatedAt}`,
    `/* eslint-disable */`,
    ``,
  ].join("\n");
}

function emitEntities(intro: HaIntrospection): string {
  const entries: string[] = [];
  const sorted = intro.states.toSorted((a, b) =>
    a.entity_id.localeCompare(b.entity_id),
  );
  for (const state of sorted) {
    const domain = state.entity_id.includes(".")
      ? state.entity_id.slice(0, state.entity_id.indexOf("."))
      : "";
    const attributes = emitAttributeSample(state.attributes);
    entries.push(
      `  ${JSON.stringify(state.entity_id)}: { domain: ${JSON.stringify(domain)}, attributes: ${attributes} },`,
    );
  }
  return `export const entities = {\n${entries.join("\n")}\n} as const;`;
}

function emitAttributeSample(
  attributes: Readonly<Record<string, unknown>>,
): string {
  const props: string[] = [];
  const sortedKeys = Object.keys(attributes).toSorted((a, b) =>
    a.localeCompare(b),
  );
  for (const key of sortedKeys) {
    const value = attributes[key];
    const sample = sampleValueLiteral(value);
    if (sample !== undefined) {
      props.push(`${JSON.stringify(key)}: ${sample}`);
    }
  }
  return props.length === 0 ? `{}` : `{ ${props.join(", ")} }`;
}

function sampleValueLiteral(value: unknown): string | undefined {
  if (typeof value === "string") {
    return `""`;
  }
  if (typeof value === "number") {
    return `0`;
  }
  if (typeof value === "boolean") {
    return `false`;
  }
  if (value === null) {
    return `null`;
  }
  if (Array.isArray(value)) {
    return `[] as readonly unknown[]`;
  }
  if (typeof value === "object") {
    return `{}`;
  }
  return undefined;
}

function emitServices(intro: HaIntrospection): string {
  const domains: string[] = [];
  const sorted = intro.services.toSorted((a, b) =>
    a.domain.localeCompare(b.domain),
  );
  for (const entry of sorted) {
    const services: string[] = [];
    const serviceEntries = Object.entries(entry.services).toSorted(([a], [b]) =>
      a.localeCompare(b),
    );
    for (const [serviceName, spec] of serviceEntries) {
      const fields = Object.entries(spec.fields ?? {})
        .toSorted(([a], [b]) => a.localeCompare(b))
        .map(([fieldName, fieldSpec]) => {
          const meta = fieldMetaFromSpec(fieldSpec);
          return `      ${JSON.stringify(fieldName)}: ${emitFieldMeta(meta)}`;
        })
        .join(",\n");
      const targetDomain = targetDomainFromSpec(spec.target);
      const targetLiteral =
        targetDomain === undefined
          ? ""
          : `, target: { domain: ${JSON.stringify(targetDomain)} }`;
      const fieldsBlock = fields === "" ? `{}` : `{\n${fields}\n    }`;
      services.push(
        `    ${JSON.stringify(serviceName)}: { fields: ${fieldsBlock}${targetLiteral} },`,
      );
    }
    domains.push(
      `  ${JSON.stringify(entry.domain)}: {\n${services.join("\n")}\n  },`,
    );
  }
  return `export const services = {\n${domains.join("\n")}\n} as const;`;
}

function emitFieldMeta(meta: FieldMeta): string {
  const parts: string[] = [`type: ${JSON.stringify(meta.type)}`];
  parts.push(`required: ${meta.required ? "true" : "false"}`);
  if (meta.domain !== undefined) {
    parts.push(`domain: ${JSON.stringify(meta.domain)}`);
  }
  if (meta.options !== undefined) {
    const opts = meta.options.map((v) => JSON.stringify(v)).join(", ");
    parts.push(`options: [${opts}] as const`);
  }
  return `{ ${parts.join(", ")} }`;
}

function emitEvents(intro: HaIntrospection): string {
  const names = intro.events
    .map((e) => e.event)
    .toSorted((a, b) => a.localeCompare(b));
  const literal =
    names.length === 0
      ? "[]"
      : `[\n${names.map((n) => `  ${JSON.stringify(n)},`).join("\n")}\n]`;
  return `export const events = ${literal} as const;`;
}

function emitEventData(intro: HaIntrospection): string {
  const lines: string[] = [];
  const names = new Set(intro.events.map((e) => e.event));
  for (const [name, shape] of Object.entries(KNOWN_EVENT_DATA).toSorted(
    ([a], [b]) => a.localeCompare(b),
  )) {
    if (!names.has(name)) {
      continue;
    }
    lines.push(`  ${JSON.stringify(name)}: ${shape};`);
  }
  return `export type EventData = {\n${lines.join("\n")}\n};`;
}

function emitSchemaType(name: string): string {
  return [
    `export type ${name} = {`,
    `  entities: typeof entities;`,
    `  services: typeof services;`,
    `  events: (typeof events)[number];`,
    `  eventData: EventData;`,
    `};`,
  ].join("\n");
}
