/**
 * Type-level schema describing a specific Home Assistant instance's entities,
 * services, and events. Generated by the `ha-codegen` CLI (see src/codegen/)
 * from a live HA instance. Consumers parameterize the client classes with
 * their generated schema to get literal-union autocomplete and compile-time
 * rejection of unknown entity IDs, domains, services, or event types.
 *
 * The default schema (`DefaultHaSchema`) keeps the original loose behavior so
 * call sites that don't supply a schema see no type changes.
 */

export type HaFieldType =
  | "number"
  | "string"
  | "boolean"
  | "entity"
  | "object"
  | "unknown";

export type HaServiceFieldMeta = {
  readonly type: HaFieldType;
  readonly required?: boolean;
  /** For `type: "entity"` fields: narrow to entity IDs whose domain matches. */
  readonly domain?: string;
  /** For select-style fields, the allowed literal values. */
  readonly options?: readonly string[];
};

export type HaServiceMeta = {
  readonly fields: Readonly<Record<string, HaServiceFieldMeta>>;
  readonly target?: { readonly domain: string } | undefined;
  readonly response?: boolean;
};

export type HaEntityMeta = {
  readonly domain: string;
  readonly attributes: Readonly<Record<string, unknown>>;
};

export type HaSchema = {
  entities: Readonly<Record<string, HaEntityMeta>>;
  services: Readonly<Record<string, Readonly<Record<string, HaServiceMeta>>>>;
  events: string;
  eventData: Readonly<Record<string, unknown>>;
};

/**
 * Loose default used when no schema is supplied. Accepts any string for
 * entity IDs / domains / services / events and `Record<string, unknown>` for
 * service data — matching the pre-typed behavior.
 */
export type DefaultHaSchema = {
  entities: Record<string, HaEntityMeta>;
  services: Record<string, Record<string, HaServiceMeta>>;
  events: string;
  eventData: Record<string, unknown>;
};

type StringKeys<T> = Extract<keyof T, string>;

/** Entity IDs registered in `S` (all of them if `S` is the default schema). */
export type EntityId<S extends HaSchema> = StringKeys<S["entities"]>;

/**
 * Entity IDs whose domain is `D`. Narrowed when the schema has literal domains.
 *
 * For the loose {@link DefaultHaSchema} (entities keyed by `string` rather
 * than literal IDs), no literal can extend the requested domain, so the
 * mapped lookup collapses to `never`. Fall back to `EntityId<S>` in that
 * case so stub-typed workflows still accept domain-prefixed literals.
 */
export type EntityIdByDomain<S extends HaSchema, D extends string> =
  string extends StringKeys<S["entities"]>
    ? EntityId<S>
    : {
        [E in keyof S["entities"]]: S["entities"][E] extends {
          domain: infer DD;
        }
          ? DD extends D
            ? E
            : never
          : never;
      }[keyof S["entities"]] &
        string;

/** Valid domain names registered in `S`. */
export type Domain<S extends HaSchema> = StringKeys<S["services"]>;

/** Valid service names registered under domain `D` in `S`. */
export type Service<S extends HaSchema, D extends Domain<S>> = StringKeys<
  S["services"][D]
>;

/** Valid event types registered in `S`. */
export type EventType<S extends HaSchema> = S["events"] & string;

/** Translate a schema field meta to the TS type accepted in service data. */
type FieldType<
  S extends HaSchema,
  F extends HaServiceFieldMeta,
> = F["type"] extends "number"
  ? number
  : F["type"] extends "string"
    ? string
    : F["type"] extends "boolean"
      ? boolean
      : F["type"] extends "entity"
        ? F["domain"] extends string
          ?
              | EntityIdByDomain<S, F["domain"]>
              | readonly EntityIdByDomain<S, F["domain"]>[]
          : EntityId<S> | readonly EntityId<S>[]
        : F["type"] extends "object"
          ? Record<string, unknown>
          : unknown;

type RequiredFieldKeys<Fields extends Record<string, HaServiceFieldMeta>> = {
  [K in keyof Fields]: Fields[K]["required"] extends true ? K : never;
}[keyof Fields];

type OptionalFieldKeys<Fields extends Record<string, HaServiceFieldMeta>> = {
  [K in keyof Fields]: Fields[K]["required"] extends true ? never : K;
}[keyof Fields];

type FieldsAsObject<
  S extends HaSchema,
  Fields extends Record<string, HaServiceFieldMeta>,
> = {
  [K in RequiredFieldKeys<Fields>]: FieldType<S, Fields[K]>;
} & {
  [K in OptionalFieldKeys<Fields>]?: FieldType<S, Fields[K]>;
};

type TargetPart<S extends HaSchema, T> = T extends {
  domain: infer TD extends string;
}
  ? {
      entity_id?: EntityIdByDomain<S, TD> | readonly EntityIdByDomain<S, TD>[];
    }
  : { entity_id?: EntityId<S> | readonly EntityId<S>[] };

/**
 * Payload accepted by `callService(domain, service, ...)`. Includes:
 * - the generated field shape for this service
 * - an optional `entity_id` narrowed to same-domain entities when the service
 *   declares a target selector (falls back to any entity ID when it doesn't)
 */
export type ServiceDataFor<
  S extends HaSchema,
  D extends Domain<S>,
  V extends Service<S, D>,
> = S["services"][D][V] extends HaServiceMeta
  ? FieldsAsObject<S, S["services"][D][V]["fields"]> &
      TargetPart<S, S["services"][D][V]["target"]>
  : never;

/** Per-event data shape if the schema provides one, else `unknown`. */
export type EventDataFor<
  S extends HaSchema,
  E extends EventType<S>,
> = E extends keyof S["eventData"] ? S["eventData"][E] : unknown;

/**
 * Typed attribute shape for an entity when the schema lists it. Attributes
 * in HA are fluid so we keep this as a partial of the observed snapshot plus
 * an open index signature rather than pretending to be exhaustive.
 */
export type EntityAttributesFor<
  S extends HaSchema,
  E extends EntityId<S>,
> = S["entities"][E] extends { attributes: infer A }
  ? Partial<A> & Record<string, unknown>
  : Record<string, unknown>;

/**
 * Structural shape of an EntityState response (parallel to the Zod-inferred
 * `EntityState` from rest/schemas.ts) with the entity_id narrowed to a
 * specific literal and attributes typed per schema.
 */
export type EntityStateFor<S extends HaSchema, E extends EntityId<S>> = {
  entity_id: E;
  state: string;
  attributes: EntityAttributesFor<S, E>;
  last_changed?: string;
  last_updated?: string;
  last_reported?: string;
  context?: {
    id: string;
    parent_id?: string | null;
    user_id?: string | null;
  };
};

/**
 * Structural shape of an EventEnvelope with the event data narrowed per
 * schema. Parallel to the Zod-inferred `EventEnvelope` from ws/messages.ts.
 */
export type EventEnvelopeFor<S extends HaSchema, E extends EventType<S>> = {
  data?: EventDataFor<S, E> extends Record<string, unknown>
    ? EventDataFor<S, E>
    : Record<string, unknown>;
  event_type?: E;
  time_fired?: string;
  origin?: string;
  context?: Record<string, unknown>;
  variables?: Record<string, unknown>;
};
