import { format } from "prettier";
import inventory from "@shepherdjerred/feature-flags/managed-flag-inventory.json" with { type: "json" };
import { ManagedFlagInventorySchema } from "@shepherdjerred/feature-flags/managed-flag-inventory.ts";

function toUpperSnake(str: string): string {
  return str.replaceAll(/[-\s]+/gu, "_").toUpperCase();
}

function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/u)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}

export async function generateFlagTypesSource(): Promise<string> {
  const parsed = ManagedFlagInventorySchema.parse(inventory);

  const lines: string[] = [
    "// Generated by scripts/generate-flag-types.ts. Do not edit.",
    "",
    'import { z } from "zod";',
    "",
  ];

  // Namespaces
  const namespaceKeys = parsed.namespaces.map((ns) => ns.key);
  lines.push("export const MANAGED_NAMESPACES = [");
  for (const ns of namespaceKeys) {
    lines.push(`  ${JSON.stringify(ns)},`);
  }
  lines.push("] as const;");
  lines.push("");
  lines.push(
    "export type ManagedNamespaceKey = (typeof MANAGED_NAMESPACES)[number];",
  );
  lines.push("");

  // Per-namespace keys
  for (const ns of parsed.namespaces) {
    const nsKey = ns.key;
    const prefixUpper = toUpperSnake(nsKey);
    const prefixPascal = toPascalCase(nsKey);

    const nsFlags = parsed.flags.filter((flag) => flag.namespace === nsKey);
    const booleanFlags = nsFlags.filter((flag) => flag.type === "boolean");
    const variantFlags = nsFlags.filter((flag) => flag.type === "variant");

    // All flags in namespace
    lines.push(`export const ${prefixUpper}_FLAG_KEYS = [`);
    for (const flag of nsFlags) {
      lines.push(`  ${JSON.stringify(flag.key)},`);
    }
    lines.push("] as const;");
    lines.push("");
    lines.push(
      `export type ${prefixPascal}FlagKey = (typeof ${prefixUpper}_FLAG_KEYS)[number];`,
    );
    lines.push("");

    // Boolean flags in namespace
    lines.push(`export const ${prefixUpper}_BOOLEAN_FLAG_KEYS = [`);
    for (const flag of booleanFlags) {
      lines.push(`  ${JSON.stringify(flag.key)},`);
    }
    lines.push("] as const;");
    lines.push("");
    lines.push(
      `export type ${prefixPascal}BooleanFlagKey = (typeof ${prefixUpper}_BOOLEAN_FLAG_KEYS)[number];`,
    );
    lines.push("");

    // Variant flags in namespace
    lines.push(`export const ${prefixUpper}_VARIANT_FLAG_KEYS = [`);
    for (const flag of variantFlags) {
      lines.push(`  ${JSON.stringify(flag.key)},`);
    }
    lines.push("] as const;");
    lines.push("");
    lines.push(
      `export type ${prefixPascal}VariantFlagKey = (typeof ${prefixUpper}_VARIANT_FLAG_KEYS)[number];`,
    );
    lines.push("");
  }

  // All managed flags
  const allFlags = parsed.flags;
  const allBooleanFlags = allFlags.filter((f) => f.type === "boolean");
  const allVariantFlags = allFlags.filter((f) => f.type === "variant");

  lines.push("export const MANAGED_FLAG_KEYS = [");
  for (const flag of allFlags) {
    lines.push(`  ${JSON.stringify(flag.key)},`);
  }
  lines.push("] as const;");
  lines.push("");
  lines.push(
    "export type ManagedFlagKey = (typeof MANAGED_FLAG_KEYS)[number];",
  );
  lines.push("");

  lines.push("export const MANAGED_BOOLEAN_FLAG_KEYS = [");
  for (const flag of allBooleanFlags) {
    lines.push(`  ${JSON.stringify(flag.key)},`);
  }
  lines.push("] as const;");
  lines.push("");
  lines.push(
    "export type ManagedBooleanFlagKey = (typeof MANAGED_BOOLEAN_FLAG_KEYS)[number];",
  );
  lines.push("");

  lines.push("export const MANAGED_VARIANT_FLAG_KEYS = [");
  for (const flag of allVariantFlags) {
    lines.push(`  ${JSON.stringify(flag.key)},`);
  }
  lines.push("] as const;");
  lines.push("");
  lines.push(
    "export type ManagedVariantFlagKey = (typeof MANAGED_VARIANT_FLAG_KEYS)[number];",
  );
  lines.push("");
  lines.push(
    "export const ManagedBooleanFlagKeySchema = z.enum(MANAGED_BOOLEAN_FLAG_KEYS);",
  );
  lines.push("");
  lines.push(
    "export const ManagedVariantFlagKeySchema = z.enum(MANAGED_VARIANT_FLAG_KEYS);",
  );
  lines.push("");

  const formatted = await format(lines.join("\n"), { parser: "typescript" });
  return formatted;
}

async function main(): Promise<void> {
  const outputPath = new URL(
    "../src/managed-flag-keys.generated.ts",
    import.meta.url,
  );
  const source = await generateFlagTypesSource();
  await Bun.write(outputPath, source);
}

if (import.meta.main) {
  void (async () => {
    try {
      await main();
    } catch (error: unknown) {
      console.error(error);
      process.exitCode = 1;
    }
  })();
}
