package com.shepherdjerred.thestorm.tools.rwfmap;

import com.shepherdjerred.thestorm.core.config.ConfigFiles;
import com.shepherdjerred.thestorm.rwf.adapter.content.LobbyFile;
import com.shepherdjerred.thestorm.rwf.adapter.content.Schematic;
import com.shepherdjerred.thestorm.rwf.adapter.content.SchematicReader;
import com.shepherdjerred.thestorm.rwf.adapter.content.SchematicWriter;
import com.shepherdjerred.thestorm.rwf.domain.geometry.Vec3;
import com.shepherdjerred.thestorm.rwf.domain.lobby.LobbyBuild;
import com.shepherdjerred.thestorm.rwf.domain.lobby.LobbyLayout;
import com.shepherdjerred.thestorm.rwfbots.domain.geom.BlockPos;
import com.shepherdjerred.thestorm.rwfbots.domain.lobby.LobbyNav;
import com.shepherdjerred.thestorm.rwfbots.domain.map.NavSites;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * The {@code rwf/lobby/} folder as the tool reads it: the layout from {@code lobby.yml} and the
 * terrain from {@code blocks.schem}. The lobby is generated by {@link LobbyBuild}, so the tool also
 * writes its schematic and checks that both files still describe what the generator builds.
 *
 * @param folder the lobby folder
 * @param file the parsed {@code lobby.yml}
 * @param schematic the parsed {@code blocks.schem}
 */
public record LobbyFolder(Path folder, LobbyFile file, Schematic schematic) {

  public static final String LOBBY_FILE = "lobby.yml";

  /** Reads {@code folder}, or throws naming the first problem. */
  public static LobbyFolder load(Path folder) {
    var file = ConfigFiles.load(folder.resolve(LOBBY_FILE), LobbyFile.class);
    var blocksFile = folder.resolve(MapFolder.BLOCKS_FILE);
    Schematic schematic;
    try (var in = Files.newInputStream(blocksFile)) {
      schematic = SchematicReader.read(in);
    } catch (IOException e) {
      throw new UncheckedIOException("Required file " + blocksFile + " could not be read", e);
    }
    return new LobbyFolder(folder, file, schematic);
  }

  /** The schematic {@link LobbyBuild} generates. */
  public static Schematic generated() {
    return new Schematic(
        new Schematic.Dimensions(LobbyBuild.WIDTH, LobbyBuild.HEIGHT, LobbyBuild.LENGTH),
        LobbyBuild.PALETTE,
        LobbyBuild.generate().indices());
  }

  /** The bytes of the generated {@code blocks.schem}. */
  public static byte[] generatedBytes() {
    return SchematicWriter.write(generated());
  }

  public LobbyLayout layout() {
    return file.toLayout();
  }

  public Path navFile() {
    return folder.resolve(MapFolder.NAV_FILE);
  }

  public Path summaryFile() {
    return folder.resolve(MapFolder.SUMMARY_FILE);
  }

  public Path blocksFile() {
    return folder.resolve(MapFolder.BLOCKS_FILE);
  }

  /** The schematic's classification through the block table. */
  public SchematicClassification classify() {
    return SchematicClassification.of(LobbyNav.ID, schematic, layout().region());
  }

  /**
   * The lobby's places as bots name them: the spawn, each team's side, each kit alcove's stand and
   * the balcony, all on the cell their feet occupy. The lobby has no bombs.
   */
  public NavSites sites() {
    var layout = layout();
    var spawns = new ArrayList<NavSites.Site>();
    spawns.add(site(LobbyNav.SPAWN, Optional.empty(), layout.spawn().position()));
    for (var side : layout.sides()) {
      var team = Sites.teamName(side.team());
      spawns.add(site(LobbyNav.side(team), Optional.of(team), side.at().position()));
    }
    for (var alcove : layout.alcoves()) {
      spawns.add(site(LobbyNav.alcove(alcove.kit()), Optional.empty(), alcove.stand().position()));
    }
    spawns.add(site(LobbyNav.BALCONY, Optional.empty(), layout.balcony().position()));
    return new NavSites(spawns, List.of());
  }

  private static NavSites.Site site(String name, Optional<String> team, Vec3 at) {
    var cell =
        new BlockPos((int) Math.floor(at.x()), (int) Math.floor(at.y()), (int) Math.floor(at.z()));
    return new NavSites.Site(name, team, cell);
  }
}
