/**
 * Git-diff based change detection with failed-build retry.
 *
 * Determines which packages changed and need to be built.
 */
import {
  ALL_PACKAGES,
  PACKAGES_WITH_IMAGES,
  PACKAGES_WITH_NPM,
  PACKAGE_TO_SITE,
} from "./catalog.ts";
import type { AffectedPackages } from "./lib/types.ts";
import { execSync } from "node:child_process";

/** Repo root — needed because the pipeline generator may run from scripts/ci/. */
const REPO_ROOT = execSync("git rev-parse --show-toplevel", {
  encoding: "utf-8",
}).trim();

/** Files that, if changed, trigger a full build. */
const INFRA_FILES = new Set([
  "bun.lock",
  "package.json",
  "tsconfig.json",
  "tsconfig.base.json",
]);

/** Directory prefixes that, if any file under them changes, trigger a full build. */
const INFRA_DIRS = [".buildkite/", ".dagger/", "scripts/ci/"];

const CI_BASE_VERSION_BUMP_BRANCH = "chore/ci-base-version-bump-pending";
const COOKLANG_VERSION_BUMP_BRANCH = "chore/cooklang-version-bump-pending";
const COOKLANG_VERSION_COMMIT_BACK_FILES = new Set([
  "packages/cooklang-for-obsidian/manifest.json",
  "packages/cooklang-for-obsidian/versions.json",
]);

/**
 * Package directories whose source changes warrant a cooklang plugin release.
 *
 * Only the Obsidian plugin itself — `cooklang-rich-preview/` is the rich-preview
 * Astro site and is never published as part of the Obsidian plugin release, so
 * edits there must not cut a plugin version.
 */
const COOKLANG_PACKAGE_PREFIXES = ["packages/cooklang-for-obsidian/"];

/**
 * Files under {@link COOKLANG_PACKAGE_PREFIXES} that do NOT count as plugin
 * source for the release gate. Includes the auto-bump artifacts
 * (`manifest.json` / `versions.json`) plus cog-generated docs (`_summary.md`),
 * which is rewritten weekly by the `readme-refresh-weekly` Temporal schedule
 * and would otherwise trip the gate every Monday.
 *
 * Kept separate from {@link COOKLANG_VERSION_COMMIT_BACK_FILES} so that the
 * commit-back fast-track keeps its strict "only manifest/versions" meaning.
 */
const COOKLANG_NON_SOURCE_FILES = new Set([
  ...COOKLANG_VERSION_COMMIT_BACK_FILES,
  "packages/cooklang-for-obsidian/_summary.md",
]);

// ---------------------------------------------------------------------------
// Version commit-back fast-track
// ---------------------------------------------------------------------------

/** Check if the current build is a version commit-back merge (auto-generated). */
function isVersionCommitBack(): boolean {
  const msg = process.env["BUILDKITE_MESSAGE"] ?? "";
  return (
    msg.startsWith("chore: bump image versions to ") ||
    /^Merge pull request #\d+ from .+\/chore\/version-bump-/.test(msg)
  );
}

/** Check if the current build is a cooklang version commit-back. */
function isCooklangVersionCommitBack(): boolean {
  const msg = process.env["BUILDKITE_MESSAGE"] ?? "";
  return (
    /^chore\(cooklang\): bump to v\d+\.\d+\.\d+/.test(msg) ||
    (/^Merge pull request #\d+ from /.test(msg) &&
      msg.includes(COOKLANG_VERSION_BUMP_BRANCH))
  );
}

function isCooklangVersionCommitBackOnly(changedFiles: string[]): boolean {
  return (
    changedFiles.length > 0 &&
    changedFiles.every((file) => COOKLANG_VERSION_COMMIT_BACK_FILES.has(file))
  );
}

/**
 * True when a real cooklang *source* file changed — a file under a cooklang
 * package that is NOT one of the auto-generated / cog-generated non-source
 * artifacts (see {@link COOKLANG_NON_SOURCE_FILES}).
 *
 * The release gate keys off this rather than "any cooklang file changed" so
 * that bot-authored manifest bumps — and infra/full builds that don't touch
 * cooklang at all — never cut a new plugin release. Cooklang is still BUILT
 * and TESTED whenever any of its files change (driven by `packages`); this
 * flag governs only whether we PUBLISH.
 */
function hasCooklangSourceChange(changedFiles: string[]): boolean {
  return changedFiles.some(
    (file) =>
      COOKLANG_PACKAGE_PREFIXES.some((prefix) => file.startsWith(prefix)) &&
      !COOKLANG_NON_SOURCE_FILES.has(file),
  );
}

/**
 * True when HEAD's commit message carries an `Auto-Generated:` trailer.
 * Bot-authored commits (e.g. version-commit-back) tag themselves with this
 * trailer so downstream pipeline steps (version-commit-back) can skip
 * themselves and avoid bot-on-bot loops.
 */
function readHeadCommitMessage(): string {
  return execSync("git log -1 --pretty=%B", {
    cwd: REPO_ROOT,
    encoding: "utf-8",
  });
}

function isCiBaseVersionBumpMerge(msg: string): boolean {
  return (
    /^Merge pull request #\d+ from /m.test(msg) &&
    msg.includes(CI_BASE_VERSION_BUMP_BRANCH)
  );
}

function isAutoGeneratedCommit(msg = readHeadCommitMessage()): boolean {
  return /^Auto-Generated:\s*\S/m.test(msg) || isCiBaseVersionBumpMerge(msg);
}

// ---------------------------------------------------------------------------
// Release-please merge detection
// ---------------------------------------------------------------------------

/** Check if the current build is a release-please merge commit. */
export function isReleasePleaseMerge(): boolean {
  const msg = process.env["BUILDKITE_MESSAGE"] ?? "";
  return msg === "chore: release main";
}

/** The head branch release-please pushes its release PRs to. */
const RELEASE_PLEASE_PR_BRANCH = "release-please--branches--main";

/**
 * True when this build is an *auto-triggered* (webhook) build of the
 * release-please release PR. These PRs are no-op version bumps, so we skip the
 * full CI rather than burn the whole pipeline (and the Greptile gate) on them.
 *
 * The skip is intentionally narrow: it fires *only* when BUILDKITE_SOURCE is
 * exactly "webhook" (the automatic build Buildkite starts from the GitHub PR
 * webhook). Every other source — "ui"/"api" (manual New Build / API /
 * `bk build create`), "schedule", "trigger_job" (triggered by another
 * pipeline), or an unknown/empty value — runs full CI. Defaulting unknown
 * sources to "run" is deliberate: we'd rather over-run CI than silently skip a
 * build and mistake the no-op pipeline for real coverage.
 *
 * RUN_RELEASE_CI=true also forces a full run regardless of source.
 *
 * This lets a release still be cut on demand while leaving the PR un-CI'd (and
 * therefore not mergeable) until you ask for it. Note this only matches the
 * release PR branch; the eventual `chore: release main` merge to `main` is a
 * different build and is handled by {@link isReleasePleaseMerge}.
 */
export function shouldSkipReleasePleasePrBuild(): boolean {
  const branch = process.env["BUILDKITE_BRANCH"] ?? "";
  if (branch !== RELEASE_PLEASE_PR_BRANCH) return false;
  const optIn = (process.env["RUN_RELEASE_CI"] ?? "").toLowerCase() === "true";
  if (optIn) return false;
  const source = process.env["BUILDKITE_SOURCE"] ?? "";
  return source === "webhook";
}

// ---------------------------------------------------------------------------
// Renovate fast-track
// ---------------------------------------------------------------------------

/**
 * Packages that are NOT JavaScript/TypeScript — excluded from the "all-js"
 * Renovate classification (root package.json changes).
 */
const NON_JS_PACKAGES = new Set([
  "terraform-provider-asuswrt", // Go
  "resume", // LaTeX
]);

/** All JS/TS workspace packages (ALL_PACKAGES minus non-JS). */
const JS_TS_PACKAGES = ALL_PACKAGES.filter((p) => !NON_JS_PACKAGES.has(p));

/** Check if the current build is a Renovate pull request. */
function isRenovatePr(): boolean {
  const email = process.env["BUILDKITE_BUILD_AUTHOR_EMAIL"] ?? "";
  const pr = process.env["BUILDKITE_PULL_REQUEST"] ?? "false";
  return email.includes("renovate[bot]") && pr !== "false";
}

type RenovateClassification =
  | { kind: "noop" }
  | { kind: "scoped"; packages: Set<string> }
  | { kind: "all-js" }
  | null;

/**
 * Classify changed files in a Renovate PR.
 * Returns null if any file doesn't match a known Renovate pattern
 * (falls through to normal detection).
 *
 * Priority: null > scoped > noop
 */
function classifyRenovateFiles(changedFiles: string[]): RenovateClassification {
  let level: "noop" | "scoped" = "noop";
  const scopedPackages = new Set<string>();

  for (const f of changedFiles) {
    // Version files — pure string value changes, nothing to test
    if (f.endsWith("/versions.ts") || f.endsWith("/lib-versions.ts")) {
      continue; // stays at current level (noop or higher)
    }

    // Per-package manifest, lockfile, or Dockerfile
    if (f.startsWith("packages/")) {
      const rest = f.slice("packages/".length);
      const pkg = rest.split("/")[0];
      if (!pkg) return null;

      const relPath = rest.slice(pkg.length + 1);
      if (
        relPath === "package.json" ||
        relPath === "bun.lock" ||
        relPath === "package-lock.json" ||
        relPath === "Dockerfile"
      ) {
        scopedPackages.add(pkg);
        if (level === "noop") level = "scoped";
        continue;
      }

      // Unknown file under packages/ — not a recognized Renovate pattern
      return null;
    }

    // Root bun.lock — derivative of manifest changes, ignore
    if (f === "bun.lock") {
      continue;
    }

    // Root package.json — only contains markdownlint-cli2 dev tool, not consumed by any
    // workspace package; if real shared workspace deps are ever added here, revisit this.
    if (f === "package.json") {
      continue;
    }

    // CI tool versions — string value bumps, nothing to test
    if (f === ".buildkite/scripts/setup-tools.sh") {
      continue;
    }

    // Dagger manifest/lockfile — tool version bumps (npm, typescript in Dagger runtime);
    // actual pipeline logic lives in .dagger/src/ which falls through correctly.
    if (
      f === ".dagger/package.json" ||
      f === ".dagger/bun.lock" ||
      f === ".dagger/package-lock.json"
    ) {
      continue;
    }

    // Anything else is unrecognized — fall through to normal detection
    return null;
  }

  if (level === "scoped") return { kind: "scoped", packages: scopedPackages };
  return { kind: "noop" };
}

// ---------------------------------------------------------------------------
// Buildkite API: find last successful base build
// ---------------------------------------------------------------------------

type ExecResult = { stdout: string; exitCode: number };
type ExecFn = (cmd: string[]) => Promise<ExecResult>;
type FetchFn = (
  input: Parameters<typeof fetch>[0],
  init?: Parameters<typeof fetch>[1],
) => ReturnType<typeof fetch>;

function errorMessage(e: unknown): string {
  return e instanceof Error ? e.message : String(e);
}

type BuildkiteJob = {
  type?: string;
  name?: string;
  command?: string;
  state?: string;
  step_key?: string;
  soft_failed?: boolean;
};

type BuildkiteBuild = {
  number?: number;
  state?: string;
  blocked?: boolean;
  commit?: string;
  jobs?: BuildkiteJob[];
};

type BuildRejectionReason =
  | "blocked"
  | "incomplete"
  | "missing-jobs"
  | "hard-failed-jobs";

const ACCEPTABLE_BUILD_STATES = new Set(["passed", "failed"]);
const EXEMPT_FAILED_STEP_KEYS = new Set(["argocd-health"]);
const EXEMPT_FAILED_JOB_STATES = new Set(["failed", "timed_out", "broken"]);
const PIPELINE_UPLOAD_COMMAND = "buildkite-agent pipeline upload";
const PIPELINE_GENERATE_COMMAND = ".buildkite/scripts/generate-pipeline.sh";

function isScriptJob(job: BuildkiteJob): boolean {
  return job.type === "script";
}

function isAllowedFailedJob(job: BuildkiteJob): boolean {
  if (job.soft_failed === true) return true;
  if (!EXEMPT_FAILED_JOB_STATES.has(job.state ?? "")) return false;
  return (
    job.step_key !== undefined && EXEMPT_FAILED_STEP_KEYS.has(job.step_key)
  );
}

function isCleanScriptJob(job: BuildkiteJob): boolean {
  return job.state === "passed" || isAllowedFailedJob(job);
}

function hasPipelineBootstrapJobs(scriptJobs: BuildkiteJob[]): boolean {
  return (
    scriptJobs.some(
      (job) =>
        job.command === PIPELINE_UPLOAD_COMMAND ||
        job.name === ":pipeline: Upload pipeline",
    ) &&
    scriptJobs.some(
      (job) =>
        job.command === PIPELINE_GENERATE_COMMAND ||
        job.name === ":pipeline: Generate Pipeline",
    )
  );
}

function getBuildRejectionReason(
  build: BuildkiteBuild,
): BuildRejectionReason | null {
  if (build.blocked === true || build.state === "blocked") return "blocked";
  if (!ACCEPTABLE_BUILD_STATES.has(build.state ?? "")) return "incomplete";

  const scriptJobs = (build.jobs ?? []).filter(isScriptJob);
  if (!hasPipelineBootstrapJobs(scriptJobs)) return "missing-jobs";

  return scriptJobs.every(isCleanScriptJob) ? null : "hard-failed-jobs";
}

function parseBuildkiteJob(value: unknown): BuildkiteJob | null {
  if (typeof value !== "object" || value === null) return null;

  const job: BuildkiteJob = {};
  if ("type" in value && typeof value.type === "string") {
    job.type = value.type;
  }
  if ("name" in value && typeof value.name === "string") {
    job.name = value.name;
  }
  if ("command" in value && typeof value.command === "string") {
    job.command = value.command;
  }
  if ("state" in value && typeof value.state === "string") {
    job.state = value.state;
  }
  if ("step_key" in value && typeof value.step_key === "string") {
    job.step_key = value.step_key;
  }
  if ("soft_failed" in value && typeof value.soft_failed === "boolean") {
    job.soft_failed = value.soft_failed;
  }

  return job;
}

function parseBuildkiteBuild(value: unknown): BuildkiteBuild | null {
  if (typeof value !== "object" || value === null) return null;

  const build: BuildkiteBuild = {};
  if ("number" in value && typeof value.number === "number") {
    build.number = value.number;
  }
  if ("state" in value && typeof value.state === "string") {
    build.state = value.state;
  }
  if ("blocked" in value && typeof value.blocked === "boolean") {
    build.blocked = value.blocked;
  }
  if ("commit" in value && typeof value.commit === "string") {
    build.commit = value.commit;
  }
  if ("jobs" in value && Array.isArray(value.jobs)) {
    const jobs: BuildkiteJob[] = [];
    for (const job of value.jobs) {
      const parsedJob = parseBuildkiteJob(job);
      if (parsedJob !== null) {
        jobs.push(parsedJob);
      }
    }
    build.jobs = jobs;
  }

  return build;
}

function parseBuildkiteBuilds(value: unknown): BuildkiteBuild[] {
  if (!Array.isArray(value)) return [];

  const builds: BuildkiteBuild[] = [];
  for (const build of value) {
    const parsedBuild = parseBuildkiteBuild(build);
    if (parsedBuild !== null) {
      builds.push(parsedBuild);
    }
  }
  return builds;
}

/**
 * Maximum pages of Buildkite history to walk when searching for the last
 * successful main build. With `per_page=100` this is 1 000 builds — enough to
 * survive any realistic streak of cancellations + failures (we have seen 100+)
 * while still bounding the recovery cost. Beyond this we surface the
 * underlying CI rot rather than walking arbitrarily far back.
 */
const LAST_SUCCESS_MAX_PAGES = 10;
const LAST_SUCCESS_PAGE_SIZE = 100;

async function getLastSuccessfulCommit(
  fetchFn: FetchFn = fetch,
): Promise<string> {
  const override = process.env["LAST_SUCCESSFUL_COMMIT_OVERRIDE"];
  if (override !== undefined && override !== "") {
    console.error(
      `LAST_SUCCESSFUL_COMMIT_OVERRIDE set; using ${override.slice(0, 10)} as base (skipping Buildkite lookup)`,
    );
    return override;
  }

  const token = process.env["BUILDKITE_API_TOKEN"];
  if (!token) {
    throw new Error(
      "BUILDKITE_API_TOKEN is required for main-branch change detection",
    );
  }

  const org = process.env["BUILDKITE_ORGANIZATION_SLUG"] ?? "";
  const pipeline = process.env["BUILDKITE_PIPELINE_SLUG"] ?? "";
  const currentBuild = process.env["BUILDKITE_BUILD_NUMBER"] ?? "";

  if (!org || !pipeline) {
    throw new Error(
      "BUILDKITE_ORGANIZATION_SLUG and BUILDKITE_PIPELINE_SLUG are required for main-branch change detection",
    );
  }

  const skipped = new Map<BuildRejectionReason, number>();
  let pagesWalked = 0;

  for (let page = 1; page <= LAST_SUCCESS_MAX_PAGES; page++) {
    const url =
      `https://api.buildkite.com/v2/organizations/${org}` +
      `/pipelines/${pipeline}/builds` +
      `?branch=main&per_page=${LAST_SUCCESS_PAGE_SIZE}&page=${page}`;

    let resp: Response;
    try {
      resp = await fetchFn(url, {
        headers: { Authorization: `Bearer ${token}` },
        signal: AbortSignal.timeout(15_000),
      });
    } catch (e) {
      throw new Error(`Buildkite API request failed: ${errorMessage(e)}`);
    }

    if (resp.status === 401 || resp.status === 403) {
      throw new Error(
        "Buildkite API token is not authorized; expected REST API token with read_builds scope",
      );
    }

    if (!resp.ok) {
      throw new Error(`Buildkite API failed with HTTP ${resp.status}`);
    }

    const builds = parseBuildkiteBuilds(await resp.json());
    pagesWalked = page;

    for (const build of builds) {
      if (String(build.number) === currentBuild) continue;

      const rejectionReason = getBuildRejectionReason(build);
      if (rejectionReason !== null) {
        skipped.set(rejectionReason, (skipped.get(rejectionReason) ?? 0) + 1);
        console.error(`Build #${build.number} skipped: ${rejectionReason}`);
        continue;
      }

      const commit = build.commit ?? "";
      if (!commit) {
        throw new Error(
          `Build #${build.number} qualified as successful but did not include a commit SHA`,
        );
      }

      const scriptJobCount = (build.jobs ?? []).filter(isScriptJob).length;
      console.error(
        `Last successful base build: #${build.number} (${scriptJobCount} script jobs, commit ${commit.slice(0, 10)}, page ${page})`,
      );
      return commit;
    }

    if (builds.length < LAST_SUCCESS_PAGE_SIZE) {
      // Reached end of history — no point requesting further pages.
      break;
    }
  }

  const reasonSummary = [...skipped]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([reason, count]) => `${reason}: ${count}`)
    .join(", ");
  const scanned = pagesWalked * LAST_SUCCESS_PAGE_SIZE;
  throw new Error(
    `No qualifying successful main build found in last ${scanned} builds (${pagesWalked} pages); ` +
      `cannot scope this build safely${reasonSummary ? ` (${reasonSummary})` : ""}. ` +
      `Set LAST_SUCCESSFUL_COMMIT_OVERRIDE on a rebuild to manually unstick main CI.`,
  );
}

// ---------------------------------------------------------------------------
// Git helpers
// ---------------------------------------------------------------------------

async function exec(cmd: string[]): Promise<ExecResult> {
  const proc = Bun.spawn(cmd, {
    stdout: "pipe",
    stderr: "pipe",
  });
  const stdout = await new Response(proc.stdout).text();
  const exitCode = await proc.exited;
  return { stdout: stdout.trim(), exitCode };
}

const ORIGIN_MAIN_REFSPEC = "+refs/heads/main:refs/remotes/origin/main";

async function fetchOriginMain(
  execFn: ExecFn,
  depthArg: string,
): Promise<void> {
  const fetch = await execFn([
    "git",
    "fetch",
    "--no-tags",
    depthArg,
    "origin",
    ORIGIN_MAIN_REFSPEC,
  ]);
  if (fetch.exitCode !== 0) {
    throw new Error("Unable to fetch origin/main for merge-base computation");
  }
}

// Buildkite's checkout uses --depth=100 and only fetches the PR HEAD ref, so
// `origin/main` is often missing as a remote-tracking ref. Fetch it explicitly
// before any merge-base call.
async function ensureOriginMain(execFn: ExecFn): Promise<void> {
  const check = await execFn([
    "git",
    "rev-parse",
    "--verify",
    "--quiet",
    "refs/remotes/origin/main",
  ]);
  if (check.exitCode === 0 && check.stdout !== "") {
    return;
  }
  await fetchOriginMain(execFn, "--depth=100");
}

async function getMergeBaseWithOriginMain(execFn: ExecFn): Promise<string> {
  await ensureOriginMain(execFn);

  const initial = await execFn(["git", "merge-base", "HEAD", "origin/main"]);
  if (initial.exitCode === 0 && initial.stdout !== "") {
    return initial.stdout;
  }

  // The remote-tracking ref can exist while the shallow clone still lacks the
  // common ancestor. Deepen in bounded steps so normal PRs stay cheap while
  // long-lived branches still get a fair retry before failing.
  for (const depthArg of ["--deepen=1000", "--deepen=10000"]) {
    await fetchOriginMain(execFn, depthArg);
    const result = await execFn(["git", "merge-base", "HEAD", "origin/main"]);
    if (result.exitCode === 0 && result.stdout !== "") {
      return result.stdout;
    }
  }

  throw new Error(
    "Unable to compute merge-base with origin/main after deepening shallow history",
  );
}

async function getBaseRevision(execFn: ExecFn = exec): Promise<string> {
  const branch = process.env["BUILDKITE_BRANCH"] ?? "";
  const pullRequest = process.env["BUILDKITE_PULL_REQUEST"] ?? "false";

  if (pullRequest && pullRequest !== "false") {
    return getMergeBaseWithOriginMain(execFn);
  }

  if (branch === "main") {
    return getLastSuccessfulCommit();
  }

  // Feature branch without PR
  return getMergeBaseWithOriginMain(execFn);
}

async function getChangedFiles(execFn: ExecFn = exec): Promise<string[]> {
  const base = await getBaseRevision(execFn);

  const result = await execFn(["git", "diff", "--name-only", base, "HEAD"]);
  if (result.exitCode !== 0) {
    throw new Error(`Unable to diff base revision ${base} against HEAD`);
  }

  return result.stdout
    .split("\n")
    .map((f) => f.trim())
    .filter((f) => f.length > 0);
}

/** Paths under INFRA_DIRS that should NOT trigger a full build. */
const INFRA_DIR_EXCLUSIONS = [".buildkite/ci-image/"];

function checkInfraChanges(changedFiles: string[]): boolean {
  for (const f of changedFiles) {
    if (INFRA_FILES.has(f)) {
      console.error(`Infrastructure file changed: ${f}`);
      return true;
    }
    for (const d of INFRA_DIRS) {
      if (f.startsWith(d)) {
        if (INFRA_DIR_EXCLUSIONS.some((ex) => f.startsWith(ex))) continue;
        console.error(`Infrastructure dir changed: ${f}`);
        return true;
      }
    }
  }
  return false;
}

function checkCiImageChanges(changedFiles: string[]): boolean {
  for (const f of changedFiles) {
    if (
      f.startsWith(".buildkite/ci-image/") &&
      f !== ".buildkite/ci-image/VERSION"
    ) {
      console.error(`CI image changed: ${f}`);
      return true;
    }
  }
  return false;
}

function checkCiImageVersionChanges(changedFiles: string[]): boolean {
  return changedFiles.includes(".buildkite/ci-image/VERSION");
}

/**
 * True when an OpenTofu source file changed. Gates the PR tofu *plan* group so
 * that cdk8s-only homelab PRs don't run (and queue behind) tofu plans that
 * produce no signal for them. Changes to the tofu Dagger logic (`.dagger/`) or
 * the CI generator (`scripts/ci/`) trigger a full build instead, which runs the
 * plan via `buildAll`.
 */
function checkTofuChanges(changedFiles: string[]): boolean {
  return changedFiles.some((f) => f.startsWith("packages/homelab/src/tofu/"));
}

/**
 * Inputs that change what `generate-helm-types` emits: the pinned chart
 * versions, the generator/parser scripts, and the helm-types library. When any
 * of these change we run the `helm-types-drift-check` gate (regenerate + diff vs
 * committed). Scoped narrowly so the ~24-chart network fetch only runs on PRs
 * that can actually change the generated tree — not on every homelab/cdk8s edit.
 *
 * Prettier/formatting drift of the committed tree is intentionally NOT included:
 * the repo-wide `prettier --check` gate already catches that.
 */
const HELM_TYPES_INPUT_FILES = new Set([
  "packages/homelab/src/cdk8s/src/versions.ts",
  "packages/homelab/src/cdk8s/scripts/generate-helm-types.ts",
  "packages/homelab/src/cdk8s/scripts/parse-helm-charts.ts",
]);

function checkHelmTypesInputChanges(changedFiles: string[]): boolean {
  return changedFiles.some(
    (f) =>
      HELM_TYPES_INPUT_FILES.has(f) ||
      f.startsWith("packages/homelab/src/helm-types/"),
  );
}

function extractPackageName(filePath: string): string | null {
  if (!filePath.startsWith("packages/")) return null;
  const rest = filePath.slice("packages/".length);
  const parts = rest.split("/");
  return parts[0] ?? null;
}

// ---------------------------------------------------------------------------
// Dependency graph
// ---------------------------------------------------------------------------

async function readWorkspaceDeps(): Promise<Map<string, Set<string>>> {
  const deps = new Map<string, Set<string>>();
  for (const pkg of ALL_PACKAGES) {
    try {
      const file = Bun.file(`${REPO_ROOT}/packages/${pkg}/package.json`);
      const json = (await file.json()) as {
        dependencies?: Record<string, string>;
        devDependencies?: Record<string, string>;
      };
      const allDeps = {
        ...json.dependencies,
        ...json.devDependencies,
      };
      const workspaceDeps = new Set<string>();
      for (const [name, version] of Object.entries(allDeps)) {
        if (
          typeof version === "string" &&
          (version.startsWith("workspace:") || version.startsWith("file:"))
        ) {
          // Extract the package directory name from the scoped name
          const dirName = name.startsWith("@")
            ? (name.split("/")[1] ?? name)
            : name;
          workspaceDeps.add(dirName);
        }
      }
      deps.set(pkg, workspaceDeps);
    } catch (e) {
      // Non-JS packages (Rust, Go, Java, docs, etc.) don't have package.json
      // — they have no workspace deps, which is correct.
      const isFileNotFound =
        e instanceof Error && e.message.includes("no such file");
      if (isFileNotFound) {
        deps.set(pkg, new Set());
      } else {
        throw new Error(
          `Failed to read workspace deps for ${pkg}: ${e}. Fix the package.json or remove from ALL_PACKAGES.`,
        );
      }
    }
  }
  return deps;
}

function transitiveClosure(
  changed: Set<string>,
  deps: Map<string, Set<string>>,
): Set<string> {
  // Build reverse dep map: if A depends on B, then B -> A
  const reverseDeps = new Map<string, Set<string>>();
  for (const [pkg, pkgDeps] of deps) {
    for (const dep of pkgDeps) {
      let set = reverseDeps.get(dep);
      if (!set) {
        set = new Set();
        reverseDeps.set(dep, set);
      }
      set.add(pkg);
    }
  }

  const result = new Set(changed);
  const queue = [...changed];
  while (queue.length > 0) {
    const current = queue.pop()!;
    const dependents = reverseDeps.get(current);
    if (dependents) {
      for (const dep of dependents) {
        if (!result.has(dep)) {
          result.add(dep);
          queue.push(dep);
        }
      }
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// Result builders
// ---------------------------------------------------------------------------

/**
 * A full build rebuilds and retests everything, but a cooklang plugin release
 * is published only when cooklang *source* actually changed — `buildAll` alone
 * must never cut a release (that was the source of the manifest-bump churn).
 */
function fullBuildResult(cooklangChanged: boolean): AffectedPackages {
  return {
    packages: new Set(ALL_PACKAGES),
    // On a full build the drift gate is skipped (every per-package job runs
    // `bun install --frozen-lockfile`), so seeds don't need to be tracked.
    directlyChanged: new Set(),
    buildAll: true,
    homelabChanged: true,
    tofuChanged: true,
    cooklangChanged,
    resumeChanged: true,
    // Full build rebuilds everything; run the drift gate too.
    helmTypesInputsChanged: true,
    ciImageChanged: false,
    hasImagePackages: new Set(PACKAGES_WITH_IMAGES),
    hasSitePackages: new Set(Object.keys(PACKAGE_TO_SITE)),
    hasNpmPackages: new Set(PACKAGES_WITH_NPM),
    ciImageVersionChanged: false,
    versionBumpOnly: false,
    releasePleaseMerge: isReleasePleaseMerge(),
    isAutoGenerated: isAutoGeneratedCommit(),
  };
}

function emptyResult(): AffectedPackages {
  return {
    packages: new Set(),
    directlyChanged: new Set(),
    buildAll: false,
    homelabChanged: false,
    tofuChanged: false,
    cooklangChanged: false,
    resumeChanged: false,
    helmTypesInputsChanged: false,
    ciImageChanged: false,
    hasImagePackages: new Set(),
    hasSitePackages: new Set(),
    hasNpmPackages: new Set(),
    ciImageVersionChanged: false,
    versionBumpOnly: false,
    releasePleaseMerge: isReleasePleaseMerge(),
    isAutoGenerated: isAutoGeneratedCommit(),
  };
}

function buildScopedResult(
  allAffected: Set<string>,
  directlyChanged: Set<string>,
  cooklangChanged: boolean,
  ciImageChanged: boolean,
  ciImageVersionChanged = false,
  tofuChanged = false,
  helmTypesInputsChanged = false,
): AffectedPackages {
  const hasImagePackages = new Set<string>();
  const hasSitePackages = new Set<string>();
  const hasNpmPackages = new Set<string>();
  for (const pkg of allAffected) {
    if (PACKAGES_WITH_IMAGES.has(pkg)) {
      hasImagePackages.add(pkg);
    }
    if (pkg in PACKAGE_TO_SITE) {
      hasSitePackages.add(pkg);
    }
    if (PACKAGES_WITH_NPM.has(pkg)) {
      hasNpmPackages.add(pkg);
    }
  }

  return {
    packages: allAffected,
    directlyChanged,
    buildAll: false,
    homelabChanged: allAffected.has("homelab"),
    tofuChanged,
    cooklangChanged,
    resumeChanged: allAffected.has("resume"),
    helmTypesInputsChanged,
    ciImageChanged,
    hasImagePackages,
    hasSitePackages,
    hasNpmPackages,
    ciImageVersionChanged,
    versionBumpOnly: false,
    releasePleaseMerge: isReleasePleaseMerge(),
    isAutoGenerated: isAutoGeneratedCommit(),
  };
}

// ---------------------------------------------------------------------------
// Main detection
// ---------------------------------------------------------------------------

export async function detectChanges(): Promise<AffectedPackages> {
  const forceFullEnv =
    (process.env["FULL_BUILD"] ?? "").toLowerCase() === "true";
  const commitMsg = process.env["BUILDKITE_MESSAGE"] ?? "";
  const forceFull = forceFullEnv || commitMsg.includes("[full-build]");

  if (forceFull) {
    // A forced full build rebuilds/retests everything but never publishes
    // cooklang — change a cooklang source file to cut a plugin release.
    console.error("Full build requested, building everything");
    return fullBuildResult(false);
  }

  const changedFiles = await getChangedFiles();
  const cooklangSourceChanged = hasCooklangSourceChange(changedFiles);
  const tofuChanged = checkTofuChanges(changedFiles);
  // Over-triggers on any versions.ts change (it mixes image + chart versions),
  // but never under-triggers on a chart bump — correctness over a little extra
  // runtime. Image-digest commit-backs go through the version-commit-back path
  // below, which keeps the default `false`.
  const helmTypesInputsChanged = checkHelmTypesInputChanges(changedFiles);

  // Renovate fast-track: runs BEFORE infra check so that bun.lock/package.json
  // in INFRA_FILES don't short-circuit the fast path.
  if (isRenovatePr()) {
    const classification = classifyRenovateFiles(changedFiles);
    if (classification !== null) {
      console.error(`Renovate fast-track: ${classification.kind}`);

      if (classification.kind === "noop") {
        if (helmTypesInputsChanged) {
          // versions.ts is a HELM_TYPES_INPUT_FILE — a Renovate chart-bump PR that
          // only touches versions.ts still needs the drift-check step so that the CI
          // gate fires on chart-version bumps (the main use-case this PR was built to
          // cover). Include "homelab" in the packages set so that the per-package loop
          // in buildPipeline runs for homelab and emits the drift-check step via
          // perPackageSteps("homelab", helmTypesInputsChanged=true). An empty set would
          // hit the early-return guard in buildPipeline and skip the drift check.
          console.error(
            "Renovate noop, but helmTypesInputsChanged=true — emitting drift-check step for homelab",
          );
          return buildScopedResult(
            new Set(["homelab"]),
            // No top-level package files changed (only versions.ts); the
            // drift gate has nothing to expand from. The closure {homelab} is
            // still emitted to drive the helm-types drift step.
            new Set(),
            false,
            false,
            false,
            false,
            true,
          );
        }
        console.error("Renovate: no builds needed");
        return emptyResult();
      }

      // Seed directly-changed packages from classification, then fall through
      // to transitive closure + flag derivation below.
      const directlyChanged = new Set<string>();
      if (classification.kind === "scoped") {
        for (const pkg of classification.packages) {
          if (ALL_PACKAGES.includes(pkg)) {
            directlyChanged.add(pkg);
          }
        }
      } else {
        // all-js
        for (const pkg of JS_TS_PACKAGES) {
          directlyChanged.add(pkg);
        }
      }

      const depGraph = await readWorkspaceDeps();
      const allAffected = transitiveClosure(directlyChanged, depGraph);

      console.error(`Renovate affected packages (${allAffected.size}):`);
      for (const p of [...allAffected].sort()) {
        console.error(`  ${p}`);
      }

      return buildScopedResult(
        allAffected,
        directlyChanged,
        cooklangSourceChanged,
        false,
        false,
        tofuChanged,
        helmTypesInputsChanged,
      );
    }

    // classification === null: unrecognized files, fall through to normal detection
    console.error(
      "Renovate PR with unrecognized files, using normal detection",
    );
  }

  // Version commit-back fast-track: prevents infinite loop where
  // version-commit-back → merge → build → images → version-commit-back.
  // The new digests still need to flow through cdk8s synth → Helm push → ArgoCD,
  // but image builds and another version-commit-back must be skipped.
  if (isVersionCommitBack()) {
    const classification = classifyRenovateFiles(changedFiles);
    if (classification !== null && classification.kind === "noop") {
      console.error(
        "Version commit-back: skipping image builds, running deploy pipeline",
      );
      const result = buildScopedResult(
        new Set(["homelab"]),
        // Version commit-back touches only versions.ts; no top-level
        // package.json/bun.lock changes for the drift gate to seed from.
        new Set(),
        cooklangSourceChanged,
        false,
        false,
        tofuChanged,
      );
      result.versionBumpOnly = true;
      return result;
    }
    console.error(
      "Version commit-back with non-trivial changes, using normal detection",
    );
  }

  // Cooklang commit-back fast-track: the publish step already released the
  // plugin and opened this metadata bump. Do not publish again from the bump.
  if (isCooklangVersionCommitBack()) {
    if (isCooklangVersionCommitBackOnly(changedFiles)) {
      console.error(
        "Cooklang version commit-back: skipping cooklang release pipeline",
      );
      return emptyResult();
    }
    console.error(
      "Cooklang version commit-back with non-trivial changes, using normal detection",
    );
  }

  // Normal detection: check infrastructure files
  const infraChanged = checkInfraChanges(changedFiles);
  if (infraChanged) {
    console.error("Infrastructure files changed, building everything");
    return fullBuildResult(cooklangSourceChanged);
  }

  // Map changed files to packages
  const directlyChanged = new Set<string>();
  for (const f of changedFiles) {
    const pkg = extractPackageName(f);
    if (pkg !== null && ALL_PACKAGES.includes(pkg)) {
      directlyChanged.add(pkg);
    }
  }

  const ciImageChanged = checkCiImageChanges(changedFiles);
  const ciImageVersionChanged = checkCiImageVersionChanges(changedFiles);

  if (directlyChanged.size === 0 && !ciImageChanged && !ciImageVersionChanged) {
    console.error("No affected packages detected");
    return emptyResult();
  }

  // Compute transitive closure via workspace dependency graph
  const depGraph = await readWorkspaceDeps();
  const allAffected = transitiveClosure(directlyChanged, depGraph);

  console.error(`Affected packages (${allAffected.size}):`);
  for (const p of [...allAffected].sort()) {
    console.error(`  ${p}`);
  }

  return buildScopedResult(
    allAffected,
    directlyChanged,
    cooklangSourceChanged,
    ciImageChanged,
    ciImageVersionChanged,
    tofuChanged,
    helmTypesInputsChanged,
  );
}

// Export for testing
export {
  checkInfraChanges as _checkInfraChanges,
  extractPackageName as _extractPackageName,
  transitiveClosure as _transitiveClosure,
  isRenovatePr as _isRenovatePr,
  isVersionCommitBack as _isVersionCommitBack,
  isCooklangVersionCommitBack as _isCooklangVersionCommitBack,
  isCooklangVersionCommitBackOnly as _isCooklangVersionCommitBackOnly,
  hasCooklangSourceChange as _hasCooklangSourceChange,
  isAutoGeneratedCommit as _isAutoGeneratedCommit,
  isReleasePleaseMerge as _isReleasePleaseMerge,
  shouldSkipReleasePleasePrBuild as _shouldSkipReleasePleasePrBuild,
  classifyRenovateFiles as _classifyRenovateFiles,
  checkCiImageChanges as _checkCiImageChanges,
  checkCiImageVersionChanges as _checkCiImageVersionChanges,
  checkTofuChanges as _checkTofuChanges,
  checkHelmTypesInputChanges as _checkHelmTypesInputChanges,
  getBuildRejectionReason as _getBuildRejectionReason,
  getLastSuccessfulCommit as _getLastSuccessfulCommit,
  getBaseRevision as _getBaseRevision,
  getChangedFiles as _getChangedFiles,
  NON_JS_PACKAGES as _NON_JS_PACKAGES,
  JS_TS_PACKAGES as _JS_TS_PACKAGES,
};
