/**
 * Assembles the full Buildkite pipeline from AffectedPackages.
 */
import {
  ALL_PACKAGES,
  IMAGE_PUSH_TARGETS,
  INFRA_PUSH_TARGETS,
  TOFU_STACKS,
} from "./catalog.ts";
import type { ImageTarget } from "./catalog.ts";
import type { AffectedPackages } from "./lib/types.ts";
import type {
  BuildkiteStep,
  PipelineStep,
  BuildkitePipeline,
} from "./lib/types.ts";
import { perPackageSteps } from "./steps/per-package.ts";
import {
  prettierStep,
  markdownlintStep,
  shellcheckStep,
  qualityRatchetStep,
  checkTodosStep,
  complianceCheckStep,
  knipCheckStep,
  gitleaksCheckStep,
  suppressionCheckStep,
  trivyScanStep,
  semgrepScanStep,
  daggerHygieneStep,
  tunnelDnsCoverageStep,
  talosSchematicSyncStep,
  reactVersionSyncStep,
  caddyfileValidateStep,
  lockfileCheckStep,
  envVarNamesStep,
  lineEndingsCheckStep,
  scoutTestTemplateCheckStep,
  migrationGuardStep,
  mergeConflictStep,
  largeFileStep,
  greptileReviewStep,
} from "./steps/quality.ts";
import { releasePleaseStep } from "./steps/release.ts";
import {
  buildImagesWithSmokeGroup,
  pushImagesGroup,
  allPushKeys,
} from "./steps/images.ts";
import { publishNpmGroup, filterNpmPackages } from "./steps/npm.ts";
import { deploySitesGroup, filterSites } from "./steps/sites.ts";
import {
  cdk8sSynthStep,
  onePasswordItemsStep,
  homelabHelmGroup,
} from "./steps/helm.ts";
import { homelabTofuGroup, homelabTofuPlanGroup } from "./steps/tofu.ts";
import { argoCdSyncStep, argoCdHealthStep } from "./steps/argocd.ts";
import { cooklangReleaseGroup } from "./steps/cooklang.ts";
import { versionCommitBackStep } from "./steps/version.ts";
import {
  ciBaseImageBuildStep,
  ciBaseImagePushStep,
  ciBaseVersionCommitBackStep,
} from "./steps/ci-image.ts";
import { buildSummaryStep } from "./steps/build-summary.ts";
import { k8sPlugin } from "./lib/k8s-plugin.ts";

function isPullRequestBuild(): boolean {
  const pullRequest = process.env["BUILDKITE_PULL_REQUEST"] ?? "false";
  return pullRequest !== "" && pullRequest !== "false";
}

function greptileGateForPullRequest(): BuildkiteStep[] {
  return isPullRequestBuild() ? [greptileReviewStep()] : [];
}

/**
 * Minimal pipeline emitted for auto-triggered release-please PR builds (see
 * {@link shouldSkipReleasePleasePrBuild}). It runs a single annotation step and
 * intentionally omits the Greptile and `ci-complete` required gates, so the
 * webhook build finishes in seconds and the PR stays un-mergeable until a real
 * build is requested on purpose.
 */
export function buildReleasePleaseSkipPipeline(): BuildkitePipeline {
  return {
    agents: { queue: "default" },
    steps: [
      {
        label: ":fast_forward: Release-please PR — CI auto-skipped",
        key: "release-please-skip",
        command:
          'buildkite-agent annotate "Full CI is auto-skipped for release-please PRs. To run CI (and make this release mergeable), trigger a build manually in the Buildkite UI (New Build) or set RUN_RELEASE_CI=true." --style info --context release-please-skip',
        plugins: [k8sPlugin()],
      },
    ],
  };
}

export function buildPipeline(affected: AffectedPackages): BuildkitePipeline {
  const steps: PipelineStep[] = [];
  const pullRequestBuild = isPullRequestBuild();
  const releaseBuild = !pullRequestBuild;

  if (affected.ciImageVersionChanged && !affected.isAutoGenerated) {
    steps.push({
      label: ":no_entry_sign: CI Base Version Guard",
      key: "ci-base-version-guard",
      command:
        "echo '.buildkite/ci-image/VERSION is updated by CI after ghcr.io/shepherdjerred/ci-base is published. Revert this file from the PR.' && exit 1",
      plugins: [k8sPlugin()],
    });
    const greptileGates = greptileGateForPullRequest();
    steps.push(...greptileGates);
    steps.push({
      label: ":white_check_mark: CI Complete",
      key: "ci-complete",
      command: "echo 'CI complete'",
      depends_on: ["ci-base-version-guard", ...greptileGates.map((s) => s.key)],
      plugins: [k8sPlugin()],
    });
    return { agents: { queue: "default" }, steps };
  }

  // If nothing changed, emit a minimal pipeline
  if (
    !affected.buildAll &&
    affected.packages.size === 0 &&
    !affected.ciImageChanged &&
    (!affected.ciImageVersionChanged || affected.isAutoGenerated)
  ) {
    steps.push({
      label: ":white_check_mark: No changes detected",
      key: "no-changes",
      command: "echo 'No affected targets detected, nothing to build.'",
      plugins: [k8sPlugin()],
    });
    const greptileGates = greptileGateForPullRequest();
    steps.push(...greptileGates);
    steps.push({
      label: ":white_check_mark: CI Complete",
      key: "ci-complete",
      command: "echo 'CI complete'",
      depends_on: ["no-changes", ...greptileGates.map((s) => s.key)],
      plugins: [k8sPlugin()],
    });
    return { agents: { queue: "default" }, steps };
  }

  // --- Per-package build & test steps ---
  const packages = affected.buildAll
    ? ALL_PACKAGES.slice().sort()
    : [...affected.packages].sort();

  // Map package name → build group key (e.g. "birmel" → "pkg-birmel")
  // Used to scope downstream steps to their own package build only.
  const pkgKeyMap = new Map<string, string>();

  // Release depends only on repo-wide quality gates, NOT per-package builds.
  const releaseDeps: string[] = [];

  for (const pkg of packages) {
    const group = perPackageSteps(pkg);
    if (group) {
      steps.push(group);
      pkgKeyMap.set(pkg, group.key);
    }
  }

  // --- Quality gates (blocking — must pass before releases) ---
  const blockingGates = [
    lockfileCheckStep(),
    shellcheckStep(),
    qualityRatchetStep(),
    checkTodosStep(),
    complianceCheckStep(),
    gitleaksCheckStep(),
    suppressionCheckStep(),
    envVarNamesStep(),
    lineEndingsCheckStep(),
    scoutTestTemplateCheckStep(),
    migrationGuardStep(),
    mergeConflictStep(),
    largeFileStep(),
    reactVersionSyncStep(),
    ...(pullRequestBuild ? [greptileReviewStep()] : []),
  ];
  for (const gate of blockingGates) {
    steps.push(gate);
    releaseDeps.push(gate.key);
  }

  // --- Async quality checks (soft_fail, run in parallel with release track) ---
  steps.push(prettierStep());
  steps.push(markdownlintStep());
  steps.push(knipCheckStep());
  steps.push(daggerHygieneStep());
  if (affected.buildAll || affected.homelabChanged) {
    steps.push(tunnelDnsCoverageStep());
    steps.push(talosSchematicSyncStep());
  }
  steps.push(trivyScanStep());
  steps.push(semgrepScanStep());

  // --- Caddyfile validation (blocking, only when homelab changes) ---
  if (affected.buildAll || affected.homelabChanged) {
    const caddyStep = caddyfileValidateStep();
    steps.push(caddyStep);
    releaseDeps.push(caddyStep.key);
  }

  // --- Main-only steps ---
  const hasMainSteps =
    affected.buildAll ||
    affected.hasImagePackages.size > 0 ||
    affected.hasSitePackages.size > 0 ||
    affected.hasNpmPackages.size > 0 ||
    affected.homelabChanged ||
    affected.cooklangChanged ||
    affected.ciImageChanged;

  if (hasMainSteps) {
    // Quality gate: lightweight step that passes once all blocking checks pass.
    // Downstream steps that don't need release metadata depend on this instead.
    steps.push({
      label: ":shield: Quality Gate",
      key: "quality-gate",
      command: "echo 'All quality gates passed'",
      depends_on: releaseDeps,
      plugins: [k8sPlugin()],
    });

    // Release-please: creates/updates version bump PRs and GitHub releases.
    // Fire-and-forget — nothing depends on it.
    if (releaseBuild) {
      steps.push(releasePleaseStep(releaseDeps));
    }

    // =======================================================================
    // BUILD PHASE — depends on quality-gate, runs before release
    // =======================================================================

    // Determine which images need building based on what changed.
    // versionBumpOnly: digests already pushed — skip image rebuilds to prevent loop.
    const imagesToBuild: ImageTarget[] = [];
    if (!affected.versionBumpOnly) {
      if (affected.buildAll) {
        imagesToBuild.push(...IMAGE_PUSH_TARGETS, ...INFRA_PUSH_TARGETS);
      } else {
        if (affected.hasImagePackages.size > 0) {
          // Filter to only the images whose package actually changed —
          // a temporal-only PR shouldn't trigger birmel/scout/etc rebuilds.
          // `img.package ?? img.name` matches the disambiguation used in
          // steps/images.ts for `--pkg-dir ./packages/<pkg>`.
          for (const img of IMAGE_PUSH_TARGETS) {
            const pkg = img.package ?? img.name;
            if (affected.hasImagePackages.has(pkg)) {
              imagesToBuild.push(img);
            }
          }
        }
        if (affected.homelabChanged) {
          imagesToBuild.push(...INFRA_PUSH_TARGETS);
        }
      }
    }
    const hasImages = imagesToBuild.length > 0;

    // --- Build all images + smoke tests ---
    if (hasImages) {
      steps.push(buildImagesWithSmokeGroup(imagesToBuild, pkgKeyMap));
    }

    // --- Build + push CI base image ---
    if (affected.ciImageChanged) {
      steps.push(ciBaseImageBuildStep());
      steps.push(ciBaseImagePushStep());
      if (!affected.isAutoGenerated) {
        steps.push(ciBaseVersionCommitBackStep());
      }
    }

    // --- Build cdk8s manifests ---
    if (affected.buildAll || affected.homelabChanged) {
      const homelabPkgKey = pkgKeyMap.get("homelab");
      const synthDeps = homelabPkgKey
        ? ["quality-gate", homelabPkgKey]
        : ["quality-gate"];
      steps.push(cdk8sSynthStep(synthDeps));
      // Blocking gate: every OnePasswordItem reference + consumed field must exist
      // in the committed vault snapshot. Shares the synth environment.
      steps.push(onePasswordItemsStep(synthDeps));
    }

    // =======================================================================
    // RELEASE PHASE — depends on release + build keys
    // =======================================================================

    // --- Push all images ---
    let imagePushKeys: string[] = [];
    if (releaseBuild && hasImages) {
      steps.push(pushImagesGroup(imagesToBuild));
      imagePushKeys = allPushKeys(imagesToBuild);
    }

    // --- Publish NPM packages ---
    if (
      releaseBuild &&
      (affected.buildAll || affected.hasNpmPackages.size > 0)
    ) {
      const npmToPublish = filterNpmPackages(
        affected.hasNpmPackages,
        affected.buildAll,
      );
      if (npmToPublish.length > 0) {
        steps.push(
          publishNpmGroup(npmToPublish, pkgKeyMap, affected.releasePleaseMerge),
        );
      }
    }

    // --- Cooklang Release ---
    // Gated on a real cooklang *source* change only — NOT `buildAll`. A full
    // build (infra/lockfile change) rebuilds cooklang for safety but must not
    // publish a new plugin version, or every unrelated full build would cut a
    // release and open a `chore(cooklang): bump plugin manifest version` PR.
    // Also skipped on bot-authored commits so the manifest commit-back merge
    // cannot re-publish the next patch and loop.
    if (releaseBuild && !affected.isAutoGenerated && affected.cooklangChanged) {
      steps.push(cooklangReleaseGroup(pkgKeyMap.get("cooklang-for-obsidian")));
    }

    // --- Deploy sites ---
    if (
      releaseBuild &&
      (affected.buildAll || affected.hasSitePackages.size > 0)
    ) {
      const sitesToDeploy = filterSites(
        affected.hasSitePackages,
        affected.buildAll,
      );
      const siteDeployDeps =
        affected.buildAll || affected.homelabChanged ? ["tofu-seaweedfs"] : [];
      steps.push(deploySitesGroup(sitesToDeploy, pkgKeyMap, siteDeployDeps));
    }

    // --- Homelab Tofu Plan (runs on PRs for early feedback) ---
    // Gated on tofu *source* changes (not any homelab change) so cdk8s-only PRs
    // don't run plans that yield no signal for them. `.dagger/` and `scripts/ci/`
    // changes trigger a full build, which runs the plan via `buildAll`.
    if (pullRequestBuild && (affected.buildAll || affected.tofuChanged)) {
      steps.push(homelabTofuPlanGroup());
    }

    // --- Homelab Helm + Tofu release track ---
    if (releaseBuild && (affected.buildAll || affected.homelabChanged)) {
      // Helm charts (push only — cdk8s synth already ran in build phase)
      steps.push(homelabHelmGroup());

      // Homelab Tofu: 3 parallel stacks
      steps.push(homelabTofuGroup(pkgKeyMap.get("homelab")));
    }

    // --- Unified ArgoCD sync (depends on whatever upstream steps ran) ---
    const needsArgoSync =
      releaseBuild &&
      (hasImages || affected.buildAll || affected.homelabChanged);
    if (needsArgoSync) {
      const argocdDeps: string[] = [];
      if (hasImages) {
        argocdDeps.push(...imagePushKeys);
      }
      if (affected.buildAll || affected.homelabChanged) {
        argocdDeps.push(
          "homelab-helm-push",
          ...TOFU_STACKS.map((s) => `tofu-${s}`),
        );
      }
      steps.push(
        argoCdSyncStep(argocdDeps, { key: "deploy-argocd", app: "apps" }),
      );
      steps.push(
        argoCdHealthStep("deploy-argocd", {
          key: "argocd-health",
          app: "apps",
        }),
      );
    }

    // --- Version Commit-Back ---
    // Skipped on bot-authored commits (Auto-Generated: trailer) so the bump
    // merge build can't open another bump PR — that's the loop we don't want.
    if (releaseBuild && hasImages && !affected.isAutoGenerated) {
      const vcbDeps: string[] = ["quality-gate", ...imagePushKeys];
      const pushedVersionKeys = imagesToBuild.map((t) => t.versionKey);
      steps.push(versionCommitBackStep(vcbDeps, pushedVersionKeys));
    }

    // --- Build Summary ---
    // Collect all terminal step keys so the summary runs last
    if (releaseBuild) {
      const summaryDeps: string[] = ["quality-gate"];
      if (hasImages) summaryDeps.push(...imagePushKeys);
      if (affected.ciImageChanged) {
        summaryDeps.push(
          affected.isAutoGenerated
            ? "push-ci-base"
            : "ci-base-version-commit-back",
        );
      }
      if (needsArgoSync) {
        summaryDeps.push("argocd-health");
      }
      steps.push(buildSummaryStep(summaryDeps));
    }
  }

  // --- CI Complete: single terminal step for GitHub required status check ---
  const ciCompleteDeps = [...releaseDeps, ...pkgKeyMap.values()];
  steps.push({
    label: ":white_check_mark: CI Complete",
    key: "ci-complete",
    command: "echo 'CI complete'",
    depends_on: ciCompleteDeps,
    plugins: [k8sPlugin()],
  });

  return { agents: { queue: "default" }, steps };
}
