/**
 * Assembles the full Buildkite pipeline from AffectedPackages.
 */
import {
  ALL_PACKAGES,
  IMAGE_PUSH_TARGETS,
  INFRA_PUSH_TARGETS,
} from "./catalog.ts";
import type { ImageTarget } from "./catalog.ts";
import type { AffectedPackages } from "./lib/types.ts";
import type {
  BuildkiteStep,
  PipelineStep,
  BuildkitePipeline,
} from "./lib/types.ts";
import { perPackageSteps } from "./steps/per-package.ts";
import {
  qualityBundleStep,
  knipCheckStep,
  trivyScanStep,
  semgrepScanStep,
  softFailBundleStep,
  tunnelDnsCoverageStep,
  talosSchematicSyncStep,
  caddyfileValidateStep,
  bunLockDriftCheckStep,
  greptileReviewStep,
} from "./steps/quality.ts";
import { releasePleaseStep } from "./steps/release.ts";
import {
  buildImagesWithSmokeGroup,
  pushImagesGroup,
  allPushKeys,
} from "./steps/images.ts";
import { publishNpmGroup, filterNpmPackages } from "./steps/npm.ts";
import { deploySitesGroup, filterSites } from "./steps/sites.ts";
import {
  homelabCdk8sBundleStep,
  homelabHelmPushAllStep,
} from "./steps/helm.ts";
import {
  homelabTofuApplyAllStep,
  homelabTofuApplyGithubStep,
  homelabTofuPlanAllStep,
} from "./steps/tofu.ts";
import { argoCdSyncAndWaitStep } from "./steps/argocd.ts";
import { cooklangReleaseGroup } from "./steps/cooklang.ts";
import { versionCommitBackStep } from "./steps/version.ts";
import {
  ciBaseImageBuildStep,
  ciBaseImagePushStep,
  ciBaseVersionCommitBackStep,
} from "./steps/ci-image.ts";
import { buildSummaryStep } from "./steps/build-summary.ts";
import { k8sPlugin } from "./lib/k8s-plugin.ts";

function isPullRequestBuild(): boolean {
  const pullRequest = process.env["BUILDKITE_PULL_REQUEST"] ?? "false";
  return pullRequest !== "" && pullRequest !== "false";
}

function greptileGateForPullRequest(): BuildkiteStep[] {
  return isPullRequestBuild() ? [greptileReviewStep()] : [];
}

/**
 * Minimal pipeline emitted for auto-triggered release-please PR builds (see
 * {@link shouldSkipReleasePleasePrBuild}). It runs a single annotation step and
 * intentionally omits the Greptile and `ci-complete` required gates, so the
 * webhook build finishes in seconds and the PR stays un-mergeable until a real
 * build is requested on purpose.
 */
export function buildReleasePleaseSkipPipeline(): BuildkitePipeline {
  return {
    agents: { queue: "default" },
    steps: [
      {
        label: ":fast_forward: Release-please PR — CI auto-skipped",
        key: "release-please-skip",
        command:
          'buildkite-agent annotate "Full CI is auto-skipped for release-please PRs. To run CI (and make this release mergeable), trigger a build manually in the Buildkite UI (New Build) or set RUN_RELEASE_CI=true." --style info --context release-please-skip',
        plugins: [k8sPlugin()],
      },
    ],
  };
}

export function buildPipeline(affected: AffectedPackages): BuildkitePipeline {
  const steps: PipelineStep[] = [];
  const pullRequestBuild = isPullRequestBuild();
  const releaseBuild = !pullRequestBuild;

  // The guard is a PR-merge blocker only. On main it must never fire: the
  // change already merged, so failing the build blocks deploys without
  // preventing anything — and because main builds diff against the LAST
  // SUCCESSFUL main commit, a bump whose own build failed for unrelated
  // reasons (e.g. build 5187's transient chart-push timeout) poisons every
  // subsequent innocent commit with an always-fail guard until the pointer
  // moves past the bump (took main down on 2026-07-09, build 5190).
  if (
    affected.ciImageVersionChanged &&
    !affected.isAutoGenerated &&
    pullRequestBuild
  ) {
    steps.push({
      label: ":no_entry_sign: CI Base Version Guard",
      key: "ci-base-version-guard",
      command:
        "echo '.buildkite/ci-image/VERSION is updated by CI after ghcr.io/shepherdjerred/ci-base is published. Revert this file from the PR.' && exit 1",
      plugins: [k8sPlugin()],
    });
    const greptileGates = greptileGateForPullRequest();
    steps.push(...greptileGates);
    steps.push({
      label: ":white_check_mark: CI Complete",
      key: "ci-complete",
      command: "echo 'CI complete'",
      depends_on: ["ci-base-version-guard", ...greptileGates.map((s) => s.key)],
      plugins: [k8sPlugin()],
    });
    return { agents: { queue: "default" }, steps };
  }

  // If nothing changed, emit a minimal pipeline.
  // Note: helmTypesInputsChanged must be false here — if it is true and packages
  // includes "homelab", the per-package loop below will emit the drift-check step.
  // This guard is intentionally written as a defense-in-depth: change-detection.ts
  // ensures that helmTypesInputsChanged=true always comes with homelab in packages.
  if (
    !affected.buildAll &&
    affected.packages.size === 0 &&
    !affected.ciImageChanged &&
    !affected.helmTypesInputsChanged &&
    (!affected.ciImageVersionChanged || affected.isAutoGenerated)
  ) {
    steps.push({
      label: ":white_check_mark: No changes detected",
      key: "no-changes",
      command: "echo 'No affected targets detected, nothing to build.'",
      plugins: [k8sPlugin()],
    });
    const greptileGates = greptileGateForPullRequest();
    steps.push(...greptileGates);
    steps.push({
      label: ":white_check_mark: CI Complete",
      key: "ci-complete",
      command: "echo 'CI complete'",
      depends_on: ["no-changes", ...greptileGates.map((s) => s.key)],
      plugins: [k8sPlugin()],
    });
    return { agents: { queue: "default" }, steps };
  }

  // --- Per-package build & test steps ---
  const packages = affected.buildAll
    ? ALL_PACKAGES.slice().sort()
    : [...affected.packages].sort();

  // Map package name → build group key (e.g. "birmel" → "pkg-birmel")
  // Used to scope downstream steps to their own package build only.
  const pkgKeyMap = new Map<string, string>();

  // Release is gated on every per-package pkg-check AND the repo-wide quality
  // gates below. Release-train rule: main red ⇒ nothing ships. Per-package
  // gating alone (a pkg-check only blocking its own image build at
  // images.ts:309-311) is not enough — a single failed pkg-check would
  // otherwise let the other 12+ images and the helm chart push under a red
  // commit (see build #4369).
  const releaseDeps: string[] = [];

  for (const pkg of packages) {
    const group = perPackageSteps(pkg, affected.helmTypesInputsChanged);
    if (group) {
      steps.push(group);
      pkgKeyMap.set(pkg, group.key);
      releaseDeps.push(group.key);
    }
  }

  // --- Quality gates (blocking — must pass before releases) ---
  // The per-package `bun.lock` drift gate runs only when there's a scoped
  // affected set with at least one directly-changed package: on `buildAll`,
  // every per-package Dagger job already runs `bun install --frozen-lockfile`
  // so the gate adds no signal; on the no-changes path we short-circuited
  // above. For scoped Renovate-style PRs the gate is the fastest signal we
  // get on transitive `file:`-dep drift.
  //
  // We pass `affected.directlyChanged` (the diff-seeds), NOT `packages` (the
  // closure). `change-detection.transitiveClosure` only reads top-level
  // `packages/<X>/package.json`, so a nested-workspace edge — like dpp's
  // `file:../../../llm-observability` in
  // `packages/discord-plays-pokemon/packages/backend/package.json` — is
  // invisible to it. The drift script re-expands the closure using a
  // nested-aware graph (`--seeds` mode), so dpp gets pulled in when
  // `llm-observability` is bumped, which is exactly the PR #1213 scenario
  // this gate was built to catch.
  const driftSeeds = [...affected.directlyChanged].sort();
  const driftGate: BuildkiteStep[] =
    !affected.buildAll && driftSeeds.length > 0
      ? [bunLockDriftCheckStep(driftSeeds)]
      : [];
  // 15 source-only blocking checks (shellcheck, ratchet, todos, compliance,
  // gitleaks, suppression, env-var-names, line-endings, scout-test-template,
  // migration-guard, merge-conflict, react-version-sync, lockfile-check,
  // prettier, markdownlint) collapse into one bundled BK pod via
  // `qualityBundle`. The bundle's Dagger function fans them out in parallel
  // with Promise.all on sibling containers — the engine de-dups the shared
  // source fetch by SHA. driftGate stays separate (runtime --seeds arg);
  // greptile stays separate (PR-only authenticated review wait).
  const blockingGates = [
    qualityBundleStep(),
    ...driftGate,
    ...(pullRequestBuild ? [greptileReviewStep()] : []),
  ];
  for (const gate of blockingGates) {
    steps.push(gate);
    releaseDeps.push(gate.key);
  }

  // --- Async quality checks (soft_fail, run in parallel with release track) ---
  steps.push(knipCheckStep());
  // dagger-hygiene + large-file-check share a bundled soft-fail step.
  steps.push(softFailBundleStep());
  if (affected.buildAll || affected.homelabChanged) {
    steps.push(tunnelDnsCoverageStep());
    steps.push(talosSchematicSyncStep());
  }
  steps.push(trivyScanStep());
  steps.push(semgrepScanStep());

  // --- Caddyfile validation (blocking, only when homelab changes) ---
  if (affected.buildAll || affected.homelabChanged) {
    const caddyStep = caddyfileValidateStep();
    steps.push(caddyStep);
    releaseDeps.push(caddyStep.key);
  }

  // --- Release and PR dryrun-capable steps ---
  const hasReleaseOrPrDryrunSteps =
    affected.buildAll ||
    affected.hasImagePackages.size > 0 ||
    affected.hasSitePackages.size > 0 ||
    affected.hasNpmPackages.size > 0 ||
    affected.homelabChanged ||
    affected.cooklangChanged ||
    affected.ciImageChanged;

  // Deploy-site step keys, populated inside the release/PR dryrun block below
  // and folded into `ci-complete`'s depends_on so a failed site build
  // (including a PR dryrun) blocks the required GitHub check.
  let siteDeployKeys: string[] = [];

  if (hasReleaseOrPrDryrunSteps) {
    // Quality gate: lightweight step that passes once all blocking checks pass.
    // Downstream steps that don't need release metadata depend on this instead.
    steps.push({
      label: ":shield: Quality Gate",
      key: "quality-gate",
      command: "echo 'All quality gates passed'",
      depends_on: releaseDeps,
      plugins: [k8sPlugin()],
    });

    // Release-please: creates/updates version bump PRs and GitHub releases.
    // Fire-and-forget — nothing depends on it.
    if (releaseBuild) {
      steps.push(releasePleaseStep(releaseDeps));
    }

    // =======================================================================
    // BUILD PHASE — depends on quality-gate, runs before release
    // =======================================================================

    // Determine which images need building based on what changed.
    // versionBumpOnly: digests already pushed — skip image rebuilds to prevent loop.
    const imagesToBuild: ImageTarget[] = [];
    if (!affected.versionBumpOnly) {
      if (affected.buildAll) {
        imagesToBuild.push(...IMAGE_PUSH_TARGETS, ...INFRA_PUSH_TARGETS);
      } else {
        if (affected.hasImagePackages.size > 0) {
          // Filter to only the images whose package actually changed —
          // a temporal-only PR shouldn't trigger birmel/scout/etc rebuilds.
          // `img.package ?? img.name` matches the disambiguation used in
          // steps/images.ts for `--pkg-dir ./packages/<pkg>`.
          for (const img of IMAGE_PUSH_TARGETS) {
            const pkg = img.package ?? img.name;
            if (affected.hasImagePackages.has(pkg)) {
              imagesToBuild.push(img);
            }
          }
        }
        if (affected.homelabChanged) {
          imagesToBuild.push(...INFRA_PUSH_TARGETS);
        }
      }
    }
    const hasImages = imagesToBuild.length > 0;

    // --- Build all images + smoke tests ---
    if (hasImages) {
      steps.push(buildImagesWithSmokeGroup(imagesToBuild, pkgKeyMap));
    }

    // --- Build + push CI base image ---
    if (affected.ciImageChanged) {
      steps.push(ciBaseImageBuildStep());
      steps.push(ciBaseImagePushStep());
      if (!affected.isAutoGenerated) {
        steps.push(ciBaseVersionCommitBackStep());
      }
    }

    // --- Build cdk8s manifests + 1Password item lint (bundled) ---
    if (affected.buildAll || affected.homelabChanged) {
      const homelabPkgKey = pkgKeyMap.get("homelab");
      const synthDeps = homelabPkgKey
        ? ["quality-gate", homelabPkgKey]
        : ["quality-gate"];
      // cdk8s synth + 1Password lint share the same bunBaseContainer
      // prefix — bundle into one pod via runBundle/Promise.all.
      steps.push(homelabCdk8sBundleStep(synthDeps));
    }

    // =======================================================================
    // RELEASE PHASE — depends on release + build keys
    // =======================================================================

    // --- Push all images ---
    let imagePushKeys: string[] = [];
    if (releaseBuild && hasImages) {
      steps.push(pushImagesGroup(imagesToBuild));
      imagePushKeys = allPushKeys(imagesToBuild);
    }

    // --- Publish NPM packages ---
    if (
      releaseBuild &&
      (affected.buildAll || affected.hasNpmPackages.size > 0)
    ) {
      const npmToPublish = filterNpmPackages(
        affected.hasNpmPackages,
        affected.buildAll,
      );
      if (npmToPublish.length > 0) {
        steps.push(
          publishNpmGroup(npmToPublish, pkgKeyMap, affected.releasePleaseMerge),
        );
      }
    }

    // --- Cooklang Release ---
    // Gated on a real cooklang *source* change only — NOT `buildAll`. A full
    // build (infra/lockfile change) rebuilds cooklang for safety but must not
    // publish a new plugin version, or every unrelated full build would cut a
    // release and open a `chore(cooklang): bump plugin manifest version` PR.
    // Also skipped on bot-authored commits so the manifest commit-back merge
    // cannot re-publish the next patch and loop.
    if (releaseBuild && !affected.isAutoGenerated && affected.cooklangChanged) {
      steps.push(cooklangReleaseGroup(pkgKeyMap.get("cooklang-for-obsidian")));
    }

    // --- Deploy sites (release) / dryrun site builds (PR) ---
    // Release builds sync to SeaweedFS. PR builds run the SAME site build as a
    // dryrun (deploySiteStep appends `--dryrun` via DRYRUN_FLAG, skipping the
    // sync) so frontend build regressions — e.g. Astro `astro:build:done`
    // OG-image generation — are caught before merge. The real deploy is
    // main-only, so without this a site build break first surfaces in the
    // main deploy (see the scout OG `jsxDEV` incident, build 5069).
    //
    // On PRs we scope to sites whose SOURCE actually changed (hasSitePackages)
    // and skip `buildAll` (infra/lockfile PRs), which would otherwise dryrun
    // all ~9 sites; those still get real deploy validation on main.
    const deploySites = releaseBuild
      ? affected.buildAll || affected.hasSitePackages.size > 0
      : !affected.buildAll && affected.hasSitePackages.size > 0;
    if (deploySites) {
      const sitesToDeploy = filterSites(
        affected.hasSitePackages,
        releaseBuild && affected.buildAll,
      );
      // Only real (release) syncs need the SeaweedFS bucket to exist, so only
      // they wait on the bundled tofu-apply-all step. PR dryruns never sync.
      const siteDeployDeps =
        releaseBuild && (affected.buildAll || affected.homelabChanged)
          ? ["tofu-apply-all"]
          : [];
      const sitesGroup = deploySitesGroup(
        sitesToDeploy,
        pkgKeyMap,
        siteDeployDeps,
      );
      steps.push(sitesGroup);
      siteDeployKeys = sitesGroup.steps.map((s) => s.key);
    }

    // --- Homelab Tofu Plan (runs on PRs for early feedback) ---
    // Gated on tofu *source* changes (not any homelab change) so cdk8s-only PRs
    // don't run plans that yield no signal for them. `.dagger/` and `scripts/ci/`
    // changes trigger a full build, which runs the plan via `buildAll`.
    if (pullRequestBuild && (affected.buildAll || affected.tofuChanged)) {
      steps.push(homelabTofuPlanAllStep());
    }

    // --- Homelab Helm + Tofu release track ---
    if (releaseBuild && (affected.buildAll || affected.homelabChanged)) {
      // Helm charts — one pod fans out per-chart in Dagger via Promise.all.
      // Shared cdk8s synth is content-addressed, so all charts share one synth.
      steps.push(homelabHelmPushAllStep());

      // Homelab Tofu — non-github stacks apply in parallel from one pod.
      // github stays in its own non-retrying pod (see tofu.ts).
      steps.push(homelabTofuApplyAllStep(pkgKeyMap.get("homelab")));
      steps.push(homelabTofuApplyGithubStep(pkgKeyMap.get("homelab")));
    }

    // --- Unified ArgoCD sync (depends on whatever upstream steps ran) ---
    const needsArgoSync =
      releaseBuild &&
      (hasImages || affected.buildAll || affected.homelabChanged);
    if (needsArgoSync) {
      const argocdDeps: string[] = [];
      if (hasImages) {
        argocdDeps.push(...imagePushKeys);
      }
      if (affected.buildAll || affected.homelabChanged) {
        argocdDeps.push("helm-push-all", "tofu-apply-all", "tofu-apply-github");
      }
      // Sync + health-wait now run in one bundled BK pod (the Dagger
      // function catches health-wait failures internally — same soft-fail
      // semantics as the wave-1 standalone argocd-health step).
      steps.push(
        argoCdSyncAndWaitStep(argocdDeps, {
          key: "deploy-argocd",
          app: "apps",
        }),
      );
    }

    // --- Version Commit-Back ---
    // Skipped on bot-authored commits (Auto-Generated: trailer) so the bump
    // merge build can't open another bump PR — that's the loop we don't want.
    if (releaseBuild && hasImages && !affected.isAutoGenerated) {
      const vcbDeps: string[] = ["quality-gate", ...imagePushKeys];
      const pushedVersionKeys = imagesToBuild.map((t) => t.versionKey);
      steps.push(versionCommitBackStep(vcbDeps, pushedVersionKeys));
    }

    // --- Build Summary ---
    // Collect all terminal step keys so the summary runs last
    if (releaseBuild) {
      const summaryDeps: string[] = ["quality-gate"];
      if (hasImages) summaryDeps.push(...imagePushKeys);
      if (affected.ciImageChanged) {
        summaryDeps.push(
          affected.isAutoGenerated
            ? "push-ci-base"
            : "ci-base-version-commit-back",
        );
      }
      if (needsArgoSync) {
        // Build summary now waits on the bundled argo sync+health step
        // (`deploy-argocd`). The standalone `argocd-health` step no longer
        // exists; health-wait soft-fail semantics are preserved inside the
        // Dagger function.
        summaryDeps.push("deploy-argocd");
      }
      steps.push(buildSummaryStep(summaryDeps));
    }
  }

  // --- CI Complete: single terminal step for GitHub required status check ---
  // Include site deploy keys so a failed site build — including a PR dryrun —
  // fails the required check and blocks merge (deploy steps aren't in
  // releaseDeps; they depend on quality-gate, so there is no dependency cycle).
  const ciCompleteDeps = [
    ...releaseDeps,
    ...pkgKeyMap.values(),
    ...siteDeployKeys,
  ];
  steps.push({
    label: ":white_check_mark: CI Complete",
    key: "ci-complete",
    command: "echo 'CI complete'",
    depends_on: ciCompleteDeps,
    plugins: [k8sPlugin()],
  });

  return { agents: { queue: "default" }, steps };
}
