import { z } from "zod";
import { format } from "prettier";

const CatalogNamesSchema = z.object({
  entries: z.array(z.object({ name: z.string().min(1) })).min(1),
});

async function main(): Promise<void> {
  const catalogPath = new URL("../src/version-catalog.json", import.meta.url);
  const outputPath = new URL(
    "../src/version-map.generated.ts",
    import.meta.url,
  );
  const catalog = CatalogNamesSchema.parse(
    JSON.parse(await Bun.file(catalogPath).text()),
  );
  const names = catalog.entries.map((entry) => entry.name);
  if (new Set(names).size !== names.length) {
    throw new Error("version catalog names must be unique");
  }
  const properties = names
    .map((name) => `    ${JSON.stringify(name)}: z.string(),`)
    .join("\n");
  const source = [
    "// Generated by scripts/generate-version-map-schema.ts. Do not edit.",
    'import { z } from "zod";',
    "",
    "export const VersionMapSchema = z",
    "  .object({",
    properties,
    "  })",
    "  .catchall(z.string());",
    "",
    "export type VersionMap = z.infer<typeof VersionMapSchema>;",
    "",
  ].join("\n");
  await Bun.write(outputPath, await format(source, { parser: "typescript" }));
}

void (async (): Promise<void> => {
  try {
    await main();
  } catch (error: unknown) {
    console.error(error);
    process.exitCode = 1;
  }
})();
