# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
# Split view of the Sonarr instance. Runtime source of truth is recyclarr.yaml.
sonarr:
  sonarr:
    base_url: http://media-sonarr-service:8989
    api_key: !secret sonarr_api_key
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p
    custom_formats:
      - trash_ids:
          - ae575f95ab639ba5d15f663bf019e3e8 # Language: Not Original
        assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p
    media_naming:
      series: default
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default
