import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import {
  detectChanges,
  _checkInfraChanges,
  _extractPackageName,
  _transitiveClosure,
  _isRenovatePr,
  _isVersionCommitBack,
  _isCooklangVersionCommitBack,
  _isCooklangVersionCommitBackOnly,
  _hasCooklangSourceChange,
  _isAutoGeneratedCommit,
  _isReleasePleaseMerge,
  _shouldSkipReleasePleasePrBuild,
  _classifyRenovateFiles,
  _checkCiImageChanges,
  _checkCiImageVersionChanges,
  _getBaseRevision,
  _getChangedFiles,
  _getBuildRejectionReason,
  _getLastSuccessfulCommit,
  _NON_JS_PACKAGES,
  _JS_TS_PACKAGES,
} from "../change-detection.ts";
import { ALL_PACKAGES } from "../catalog.ts";

type ExecResult = { stdout: string; exitCode: number };
type ExecFn = (cmd: string[]) => Promise<ExecResult>;

function buildkiteBootstrapJobs(): Array<{
  type: string;
  state: string;
  name: string;
  command: string;
}> {
  return [
    {
      type: "script",
      state: "passed",
      name: ":pipeline: Upload pipeline",
      command: "buildkite-agent pipeline upload",
    },
    {
      type: "script",
      state: "passed",
      name: ":pipeline: Generate Pipeline",
      command: ".buildkite/scripts/generate-pipeline.sh",
    },
  ];
}

function restoreEnv(originalEnv: NodeJS.ProcessEnv, keys: string[]): void {
  for (const key of keys) {
    const value = originalEnv[key];
    if (value === undefined) {
      delete process.env[key];
    } else {
      process.env[key] = value;
    }
  }
}

describe("checkInfraChanges", () => {
  it("returns true for bun.lock changes", () => {
    expect(_checkInfraChanges(["bun.lock"])).toBe(true);
  });

  it("returns true for package.json changes", () => {
    expect(_checkInfraChanges(["package.json"])).toBe(true);
  });

  it("returns true for .buildkite/ changes", () => {
    expect(_checkInfraChanges([".buildkite/pipeline.yml"])).toBe(true);
  });

  it("returns true for .dagger/ changes", () => {
    expect(_checkInfraChanges([".dagger/src/index.ts"])).toBe(true);
  });

  it("returns true for scripts/ci/ changes", () => {
    expect(_checkInfraChanges(["scripts/ci/src/main.ts"])).toBe(true);
  });

  it("returns false for package-only changes", () => {
    expect(_checkInfraChanges(["packages/birmel/src/index.ts"])).toBe(false);
  });

  it("returns false for empty list", () => {
    expect(_checkInfraChanges([])).toBe(false);
  });
});

describe("extractPackageName", () => {
  it("extracts package name from packages/ path", () => {
    expect(_extractPackageName("packages/birmel/src/index.ts")).toBe("birmel");
  });

  it("extracts top-level package from nested paths", () => {
    expect(_extractPackageName("packages/homelab/src/cdk8s/main.ts")).toBe(
      "homelab",
    );
  });

  it("returns null for non-package paths", () => {
    expect(_extractPackageName("scripts/ci/src/main.ts")).toBeNull();
    expect(_extractPackageName(".buildkite/pipeline.yml")).toBeNull();
  });
});

describe("transitiveClosure", () => {
  it("includes directly changed packages", () => {
    const deps = new Map<string, Set<string>>();
    deps.set("a", new Set());
    deps.set("b", new Set());

    const result = _transitiveClosure(new Set(["a"]), deps);
    expect(result.has("a")).toBe(true);
    expect(result.has("b")).toBe(false);
  });

  it("includes packages that depend on changed packages", () => {
    const deps = new Map<string, Set<string>>();
    deps.set("a", new Set()); // a has no deps
    deps.set("b", new Set(["a"])); // b depends on a

    const result = _transitiveClosure(new Set(["a"]), deps);
    expect(result.has("a")).toBe(true);
    expect(result.has("b")).toBe(true);
  });

  it("follows transitive dependencies", () => {
    const deps = new Map<string, Set<string>>();
    deps.set("a", new Set()); // a has no deps
    deps.set("b", new Set(["a"])); // b depends on a
    deps.set("c", new Set(["b"])); // c depends on b

    const result = _transitiveClosure(new Set(["a"]), deps);
    expect(result.has("a")).toBe(true);
    expect(result.has("b")).toBe(true);
    expect(result.has("c")).toBe(true);
  });

  it("does not include unrelated packages", () => {
    const deps = new Map<string, Set<string>>();
    deps.set("a", new Set());
    deps.set("b", new Set(["a"]));
    deps.set("c", new Set());

    const result = _transitiveClosure(new Set(["a"]), deps);
    expect(result.has("c")).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Renovate fast-track
// ---------------------------------------------------------------------------

describe("isRenovatePr", () => {
  const originalEnv = { ...process.env };

  beforeEach(() => {
    delete process.env["BUILDKITE_BUILD_AUTHOR_EMAIL"];
    delete process.env["BUILDKITE_PULL_REQUEST"];
  });

  afterEach(() => {
    process.env["BUILDKITE_BUILD_AUTHOR_EMAIL"] =
      originalEnv["BUILDKITE_BUILD_AUTHOR_EMAIL"];
    process.env["BUILDKITE_PULL_REQUEST"] =
      originalEnv["BUILDKITE_PULL_REQUEST"];
  });

  it("returns true when email matches and PR is set", () => {
    process.env["BUILDKITE_BUILD_AUTHOR_EMAIL"] =
      "29139614+renovate[bot]@users.noreply.github.com";
    process.env["BUILDKITE_PULL_REQUEST"] = "42";
    expect(_isRenovatePr()).toBe(true);
  });

  it("returns false when email matches but PR is false", () => {
    process.env["BUILDKITE_BUILD_AUTHOR_EMAIL"] =
      "29139614+renovate[bot]@users.noreply.github.com";
    process.env["BUILDKITE_PULL_REQUEST"] = "false";
    expect(_isRenovatePr()).toBe(false);
  });

  it("returns false when PR is set but email is wrong", () => {
    process.env["BUILDKITE_BUILD_AUTHOR_EMAIL"] = "dev@example.com";
    process.env["BUILDKITE_PULL_REQUEST"] = "42";
    expect(_isRenovatePr()).toBe(false);
  });

  it("returns false when env vars are undefined", () => {
    expect(_isRenovatePr()).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Version commit-back fast-track
// ---------------------------------------------------------------------------

describe("isVersionCommitBack", () => {
  const originalEnv = { ...process.env };

  beforeEach(() => {
    delete process.env["BUILDKITE_MESSAGE"];
  });

  afterEach(() => {
    process.env["BUILDKITE_MESSAGE"] = originalEnv["BUILDKITE_MESSAGE"];
  });

  it("returns true for version bump commit message", () => {
    process.env["BUILDKITE_MESSAGE"] =
      "chore: bump image versions to 2.0.0-867";
    expect(_isVersionCommitBack()).toBe(true);
  });

  it("returns false for unrelated commit message", () => {
    process.env["BUILDKITE_MESSAGE"] = "feat: add new feature";
    expect(_isVersionCommitBack()).toBe(false);
  });

  it("returns false when env var is undefined", () => {
    expect(_isVersionCommitBack()).toBe(false);
  });

  it("returns false for partial match", () => {
    process.env["BUILDKITE_MESSAGE"] = "chore: bump image versions";
    expect(_isVersionCommitBack()).toBe(false);
  });

  it("returns false for similar but different message", () => {
    process.env["BUILDKITE_MESSAGE"] =
      "chore: bump chart versions to 2.0.0-867";
    expect(_isVersionCommitBack()).toBe(false);
  });

  it("matches real commit message format from versionCommitBackHelper", () => {
    // This is the exact format produced by .dagger/src/release.ts
    process.env["BUILDKITE_MESSAGE"] =
      "chore: bump image versions to 2.0.0-1234";
    expect(_isVersionCommitBack()).toBe(true);
  });
});

describe("isCooklangVersionCommitBack", () => {
  const originalEnv = { ...process.env };

  beforeEach(() => {
    delete process.env["BUILDKITE_MESSAGE"];
  });

  afterEach(() => {
    process.env["BUILDKITE_MESSAGE"] = originalEnv["BUILDKITE_MESSAGE"];
  });

  it("returns true for cooklang version bump commit message", () => {
    process.env["BUILDKITE_MESSAGE"] =
      "chore(cooklang): bump to v1.0.11\n\nAuto-Generated: ci-bot";
    expect(_isCooklangVersionCommitBack()).toBe(true);
  });

  it("returns true for cooklang version bump merge commit", () => {
    process.env["BUILDKITE_MESSAGE"] =
      "Merge pull request #936 from shepherdjerred/chore/cooklang-version-bump-pending";
    expect(_isCooklangVersionCommitBack()).toBe(true);
  });

  it("returns false for image version bump commit message", () => {
    process.env["BUILDKITE_MESSAGE"] =
      "chore: bump image versions to 2.0.0-1234";
    expect(_isCooklangVersionCommitBack()).toBe(false);
  });

  it("returns false when env var is undefined", () => {
    expect(_isCooklangVersionCommitBack()).toBe(false);
  });
});

describe("isCooklangVersionCommitBackOnly", () => {
  it("returns true for cooklang manifest only", () => {
    expect(
      _isCooklangVersionCommitBackOnly([
        "packages/cooklang-for-obsidian/manifest.json",
      ]),
    ).toBe(true);
  });

  it("returns true for cooklang manifest plus compatibility map", () => {
    expect(
      _isCooklangVersionCommitBackOnly([
        "packages/cooklang-for-obsidian/manifest.json",
        "packages/cooklang-for-obsidian/versions.json",
      ]),
    ).toBe(true);
  });

  it("returns false for cooklang source changes", () => {
    expect(
      _isCooklangVersionCommitBackOnly([
        "packages/cooklang-for-obsidian/manifest.json",
        "packages/cooklang-for-obsidian/src/main.ts",
      ]),
    ).toBe(false);
  });

  it("returns false for empty file list", () => {
    expect(_isCooklangVersionCommitBackOnly([])).toBe(false);
  });
});

describe("hasCooklangSourceChange", () => {
  it("returns true for a cooklang source file", () => {
    expect(
      _hasCooklangSourceChange(["packages/cooklang-for-obsidian/src/main.ts"]),
    ).toBe(true);
  });

  it("returns true for a cooklang package.json (dependency bump)", () => {
    expect(
      _hasCooklangSourceChange([
        "packages/cooklang-for-obsidian/package.json",
        "bun.lock",
      ]),
    ).toBe(true);
  });

  it("returns true for cooklang-rich-preview source", () => {
    expect(
      _hasCooklangSourceChange([
        "packages/cooklang-rich-preview/src/pages/index.astro",
      ]),
    ).toBe(true);
  });

  it("returns false when only the auto-bump manifest changed", () => {
    expect(
      _hasCooklangSourceChange([
        "packages/cooklang-for-obsidian/manifest.json",
      ]),
    ).toBe(false);
  });

  it("returns false for auto-bump manifest plus versions map", () => {
    expect(
      _hasCooklangSourceChange([
        "packages/cooklang-for-obsidian/manifest.json",
        "packages/cooklang-for-obsidian/versions.json",
      ]),
    ).toBe(false);
  });

  it("returns false for unrelated infra/full-build files", () => {
    expect(
      _hasCooklangSourceChange([
        ".dagger/src/release.ts",
        "scripts/ci/src/main.ts",
        "bun.lock",
      ]),
    ).toBe(false);
  });

  it("returns true when a real source change accompanies a manifest bump", () => {
    expect(
      _hasCooklangSourceChange([
        "packages/cooklang-for-obsidian/manifest.json",
        "packages/cooklang-for-obsidian/src/main.ts",
      ]),
    ).toBe(true);
  });

  it("returns false for empty file list", () => {
    expect(_hasCooklangSourceChange([])).toBe(false);
  });
});

describe("isAutoGeneratedCommit", () => {
  it("returns true when message body has Auto-Generated trailer", () => {
    const msg =
      "chore: bump image versions to 2.0.0-9999\n\nAuto-Generated: ci-bot";
    expect(_isAutoGeneratedCommit(msg)).toBe(true);
  });

  it("returns true for trailer-only message", () => {
    expect(_isAutoGeneratedCommit("Auto-Generated: ci-bot")).toBe(true);
  });

  it("returns true for ci-base generated merge commit", () => {
    const msg =
      "Merge pull request #808 from shepherdjerred/chore/ci-base-version-bump-pending\n\nchore: bump ci-base image to 407";
    expect(_isAutoGeneratedCommit(msg)).toBe(true);
  });

  it("returns false for ordinary feature commit", () => {
    expect(_isAutoGeneratedCommit("feat: add new feature")).toBe(false);
  });

  it("returns false for ci-base version bump subject without generated marker", () => {
    expect(_isAutoGeneratedCommit("chore: bump ci-base image to 407")).toBe(
      false,
    );
  });

  it("does not match a trailer mentioned mid-line", () => {
    const msg = "chore: discussing Auto-Generated: in the body";
    expect(_isAutoGeneratedCommit(msg)).toBe(false);
  });
});

describe("isReleasePleaseMerge", () => {
  const originalEnv = { ...process.env };

  beforeEach(() => {
    delete process.env["BUILDKITE_MESSAGE"];
  });

  afterEach(() => {
    process.env["BUILDKITE_MESSAGE"] = originalEnv["BUILDKITE_MESSAGE"];
  });

  it("returns true for release-please commit message", () => {
    process.env["BUILDKITE_MESSAGE"] = "chore: release main";
    expect(_isReleasePleaseMerge()).toBe(true);
  });

  it("returns false for unrelated commit message", () => {
    process.env["BUILDKITE_MESSAGE"] = "feat: add new feature";
    expect(_isReleasePleaseMerge()).toBe(false);
  });

  it("returns false when env var is undefined", () => {
    expect(_isReleasePleaseMerge()).toBe(false);
  });

  it("returns false for version bump commit message", () => {
    process.env["BUILDKITE_MESSAGE"] =
      "chore: bump image versions to 2.0.0-867";
    expect(_isReleasePleaseMerge()).toBe(false);
  });
});

describe("shouldSkipReleasePleasePrBuild", () => {
  const KEYS = ["BUILDKITE_BRANCH", "BUILDKITE_SOURCE", "RUN_RELEASE_CI"];
  const originalEnv = { ...process.env };

  beforeEach(() => {
    for (const key of KEYS) delete process.env[key];
  });

  afterEach(() => {
    restoreEnv(originalEnv, KEYS);
  });

  it("skips a webhook build of the release-please PR branch", () => {
    process.env["BUILDKITE_BRANCH"] = "release-please--branches--main";
    process.env["BUILDKITE_SOURCE"] = "webhook";
    expect(_shouldSkipReleasePleasePrBuild()).toBe(true);
  });

  it("skips when source is unset (defensive default)", () => {
    process.env["BUILDKITE_BRANCH"] = "release-please--branches--main";
    expect(_shouldSkipReleasePleasePrBuild()).toBe(true);
  });

  it("does not skip a manually-triggered (ui) build", () => {
    process.env["BUILDKITE_BRANCH"] = "release-please--branches--main";
    process.env["BUILDKITE_SOURCE"] = "ui";
    expect(_shouldSkipReleasePleasePrBuild()).toBe(false);
  });

  it("does not skip an api-triggered build", () => {
    process.env["BUILDKITE_BRANCH"] = "release-please--branches--main";
    process.env["BUILDKITE_SOURCE"] = "api";
    expect(_shouldSkipReleasePleasePrBuild()).toBe(false);
  });

  it("does not skip when RUN_RELEASE_CI=true overrides a webhook build", () => {
    process.env["BUILDKITE_BRANCH"] = "release-please--branches--main";
    process.env["BUILDKITE_SOURCE"] = "webhook";
    process.env["RUN_RELEASE_CI"] = "true";
    expect(_shouldSkipReleasePleasePrBuild()).toBe(false);
  });

  it("treats RUN_RELEASE_CI case-insensitively", () => {
    process.env["BUILDKITE_BRANCH"] = "release-please--branches--main";
    process.env["BUILDKITE_SOURCE"] = "webhook";
    process.env["RUN_RELEASE_CI"] = "TRUE";
    expect(_shouldSkipReleasePleasePrBuild()).toBe(false);
  });

  it("does not skip a webhook build on another branch", () => {
    process.env["BUILDKITE_BRANCH"] = "feature/whatever";
    process.env["BUILDKITE_SOURCE"] = "webhook";
    expect(_shouldSkipReleasePleasePrBuild()).toBe(false);
  });

  it("does not skip the main-branch release merge build", () => {
    process.env["BUILDKITE_BRANCH"] = "main";
    process.env["BUILDKITE_SOURCE"] = "webhook";
    expect(_shouldSkipReleasePleasePrBuild()).toBe(false);
  });
});

describe("version commit-back + classifyRenovateFiles interaction", () => {
  it("versions.ts-only change classifies as noop (used by commit-back fast-track)", () => {
    // This is the exact file changed by version-commit-back
    const result = _classifyRenovateFiles([
      "packages/homelab/src/cdk8s/src/versions.ts",
    ]);
    expect(result).toEqual({ kind: "noop" });
  });

  it("versions.ts + bun.lock classifies as noop", () => {
    const result = _classifyRenovateFiles([
      "packages/homelab/src/cdk8s/src/versions.ts",
      "bun.lock",
    ]);
    expect(result).toEqual({ kind: "noop" });
  });

  it("versions.ts + unexpected source file classifies as null (falls through)", () => {
    const result = _classifyRenovateFiles([
      "packages/homelab/src/cdk8s/src/versions.ts",
      "packages/homelab/src/cdk8s/src/main.ts",
    ]);
    expect(result).toBeNull();
  });
});

describe("classifyRenovateFiles", () => {
  // noop cases
  it("returns noop for versions.ts only", () => {
    expect(
      _classifyRenovateFiles(["packages/homelab/src/cdk8s/src/versions.ts"]),
    ).toEqual({ kind: "noop" });
  });

  it("returns noop for lib-versions.ts", () => {
    expect(
      _classifyRenovateFiles(["packages/homelab/src/lib-versions.ts"]),
    ).toEqual({ kind: "noop" });
  });

  it("returns noop for .buildkite/scripts/setup-tools.sh", () => {
    expect(
      _classifyRenovateFiles([".buildkite/scripts/setup-tools.sh"]),
    ).toEqual({ kind: "noop" });
  });

  it("falls through for .buildkite/ci-image/ files", () => {
    expect(
      _classifyRenovateFiles([".buildkite/ci-image/Dockerfile"]),
    ).toBeNull();
  });

  it("returns noop for root bun.lock alone", () => {
    expect(_classifyRenovateFiles(["bun.lock"])).toEqual({ kind: "noop" });
  });

  it("returns noop for empty file list", () => {
    expect(_classifyRenovateFiles([])).toEqual({ kind: "noop" });
  });

  // scoped cases
  it("returns scoped for single package.json + bun.lock", () => {
    const result = _classifyRenovateFiles([
      "packages/birmel/package.json",
      "packages/birmel/bun.lock",
    ]);
    expect(result).toEqual({
      kind: "scoped",
      packages: new Set(["birmel"]),
    });
  });

  it("returns scoped for package-lock.json", () => {
    const result = _classifyRenovateFiles([
      "packages/birmel/package-lock.json",
    ]);
    expect(result).toEqual({
      kind: "scoped",
      packages: new Set(["birmel"]),
    });
  });

  it("returns scoped for Dockerfile", () => {
    const result = _classifyRenovateFiles([
      "packages/starlight-karma-bot/Dockerfile",
    ]);
    expect(result).toEqual({
      kind: "scoped",
      packages: new Set(["starlight-karma-bot"]),
    });
  });

  it("returns scoped for multiple packages", () => {
    const result = _classifyRenovateFiles([
      "packages/birmel/package.json",
      "packages/scout-for-lol/package.json",
      "bun.lock",
    ]);
    expect(result).toEqual({
      kind: "scoped",
      packages: new Set(["birmel", "scout-for-lol"]),
    });
  });

  // root package.json — noop (only contains markdownlint-cli2, no workspace-consumed deps)
  it("returns noop for root package.json", () => {
    expect(_classifyRenovateFiles(["package.json", "bun.lock"])).toEqual({
      kind: "noop",
    });
  });

  // .dagger manifest/lockfile — noop (Dagger runtime tool versions, not workspace code)
  it("returns noop for .dagger/package.json", () => {
    expect(_classifyRenovateFiles([".dagger/package.json"])).toEqual({
      kind: "noop",
    });
  });

  it("returns noop for .dagger/bun.lock", () => {
    expect(_classifyRenovateFiles([".dagger/bun.lock"])).toEqual({
      kind: "noop",
    });
  });

  it("returns noop for .dagger/package-lock.json", () => {
    expect(_classifyRenovateFiles([".dagger/package-lock.json"])).toEqual({
      kind: "noop",
    });
  });

  // null (fallthrough) cases

  it("returns null for unknown file", () => {
    expect(_classifyRenovateFiles(["some/random/file.ts"])).toBeNull();
  });

  it("returns null for unknown file under packages/", () => {
    expect(_classifyRenovateFiles(["packages/birmel/src/index.ts"])).toBeNull();
  });

  // priority tests
  it("scoped wins over noop when mixed", () => {
    const result = _classifyRenovateFiles([
      "packages/homelab/src/cdk8s/src/versions.ts",
      "packages/birmel/package.json",
    ]);
    expect(result).toEqual({
      kind: "scoped",
      packages: new Set(["birmel"]),
    });
  });

  it("scoped wins over noop when root package.json is present", () => {
    // root package.json is noop, so scoped (packages/birmel/package.json) wins
    const result = _classifyRenovateFiles([
      "packages/birmel/package.json",
      "package.json",
      "bun.lock",
    ]);
    expect(result).toEqual({
      kind: "scoped",
      packages: new Set(["birmel"]),
    });
  });

  it("null wins over noop when an unrecognized file is present", () => {
    expect(
      _classifyRenovateFiles([
        "packages/homelab/src/cdk8s/src/versions.ts",
        "some/unrecognized/file.ts",
      ]),
    ).toBeNull();
  });
});

describe("ci image change detection", () => {
  it("treats Dockerfile changes as ci image source changes", () => {
    expect(_checkCiImageChanges([".buildkite/ci-image/Dockerfile"])).toBe(true);
    expect(
      _checkCiImageVersionChanges([".buildkite/ci-image/Dockerfile"]),
    ).toBe(false);
  });

  it("tracks VERSION separately from ci image source changes", () => {
    expect(_checkCiImageChanges([".buildkite/ci-image/VERSION"])).toBe(false);
    expect(_checkCiImageVersionChanges([".buildkite/ci-image/VERSION"])).toBe(
      true,
    );
  });
});

describe("fail-fast base detection", () => {
  const originalEnv = { ...process.env };
  const envKeys = [
    "BUILDKITE_API_TOKEN",
    "BUILDKITE_AGENT_ACCESS_TOKEN",
    "BUILDKITE_ORGANIZATION_SLUG",
    "BUILDKITE_PIPELINE_SLUG",
    "BUILDKITE_BUILD_NUMBER",
    "BUILDKITE_BRANCH",
    "BUILDKITE_PULL_REQUEST",
    "BUILDKITE_MESSAGE",
    "FULL_BUILD",
  ];

  beforeEach(() => {
    for (const key of envKeys) {
      delete process.env[key];
    }
    process.env["BUILDKITE_ORGANIZATION_SLUG"] = "sjerred";
    process.env["BUILDKITE_PIPELINE_SLUG"] = "monorepo";
    process.env["BUILDKITE_BUILD_NUMBER"] = "100";
  });

  afterEach(() => {
    restoreEnv(originalEnv, envKeys);
  });

  it("requires BUILDKITE_API_TOKEN for main-branch Buildkite API detection", async () => {
    await expect(_getLastSuccessfulCommit()).rejects.toThrow(
      "BUILDKITE_API_TOKEN is required",
    );
  });

  it("does not use BUILDKITE_AGENT_ACCESS_TOKEN as a REST API fallback", async () => {
    process.env["BUILDKITE_AGENT_ACCESS_TOKEN"] = "agent-token";
    const fetchFn = async () => {
      throw new Error("fetch should not be called");
    };

    await expect(_getLastSuccessfulCommit(fetchFn)).rejects.toThrow(
      "BUILDKITE_API_TOKEN is required",
    );
  });

  it("rejects unauthorized Buildkite API responses with scope guidance", async () => {
    process.env["BUILDKITE_API_TOKEN"] = "api-token";
    const fetchFn = async () => new Response("", { status: 401 });

    await expect(_getLastSuccessfulCommit(fetchFn)).rejects.toThrow(
      "read_builds scope",
    );
  });

  it("rejects non-OK Buildkite API responses", async () => {
    process.env["BUILDKITE_API_TOKEN"] = "api-token";
    const fetchFn = async () => new Response("", { status: 500 });

    await expect(_getLastSuccessfulCommit(fetchFn)).rejects.toThrow("HTTP 500");
  });

  it("rejects Buildkite API request failures", async () => {
    process.env["BUILDKITE_API_TOKEN"] = "api-token";
    const fetchFn = async () => {
      throw new Error("timeout");
    };

    await expect(_getLastSuccessfulCommit(fetchFn)).rejects.toThrow(
      "Buildkite API request failed: timeout",
    );
  });

  it("rejects when no qualifying successful main build exists", async () => {
    process.env["BUILDKITE_API_TOKEN"] = "api-token";
    const fetchFn = async () =>
      new Response(
        JSON.stringify([
          {
            number: 99,
            commit: "abc123",
            state: "failed",
            jobs: [
              ...buildkiteBootstrapJobs(),
              {
                type: "script",
                state: "failed",
                step_key: "lint-birmel",
                name: ":eslint: Lint",
              },
            ],
          },
        ]),
        { status: 200 },
      );

    await expect(_getLastSuccessfulCommit(fetchFn)).rejects.toThrow(
      "No qualifying successful main build found",
    );
  });

  it("returns the first qualifying successful build even with zero test jobs", async () => {
    process.env["BUILDKITE_API_TOKEN"] = "api-token";
    const fetchFn = async () =>
      new Response(
        JSON.stringify([
          {
            number: 100,
            commit: "current",
            state: "passed",
            jobs: buildkiteBootstrapJobs(),
          },
          {
            number: 99,
            commit: "abc123def456",
            state: "passed",
            jobs: [
              ...buildkiteBootstrapJobs(),
              {
                type: "script",
                state: "passed",
                step_key: "lockfile-check",
                name: ":lock: Lockfile Check",
              },
              {
                type: "script",
                state: "passed",
                step_key: "ci-complete",
                name: ":white_check_mark: CI Complete",
              },
            ],
          },
        ]),
        { status: 200 },
      );

    await expect(_getLastSuccessfulCommit(fetchFn)).resolves.toBe(
      "abc123def456",
    );
  });

  it("recognizes pipeline bootstrap jobs by stable command when labels change", () => {
    expect(
      _getBuildRejectionReason({
        number: 99,
        state: "passed",
        jobs: [
          {
            type: "script",
            state: "passed",
            name: ":pipeline: Upload Pipeline",
            command: "buildkite-agent pipeline upload",
          },
          {
            type: "script",
            state: "passed",
            name: ":pipeline: Generate pipeline",
            command: ".buildkite/scripts/generate-pipeline.sh",
          },
        ],
      }),
    ).toBeNull();
  });

  it("skips canceled, skipped, running, scheduled, and blocked builds", async () => {
    process.env["BUILDKITE_API_TOKEN"] = "api-token";
    const fetchFn = async () =>
      new Response(
        JSON.stringify([
          {
            number: 99,
            commit: "canceled",
            state: "canceled",
            jobs: buildkiteBootstrapJobs(),
          },
          {
            number: 98,
            commit: "skipped",
            state: "skipped",
            jobs: buildkiteBootstrapJobs(),
          },
          {
            number: 97,
            commit: "running",
            state: "running",
            jobs: buildkiteBootstrapJobs(),
          },
          {
            number: 96,
            commit: "scheduled",
            state: "scheduled",
            jobs: buildkiteBootstrapJobs(),
          },
          {
            number: 95,
            commit: "blocked",
            state: "blocked",
            jobs: buildkiteBootstrapJobs(),
          },
          {
            number: 94,
            commit: "good-base",
            state: "passed",
            jobs: buildkiteBootstrapJobs(),
          },
        ]),
        { status: 200 },
      );

    await expect(_getLastSuccessfulCommit(fetchFn)).resolves.toBe("good-base");
  });

  it("rejects hard-failed non-exempt jobs", () => {
    expect(
      _getBuildRejectionReason({
        number: 99,
        state: "failed",
        jobs: [
          ...buildkiteBootstrapJobs(),
          {
            type: "script",
            state: "failed",
            step_key: "deploy-argocd",
            name: ":argocd: Sync ArgoCD",
          },
        ],
      }),
    ).toBe("hard-failed-jobs");
  });

  it("accepts failed soft-fail jobs", () => {
    expect(
      _getBuildRejectionReason({
        number: 99,
        state: "passed",
        jobs: [
          ...buildkiteBootstrapJobs(),
          {
            type: "script",
            state: "failed",
            step_key: "knip-check",
            name: ":scissors: Knip",
            soft_failed: true,
          },
        ],
      }),
    ).toBeNull();
  });

  it("accepts timed-out soft-fail jobs", () => {
    expect(
      _getBuildRejectionReason({
        number: 99,
        state: "failed",
        jobs: [
          ...buildkiteBootstrapJobs(),
          {
            type: "script",
            state: "timed_out",
            step_key: "knip-check",
            name: ":scissors: Knip",
            soft_failed: true,
          },
        ],
      }),
    ).toBeNull();
  });

  it("accepts failed argocd-health jobs", () => {
    expect(
      _getBuildRejectionReason({
        number: 99,
        state: "failed",
        jobs: [
          ...buildkiteBootstrapJobs(),
          {
            type: "script",
            state: "failed",
            step_key: "argocd-health",
            name: ":heart: Wait for ArgoCD Healthy (apps)",
          },
        ],
      }),
    ).toBeNull();
  });

  it("accepts timed-out argocd-health jobs", () => {
    expect(
      _getBuildRejectionReason({
        number: 99,
        state: "failed",
        jobs: [
          ...buildkiteBootstrapJobs(),
          {
            type: "script",
            state: "timed_out",
            step_key: "argocd-health",
            name: ":heart: Wait for ArgoCD Healthy (apps)",
          },
        ],
      }),
    ).toBeNull();
  });

  it("rejects when merge-base cannot be computed", async () => {
    process.env["BUILDKITE_BRANCH"] = "feature";
    process.env["BUILDKITE_PULL_REQUEST"] = "42";
    const execFn: ExecFn = async (cmd) => {
      if (cmd[1] === "rev-parse") {
        return { stdout: "deadbeef", exitCode: 0 };
      }
      if (cmd[1] === "fetch") {
        return { stdout: "", exitCode: 0 };
      }
      return { stdout: "", exitCode: 1 };
    };

    await expect(_getBaseRevision(execFn)).rejects.toThrow(
      "Unable to compute merge-base with origin/main after deepening shallow history",
    );
  });

  it("deepens origin/main history when the shallow checkout lacks a merge-base", async () => {
    process.env["BUILDKITE_BRANCH"] = "feature";
    process.env["BUILDKITE_PULL_REQUEST"] = "42";
    const calls: string[][] = [];
    let mergeBaseCalls = 0;
    const execFn: ExecFn = async (cmd) => {
      calls.push(cmd);
      if (cmd[1] === "rev-parse") {
        return { stdout: "deadbeef", exitCode: 0 };
      }
      if (cmd[1] === "fetch") {
        return { stdout: "", exitCode: 0 };
      }
      if (cmd[1] === "merge-base") {
        mergeBaseCalls += 1;
        if (mergeBaseCalls === 1) {
          return { stdout: "", exitCode: 1 };
        }
        return { stdout: "abc123", exitCode: 0 };
      }
      return { stdout: "", exitCode: 1 };
    };

    const base = await _getBaseRevision(execFn);
    expect(base).toBe("abc123");
    expect(calls.some((c) => c.includes("--deepen=1000"))).toBe(true);
  });

  it("fetches origin/main when missing before merge-base", async () => {
    process.env["BUILDKITE_BRANCH"] = "feature";
    process.env["BUILDKITE_PULL_REQUEST"] = "42";
    const calls: string[][] = [];
    const execFn: ExecFn = async (cmd) => {
      calls.push(cmd);
      if (cmd[1] === "rev-parse") {
        return { stdout: "", exitCode: 1 };
      }
      if (cmd[1] === "fetch") {
        return { stdout: "", exitCode: 0 };
      }
      if (cmd[1] === "merge-base") {
        return { stdout: "abc123", exitCode: 0 };
      }
      return { stdout: "", exitCode: 1 };
    };

    const base = await _getBaseRevision(execFn);
    expect(base).toBe("abc123");
    const fetchCmd = calls.find((c) => c[1] === "fetch");
    expect(fetchCmd).toBeDefined();
    expect(fetchCmd).toContain("--depth=100");
    expect(fetchCmd).toContain("+refs/heads/main:refs/remotes/origin/main");
  });

  it("rejects when origin/main fetch fails", async () => {
    process.env["BUILDKITE_BRANCH"] = "feature";
    process.env["BUILDKITE_PULL_REQUEST"] = "42";
    const execFn: ExecFn = async (cmd) => {
      if (cmd[1] === "rev-parse") {
        return { stdout: "", exitCode: 1 };
      }
      if (cmd[1] === "fetch") {
        return { stdout: "", exitCode: 128 };
      }
      return { stdout: "", exitCode: 1 };
    };

    await expect(_getBaseRevision(execFn)).rejects.toThrow(
      "Unable to fetch origin/main",
    );
  });

  it("rejects when git diff fails after resolving a base", async () => {
    process.env["BUILDKITE_BRANCH"] = "feature";
    process.env["BUILDKITE_PULL_REQUEST"] = "false";
    const execFn: ExecFn = async (cmd) => {
      if (cmd[1] === "rev-parse") {
        return { stdout: "deadbeef", exitCode: 0 };
      }
      if (cmd[1] === "merge-base") {
        return { stdout: "abc123", exitCode: 0 };
      }
      return { stdout: "", exitCode: 1 };
    };

    await expect(_getChangedFiles(execFn)).rejects.toThrow(
      "Unable to diff base revision abc123 against HEAD",
    );
  });

  it("returns a full build when explicitly requested without checking Buildkite API", async () => {
    process.env["BUILDKITE_BRANCH"] = "main";
    process.env["FULL_BUILD"] = "true";

    const result = await detectChanges();

    expect(result.buildAll).toBe(true);
    expect(result.packages.size).toBe(ALL_PACKAGES.length);
  });
});

describe("NON_JS_PACKAGES and JS_TS_PACKAGES", () => {
  it("NON_JS_PACKAGES contains exactly the non-JS packages", () => {
    expect(_NON_JS_PACKAGES).toEqual(
      new Set(["terraform-provider-asuswrt", "resume"]),
    );
  });

  it("JS_TS_PACKAGES excludes non-JS packages", () => {
    for (const pkg of _NON_JS_PACKAGES) {
      expect(_JS_TS_PACKAGES).not.toContain(pkg);
    }
  });

  it("JS_TS_PACKAGES + NON_JS_PACKAGES = ALL_PACKAGES", () => {
    const combined = [..._JS_TS_PACKAGES, ..._NON_JS_PACKAGES].sort();
    expect(combined).toEqual([...ALL_PACKAGES].sort());
  });
});
