/**
 * Shared fixtures and helpers for the pipeline-builder test suites. Extracted
 * so pipeline-builder.test.ts stays under the standard max-lines cap.
 */
import { buildPipeline } from "../pipeline-builder.ts";
import type {
  AffectedPackages,
  BuildkiteGroup,
  BuildkiteStep,
  PipelineStep,
} from "../lib/types.ts";
import {
  ALL_PACKAGES,
  PACKAGES_WITH_IMAGES,
  PACKAGES_WITH_NPM,
  PACKAGE_TO_SITE,
} from "../catalog.ts";

export function emptyAffected(): AffectedPackages {
  return {
    packages: new Set(),
    directlyChanged: new Set(),
    buildAll: false,
    homelabChanged: false,
    tofuChanged: false,
    cooklangChanged: false,
    resumeChanged: false,
    helmTypesInputsChanged: false,
    ciImageChanged: false,
    hasImagePackages: new Set(),
    hasSitePackages: new Set(),
    hasNpmPackages: new Set(),
    ciImageVersionChanged: false,
    versionBumpOnly: false,
    releasePleaseMerge: false,
    isAutoGenerated: false,
  };
}

export function fullBuild(): AffectedPackages {
  return {
    packages: new Set(ALL_PACKAGES),
    directlyChanged: new Set(),
    buildAll: true,
    homelabChanged: true,
    tofuChanged: true,
    cooklangChanged: true,
    resumeChanged: true,
    helmTypesInputsChanged: true,
    ciImageChanged: false,
    hasImagePackages: new Set(PACKAGES_WITH_IMAGES),
    hasSitePackages: new Set(Object.keys(PACKAGE_TO_SITE)),
    hasNpmPackages: new Set(PACKAGES_WITH_NPM),
    ciImageVersionChanged: false,
    versionBumpOnly: false,
    releasePleaseMerge: false,
    isAutoGenerated: false,
  };
}

/**
 * Narrowing extractors for the `PipelineStep` discriminated union. Using
 * `flatMap` with an `in`-narrowed ternary yields the concrete element type
 * (BuildkiteStep / BuildkiteGroup / wait) without a `value is T` predicate or a
 * type assertion.
 */
export function commandSteps(steps: readonly PipelineStep[]): BuildkiteStep[] {
  return steps.flatMap((s) => ("label" in s ? [s] : []));
}

export function groupSteps(steps: readonly PipelineStep[]): BuildkiteGroup[] {
  return steps.flatMap((s) => ("group" in s ? [s] : []));
}

export function waitSteps(steps: readonly PipelineStep[]): { wait: string }[] {
  return steps.flatMap((s) => ("wait" in s ? [s] : []));
}

export function collectSteps(
  steps: readonly PipelineStep[],
  allSteps: BuildkiteStep[],
): void {
  for (const s of steps) {
    if ("group" in s) {
      collectSteps(s.steps, allSteps);
    } else if ("label" in s) {
      allSteps.push(s);
    }
  }
}

export function collectKeys(
  steps: readonly PipelineStep[],
  keys: string[],
): void {
  for (const step of steps) {
    if ("group" in step) {
      keys.push(step.key);
      collectKeys(step.steps, keys);
    } else if ("label" in step) {
      keys.push(step.key);
    }
  }
}

export function collectKeysAndDeps(
  steps: readonly PipelineStep[],
  allKeys: Set<string>,
  allDeps: string[],
): void {
  for (const step of steps) {
    if ("group" in step) {
      allKeys.add(step.key);
      collectKeysAndDeps(step.steps, allKeys, allDeps);
      continue;
    }
    if ("wait" in step) continue;
    allKeys.add(step.key);
    const dependsOn = step.depends_on;
    if (typeof dependsOn === "string") {
      allDeps.push(dependsOn);
    } else if (Array.isArray(dependsOn)) {
      for (const dep of dependsOn) {
        if (typeof dep === "string") {
          allDeps.push(dep);
        }
      }
    }
  }
}

export function withBuildkitePullRequest<T>(value: string, fn: () => T): T {
  const original = Bun.env["BUILDKITE_PULL_REQUEST"];
  Bun.env["BUILDKITE_PULL_REQUEST"] = value;

  try {
    return fn();
  } finally {
    if (original === undefined) {
      delete Bun.env["BUILDKITE_PULL_REQUEST"];
    } else {
      Bun.env["BUILDKITE_PULL_REQUEST"] = original;
    }
  }
}

export function withDryRun<T>(fn: () => T): T {
  const original = Bun.env["DRYRUN"];
  Bun.env["DRYRUN"] = "true";

  try {
    return fn();
  } finally {
    if (original === undefined) {
      delete Bun.env["DRYRUN"];
    } else {
      Bun.env["DRYRUN"] = original;
    }
  }
}

export function withBuildkiteBranchContext<T>(
  branch: string,
  defaultBranch: string,
  fn: () => T,
): T {
  const originalBranch = Bun.env["BUILDKITE_BRANCH"];
  const originalDefaultBranch = Bun.env["BUILDKITE_PIPELINE_DEFAULT_BRANCH"];

  Bun.env["BUILDKITE_BRANCH"] = branch;
  Bun.env["BUILDKITE_PIPELINE_DEFAULT_BRANCH"] = defaultBranch;

  try {
    return fn();
  } finally {
    if (originalBranch === undefined) {
      delete Bun.env["BUILDKITE_BRANCH"];
    } else {
      Bun.env["BUILDKITE_BRANCH"] = originalBranch;
    }

    if (originalDefaultBranch === undefined) {
      delete Bun.env["BUILDKITE_PIPELINE_DEFAULT_BRANCH"];
    } else {
      Bun.env["BUILDKITE_PIPELINE_DEFAULT_BRANCH"] = originalDefaultBranch;
    }
  }
}

export function homelabStepKeys(affected: AffectedPackages): string[] {
  const pipeline = buildPipeline(affected);
  const homelab = groupSteps(pipeline.steps).find(
    (g) => g.key === "pkg-homelab",
  );
  return commandSteps(homelab?.steps ?? []).map((s) => s.key);
}

export function driftStep(
  affected: AffectedPackages,
): BuildkiteStep | undefined {
  return commandSteps(buildPipeline(affected).steps).find(
    (s) => s.key === "bun-lock-drift-check",
  );
}

export function versionBumpAffected(): AffectedPackages {
  const affected = emptyAffected();
  affected.packages.add("homelab");
  affected.homelabChanged = true;
  affected.versionBumpOnly = true;
  return affected;
}

export function releasePleaseAffected(): AffectedPackages {
  const affected = fullBuild();
  affected.releasePleaseMerge = true;
  return affected;
}
