import { describe, expect, it } from "bun:test";
import {
  buildPipeline,
  buildReleasePleaseSkipPipeline,
} from "../pipeline-builder.ts";
import type { AffectedPackages } from "../lib/types.ts";
import type { BuildkiteGroup, BuildkiteStep } from "../lib/types.ts";
import {
  ALL_PACKAGES,
  PACKAGES_WITH_IMAGES,
  PACKAGES_WITH_NPM,
  PACKAGE_TO_SITE,
  SKIP_PACKAGES,
} from "../catalog.ts";

function emptyAffected(): AffectedPackages {
  return {
    packages: new Set(),
    directlyChanged: new Set(),
    buildAll: false,
    homelabChanged: false,
    tofuChanged: false,
    cooklangChanged: false,
    resumeChanged: false,
    helmTypesInputsChanged: false,
    ciImageChanged: false,
    hasImagePackages: new Set(),
    hasSitePackages: new Set(),
    hasNpmPackages: new Set(),
    ciImageVersionChanged: false,
    versionBumpOnly: false,
    releasePleaseMerge: false,
    isAutoGenerated: false,
  };
}

function fullBuild(): AffectedPackages {
  return {
    packages: new Set(ALL_PACKAGES),
    directlyChanged: new Set(),
    buildAll: true,
    homelabChanged: true,
    tofuChanged: true,
    cooklangChanged: true,
    resumeChanged: true,
    helmTypesInputsChanged: true,
    ciImageChanged: false,
    hasImagePackages: new Set(PACKAGES_WITH_IMAGES),
    hasSitePackages: new Set(Object.keys(PACKAGE_TO_SITE)),
    hasNpmPackages: new Set(PACKAGES_WITH_NPM),
    ciImageVersionChanged: false,
    versionBumpOnly: false,
    releasePleaseMerge: false,
    isAutoGenerated: false,
  };
}

function isGroup(step: unknown): step is BuildkiteGroup {
  return typeof step === "object" && step !== null && "group" in step;
}

function isStep(step: unknown): step is BuildkiteStep {
  return (
    typeof step === "object" &&
    step !== null &&
    "label" in step &&
    !("group" in step) &&
    !("wait" in step)
  );
}

function isWait(step: unknown): step is { wait: string } {
  return typeof step === "object" && step !== null && "wait" in step;
}

function collectSteps(steps: unknown[], allSteps: BuildkiteStep[]): void {
  for (const s of steps) {
    if (isStep(s)) allSteps.push(s);
    if (
      typeof s === "object" &&
      s !== null &&
      "steps" in s &&
      Array.isArray((s as Record<string, unknown>)["steps"])
    ) {
      collectSteps(
        (s as Record<string, unknown>)["steps"] as unknown[],
        allSteps,
      );
    }
  }
}

function collectKeysAndDeps(
  steps: unknown[],
  allKeys: Set<string>,
  allDeps: string[],
): void {
  for (const step of steps) {
    if (typeof step !== "object" || step === null) continue;
    if ("key" in step && typeof step.key === "string") {
      allKeys.add(step.key);
    }
    if ("depends_on" in step && typeof step.depends_on === "string") {
      allDeps.push(step.depends_on);
    }
    if ("depends_on" in step && Array.isArray(step.depends_on)) {
      for (const dep of step.depends_on) {
        if (typeof dep === "string") {
          allDeps.push(dep);
        }
      }
    }
    if ("steps" in step && Array.isArray(step.steps)) {
      collectKeysAndDeps(step.steps, allKeys, allDeps);
    }
  }
}

function withBuildkitePullRequest<T>(value: string, fn: () => T): T {
  const original = process.env["BUILDKITE_PULL_REQUEST"];
  process.env["BUILDKITE_PULL_REQUEST"] = value;

  try {
    return fn();
  } finally {
    if (original === undefined) {
      delete process.env["BUILDKITE_PULL_REQUEST"];
    } else {
      process.env["BUILDKITE_PULL_REQUEST"] = original;
    }
  }
}

function withDryRun<T>(fn: () => T): T {
  const original = process.env["DRYRUN"];
  process.env["DRYRUN"] = "true";

  try {
    return fn();
  } finally {
    if (original === undefined) {
      delete process.env["DRYRUN"];
    } else {
      process.env["DRYRUN"] = original;
    }
  }
}

function withBuildkiteBranchContext<T>(
  branch: string,
  defaultBranch: string,
  fn: () => T,
): T {
  const originalBranch = process.env["BUILDKITE_BRANCH"];
  const originalDefaultBranch =
    process.env["BUILDKITE_PIPELINE_DEFAULT_BRANCH"];

  process.env["BUILDKITE_BRANCH"] = branch;
  process.env["BUILDKITE_PIPELINE_DEFAULT_BRANCH"] = defaultBranch;

  try {
    return fn();
  } finally {
    if (originalBranch === undefined) {
      delete process.env["BUILDKITE_BRANCH"];
    } else {
      process.env["BUILDKITE_BRANCH"] = originalBranch;
    }

    if (originalDefaultBranch === undefined) {
      delete process.env["BUILDKITE_PIPELINE_DEFAULT_BRANCH"];
    } else {
      process.env["BUILDKITE_PIPELINE_DEFAULT_BRANCH"] = originalDefaultBranch;
    }
  }
}

describe("buildPipeline", () => {
  describe("no changes", () => {
    it("returns a minimal pipeline with no-changes and ci-complete steps", () => {
      const pipeline = buildPipeline(emptyAffected());
      expect(pipeline.steps).toHaveLength(2);
      const noChanges = pipeline.steps[0]!;
      expect(isStep(noChanges)).toBe(true);
      if (isStep(noChanges)) {
        expect(noChanges.key).toBe("no-changes");
      }
      const ciComplete = pipeline.steps[1]!;
      expect(isStep(ciComplete)).toBe(true);
      if (isStep(ciComplete)) {
        expect(ciComplete.key).toBe("ci-complete");
        expect(ciComplete.depends_on).toEqual(["no-changes"]);
      }
    });

    it("includes Greptile review gate on no-change pull request builds", () => {
      const pipeline = withBuildkitePullRequest("123", () =>
        buildPipeline(emptyAffected()),
      );
      expect(pipeline.steps).toHaveLength(3);
      const steps = pipeline.steps.filter(isStep);
      const greptile = steps.find((s) => s.key === "greptile-review");
      const ciComplete = steps.find((s) => s.key === "ci-complete");

      expect(greptile).toBeDefined();
      expect(greptile?.command).toContain("github-app-token.ts");
      expect(greptile?.command).toContain("wait-for-greptile.ts");
      expect(ciComplete?.depends_on).toContain("greptile-review");
    });

    it("omits Greptile review gate on no-change main builds", () => {
      const pipeline = withBuildkitePullRequest("false", () =>
        buildPipeline(emptyAffected()),
      );
      const steps = pipeline.steps.filter(isStep);

      expect(steps.some((s) => s.key === "greptile-review")).toBe(false);
    });
  });

  describe("ci-base image changes", () => {
    it("builds, pushes, and commits back the next ci-base version", () => {
      const affected = emptyAffected();
      affected.ciImageChanged = true;

      const pipeline = buildPipeline(affected);
      const steps = pipeline.steps.filter(isStep);

      const build = steps.find((s) => s.key === "build-ci-base");
      const push = steps.find((s) => s.key === "push-ci-base");
      const commitBack = steps.find(
        (s) => s.key === "ci-base-version-commit-back",
      );

      expect(build).toBeDefined();
      expect(build?.if).toBeUndefined();
      expect(push).toBeDefined();
      expect(push?.if).toBe("build.branch == pipeline.default_branch");
      expect(push?.command).toContain("ghcr.io/shepherdjerred/ci-base:");
      expect(push?.command).toContain("--registry-password env:GHCR_TOKEN");
      expect(push?.command).toContain(
        "WARNING: GHCR_TOKEN unset, falling back to GH_TOKEN for GHCR push",
      );
      expect(push?.command).toContain(
        'export GHCR_TOKEN="$${GHCR_TOKEN:-$${GH_TOKEN:-}}"',
      );
      expect(commitBack).toBeDefined();
      expect(commitBack?.depends_on).toBe("push-ci-base");
      expect(commitBack?.concurrency_group).toBe(
        "monorepo/ci-base-version-commit-back",
      );
    });

    it("fails fast when a non-generated commit edits ci-base VERSION", () => {
      const affected = emptyAffected();
      affected.ciImageVersionChanged = true;

      const pipeline = buildPipeline(affected);
      const steps = pipeline.steps.filter(isStep);

      expect(steps[0]?.key).toBe("ci-base-version-guard");
      expect(steps[0]?.command).toContain(".buildkite/ci-image/VERSION");
      expect(steps[0]?.command).toContain("exit 1");
    });

    it("does not loop on generated ci-base VERSION commits", () => {
      const affected = emptyAffected();
      affected.ciImageVersionChanged = true;
      affected.isAutoGenerated = true;

      const pipeline = buildPipeline(affected);
      const steps = pipeline.steps.filter(isStep);

      expect(steps.some((s) => s.key === "ci-base-version-guard")).toBe(false);
      expect(steps.some((s) => s.key === "build-ci-base")).toBe(false);
      expect(steps.some((s) => s.key === "ci-base-version-commit-back")).toBe(
        false,
      );
      expect(steps.some((s) => s.key === "no-changes")).toBe(true);
    });
  });

  describe("single package change", () => {
    it("emits only that package's group plus quality gates", () => {
      const affected = emptyAffected();
      affected.packages.add("webring");

      const pipeline = buildPipeline(affected);

      const groups = pipeline.steps.filter(isGroup);
      const pkgGroups = groups.filter((g) => g.key.startsWith("pkg-"));
      expect(pkgGroups).toHaveLength(1);
      expect(pkgGroups[0]!.key).toBe("pkg-webring");
    });

    it("does not include release steps for non-main", () => {
      const affected = emptyAffected();
      affected.packages.add("webring");

      const pipeline = buildPipeline(affected);
      const waits = pipeline.steps.filter(isWait);
      expect(waits).toHaveLength(0);
    });

    it("includes ci-complete step depending on quality gates and package build", () => {
      const affected = emptyAffected();
      affected.packages.add("webring");

      const pipeline = buildPipeline(affected);
      const steps = pipeline.steps.filter(isStep);
      const ciComplete = steps.find((s) => s.key === "ci-complete");
      expect(ciComplete).toBeDefined();
      const deps = Array.isArray(ciComplete?.depends_on)
        ? ciComplete.depends_on
        : [];
      // Should include the package build group
      expect(deps).toContain("pkg-webring");
      // Should include the bundled blocking quality gates step
      expect(deps).toContain("quality-bundle");
    });

    it("includes async quality checks even without main steps", () => {
      const affected = emptyAffected();
      affected.packages.add("webring");

      const pipeline = buildPipeline(affected);
      const steps = pipeline.steps.filter(isStep);
      // All async checks should be present.
      // - prettier + markdownlint live inside `quality-bundle`
      // - dagger-hygiene + large-file-check live inside `soft-fail-bundle`
      for (const key of [
        "quality-bundle",
        "knip-check",
        "soft-fail-bundle",
        "trivy-scan",
        "semgrep-scan",
      ]) {
        expect(steps.find((s) => s.key === key)).toBeDefined();
      }
      // These specific checks should be soft_fail
      for (const key of [
        "knip-check",
        "soft-fail-bundle",
        "trivy-scan",
        "semgrep-scan",
      ]) {
        expect(steps.find((s) => s.key === key)?.soft_fail).toBe(true);
      }
    });

    it("checks TasksForObsidian iOS native dependencies when the package changes", () => {
      const affected = emptyAffected();
      affected.packages.add("tasks-for-obsidian");

      const pipeline = buildPipeline(affected);
      const pkgGroup = pipeline.steps
        .filter(isGroup)
        .find((g) => g.key === "pkg-tasks-for-obsidian");
      const nativeDepsStep = pkgGroup?.steps.find(
        (s) => s.key === "ios-native-deps-tasks-for-obsidian",
      );

      expect(nativeDepsStep).toBeDefined();
      // DAGGER_CALL injects constructor args between `call` and the function
      // name; keep this assertion focused on the function invocation.
      expect(nativeDepsStep?.command).toMatch(
        /dagger(\s+-[\w-]+\s+\S+)*\s+call(\s+--repo-root\s+"[^"]+")?\s+tasks-for-obsidian-ios-native-deps/,
      );
      expect(nativeDepsStep?.command).toContain(
        "https://github.com/shepherdjerred/monorepo.git",
      );
      expect(nativeDepsStep?.soft_fail).toBeUndefined();
    });

    it("only builds the image whose package actually changed", () => {
      const affected = emptyAffected();
      affected.packages.add("temporal");
      affected.hasImagePackages.add("temporal");

      const pipeline = buildPipeline(affected);
      const groups = pipeline.steps.filter(isGroup);

      // Build/push groups should exist for temporal-worker only
      const buildGroup = groups.find((g) => g.key === "build-images");
      expect(buildGroup).toBeDefined();
      const buildSteps = buildGroup?.steps ?? [];
      const buildKeys = buildSteps
        .filter(isStep)
        .map((s) => s.key)
        .filter((k): k is string => typeof k === "string");
      // Should include build for temporal-worker, NOT for birmel/scout/etc.
      expect(buildKeys.some((k) => k.includes("temporal-worker"))).toBe(true);
      expect(buildKeys.some((k) => k.includes("birmel"))).toBe(false);
      expect(buildKeys.some((k) => k.includes("scout-for-lol"))).toBe(false);
      expect(buildKeys.some((k) => k.includes("starlight-karma-bot"))).toBe(
        false,
      );
      expect(buildKeys.some((k) => k.includes("discord-plays-pokemon"))).toBe(
        false,
      );
      expect(buildKeys.some((k) => k.includes("tasknotes-server"))).toBe(false);

      // Push steps live inside the push-images group, mirror should hold
      const pushGroup = groups.find((g) => g.key === "push-images");
      expect(pushGroup).toBeDefined();
      const pushKeys = (pushGroup?.steps ?? [])
        .filter(isStep)
        .map((s) => s.key)
        .filter((k): k is string => typeof k === "string");
      expect(pushKeys.some((k) => k.includes("temporal-worker"))).toBe(true);
      expect(pushKeys.some((k) => k.includes("birmel"))).toBe(false);
    });
  });

  describe("helm-types drift check", () => {
    function homelabStepKeys(affected: AffectedPackages): string[] {
      const pipeline = buildPipeline(affected);
      const homelab = pipeline.steps
        .filter(isGroup)
        .find((g) => g.key === "pkg-homelab");
      return (homelab?.steps ?? []).filter(isStep).map((s) => s.key);
    }

    it("emits the drift-check step when a generator input changed", () => {
      const affected = emptyAffected();
      affected.packages.add("homelab");
      affected.homelabChanged = true;
      affected.helmTypesInputsChanged = true;

      const keys = homelabStepKeys(affected);
      expect(keys).toContain("helm-types-drift-check");
      // build-helm-types is unconditional for homelab; drift-check is the gate.
      expect(keys).toContain("build-helm-types");
    });

    it("omits the drift-check step when no generator input changed", () => {
      const affected = emptyAffected();
      affected.packages.add("homelab");
      affected.homelabChanged = true;

      const keys = homelabStepKeys(affected);
      expect(keys).not.toContain("helm-types-drift-check");
      expect(keys).toContain("build-helm-types");
    });

    it("emits drift-check for Renovate noop+helmTypesInputsChanged (homelab in packages, empty otherwise)", () => {
      // Simulates the Renovate chart-bump case: only versions.ts changed.
      // change-detection returns buildScopedResult(new Set(["homelab"]), ..., helmTypesInputsChanged=true).
      // buildPipeline must NOT hit the empty-packages early return and must emit the drift-check.
      const affected = emptyAffected();
      affected.packages.add("homelab");
      affected.homelabChanged = true;
      affected.helmTypesInputsChanged = true;
      // All other flags false — simulates a Renovate noop path

      const pipeline = buildPipeline(affected);
      const homelabGroup = pipeline.steps
        .filter(isGroup)
        .find((g) => g.key === "pkg-homelab");
      const stepKeys = (homelabGroup?.steps ?? [])
        .filter(isStep)
        .map((s) => s.key);

      expect(stepKeys).toContain("helm-types-drift-check");
    });

    it("no-changes early return does NOT fire when helmTypesInputsChanged is true", () => {
      // Defense-in-depth: even if packages is empty but helmTypesInputsChanged=true,
      // the early return must be skipped. (change-detection ensures homelab is in
      // packages, but pipeline-builder also guards independently.)
      const affected = emptyAffected();
      affected.helmTypesInputsChanged = true;
      // packages.size === 0, buildAll=false, ciImageChanged=false — triggers early return
      // without the helmTypesInputsChanged guard added in this PR

      const pipeline = buildPipeline(affected);
      // The pipeline must NOT contain the "no-changes" key
      const noChangesStep = pipeline.steps
        .filter(isStep)
        .find((s) => s.key === "no-changes");
      expect(noChangesStep).toBeUndefined();
    });
  });

  describe("full build", () => {
    it("includes all packages", () => {
      const pipeline = buildPipeline(fullBuild());
      const pkgGroups = pipeline.steps
        .filter(isGroup)
        .filter((g) => g.key.startsWith("pkg-"));
      expect(pkgGroups.length).toBe(ALL_PACKAGES.length - SKIP_PACKAGES.size);
    });

    it("includes quality gates", () => {
      const pipeline = buildPipeline(fullBuild());
      const steps = pipeline.steps.filter(isStep);
      // 15 source-only blocking checks are bundled into one `quality-bundle`
      // step now — see `.dagger/src/quality.ts:qualityBundleHelper`. The
      // soft-fail / annotated scans stay separate.
      const qualityKeys = ["quality-bundle", "knip-check"];
      for (const key of qualityKeys) {
        expect(steps.some((s) => s.key === key)).toBe(true);
      }
    });

    it("includes security and quality scans with soft_fail", () => {
      const pipeline = buildPipeline(fullBuild());
      const steps = pipeline.steps.filter(isStep);
      // dagger-hygiene + large-file-check now run inside `soft-fail-bundle`.
      for (const key of [
        "semgrep-scan",
        "trivy-scan",
        "soft-fail-bundle",
        "knip-check",
      ]) {
        const step = steps.find((s) => s.key === key);
        expect(step).toBeDefined();
        expect(step?.soft_fail).toBe(true);
      }
    });

    it("quality gate depends on every per-package pkg-check + repo-wide hard-fail checks (but not soft-fail checks)", () => {
      const pipeline = buildPipeline(fullBuild());

      // No wait steps — quality-gate uses explicit depends_on
      const waits = pipeline.steps.filter(isWait);
      expect(waits).toHaveLength(0);

      // Quality gate step exists with depends_on
      const steps = pipeline.steps.filter(isStep);
      const gate = steps.find((s) => s.key === "quality-gate");
      expect(gate).toBeDefined();
      expect(Array.isArray(gate?.depends_on)).toBe(true);
      const deps = gate?.depends_on;
      const depList = Array.isArray(deps) ? deps : [];
      expect(depList).not.toHaveLength(0);

      // Release-train rule: every per-package pkg-* group key gates release,
      // so a single failing pkg-check blocks every image/helm/site push.
      const pkgGroups = pipeline.steps
        .filter(isGroup)
        .filter((g) => g.key.startsWith("pkg-"));
      expect(pkgGroups.length).toBeGreaterThan(0);
      for (const g of pkgGroups) {
        expect(depList).toContain(g.key);
      }

      // depends_on includes the bundled hard-fail quality gates + the
      // change-detection conditional gates.
      const blockingGateKeys = ["quality-bundle", "caddyfile-validate"];
      for (const key of blockingGateKeys) {
        expect(depList).toContain(key);
      }

      // depends_on does NOT include async (soft_fail) check keys — those
      // are advisory by design (see quality.ts knipCheckStep softFail: true).
      const asyncKeys = [
        "knip-check",
        "soft-fail-bundle",
        "trivy-scan",
        "semgrep-scan",
      ];
      for (const key of asyncKeys) {
        expect(depList).not.toContain(key);
      }
    });

    it("includes TasksForObsidian iOS native dependency check in full builds", () => {
      const pipeline = buildPipeline(fullBuild());
      const pkgGroup = pipeline.steps
        .filter(isGroup)
        .find((g) => g.key === "pkg-tasks-for-obsidian");

      expect(
        pkgGroup?.steps.some(
          (s) => s.key === "ios-native-deps-tasks-for-obsidian",
        ),
      ).toBe(true);
    });

    it("smoke tests gate image pushes (smoke before push)", () => {
      const pipeline = buildPipeline(fullBuild());
      const allSteps: BuildkiteStep[] = [];

      function collect(steps: unknown[]) {
        for (const s of steps) {
          if (isStep(s)) allSteps.push(s);
          if (
            typeof s === "object" &&
            s !== null &&
            "steps" in s &&
            Array.isArray((s as Record<string, unknown>)["steps"])
          ) {
            collect((s as Record<string, unknown>)["steps"] as unknown[]);
          }
        }
      }
      collect(pipeline.steps);

      // Build+smoke is now a single bundled step (no standalone build-<img>
      // for smokeable images). Each smoke step depends on quality-gate (and
      // its per-package pkg-check step if one exists) directly.
      const smokeSteps = allSteps.filter((s) => s.key.startsWith("smoke-"));
      expect(smokeSteps.length).toBeGreaterThan(0);
      for (const s of smokeSteps) {
        const deps = Array.isArray(s.depends_on)
          ? s.depends_on
          : [s.depends_on];
        expect(deps).toContain("quality-gate");
        const imgName = s.key.replace("smoke-", "");
        // The standalone build step should NOT exist for smokeable images.
        expect(
          allSteps.find((step) => step.key === `build-${imgName}`),
        ).toBeUndefined();
      }

      // Push steps with smoke tests depend on their smoke step
      for (const smoke of smokeSteps) {
        const imgName = smoke.key.replace("smoke-", "");
        const push = allSteps.find((s) => s.key === `push-${imgName}`);
        expect(push).toBeDefined();
        const pushDeps = Array.isArray(push?.depends_on)
          ? push?.depends_on
          : [push?.depends_on];
        expect(pushDeps).toContain(smoke.key);
      }

      // Push steps without smoke tests depend on their build step
      const smokeNames = new Set(
        smokeSteps.map((s) => s.key.replace("smoke-", "")),
      );
      const pushOnly = allSteps.filter(
        (s) =>
          s.key.startsWith("push-") &&
          !smokeNames.has(s.key.replace("push-", "")),
      );
      for (const s of pushOnly) {
        const deps = Array.isArray(s.depends_on)
          ? s.depends_on
          : [s.depends_on];
        const imgName = s.key.replace("push-", "");
        expect(deps).toContain(`build-${imgName}`);
      }
    });

    it("tofu plan bundle is PR-only", () => {
      const mainPipeline = withBuildkitePullRequest("false", () =>
        buildPipeline(fullBuild()),
      );
      const mainSteps: BuildkiteStep[] = [];
      collectSteps(mainPipeline.steps, mainSteps);
      expect(mainSteps.some((s) => s.key === "tofu-plan-all")).toBe(false);

      const pipeline = withBuildkitePullRequest("123", () =>
        buildPipeline(fullBuild()),
      );
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);

      const planAll = allSteps.find((s) => s.key === "tofu-plan-all");
      expect(planAll).toBeDefined();
      expect(planAll?.if).toBe("build.branch != pipeline.default_branch");
      // Plan is read-only — no per-step concurrency group on the bundle.
      expect(planAll?.concurrency).toBeUndefined();
      expect(planAll?.concurrency_group).toBeUndefined();
      // Bundle command carries every stack-relevant secret; the underlying
      // Dagger helpers conditionally bind only the secrets each stack needs.
      const cmdStr = planAll?.command ?? "";
      expect(cmdStr).toContain("--github-token env:TOFU_GITHUB_TOKEN");
      expect(cmdStr).toContain(
        "--tailscale-oauth-client-id env:TAILSCALE_OAUTH_CLIENT_ID",
      );
      expect(cmdStr).toContain(
        "--tailscale-oauth-client-secret env:TAILSCALE_OAUTH_CLIENT_SECRET",
      );
    });

    it("omits main-only release and deploy graph from pull request builds", () => {
      const pipeline = withBuildkitePullRequest("123", () =>
        buildPipeline(fullBuild()),
      );
      const groups = pipeline.steps.filter(isGroup);
      const groupKeys = groups.map((g) => g.key);
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);
      const stepKeys = allSteps.map((s) => s.key);

      expect(groupKeys).toContain("build-images");
      expect(stepKeys).toContain("tofu-plan-all");
      expect(stepKeys).toContain("ci-complete");
      expect(stepKeys).toContain("greptile-review");

      expect(groupKeys).not.toContain("push-images");
      expect(groupKeys).not.toContain("publish-npm");
      expect(groupKeys).not.toContain("cooklang-release");
      expect(groupKeys).not.toContain("deploy-sites");

      expect(stepKeys).not.toContain("helm-push-all");
      expect(stepKeys).not.toContain("tofu-apply-all");
      expect(stepKeys).not.toContain("release-please");
      expect(stepKeys).not.toContain("deploy-argocd");
      expect(stepKeys).not.toContain("argocd-health");
      expect(stepKeys).not.toContain("version-commit-back");
      expect(stepKeys).not.toContain("build-summary");
    });

    it("dryrun-builds a source-changed site on pull request builds and gates ci-complete on it", () => {
      const affected = emptyAffected();
      affected.packages = new Set(["scout-for-lol"]);
      affected.directlyChanged = new Set(["scout-for-lol"]);
      affected.hasSitePackages = new Set(["scout-for-lol"]);

      const pipeline = withBuildkitePullRequest("123", () =>
        buildPipeline(affected),
      );

      const groupKeys = pipeline.steps.filter(isGroup).map((g) => g.key);
      expect(groupKeys).toContain("deploy-sites");

      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);

      const scoutDeploy = allSteps.find(
        (s) => s.key === "deploy-scout-frontend",
      );
      expect(scoutDeploy).toBeDefined();
      // PR dryruns never sync, so they must not wait on the main-only bucket apply.
      expect(scoutDeploy?.depends_on).not.toContain("tofu-apply-all");

      // A failed dryrun build must fail the required check and block merge.
      const ciComplete = allSteps.find((s) => s.key === "ci-complete");
      expect(ciComplete?.depends_on).toContain("deploy-scout-frontend");
      expect(ciComplete?.depends_on).toContain("deploy-scout-frontend-beta");
    });

    it("does not dryrun-build sites for buildAll (infra) pull request builds", () => {
      const pipeline = withBuildkitePullRequest("123", () =>
        buildPipeline(fullBuild()),
      );
      const groupKeys = pipeline.steps.filter(isGroup).map((g) => g.key);
      expect(groupKeys).not.toContain("deploy-sites");
    });

    it("makes ci-complete depend on Greptile for pull request builds", () => {
      const pipeline = withBuildkitePullRequest("123", () =>
        buildPipeline(fullBuild()),
      );
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);
      const ciComplete = allSteps.find((s) => s.key === "ci-complete");

      expect(ciComplete).toBeDefined();
      expect(ciComplete?.depends_on).toContain("greptile-review");
    });

    it("does not include Greptile on main builds", () => {
      const pipeline = withBuildkitePullRequest("false", () =>
        buildPipeline(fullBuild()),
      );
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);

      expect(allSteps.some((s) => s.key === "greptile-review")).toBe(false);
    });

    it("includes image build/push, npm, cooklang, and sites groups", () => {
      const pipeline = buildPipeline(fullBuild());
      const groups = pipeline.steps.filter(isGroup);
      const groupKeys = groups.map((g) => g.key);

      expect(groupKeys).toContain("build-images");
      expect(groupKeys).toContain("push-images");
      expect(groupKeys).toContain("publish-npm");
      expect(groupKeys).toContain("cooklang-release");
      expect(groupKeys).toContain("deploy-sites");
    });

    it("omits cooklang release on auto-generated cooklang bumps", () => {
      const affected = emptyAffected();
      affected.packages.add("cooklang-for-obsidian");
      affected.cooklangChanged = true;
      affected.isAutoGenerated = true;

      const pipeline = buildPipeline(affected);
      const groups = pipeline.steps.filter(isGroup);
      const groupKeys = groups.map((g) => g.key);

      expect(groupKeys).not.toContain("cooklang-release");
    });

    it("omits cooklang release on a full build when cooklang did not change", () => {
      // A full build (infra/lockfile change) rebuilds everything but must not
      // publish a cooklang plugin version when no cooklang source changed —
      // otherwise every unrelated full build opens a manifest-bump PR.
      const affected = fullBuild();
      affected.cooklangChanged = false;

      const pipeline = buildPipeline(affected);
      const groupKeys = pipeline.steps.filter(isGroup).map((g) => g.key);

      expect(groupKeys).not.toContain("cooklang-release");
      // ...but the rest of the full-build release track still runs.
      expect(groupKeys).toContain("build-images");
      expect(groupKeys).toContain("push-images");
      expect(groupKeys).toContain("publish-npm");
      expect(groupKeys).toContain("deploy-sites");
    });

    it("includes cooklang release on a scoped build when cooklang changed", () => {
      const affected = emptyAffected();
      affected.packages.add("cooklang-for-obsidian");
      affected.cooklangChanged = true;

      const pipeline = buildPipeline(affected);
      const groupKeys = pipeline.steps.filter(isGroup).map((g) => g.key);

      expect(groupKeys).toContain("cooklang-release");
    });

    it("uses GitHub App auth for release tasks and GHCR_TOKEN for image pushes with GH_TOKEN fallback", () => {
      const pipeline = buildPipeline(fullBuild());
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);

      const releaseSteps = allSteps.filter((s) =>
        ["cooklang-publish"].includes(s.key),
      );
      expect(releaseSteps.length).toBe(1);
      for (const s of releaseSteps) {
        expect(s.command).toContain("--github-app-id env:GITHUB_APP_ID");
        expect(s.command).not.toContain("env:GH_TOKEN");
      }

      const imagePushSteps = allSteps.filter((s) => s.key.startsWith("push-"));
      expect(imagePushSteps.length).toBeGreaterThan(0);
      for (const s of imagePushSteps) {
        if (s.command.includes("--registry-password")) {
          expect(s.command).toContain("--registry-password env:GHCR_TOKEN");
          expect(s.command).not.toContain("--registry-password env:GH_TOKEN");
          expect(s.command).toContain(
            "WARNING: GHCR_TOKEN unset, falling back to GH_TOKEN for GHCR push",
          );
          expect(s.command).toContain(
            'export GHCR_TOKEN="$${GHCR_TOKEN:-$${GH_TOKEN:-}}"',
          );
        }
      }
    });

    it("forwards Scout marketing pixel env vars into the deploy build container", () => {
      const pipeline = withBuildkiteBranchContext("main", "main", () =>
        buildPipeline(fullBuild()),
      );
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);

      const scoutDeploy = allSteps.find(
        (s) => s.key === "deploy-scout-frontend",
      );

      expect(scoutDeploy).toBeDefined();
      expect(scoutDeploy?.command).toContain(
        "--build-env-names PUBLIC_PINTEREST_TAG_ID",
      );
      expect(scoutDeploy?.command).toContain(
        "--build-env-values env:PUBLIC_PINTEREST_TAG_ID",
      );
      expect(scoutDeploy?.command).toContain(
        "--build-env-names PUBLIC_REDDIT_PIXEL_ID",
      );
      expect(scoutDeploy?.command).toContain(
        "--build-env-values env:PUBLIC_REDDIT_PIXEL_ID",
      );
    });

    it("uses explicit Scout marketing placeholders for dry-run deploy builds", () => {
      const pipeline = withDryRun(() => buildPipeline(fullBuild()));
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);

      const scoutDeploy = allSteps.find(
        (s) => s.key === "deploy-scout-frontend",
      );

      expect(scoutDeploy).toBeDefined();
      expect(scoutDeploy?.command).not.toContain(
        "--build-env-values env:PUBLIC_PINTEREST_TAG_ID",
      );
      expect(scoutDeploy?.command).not.toContain(
        "--build-env-values env:PUBLIC_REDDIT_PIXEL_ID",
      );
      expect(scoutDeploy?.command).toContain(
        "PUBLIC_PINTEREST_TAG_ID='dev-pinterest-tag-id'",
      );
      expect(scoutDeploy?.command).toContain(
        "PUBLIC_REDDIT_PIXEL_ID='dev-reddit-pixel-id'",
      );
    });

    it("uses non-tracking Scout marketing placeholders for beta deploy builds", () => {
      const pipeline = withBuildkiteBranchContext("main", "main", () =>
        buildPipeline(fullBuild()),
      );
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);

      const scoutBetaDeploy = allSteps.find(
        (s) => s.key === "deploy-scout-frontend-beta",
      );

      expect(scoutBetaDeploy).toBeDefined();
      expect(scoutBetaDeploy?.command).not.toContain(
        "--build-env-values env:PUBLIC_PINTEREST_TAG_ID",
      );
      expect(scoutBetaDeploy?.command).not.toContain(
        "--build-env-values env:PUBLIC_REDDIT_PIXEL_ID",
      );
      expect(scoutBetaDeploy?.command).toContain(
        "PUBLIC_PINTEREST_TAG_ID='beta-placeholder-pinterest-tag-id'",
      );
      expect(scoutBetaDeploy?.command).toContain(
        "PUBLIC_REDDIT_PIXEL_ID='beta-placeholder-reddit-pixel-id'",
      );
    });

    it("includes homelab track", () => {
      const pipeline = buildPipeline(fullBuild());
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);
      const groups = pipeline.steps.filter(isGroup);
      const groupKeys = groups.map((g) => g.key);
      const stepKeys = allSteps.map((s) => s.key);

      // Homelab images are now part of the unified build/push groups
      expect(groupKeys).toContain("build-images");
      expect(groupKeys).toContain("push-images");
      expect(stepKeys).toContain("helm-push-all");
      expect(stepKeys).toContain("tofu-apply-all");
    });

    it("waits for SeaweedFS bucket reconciliation before deploying sites", () => {
      const pipeline = buildPipeline(fullBuild());
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);

      const scoutBetaDeploy = allSteps.find(
        (s) => s.key === "deploy-scout-frontend-beta",
      );

      expect(scoutBetaDeploy).toBeDefined();
      expect(scoutBetaDeploy?.depends_on).toContain("tofu-apply-all");
    });

    it("waits for SeaweedFS bucket reconciliation for partial homelab + site releases", () => {
      const affected = emptyAffected();
      affected.packages.add("homelab");
      affected.packages.add("scout-for-lol");
      affected.homelabChanged = true;
      affected.hasSitePackages.add("scout-for-lol");

      const pipeline = buildPipeline(affected);
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);

      const tofuApplyAll = allSteps.find((s) => s.key === "tofu-apply-all");
      const scoutBetaDeploy = allSteps.find(
        (s) => s.key === "deploy-scout-frontend-beta",
      );

      expect(tofuApplyAll).toBeDefined();
      expect(scoutBetaDeploy).toBeDefined();
      expect(scoutBetaDeploy?.depends_on).toContain("tofu-apply-all");
    });

    it("includes version commit-back", () => {
      const pipeline = buildPipeline(fullBuild());
      const steps = pipeline.steps.filter(isStep);
      expect(steps.some((s) => s.key === "version-commit-back")).toBe(true);
    });

    it("serializes version commit-back", () => {
      const pipeline = buildPipeline(fullBuild());
      const steps = pipeline.steps.filter(isStep);
      const versionCommitBack = steps.find(
        (s) => s.key === "version-commit-back",
      );

      expect(versionCommitBack).toBeDefined();
      expect(versionCommitBack?.concurrency).toBe(1);
      expect(versionCommitBack?.concurrency_group).toBe(
        "monorepo/version-commit-back",
      );
    });

    it("omits version commit-back on auto-generated commits", () => {
      const affected = fullBuild();
      affected.isAutoGenerated = true;
      const pipeline = buildPipeline(affected);
      const steps = pipeline.steps.filter(isStep);
      expect(steps.some((s) => s.key === "version-commit-back")).toBe(false);
    });

    it("includes ci-complete step in full build", () => {
      const pipeline = buildPipeline(fullBuild());
      const steps = pipeline.steps.filter(isStep);
      const ciComplete = steps.find((s) => s.key === "ci-complete");
      expect(ciComplete).toBeDefined();
      const deps = Array.isArray(ciComplete?.depends_on)
        ? ciComplete.depends_on
        : [];
      // Should include the bundled blocking quality gates step
      expect(deps).toContain("quality-bundle");
      // Should include per-package build keys
      expect(deps.some((d: string) => d.startsWith("pkg-"))).toBe(true);
    });

    it("includes build summary step with allow_dependency_failure", () => {
      const pipeline = buildPipeline(fullBuild());
      const steps = pipeline.steps.filter(isStep);
      const summary = steps.find((s) => s.key === "build-summary");
      expect(summary).toBeDefined();
      expect(summary?.depends_on).toBeDefined();
      expect(summary?.allow_dependency_failure).toBe(true);
    });

    it("build summary command emits escaped backticks, no ${BT} leakage", () => {
      // Regression test: build 1011 failed with `/bin/sh: ghcr: parameter not set`
      // because the generator emitted `$$${BT}` which collapsed to a bare `$` once
      // Buildkite stripped `${BT}` as an unset env var. Ensure the new form survives
      // Buildkite's variable interpolation and produces literal backticks in bash.
      const pipeline = buildPipeline(fullBuild());
      const steps = pipeline.steps.filter(isStep);
      const summary = steps.find((s) => s.key === "build-summary");
      const command =
        typeof summary?.command === "string"
          ? summary.command
          : (summary?.command ?? []).join("\n");
      expect(command).toContain("\\`ghcr.io/");
      expect(command).toContain("\\`$$DIGEST\\`");
      expect(command).not.toContain("${BT}");
      expect(command).not.toContain("BT=");
      // After Buildkite $$ -> $ expansion the surviving markdown code span uses \`.
      const postBuildkite = command.replace(/\$\$/g, "$");
      expect(postBuildkite).toMatch(/\\`ghcr\.io\/[^`]+:\$VERSION\\`/);
      expect(postBuildkite).toMatch(/\\`\$DIGEST\\`/);
    });

    it("deploy steps have concurrency groups", () => {
      const pipeline = buildPipeline(fullBuild());
      const allSteps: BuildkiteStep[] = [];

      function collect(steps: unknown[]) {
        for (const s of steps) {
          if (isStep(s)) allSteps.push(s);
          if (
            typeof s === "object" &&
            s !== null &&
            "steps" in s &&
            Array.isArray((s as Record<string, unknown>)["steps"])
          ) {
            collect((s as Record<string, unknown>)["steps"] as unknown[]);
          }
        }
      }
      collect(pipeline.steps);

      // tofu-apply-all is the bundled step that applies every stack in
      // parallel inside one Dagger call. It carries no BK concurrency group
      // — each stack has its own S3 state lock, so concurrent applies are
      // safe at the backend layer. The bundle command carries every secret;
      // the underlying Dagger helpers conditionally bind only the secrets
      // the stack consumes.
      const tofuApplyAll = allSteps.find((s) => s.key === "tofu-apply-all");
      expect(tofuApplyAll).toBeDefined();
      expect(tofuApplyAll?.concurrency).toBeUndefined();
      expect(tofuApplyAll?.concurrency_group).toBeUndefined();
      const cmdStr = tofuApplyAll?.command ?? "";
      expect(cmdStr).toContain("--github-token env:TOFU_GITHUB_TOKEN");
      expect(cmdStr).toContain(
        "--tailscale-oauth-client-id env:TAILSCALE_OAUTH_CLIENT_ID",
      );

      const argoSteps = allSteps.filter((s) =>
        s.key.startsWith("deploy-argocd"),
      );
      expect(argoSteps.length).toBeGreaterThan(0);
      for (const s of argoSteps) {
        expect(s.concurrency).toBe(1);
        expect(s.concurrency_group).toContain("monorepo/argocd-sync-");
      }
    });
  });

  describe("version-bump-only (commit-back)", () => {
    function versionBumpAffected(): AffectedPackages {
      const affected = emptyAffected();
      affected.packages.add("homelab");
      affected.homelabChanged = true;
      affected.versionBumpOnly = true;
      return affected;
    }

    it("includes cdk8s synth so new digests are rendered into manifests", () => {
      const pipeline = buildPipeline(versionBumpAffected());
      const steps = pipeline.steps.filter(isStep);
      expect(steps.some((s) => s.key === "homelab-cdk8s")).toBe(true);
    });

    it("includes the 1Password item/field lint gate (bundled with cdk8s synth)", () => {
      const pipeline = buildPipeline(versionBumpAffected());
      const steps = pipeline.steps.filter(isStep);
      // Both checks now run inside the `homelab-cdk8s` bundle Dagger func.
      const bundle = steps.find((s) => s.key === "homelab-cdk8s");
      expect(bundle).toBeDefined();
      // Dagger CLI kebab-cases the method name `homelabCdk8sBundle` →
      // `homelab-cdk-8-s-bundle` (digit boundary; see helm.ts:46-47).
      expect(bundle?.command).toContain("homelab-cdk-8-s-bundle");
    });

    it("includes helm chart push so ArgoCD picks up new manifests", () => {
      const pipeline = buildPipeline(versionBumpAffected());
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);
      expect(allSteps.some((s) => s.key === "helm-push-all")).toBe(true);
    });

    it("includes tofu apply", () => {
      const pipeline = buildPipeline(versionBumpAffected());
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);
      expect(allSteps.some((s) => s.key === "tofu-apply-all")).toBe(true);
    });

    it("includes one bundled ArgoCD sync + health step", () => {
      const pipeline = buildPipeline(versionBumpAffected());
      const steps = pipeline.steps.filter(isStep);
      // Sync + health-wait collapsed into one BK pod via
      // `argo-cd-sync-and-wait`; health-wait failure is caught Dagger-side.
      expect(steps.some((s) => s.key === "deploy-argocd")).toBe(true);
      expect(steps.some((s) => s.key === "argocd-health")).toBe(false);
    });

    it("does NOT build any images (they were already pushed)", () => {
      const pipeline = buildPipeline(versionBumpAffected());
      const groups = pipeline.steps.filter(isGroup);
      expect(groups.some((g) => g.key === "build-images")).toBe(false);
    });

    it("does NOT push any images", () => {
      const pipeline = buildPipeline(versionBumpAffected());
      const groups = pipeline.steps.filter(isGroup);
      expect(groups.some((g) => g.key === "push-images")).toBe(false);
    });

    it("does NOT run version-commit-back (breaks the loop)", () => {
      const pipeline = buildPipeline(versionBumpAffected());
      const steps = pipeline.steps.filter(isStep);
      expect(steps.some((s) => s.key === "version-commit-back")).toBe(false);
    });

    it("does NOT include unrelated packages (cooklang, npm, sites)", () => {
      const pipeline = buildPipeline(versionBumpAffected());
      const groups = pipeline.steps.filter(isGroup);
      const groupKeys = groups.map((g) => g.key);
      expect(groupKeys).not.toContain("cooklang-release");
      expect(groupKeys).not.toContain("publish-npm");
      expect(groupKeys).not.toContain("deploy-sites");
    });

    it("ArgoCD sync depends on helm and tofu, not image pushes", () => {
      const pipeline = buildPipeline(versionBumpAffected());
      const steps = pipeline.steps.filter(isStep);
      const argoSync = steps.find((s) => s.key === "deploy-argocd");
      expect(argoSync).toBeDefined();
      const deps = Array.isArray(argoSync?.depends_on)
        ? argoSync.depends_on
        : [];
      expect(deps).toContain("helm-push-all");
      // Should NOT depend on any push-* image keys
      const imagePushDeps = deps.filter((d: string) => d.startsWith("push-"));
      expect(imagePushDeps).toHaveLength(0);
    });

    it("has valid depends_on references (no dangling refs to skipped image steps)", () => {
      const pipeline = buildPipeline(versionBumpAffected());
      const allKeys = new Set<string>();
      const allDeps: string[] = [];

      function collect(steps: unknown[]) {
        for (const s of steps) {
          if (typeof s !== "object" || s === null) continue;
          const obj = s as Record<string, unknown>;
          if (typeof obj["key"] === "string") allKeys.add(obj["key"]);
          if (typeof obj["depends_on"] === "string")
            allDeps.push(obj["depends_on"]);
          if (Array.isArray(obj["depends_on"])) {
            for (const d of obj["depends_on"]) {
              if (typeof d === "string") allDeps.push(d);
            }
          }
          if (Array.isArray(obj["steps"])) collect(obj["steps"] as unknown[]);
        }
      }

      collect(pipeline.steps);

      const missing = allDeps.filter((d) => !allKeys.has(d));
      expect(missing).toEqual([]);
    });
  });

  describe("homelab-only change", () => {
    it("includes homelab track and images but not cooklang", () => {
      const affected = emptyAffected();
      affected.packages.add("homelab");
      affected.homelabChanged = true;

      const pipeline = buildPipeline(affected);
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);
      const groups = pipeline.steps.filter(isGroup);
      const groupKeys = groups.map((g) => g.key);
      const stepKeys = allSteps.map((s) => s.key);

      // Homelab images are part of the unified build/push groups
      expect(groupKeys).toContain("build-images");
      expect(groupKeys).toContain("push-images");
      expect(stepKeys).toContain("helm-push-all");
      expect(stepKeys).toContain("tofu-apply-all");
      expect(groupKeys).not.toContain("cooklang-release");
    });
  });

  describe("tofu plan gating (PR builds)", () => {
    it("omits the tofu plan bundle for a cdk8s-only homelab PR", () => {
      // homelab changed (e.g. cdk8s) but no tofu source files changed
      const affected = emptyAffected();
      affected.packages.add("homelab");
      affected.homelabChanged = true;
      affected.tofuChanged = false;

      const pipeline = withBuildkitePullRequest("123", () =>
        buildPipeline(affected),
      );
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);
      expect(allSteps.some((s) => s.key === "tofu-plan-all")).toBe(false);
    });

    it("includes the tofu plan bundle when tofu source changed", () => {
      const affected = emptyAffected();
      affected.packages.add("homelab");
      affected.homelabChanged = true;
      affected.tofuChanged = true;

      const pipeline = withBuildkitePullRequest("123", () =>
        buildPipeline(affected),
      );
      const allSteps: BuildkiteStep[] = [];
      collectSteps(pipeline.steps, allSteps);
      expect(allSteps.some((s) => s.key === "tofu-plan-all")).toBe(true);
    });
  });

  describe("structural validation", () => {
    it("has unique step keys across the full build", () => {
      const pipeline = buildPipeline(fullBuild());
      const keys: string[] = [];

      function collectKeys(steps: unknown[]) {
        for (const s of steps) {
          if (typeof s === "object" && s !== null) {
            if (
              "key" in s &&
              typeof (s as Record<string, unknown>)["key"] === "string"
            ) {
              keys.push((s as Record<string, unknown>)["key"] as string);
            }
            if (
              "steps" in s &&
              Array.isArray((s as Record<string, unknown>)["steps"])
            ) {
              collectKeys((s as Record<string, unknown>)["steps"] as unknown[]);
            }
          }
        }
      }

      collectKeys(pipeline.steps);

      const seen = new Set<string>();
      const dupes: string[] = [];
      for (const k of keys) {
        if (seen.has(k)) dupes.push(k);
        seen.add(k);
      }

      expect(dupes).toEqual([]);
    });

    it("has valid depends_on references in full build", () => {
      const pipeline = buildPipeline(fullBuild());
      const allKeys = new Set<string>();
      const allDeps: string[] = [];

      function collect(steps: unknown[]) {
        for (const s of steps) {
          if (typeof s !== "object" || s === null) continue;
          const obj = s as Record<string, unknown>;
          if (typeof obj["key"] === "string") allKeys.add(obj["key"]);
          if (typeof obj["depends_on"] === "string")
            allDeps.push(obj["depends_on"]);
          if (Array.isArray(obj["depends_on"])) {
            for (const d of obj["depends_on"]) {
              if (typeof d === "string") allDeps.push(d);
            }
          }
          if (Array.isArray(obj["steps"])) collect(obj["steps"] as unknown[]);
        }
      }

      collect(pipeline.steps);

      const missing = allDeps.filter((d) => !allKeys.has(d));
      expect(missing).toEqual([]);
    });

    it("has valid depends_on references in full pull request build", () => {
      const pipeline = withBuildkitePullRequest("123", () =>
        buildPipeline(fullBuild()),
      );
      const allKeys = new Set<string>();
      const allDeps: string[] = [];

      collectKeysAndDeps(pipeline.steps, allKeys, allDeps);

      const missing = allDeps.filter((dep) => !allKeys.has(dep));
      expect(missing).toEqual([]);
    });

    it("all commands use dagger call or are known plain steps", () => {
      const pipeline = buildPipeline(fullBuild());
      /** Steps that intentionally run directly on the agent (no Dagger). */
      const PLAIN_STEP_KEYS = new Set([
        "lockfile-check",
        "quality-ratchet",
        "compliance-check",
        "env-var-names",
        "line-endings-check",
        "scout-test-template-check",
        "migration-guard",
        "dagger-hygiene",
        "merge-conflict-check",
        "large-file-check",
        "prettier",
        "shellcheck",
        "knip-check",
        "gitleaks-check",
        "suppression-check",
        "trivy-scan",
        "semgrep-scan",
        "tunnel-dns-coverage",
        "ios-native-deps-tasks-for-obsidian",
      ]);
      const nonDagger: string[] = [];

      function check(steps: unknown[]) {
        for (const s of steps) {
          if (typeof s !== "object" || s === null) continue;
          const obj = s as Record<string, unknown>;
          if (typeof obj["command"] === "string") {
            const cmd = obj["command"] as string;
            const key = obj["key"];
            // Dagger CLI invocations may have flags between `dagger` and `call`
            // (e.g. `dagger -m <module-ref> call`) so we look for both tokens
            // rather than the literal substring.
            const isDaggerCall =
              /(^|\s)dagger(\s+-[\w-]+(\s+\S+)?)*\s+call(\s|$)/.test(cmd);
            if (
              !isDaggerCall &&
              !cmd.includes("echo ") &&
              !cmd.includes("buildkite-agent") &&
              !(typeof key === "string" && PLAIN_STEP_KEYS.has(key))
            ) {
              nonDagger.push(`${key}: ${cmd}`);
            }
          }
          if (Array.isArray(obj["steps"])) check(obj["steps"] as unknown[]);
        }
      }

      check(pipeline.steps);
      expect(nonDagger).toEqual([]);
    });

    it("every K8s plugin has _EXPERIMENTAL_DAGGER_RUNNER_HOST", () => {
      const pipeline = buildPipeline(fullBuild());
      let pluginCount = 0;
      let hasRunnerHost = 0;

      function check(steps: unknown[]) {
        for (const s of steps) {
          if (typeof s !== "object" || s === null) continue;
          const obj = s as Record<string, unknown>;
          if (Array.isArray(obj["plugins"])) {
            for (const p of obj["plugins"]) {
              if (typeof p === "object" && p !== null && "kubernetes" in p) {
                pluginCount++;
                const json = JSON.stringify(p);
                if (json.includes("_EXPERIMENTAL_DAGGER_RUNNER_HOST")) {
                  hasRunnerHost++;
                }
              }
            }
          }
          if (Array.isArray(obj["steps"])) check(obj["steps"] as unknown[]);
        }
      }

      check(pipeline.steps);
      expect(pluginCount).toBeGreaterThan(0);
      expect(hasRunnerHost).toBe(pluginCount);
    });

    it("has unique step keys in release-please merge full build", () => {
      const affected = fullBuild();
      affected.releasePleaseMerge = true;
      const pipeline = buildPipeline(affected);
      const keys: string[] = [];

      function collectKeys(steps: unknown[]) {
        for (const s of steps) {
          if (typeof s === "object" && s !== null) {
            if (
              "key" in s &&
              typeof (s as Record<string, unknown>)["key"] === "string"
            ) {
              keys.push((s as Record<string, unknown>)["key"] as string);
            }
            if (
              "steps" in s &&
              Array.isArray((s as Record<string, unknown>)["steps"])
            ) {
              collectKeys((s as Record<string, unknown>)["steps"] as unknown[]);
            }
          }
        }
      }

      collectKeys(pipeline.steps);

      const seen = new Set<string>();
      const dupes: string[] = [];
      for (const k of keys) {
        if (seen.has(k)) dupes.push(k);
        seen.add(k);
      }

      expect(dupes).toEqual([]);
    });
  });

  describe("release-please merge", () => {
    function releasePleaseAffected(): AffectedPackages {
      const affected = fullBuild();
      affected.releasePleaseMerge = true;
      return affected;
    }

    it("generates both prod and dev npm publish bundle steps", () => {
      const pipeline = buildPipeline(releasePleaseAffected());
      const groups = pipeline.steps.filter(isGroup);
      const npmGroup = groups.find((g) => g.key === "publish-npm");
      expect(npmGroup).toBeDefined();
      const steps = npmGroup!.steps;
      // Every package is published from ONE bundled pod per mode; with
      // release-please merge, both prod and dev modes apply.
      expect(steps.length).toBe(2);
      expect(steps.some((s) => s.key === "npm-publish-all-prod")).toBe(true);
      expect(steps.some((s) => s.key === "npm-publish-all")).toBe(true);
    });

    it("prod bundle does not carry --dev-suffix flag", () => {
      const pipeline = buildPipeline(releasePleaseAffected());
      const groups = pipeline.steps.filter(isGroup);
      const npmGroup = groups.find((g) => g.key === "publish-npm");
      const prod = npmGroup!.steps.find(
        (s) => s.key === "npm-publish-all-prod",
      );
      expect(prod?.command).not.toContain("--dev-suffix");
    });

    it("dev bundle carries --dev-suffix flag", () => {
      const pipeline = buildPipeline(releasePleaseAffected());
      const groups = pipeline.steps.filter(isGroup);
      const npmGroup = groups.find((g) => g.key === "publish-npm");
      const dev = npmGroup!.steps.find((s) => s.key === "npm-publish-all");
      expect(dev?.command).toContain("--dev-suffix");
    });
  });

  describe("publish step mount paths", () => {
    it("bundle carries one --pkg-paths flag per package on-disk dir", () => {
      const pipeline = buildPipeline(fullBuild());
      const groups = pipeline.steps.filter(isGroup);
      const npmGroup = groups.find((g) => g.key === "publish-npm");
      expect(npmGroup).toBeDefined();
      const dev = npmGroup!.steps.find((s) => s.key === "npm-publish-all");
      expect(dev).toBeDefined();
      // Scoped/nested package: npm name and dir disagree, so --pkg-paths is
      // load-bearing for file: workspace dep resolution inside the container.
      expect(dev!.command).toContain("--pkg-paths homelab/src/helm-types");
      // Top-level packages keep their dir name as the pkg-path.
      expect(dev!.command).toContain("--pkg-paths webring");
      expect(dev!.command).toContain("--pkg-paths astro-opengraph-images");
    });
  });
});

describe("buildReleasePleaseSkipPipeline", () => {
  it("emits a single annotation step and no required gates", () => {
    const pipeline = buildReleasePleaseSkipPipeline();
    const steps = pipeline.steps.filter(isStep);
    expect(steps).toHaveLength(1);
    expect(steps[0]!.key).toBe("release-please-skip");
    expect(steps[0]!.command).toContain("buildkite-agent annotate");
    const keys = pipeline.steps.map((s) => ("key" in s ? s.key : undefined));
    // The skip pipeline must NOT post the required merge gates, so the PR stays
    // un-mergeable until a real build is requested on purpose.
    expect(keys).not.toContain("ci-complete");
    expect(keys).not.toContain("greptile-review");
  });
});
