package com.shepherdjerred.thestorm.rwfbots.domain.learning;

/** Named values; the language-neutral contract owns their order and normalization. */
public enum Feature {
  HP,
  ABSORPTION,
  VELOCITY_FORWARD,
  VELOCITY_SIDE,
  ON_GROUND,
  USING_ITEM,
  SLOT,
  HURT_RECENT,
  TARGET_VISIBLE,
  TARGET_KNOWN,
  TARGET_FORWARD,
  TARGET_SIDE,
  TARGET_UP,
  TARGET_DISTANCE,
  TARGET_VELOCITY_FORWARD,
  TARGET_VELOCITY_SIDE,
  TARGET_BEARING_SIN,
  TARGET_BEARING_COS,
  TARGET_AGE,
  TARGET_CONFIDENCE,
  RAY_0,
  RAY_1,
  RAY_2,
  RAY_3,
  RAY_4,
  RAY_5,
  RAY_6,
  RAY_7,
  KIT_TROOPER,
  KIT_LONGBOW,
  KIT_SHORTBOW,
  KIT_REWIND,
  AGGRESSION,
  TECHNIQUE
}
