#!/bin/bash

if ! command -v op &> /dev/null; then
  echo "Unable to find the 'op' command. Using value stored in VAULT_PASSWORD environment variable." 1>&2
  echo "$VAULT_PASSWORD"
else
  op get item "6gt4vffwijbu7msdaucbklqbnq" --fields password
fi
