import { afterEach, describe, expect, test } from "vitest";
import { StaticProvider } from "@shepherdjerred/feature-flags/providers/static.ts";
import { managedFlagInventory } from "@shepherdjerred/feature-flags/managed-flag-inventory.ts";
import { loadConfig } from "@shepherdjerred/streambot/config/index.ts";
import {
  DYNAMIC_FLAG_NAMES,
  initializeDynamicConfig,
  isDynamicConfigReady,
  playerCardEnabled,
  shutdownDynamicConfig,
  subtitlesEnabled,
} from "@shepherdjerred/streambot/config/dynamic.ts";

const DISABLED = { FEATURE_FLAGS_MODE: "disabled" } as const;
const SEED = { playerCardEnabled: true, subtitlesEnabled: true };
const VALID_ENVIRONMENT = {
  BOT_TOKEN: "bot-token",
  USER_TOKENS: "user-token",
  VIDEOS_DIR: "/videos",
  MEDIA_DIRS: "/media",
};

afterEach(async () => {
  await shutdownDynamicConfig();
});

describe("streambot dynamic config", () => {
  test("covers exactly the Streambot entries in the managed inventory", () => {
    const expected = managedFlagInventory.flags
      .filter((flag) => flag.owner === "streambot")
      .map((flag) => flag.key)
      .sort();
    expect([...DYNAMIC_FLAG_NAMES].sort()).toEqual(expected);
  });

  test("returns the caller's value before initialization", () => {
    // No window where a toggle flips because config was not ready. The call
    // sites pass what they already had.
    expect(isDynamicConfigReady()).toBe(false);
    expect(playerCardEnabled(true)).toBe(true);
    expect(subtitlesEnabled(false)).toBe(false);
  });

  test("a flag outranks the seeded value", async () => {
    await initializeDynamicConfig({
      environment: DISABLED,
      seed: SEED,
      startPolling: false,
      provider: new StaticProvider({ "player-card-enabled": false }),
    });
    expect(playerCardEnabled(true)).toBe(false);
  });

  test("an undefined flag leaves the seeded value in place", async () => {
    await initializeDynamicConfig({
      environment: DISABLED,
      seed: SEED,
      startPolling: false,
      provider: new StaticProvider({ "some-other-flag": true }),
    });
    expect(playerCardEnabled(true)).toBe(true);
    expect(subtitlesEnabled(false)).toBe(true);
  });

  test("env sits between the flag and the seed", async () => {
    await initializeDynamicConfig({
      environment: { ...DISABLED, SUBTITLES_ENABLED: "true" },
      seed: SEED,
      startPolling: false,
    });
    expect(subtitlesEnabled(false)).toBe(true);
  });

  test("the string false env value disables subtitles", async () => {
    await initializeDynamicConfig({
      environment: { ...DISABLED, SUBTITLES_ENABLED: "false" },
      seed: SEED,
      startPolling: false,
    });
    expect(subtitlesEnabled(true)).toBe(false);
  });

  test("shutdown returns readings to the caller's value", async () => {
    await initializeDynamicConfig({
      environment: DISABLED,
      seed: SEED,
      startPolling: false,
      provider: new StaticProvider({ "player-card-enabled": false }),
    });
    expect(playerCardEnabled(true)).toBe(false);
    await shutdownDynamicConfig();
    expect(playerCardEnabled(true)).toBe(true);
  });

  test("refreshes the safe tunables with typed flag values", async () => {
    const config = loadConfig(VALID_ENVIRONMENT);
    await initializeDynamicConfig({
      environment: DISABLED,
      seed: {
        ...SEED,
        subtitlesLanguages: config.subtitles.languages,
        subtitlesIncludeAutoGenerated: config.subtitles.includeAutoGenerated,
        reconnectEnabled: config.reconnect.enabled,
        reconnectDelaySeconds: config.reconnect.delaySeconds,
        reconnectMaxAttempts: config.reconnect.maxAttempts,
        playerCardTickMs: config.playerCard.tickMs,
        playerCardRepostAfterMessages: config.playerCard.repostAfterMessages,
        idleTimeoutSeconds: config.idleTimeoutSeconds,
        playlistLimit: config.playlistLimit,
      },
      config,
      startPolling: false,
      provider: new StaticProvider({
        "streambot-subtitle-languages": "en,es",
        "streambot-reconnect-delay-seconds": 7,
        "streambot-playlist-limit": 12,
      }),
    });
    expect(config.subtitles.languages).toEqual(["en", "es"]);
    expect(config.reconnect.delaySeconds).toBe(7);
    expect(config.playlistLimit).toBe(12);
  });

  test("keeps the seeded value when a flag has the wrong type", async () => {
    const config = loadConfig(VALID_ENVIRONMENT);
    await initializeDynamicConfig({
      environment: DISABLED,
      seed: {
        ...SEED,
        subtitlesLanguages: config.subtitles.languages,
        subtitlesIncludeAutoGenerated: config.subtitles.includeAutoGenerated,
        reconnectEnabled: config.reconnect.enabled,
        reconnectDelaySeconds: config.reconnect.delaySeconds,
        reconnectMaxAttempts: config.reconnect.maxAttempts,
        playerCardTickMs: config.playerCard.tickMs,
        playerCardRepostAfterMessages: config.playerCard.repostAfterMessages,
        idleTimeoutSeconds: config.idleTimeoutSeconds,
        playlistLimit: config.playlistLimit,
      },
      config,
      startPolling: false,
      provider: new StaticProvider({ "streambot-playlist-limit": "twelve" }),
    });
    expect(config.playlistLimit).toBe(100);
  });
});
