import { describe, expect, test } from "bun:test";
import {
  buildMenuOptions,
  decodeTrackRef,
  encodeTrackRef,
} from "@shepherdjerred/streambot/discord/subtitle-menu.ts";
import type { SubtitleTrackRef } from "@shepherdjerred/streambot/sources/source.ts";
import type { SubtitleCandidate } from "@shepherdjerred/streambot/sources/subtitles.ts";

describe("encodeTrackRef / decodeTrackRef", () => {
  const cases: SubtitleTrackRef[] = [
    { kind: "off" },
    { kind: "sidecar", file: "Movie.en.forced.srt" },
    { kind: "embedded", subtitleIndex: 2, codec: "subrip" },
    { kind: "ytdlp", lang: "en", autoGenerated: false },
    { kind: "ytdlp", lang: "en-orig", autoGenerated: true },
  ];

  for (const ref of cases) {
    test(`round-trips ${JSON.stringify(ref)}`, () => {
      expect(decodeTrackRef(encodeTrackRef(ref))).toEqual(ref);
    });
  }

  test("throws on an unrecognized encoded value", () => {
    expect(() => decodeTrackRef("bogus:x")).toThrow();
  });

  test("embedded values with a colon-containing codec still round-trip", () => {
    const ref: SubtitleTrackRef = {
      kind: "embedded",
      subtitleIndex: 0,
      codec: "weird:codec",
    };
    expect(decodeTrackRef(encodeTrackRef(ref))).toEqual(ref);
  });
});

describe("buildMenuOptions", () => {
  test("option values stay short even when the encoded trackRef is very long", () => {
    const longFile = `${"Movie.Extended.Directors.Cut.2023.2160p.UHD.BluRay.REMUX.HDR10Plus.DV.TrueHD.7.1.Atmos-".repeat(2)}en.forced.srt`;
    const candidate: SubtitleCandidate = {
      kind: "sidecar",
      file: longFile,
      lang: "en",
      modifier: "forced",
    };
    const { options, encodedRefs } = buildMenuOptions([candidate]);
    for (const option of options) {
      expect(option.value.length).toBeLessThanOrEqual(100);
      expect(option.label.length).toBeLessThanOrEqual(100);
    }
    // The real (long) encoded ref is still recoverable by index — nothing was lost/truncated.
    const picked = options[1];
    if (picked === undefined) throw new Error("expected a candidate option");
    const resolved = encodedRefs[Number(picked.value)];
    if (resolved === undefined) throw new Error("expected a resolved trackRef");
    expect(decodeTrackRef(resolved)).toEqual({
      kind: "sidecar",
      file: longFile,
    });
  });

  test("index 0 always resolves to the off trackRef", () => {
    const { options, encodedRefs } = buildMenuOptions([]);
    expect(options).toEqual([{ label: "Off (no subtitles)", value: "0" }]);
    expect(decodeTrackRef(encodedRefs[0] ?? "")).toEqual({ kind: "off" });
  });

  test("truncates to 24 candidates and reports the hidden count", () => {
    const many: SubtitleCandidate[] = Array.from({ length: 30 }, (_, i) => ({
      kind: "ytdlp",
      lang: `lang${String(i)}`,
      name: null,
      autoGenerated: false,
      modifier: null,
    }));
    const { options, hiddenCount } = buildMenuOptions(many);
    // 24 candidates + the fixed "Off" option.
    expect(options).toHaveLength(25);
    expect(hiddenCount).toBe(6);
  });
});
