import { describe, expect, test } from "bun:test";
import {
  decodeTrackRef,
  encodeTrackRef,
} from "@shepherdjerred/streambot/discord/subtitle-menu.ts";
import type { SubtitleTrackRef } from "@shepherdjerred/streambot/sources/source.ts";

describe("encodeTrackRef / decodeTrackRef", () => {
  const cases: SubtitleTrackRef[] = [
    { kind: "off" },
    { kind: "sidecar", file: "Movie.en.forced.srt" },
    { kind: "embedded", subtitleIndex: 2, codec: "subrip" },
    { kind: "ytdlp", lang: "en", autoGenerated: false },
    { kind: "ytdlp", lang: "en-orig", autoGenerated: true },
  ];

  for (const ref of cases) {
    test(`round-trips ${JSON.stringify(ref)}`, () => {
      expect(decodeTrackRef(encodeTrackRef(ref))).toEqual(ref);
    });
  }

  test("throws on an unrecognized encoded value", () => {
    expect(() => decodeTrackRef("bogus:x")).toThrow();
  });

  test("embedded values with a colon-containing codec still round-trip", () => {
    const ref: SubtitleTrackRef = {
      kind: "embedded",
      subtitleIndex: 0,
      codec: "weird:codec",
    };
    expect(decodeTrackRef(encodeTrackRef(ref))).toEqual(ref);
  });
});
