export const GLITTER_CORPUS_STORAGE_ENV = [
  "GLITTER_CORPUS_S3_ENDPOINT",
  "GLITTER_CORPUS_S3_BUCKET",
  "GLITTER_CORPUS_S3_ACCESS_KEY_ID",
  "GLITTER_CORPUS_S3_SECRET_ACCESS_KEY",
  "GLITTER_CORPUS_R2_ENDPOINT",
  "GLITTER_CORPUS_R2_BUCKET",
  "GLITTER_CORPUS_R2_ACCESS_KEY_ID",
  "GLITTER_CORPUS_R2_SECRET_ACCESS_KEY",
] as const;
