import { Context } from "@temporalio/activity";
import { simpleGit } from "simple-git";
import { z } from "zod";
import { createAlertmanagerPoster } from "#lib/alertmanager.ts";
import { createGitHubAppInstallationToken } from "#lib/github-app-token.ts";
import {
  buildCatalogAlerts,
  type CatalogSyncOutcome,
} from "#shared/llm-catalog-alert.ts";
import { parsePorcelainPaths } from "#shared/porcelain.ts";
import { rootInstallWithoutHooks } from "./bot-clone.ts";
import { runCommand } from "./data-dragon-shell.ts";
import { discardFormattingOnlyChanges } from "./scout-generated-preflight.ts";
import { openSeasonRefreshPr } from "./scout-season-refresh-git.ts";

const REPO_URL = "https://github.com/shepherdjerred/monorepo.git";
const REPO_SLUG = "shepherdjerred/monorepo";
const MAIN_BRANCH = "main";
const CATALOG_FILE = "packages/llm-models/src/catalog.json";

/** Mirrors `SyncReport` in packages/llm-models/scripts/sync-from-upstreams.ts. */
const SyncReportSchema = z.object({
  applied: z.array(z.string()),
  withheld: z.array(z.string()),
  models: z.record(
    z.string(),
    z.object({
      withheld: z.record(z.string(), z.string()),
      measured: z.array(z.string()),
      unmeasured: z.array(z.string()),
      retired: z.array(z.string()),
    }),
  ),
  overlayOnly: z.array(z.string()),
  notChecked: z.array(z.string()),
});

/**
 * Retry-stable branch name for the refresh PR.
 *
 * `openSeasonRefreshPr` avoids duplicate PRs by reusing an open PR whose head
 * is this branch, so the branch is the idempotency key for the whole
 * PR-creating half of this activity — it must never be derived from anything
 * that varies per attempt. A per-attempt UUID silently defeats that reuse: any
 * failure after the PR is created (the Alertmanager publish, a worker death
 * before Temporal records completion) retries the activity under a fresh
 * branch and opens a second catalog PR.
 *
 * The proposed catalog content is the key. A run id is retry-stable but changes
 * every week, so an unmerged proposal regenerated by the next scheduled run
 * landed on a new branch and opened a second PR for the identical change —
 * `openSeasonRefreshPr` only reuses a PR whose head is the branch it was given.
 * Hashing the content instead gives the branch the lifetime the proposal has:
 * the same proposed catalog reuses its open PR however many weeks it sits
 * unreviewed, and a genuinely different proposal gets its own PR rather than
 * force-pushing over one an operator is part-way through adjudicating.
 *
 * This is the same content-derived key `data-dragon.ts` uses.
 */
export function catalogRefreshBranch(catalogJson: string): string {
  const digest = new Bun.CryptoHasher("sha256")
    .update(catalogJson)
    .digest("hex");
  return `chore/llm-catalog-refresh-${digest.slice(0, 8)}`;
}

export type LlmCatalogRefreshResult = {
  changedFiles: string[];
  branchName: string | undefined;
  commitHash: string | undefined;
  prUrl: string | undefined;
  /** Edits the plausibility guards withheld — each needs a human to adjudicate. */
  withheld: string[];
  outcome: "pr-created" | "no-diff" | "withheld-only";
};

/**
 * Publish this run's withheld state — firing while edits await adjudication,
 * resolving as soon as a run finds none. Which of the two it is depends on the
 * report alone, never on whether the catalog changed: conditioning the resolve
 * on the diff would leave an already-remediated alert firing for its full
 * eight-day lifetime.
 *
 * Every `return` publishes exactly once, and only once its own `prUrl` is
 * settled. Publishing earlier from a single site would be more obviously
 * unskippable, but it can only name a PR it has not yet opened, and a failure
 * in the steps between would strand an eight-day alert pointing at nothing.
 * A run that dies before any exit publishes nothing and fails the activity,
 * which `temporal-failure-watch` turns into its own occurrence.
 */
async function publishWithheldAlerts(
  outcome: CatalogSyncOutcome,
): Promise<void> {
  // One occurrence per model the run actually measured. A model missing from
  // both upstreams gets none, so its previous occurrence stands rather than
  // being closed on absent evidence — and, unlike a run-wide gate, it cannot
  // hold every other model's resolution hostage while it sits there.
  const alerts = buildCatalogAlerts(outcome, new Date());
  if (alerts.length === 0) {
    return;
  }
  const alertmanagerUrl = Bun.env["ALERTMANAGER_URL"];
  if (alertmanagerUrl === undefined || alertmanagerUrl === "") {
    throw new Error(
      "ALERTMANAGER_URL is required to report withheld LLM catalog edits",
    );
  }
  await createAlertmanagerPoster(alertmanagerUrl)(alerts);
}

export type LlmCatalogRefreshActivities = typeof llmCatalogRefreshActivities;

export const llmCatalogRefreshActivities = {
  /**
   * Run the deterministic catalog cross-check (packages/llm-models/scripts/
   * sync-from-upstreams.ts) against models.dev, LiteLLM, and OpenRouter and,
   * if our metadata drifted, open a PR. No LLM, no scraping.
   */
  async refreshLlmCatalog(): Promise<LlmCatalogRefreshResult> {
    const start = Date.now();
    // Scratch directory only. Deliberately per-attempt so a retry cannot trip
    // over a previous attempt's half-cleaned clone — never reuse it for the
    // branch name, which must be stable across attempts (catalogRefreshBranch).
    const id = crypto.randomUUID();
    const tempDir = `/tmp/llm-catalog-refresh-${id}`;
    const repoDir = `${tempDir}/monorepo`;
    const catalogDir = `${repoDir}/packages/llm-models`;

    // Heartbeat every 10s while the long subprocesses (clone, install, sync) run;
    // pairs with the activity's heartbeatTimeout in workflows/llm-catalog-refresh.ts.
    const heartbeat = setInterval(() => {
      Context.current().heartbeat({
        phase: "refreshLlmCatalog",
        elapsedMs: Date.now() - start,
      });
    }, 10_000);

    try {
      const { token: githubToken } = await createGitHubAppInstallationToken();
      await runCommand(["mkdir", "-p", tempDir], { cwd: "/tmp" });
      await simpleGit().clone(REPO_URL, repoDir, [
        "--branch",
        MAIN_BRANCH,
        "--single-branch",
        "--filter=blob:none",
      ]);

      // One hook-free root install for the whole activity: it covers the
      // catalog package's own deps (zod, for the sync script) and the repo's
      // pinned prettier used further down. Bot clones must go through this
      // helper rather than a bare `bun install` — it isolates the per-run Bun
      // cache, retries a transient install, suppresses lifecycle scripts so
      // the dev pre-commit suite is never armed inside the worker pod, and is
      // the path `scripts/rehearse-bot-clone.ts` exercises in CI.
      await rootInstallWithoutHooks(repoDir);
      const reportJsonPath = `${tempDir}/sync-report.json`;
      const report = await runCommand(
        [
          "bun",
          "run",
          "scripts/sync-from-upstreams.ts",
          "--report-json",
          reportJsonPath,
        ],
        { cwd: catalogDir },
      );
      const summary = SyncReportSchema.parse(
        await Bun.file(reportJsonPath).json(),
      );
      // Every exit goes through here. A withheld edit never reaches the
      // catalog, so a run whose edits were all refused is otherwise
      // indistinguishable from a clean no-op.
      const finish = async (
        result: LlmCatalogRefreshResult,
      ): Promise<LlmCatalogRefreshResult> => {
        await publishWithheldAlerts({
          applied: summary.applied,
          models: summary.models,
          prUrl: result.prUrl,
        });
        return result;
      };

      const noDiff = (): LlmCatalogRefreshResult => ({
        changedFiles: [],
        branchName: undefined,
        commitHash: undefined,
        prUrl: undefined,
        withheld: summary.withheld,
        outcome: summary.withheld.length === 0 ? "no-diff" : "withheld-only",
      });

      // trimStdout: false so porcelain v1's leading-space status code isn't
      // stripped (see parsePorcelainPaths in #shared/porcelain.ts).
      let dirty = parsePorcelainPaths(
        await runCommand(["git", "status", "--porcelain", "--", CATALOG_FILE], {
          cwd: repoDir,
          trimStdout: false,
        }),
      );
      await discardFormattingOnlyChanges({
        repoDir,
        changedFiles: dirty,
        component: "llm-catalog-refresh",
      });
      dirty = parsePorcelainPaths(
        await runCommand(["git", "status", "--porcelain", "--", CATALOG_FILE], {
          cwd: repoDir,
          trimStdout: false,
        }),
      );
      if (dirty.length === 0) {
        return await finish(noDiff());
      }

      // Format the rewritten JSON with the repo's pinned prettier so the PR
      // passes the prettier gate (the sync writes plain JSON.stringify output).
      // The root install above already provisioned it.
      await runCommand(["bunx", "prettier", "--write", CATALOG_FILE], {
        cwd: repoDir,
      });

      const files = parsePorcelainPaths(
        await runCommand(["git", "status", "--porcelain", "--", CATALOG_FILE], {
          cwd: repoDir,
          trimStdout: false,
        }),
      );
      if (files.length === 0) {
        return await finish(noDiff());
      }

      // Hashed after the prettier pass so the key covers the exact bytes the
      // commit will carry; formatting-only differences must not fork a branch.
      const branch = catalogRefreshBranch(
        await Bun.file(`${repoDir}/${CATALOG_FILE}`).text(),
      );
      const title =
        "chore(llm-models): refresh model catalog pricing from upstreams";
      const body = [
        "Automated LLM model-catalog cross-check from Temporal",
        "(`llm-catalog-refresh-weekly` schedule).",
        "",
        "`packages/llm-models/scripts/sync-from-upstreams.ts` compared our catalog",
        "against models.dev, LiteLLM, and OpenRouter and applied metadata drift.",
        "Review the numbers below against the official provider pricing pages.",
        "",
        "```",
        report.trim(),
        "```",
      ].join("\n");

      const { commitHash, prUrl } = await openSeasonRefreshPr({
        repoDir,
        tempDir,
        branch,
        title,
        body,
        files,
        ghToken: githubToken,
        repoSlug: REPO_SLUG,
        mainBranch: MAIN_BRANCH,
      });

      return await finish({
        changedFiles: files,
        branchName: branch,
        commitHash,
        prUrl,
        withheld: summary.withheld,
        outcome: "pr-created",
      });
    } finally {
      clearInterval(heartbeat);
      try {
        await runCommand(["rm", "-rf", tempDir], { cwd: "/tmp" });
      } catch {
        // best-effort cleanup
      }
    }
  },
};
