import { Context } from "@temporalio/activity";
import { simpleGit } from "simple-git";
import { createGitHubAppInstallationToken } from "#lib/github-app-token.ts";
import { runCommand } from "./data-dragon-shell.ts";
import { openSeasonRefreshPr } from "./scout-season-refresh-git.ts";

const REPO_URL = "https://github.com/shepherdjerred/monorepo.git";
const REPO_SLUG = "shepherdjerred/monorepo";
const MAIN_BRANCH = "main";

// The three READMEs whose embedded `[[[cog]]]` project-listing tables are
// regenerated by `cog -r`. Run from the repo root; cog derives each listing's
// source directory from the file it is rewriting.
const COG_TARGETS = ["README.md", "practice/README.md", "archive/README.md"];

export type ReadmeRefreshResult = {
  changedFiles: string[];
  branchName: string | undefined;
  commitHash: string | undefined;
  prUrl: string | undefined;
  outcome: "pr-created" | "no-diff";
};

export type ReadmeRefreshActivities = typeof readmeRefreshActivities;

// cog only ever rewrites the three target READMEs and writes new per-package
// `_summary.md` caches. Any other dirty path is unrelated to this job and must
// not be staged.
function isReadmeRefreshPath(path: string): boolean {
  return COG_TARGETS.includes(path) || path.endsWith("/_summary.md");
}

// Parse `git status --porcelain` (v1). Columns 0-1 are the status code and
// column 2 is a space, so the path starts at index 3. We deliberately do NOT
// trim the leading status before slicing — an unstaged-only change is ` M path`
// and a left-trim would eat into the filename.
function parsePorcelainPaths(status: string): string[] {
  return status
    .split("\n")
    .filter((line) => line.length > 3)
    .map((line) => line.slice(3).trim());
}

export const readmeRefreshActivities = {
  /**
   * Regenerate the cog-managed project listings in the repo's READMEs and, if
   * they drifted, open a PR. Deterministic-ish: the listings are derived from
   * the package tree + committed `_summary.md` caches, so a steady-state run
   * makes no Codex calls and opens no PR. Mirrors the helm-types-refresh job.
   */
  async refreshReadmes(): Promise<ReadmeRefreshResult> {
    const start = Date.now();
    const id = crypto.randomUUID();
    const tempDir = `/tmp/readme-refresh-${id}`;
    const repoDir = `${tempDir}/monorepo`;

    // Heartbeat every 10s while the long subprocesses (clone, cog regeneration,
    // any Codex calls) run. Pairs with the activity's heartbeatTimeout in
    // workflows/readme-refresh.ts.
    const heartbeat = setInterval(() => {
      Context.current().heartbeat({
        phase: "refreshReadmes",
        elapsedMs: Date.now() - start,
      });
    }, 10_000);

    try {
      const { token: githubToken } = await createGitHubAppInstallationToken();
      await runCommand(["mkdir", "-p", tempDir], { cwd: "/tmp" });

      // Full commit history (blobless): the cog blocks sort packages by their
      // first-commit date via `git log --diff-filter=A --reverse`, which a
      // shallow clone would break. `--filter=blob:none` keeps the clone cheap
      // while retaining the full commit graph.
      await simpleGit().clone(REPO_URL, repoDir, [
        "--branch",
        MAIN_BRANCH,
        "--single-branch",
        "--filter=blob:none",
      ]);

      // Regenerate the embedded listings. cog rewrites the three READMEs in
      // place and writes a `_summary.md` for any package missing one (calling
      // the Codex CLI via the pod's OPENAI_API_KEY). Existing summaries are
      // reused as a cache, so a steady-state run makes no Codex calls.
      await runCommand(["cog", "-r", ...COG_TARGETS], { cwd: repoDir });

      const status = await runCommand(["git", "status", "--porcelain"], {
        cwd: repoDir,
      });
      const files = parsePorcelainPaths(status).filter((path) =>
        isReadmeRefreshPath(path),
      );

      if (files.length === 0) {
        return {
          changedFiles: [],
          branchName: undefined,
          commitHash: undefined,
          prUrl: undefined,
          outcome: "no-diff",
        };
      }

      const branch = `chore/readme-refresh-${id.slice(0, 8)}`;
      const title = "docs(root): refresh README project listings";
      const body = [
        "Automated README project-listing refresh from Temporal",
        "(`readme-refresh-weekly` schedule).",
        "",
        "Regenerated the cog-managed project tables in `README.md`,",
        "`practice/README.md`, and `archive/README.md` (plus any new per-package",
        "`_summary.md`). The committed listings had drifted.",
        "",
        `Changed files: ${String(files.length)}`,
        "",
        ...files.slice(0, 30).map((f) => `- ${f}`),
        files.length > 30 ? `- …and ${String(files.length - 30)} more` : "",
      ]
        .filter((line) => line !== "")
        .join("\n");

      const { commitHash, prUrl } = await openSeasonRefreshPr({
        repoDir,
        tempDir,
        branch,
        title,
        body,
        files,
        ghToken: githubToken,
        repoSlug: REPO_SLUG,
        mainBranch: MAIN_BRANCH,
      });

      return {
        changedFiles: files,
        branchName: branch,
        commitHash,
        prUrl,
        outcome: "pr-created",
      };
    } finally {
      clearInterval(heartbeat);
      try {
        await runCommand(["rm", "-rf", tempDir], { cwd: "/tmp" });
      } catch {
        // best-effort cleanup
      }
    }
  },
};
