[general]
botToken = "${CFG_DISCORD_BOT_TOKEN}"
botChannel = "${CFG_DISCORD_CHANNEL_ID}"
botStatusName = "%online% players on RLCraft"
botStatusType = "PLAYING"
streamingURL = ""
enableUpdateChecker = false
allowConfigMigration = false
parseMentionsIngame = true
ignoreFileSource = false

[commands]
adminRoleIDs = []
customCommands = []
senderUUID = "8d8982a5-8cf9-4604-8feb-3dd5ee1f83a3"
helpCmdEnabled = false
listCmdEnabled = false
uptimeCmdEnabled = false
showUnknownCommandMessage = false
showUnknownCommandEverywhere = false

[messages]
language = "local"
convertCodes = true
formattingCodesToDiscord = true
sendOnSayCommand = false
sendOnMeCommand = false
sayCommandIgnoredPrefix = ""
sendDeathMessagesForTamedAnimals = false

[advanced]
serverChannelID = "default"
deathsChannelID = "default"
chatOutputChannelID = "default"
chatInputChannelID = "default"
baseAPIUrl = "https://discord.com"

[forgeSpecific]
IMC_modIdBlacklist = []
sendItemInfo = false

[linking]
unlinkOnLeave = false
enableLinking = false
linkedRoleID = ""
whitelistMode = false
requiredRoles = []
settingsBlacklist = []

[linking.personalSettingsDefaults]
default_useDiscordNameInChannel = true
default_ignoreReactions = false
default_pingSound = true

[webhook]
enable = false
serverAvatarURL = ""
serverName = "RLCraft"
playerAvatarURL = ""
webhookName = ""

[ingameCommand]
enabled = false
message = ""
hoverMessage = ""
inviteURL = ""

[commandLog]
channelID = "0"
message = ""
ignoredCommands = []

[votifier]
enabled = false
votifierChannelID = "0"
message = ""
name = ""
avatarURL = ""

[dynmap]
dcMessage = ""
dynmapChannelID = "0"
name = ""
avatarURL = ""
webName = ""
unnamed = ""

[bstats]
sendAddonStats = false

[bungee]
isBehindBungee = false
