#!/usr/bin/env bun

import {
  GenerationStateDocumentSchema,
  LoreDocumentSchema,
  PeopleDocumentSchema,
  RelationshipsDocumentSchema,
  StyleCardsDocumentSchema,
} from "#src/schema.ts";

const packageRoot = new URL("..", import.meta.url);
const dataRoot = new URL("data/", packageRoot);
const styleCardsRoot = new URL("style-cards/", dataRoot);

async function readJson(url: URL): Promise<unknown> {
  return await Bun.file(url).json();
}

async function main(): Promise<void> {
  const people = PeopleDocumentSchema.parse(
    await readJson(new URL("people.json", dataRoot)),
  );
  const relationships = RelationshipsDocumentSchema.parse(
    await readJson(new URL("relationships.json", dataRoot)),
  );
  const generationState = GenerationStateDocumentSchema.parse(
    await readJson(new URL("generation-state.json", dataRoot)),
  );
  LoreDocumentSchema.parse(await readJson(new URL("lore.json", dataRoot)));

  const styleCardGlob = new Bun.Glob("*_style.json");
  const rawStyleCards: Record<string, unknown> = {};
  for await (const filename of styleCardGlob.scan({
    cwd: styleCardsRoot.pathname,
    absolute: false,
  })) {
    const personId = filename.replace(/_style\.json$/u, "");
    rawStyleCards[personId] = await readJson(new URL(filename, styleCardsRoot));
  }
  const styleCards = StyleCardsDocumentSchema.parse(rawStyleCards);

  const knownPeople = new Set(people.people.map((person) => person.id));
  for (const event of relationships.events) {
    if (!knownPeople.has(event.sourceId) || !knownPeople.has(event.targetId)) {
      throw new Error(`relationship ${event.id} references an unknown person`);
    }
  }
  for (const personId of Object.keys(styleCards)) {
    if (!knownPeople.has(personId)) {
      throw new Error(`style card references an unknown person: ${personId}`);
    }
  }
  for (const state of generationState.people) {
    if (!knownPeople.has(state.personId)) {
      throw new Error(
        `generation state references an unknown person: ${state.personId}`,
      );
    }
  }

  const cardImports = Object.keys(styleCards)
    .sort()
    .map(
      (personId) =>
        `import ${personId}Card from "#data/style-cards/${personId}_style.json" with { type: "json" };`,
    )
    .join("\n");
  const cardEntries = Object.keys(styleCards)
    .sort()
    .map((personId) => `  ${personId}: ${personId}Card,`)
    .join("\n");
  const generated = `// Generated by scripts/generate.ts. Do not edit directly.
import generationStateJson from "#data/generation-state.json" with { type: "json" };
import loreJson from "#data/lore.json" with { type: "json" };
import peopleJson from "#data/people.json" with { type: "json" };
import relationshipsJson from "#data/relationships.json" with { type: "json" };
${cardImports}
import {
  GenerationStateDocumentSchema,
  LoreDocumentSchema,
  PeopleDocumentSchema,
  RelationshipsDocumentSchema,
  StyleCardsDocumentSchema,
} from "#src/schema.ts";

export const peopleDocument = PeopleDocumentSchema.parse(peopleJson);
export const relationshipsDocument =
  RelationshipsDocumentSchema.parse(relationshipsJson);
export const generationStateDocument =
  GenerationStateDocumentSchema.parse(generationStateJson);
export const loreDocument = LoreDocumentSchema.parse(loreJson);
export const styleCards = StyleCardsDocumentSchema.parse({
${cardEntries}
});
`;

  await Bun.write(new URL("src/generated-data.ts", packageRoot), generated);
}

void main();
