#!/usr/bin/env bun
/**
 * Generate .dagger/src/deps.ts from workspace package.json files.
 *
 * Reads each package's package.json, finds workspace dependencies
 * (file: or workspace: protocol), and outputs the WORKSPACE_DEPS map.
 *
 * Usage:
 *   bun run scripts/generate-deps.ts          # overwrite deps.ts
 *   bun run scripts/generate-deps.ts --check  # exit 1 if deps.ts is stale
 */
import { readdir, readFile } from "node:fs/promises";
import { join, relative } from "node:path";

const ROOT = import.meta.dir + "/..";
const DEPS_FILE = join(ROOT, ".dagger/src/deps.ts");
const PACKAGES_DIR = join(ROOT, "packages");

interface PkgInfo {
  name: string;
  path: string;
  workspaceDeps: string[];
}

/** Recursively find package.json files under packages/ */
async function findPackageJsons(dir: string, depth = 0): Promise<string[]> {
  const results: string[] = [];
  const pkgJson = join(dir, "package.json");
  try {
    await readFile(pkgJson, "utf8");
    results.push(pkgJson);
  } catch {
    // no package.json here
  }

  if (depth < 3) {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (
        entry.isDirectory() &&
        !["node_modules", "dist", "build", ".git", "target", "archive"].includes(entry.name)
      ) {
        results.push(...(await findPackageJsons(join(dir, entry.name), depth + 1)));
      }
    }
  }
  return results;
}

/** Extract workspace deps from a package.json */
function extractWorkspaceDeps(
  pkg: Record<string, unknown>,
  allPackageNames: Map<string, string>,
): string[] {
  const deps: string[] = [];
  for (const section of ["dependencies", "devDependencies"]) {
    const depsObj = pkg[section];
    if (typeof depsObj !== "object" || depsObj === null) continue;
    for (const [name, version] of Object.entries(depsObj as Record<string, string>)) {
      if (
        typeof version === "string" &&
        (version.startsWith("workspace:") || version.startsWith("file:"))
      ) {
        // Map scoped package name to directory name
        const shortName = name.startsWith("@") ? name.split("/").pop() : name;
        if (shortName && allPackageNames.has(shortName)) {
          deps.push(allPackageNames.get(shortName)!);
        } else if (shortName && allPackageNames.has(name)) {
          deps.push(allPackageNames.get(name)!);
        }
      }
    }
  }
  return [...new Set(deps)].sort();
}

async function main() {
  const checkMode = process.argv.includes("--check");

  // Find all package.json files
  const pkgJsonPaths = await findPackageJsons(PACKAGES_DIR);

  // Build name → relative path map
  const nameToPath = new Map<string, string>();
  const packages: PkgInfo[] = [];

  for (const pkgJsonPath of pkgJsonPaths) {
    const content = JSON.parse(await readFile(pkgJsonPath, "utf8"));
    const relPath = relative(join(ROOT, "packages"), join(pkgJsonPath, ".."));

    // Use the package name (without scope) as the key
    const name: string = content.name ?? relPath;
    const shortName = name.startsWith("@") ? name.split("/").pop()! : name;

    nameToPath.set(shortName, relPath);
    nameToPath.set(name, relPath);
    packages.push({ name: shortName, path: relPath, workspaceDeps: [] });
  }

  // Resolve workspace deps for each package
  for (const pkg of packages) {
    const pkgJsonPath = join(PACKAGES_DIR, pkg.path, "package.json");
    const content = JSON.parse(await readFile(pkgJsonPath, "utf8"));
    pkg.workspaceDeps = extractWorkspaceDeps(content, nameToPath);
  }

  // Filter to packages that are in the current WORKSPACE_DEPS (i.e., ones Dagger cares about)
  // Read the current file to preserve the same set of packages
  const currentContent = await readFile(DEPS_FILE, "utf8");
  const currentKeys = [
    ...currentContent.matchAll(/^\s+"([^"]+)":\s*\[/gm),
  ].map((m) => m[1]);

  // Build BUILD_TIME_DEPS from current file (preserve manually maintained order)
  const buildTimeDepsMatch = currentContent.match(
    /BUILD_TIME_DEPS:\s*string\[\]\s*=\s*\[([\s\S]*?)\];/,
  );
  const buildTimeDeps = buildTimeDepsMatch
    ? [...buildTimeDepsMatch[1].matchAll(/"([^"]+)"/g)].map((m) => m[1])
    : [];

  // Generate the new deps.ts content
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * Workspace dependency map: for each package, the list of other packages`);
  lines.push(` * that must be present in the container for file: deps to resolve.`);
  lines.push(` *`);
  lines.push(` * Used by both the Dagger module (to mount deps) and the CI pipeline`);
  lines.push(` * generator (to produce --dep-names / --dep-dirs flags).`);
  lines.push(` *`);
  lines.push(` * AUTO-GENERATED by scripts/generate-deps.ts — do not edit manually.`);
  lines.push(` */`);
  lines.push(`export const WORKSPACE_DEPS: Record<string, string[]> = {`);

  for (const key of currentKeys) {
    const pkg = packages.find((p) => p.path === key || p.name === key);
    const deps = pkg ? pkg.workspaceDeps : [];
    const depsStr = deps.length > 0 ? deps.map((d) => `"${d}"`).join(", ") : "";
    lines.push(`  "${key}": [${depsStr}],`);
  }

  lines.push(`};`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Packages that must have \`bun run build\` executed before dependents`);
  lines.push(` * can use them (they export types/assets via dist/).`);
  lines.push(` * Order matters: build in this order.`);
  lines.push(` */`);
  lines.push(
    `export const BUILD_TIME_DEPS: string[] = [${buildTimeDeps.map((d) => `"${d}"`).join(", ")}];`,
  );
  lines.push(``);

  const newContent = lines.join("\n");

  if (checkMode) {
    if (currentContent.trim() !== newContent.trim()) {
      console.error("deps.ts is stale. Run: bun run scripts/generate-deps.ts");
      process.exit(1);
    }
    console.log("deps.ts is up to date");
  } else {
    await Bun.write(DEPS_FILE, newContent);
    console.log("Generated .dagger/src/deps.ts");
  }
}

await main();
