#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/setup-tools.sh"

install_base
install_uv
install_gh
install_bun

# renovate: datasource=pypi depName=cogapp
COGAPP_VERSION="3.6.0"
echo "--- :python: Installing cogapp ${COGAPP_VERSION}"
uv tool install "cogapp==${COGAPP_VERSION}"
export PATH="$HOME/.local/bin:$PATH"

# Validate required env vars
: "${GH_TOKEN:?Required}"
: "${BUILDKITE_BRANCH:?Required}"

REPO="shepherdjerred/monorepo"
BASE_BRANCH="${BUILDKITE_BRANCH}"
BRANCH="auto/update-readmes"

echo "+++ :books: Updating READMEs"

git config --global user.name "github-actions[bot]"
git config --global user.email "github-actions[bot]@users.noreply.github.com"
git config --global core.hooksPath /dev/null

GIT_ASKPASS_SCRIPT="$(mktemp)"
printf '#!/bin/sh\necho "%s"\n' "${GH_TOKEN}" > "${GIT_ASKPASS_SCRIPT}"
chmod +x "${GIT_ASKPASS_SCRIPT}"
export GIT_ASKPASS="${GIT_ASKPASS_SCRIPT}"
git remote set-url origin "https://git@github.com/${REPO}.git"

# Regenerate README content (cog blocks call Codex CLI).
# Existing _summary.md files are reused as cache; Codex is only called for missing ones.
cog -r README.md practice/README.md archive/README.md

if git diff --quiet; then
  echo "No README changes detected."
  exit 0
fi

git checkout -B "${BRANCH}"
git add README.md practice/README.md archive/README.md

# Also add any generated summary files
while IFS= read -r summary_file; do
  [ -n "$summary_file" ] && git add "$summary_file"
done < <(git ls-files -m -o --exclude-standard -- "packages/*/_summary.md" "practice/*/_summary.md" "archive/*/_summary.md")

LEFTHOOK=0 HUSKY=0 git commit -m "docs: auto-update READMEs"
git push --force origin "${BRANCH}"

OPEN_PR_COUNT="$(gh pr list --repo "${REPO}" --state open --head "${BRANCH}" --json number --jq 'length')"
if [ "$OPEN_PR_COUNT" -eq 0 ]; then
  gh pr create \
    --repo "${REPO}" \
    --title "docs: auto-update READMEs" \
    --body "Automated README updates generated by cog." \
    --head "${BRANCH}" \
    --base "${BASE_BRANCH}"
else
  echo "Open PR already exists for ${BRANCH}"
fi
