import {
  Cpu,
  Deployment,
  DeploymentStrategy,
  EnvValue,
  type ISecret,
  Probe,
  Protocol,
  Secret,
  Service,
  Volume,
} from "cdk8s-plus-31";
import type { Chart } from "cdk8s";
import { Duration, Size } from "cdk8s";
import {
  withCommonProps,
  setRevisionHistoryLimit,
} from "@shepherdjerred/homelab/cdk8s/src/misc/common.ts";
import { createServiceMonitor } from "@shepherdjerred/homelab/cdk8s/src/misc/service-monitor.ts";
import { OnePasswordItem } from "@shepherdjerred/homelab/cdk8s/generated/imports/onepassword.com.ts";
import versions, {
  postgresImageDigests,
} from "@shepherdjerred/homelab/cdk8s/src/versions.ts";
import type { Stage } from "@shepherdjerred/homelab/cdk8s/src/cdk8s-charts/scout.ts";
import { match } from "ts-pattern";
import { ZfsNvmeVolume } from "@shepherdjerred/homelab/cdk8s/src/misc/zfs-nvme-volume.ts";
import { llmArchiveEnvVars } from "@shepherdjerred/homelab/cdk8s/src/misc/llm-archive-env.ts";
import {
  applyZfsVolumeSelinuxRelabeling,
  zfsVolumeSelinuxLevels,
} from "@shepherdjerred/homelab/cdk8s/src/misc/selinux.ts";
import { scoutAnalyticsConfiguration } from "@shepherdjerred/homelab/cdk8s/src/resources/scout/analytics.ts";
import { scoutImageUsesPostgres } from "@shepherdjerred/homelab/cdk8s/src/release-configuration.ts";
import { vaultItemPath } from "@shepherdjerred/homelab/cdk8s/src/misc/onepassword-vault.ts";

function requiredWeeklyParlaySecret(secret: ISecret | undefined): ISecret {
  if (secret === undefined) {
    throw new Error("Beta Scout requires its weekly parlay secret.");
  }
  return secret;
}

export function createScoutDeployment(chart: Chart, stage: Stage) {
  const analytics = scoutAnalyticsConfiguration(stage);
  const deployment = new Deployment(chart, "scout-backend", {
    replicas: 1,
    strategy: DeploymentStrategy.recreate(),
    progressDeadline: Duration.seconds(2400),
    terminationGracePeriod: Duration.seconds(45),
    securityContext: {},
    // Stable pod label so the namespace NetworkPolicies select only the
    // backend — a bare podSelector would also catch the Patroni/Spilo
    // postgres pods and cut them off from the Kubernetes API.
    podMetadata: {
      labels: { app: "scout-backend" },
    },
    metadata: {
      annotations: {
        "ignore-check.kube-linter.io/run-as-non-root":
          "Scout requires flexible user permissions",
        "ignore-check.kube-linter.io/no-read-only-root-fs":
          "Scout requires writable filesystem for the report lake and the retained legacy SQLite file",
      },
    },
  });
  const {
    path,
    imageVersion,
    applicationId,
    s3BucketName,
    selinuxLevel,
    cpuRequest,
    memoryRequest,
  } = match(stage)
    .with("beta", () => {
      return {
        imageVersion: versions["shepherdjerred/scout-for-lol/beta"],
        path: "vaults/v64ocnykdqju4ui6j6pua56xw4/items/rtu44pohnp5ixdp2njuv5f6t2e",
        applicationId: "1311755320745394317",
        s3BucketName: "scout-beta",
        selinuxLevel: zfsVolumeSelinuxLevels.scoutBeta,
        cpuRequest: Cpu.millis(50),
        memoryRequest: Size.gibibytes(2),
      };
    })
    .with("prod", () => {
      return {
        imageVersion: versions["shepherdjerred/scout-for-lol/prod"],
        path: "vaults/v64ocnykdqju4ui6j6pua56xw4/items/pacrc4wfbtct4y3qazkvazop5a",
        applicationId: "1182800769188110366",
        s3BucketName: "scout-prod",
        selinuxLevel: zfsVolumeSelinuxLevels.scoutProd,
        cpuRequest: Cpu.millis(100),
        memoryRequest: Size.mebibytes(2560),
      };
    })
    .exhaustive();

  const onePasswordItem = new OnePasswordItem(chart, "scout-for-lol-1p", {
    spec: {
      itemPath: path,
    },
  });
  const weeklyParlaySecret =
    stage === "beta"
      ? Secret.fromSecretName(
          chart,
          "scout-weekly-parlay-control-secret",
          new OnePasswordItem(chart, "scout-weekly-parlay-control-1p", {
            metadata: { name: "scout-weekly-parlay-control" },
            spec: { itemPath: vaultItemPath("scout-weekly-parlay-control") },
          }).name,
        )
      : undefined;
  // PostgreSQL credentials secret generated by postgres-operator
  // ({username}.{cluster}.credentials...; see resources/postgres/scout-db.ts).
  // DATABASE_URL is composed via K8s $(VAR) substitution, which only sees
  // env vars defined EARLIER in the list — so ...dbEnv must be spread FIRST
  // in baseEnvVariables (same load-bearing ordering as Bugsink).
  const pgSecretRef = Secret.fromSecretName(
    chart,
    "scout-pg-secret-ref",
    `scout.scout-${stage}-postgresql.credentials.postgresql.acid.zalan.do`,
  );
  const dbEnv: Record<string, EnvValue> = scoutImageUsesPostgres(
    imageVersion,
    postgresImageDigests,
  )
    ? {
        DB_USER: EnvValue.fromSecretValue({
          secret: pgSecretRef,
          key: "username",
        }),
        DB_PASSWORD: EnvValue.fromSecretValue({
          secret: pgSecretRef,
          key: "password",
        }),
        DATABASE_URL: EnvValue.fromValue(
          `postgresql://$(DB_USER):$(DB_PASSWORD)@scout-${stage}-postgresql.scout-${stage}.svc.cluster.local:5432/scout`,
        ),
      }
    : {
        // Older production pins remain on SQLite until a PostgreSQL-
        // compatible image is promoted after the beta soak.
        DATABASE_URL: EnvValue.fromValue("file:/data/db.sqlite"),
      };

  const localPathVolume = new ZfsNvmeVolume(chart, "scout-storage-claim", {
    // 24Gi: sized when the SQLite match DB lived here and filled the original
    // 8Gi (2026-05). Still hosts the report lake plus the retained legacy
    // /data/db.sqlite (importer source + rollback path for the Postgres
    // migration); shrink only after the legacy file is deleted post-soak.
    storage: Size.gibibytes(24),
  });

  const baseEnvVariables = {
    ...dbEnv,
    APPLICATION_ID: EnvValue.fromValue(applicationId),
    AWS_ACCESS_KEY_ID: EnvValue.fromSecretValue({
      secret: Secret.fromSecretName(
        chart,
        "aws-access-key-id",
        onePasswordItem.name,
      ),
      key: "AWS_ACCESS_KEY_ID",
    }),
    AWS_SECRET_ACCESS_KEY: EnvValue.fromSecretValue({
      secret: Secret.fromSecretName(
        chart,
        "aws-access-key-secret",
        onePasswordItem.name,
      ),
      key: "AWS_SECRET_ACCESS_KEY",
    }),
    AWS_ENDPOINT_URL: EnvValue.fromValue(
      "http://seaweedfs-s3.seaweedfs.svc.cluster.local:8333",
    ),
    // S3_ENDPOINT mirrors AWS_ENDPOINT_URL for llm-observability + any other
    // tool that reads the SDK-style env var rather than the AWS-CLI one.
    S3_ENDPOINT: EnvValue.fromValue(
      "http://seaweedfs-s3.seaweedfs.svc.cluster.local:8333",
    ),
    S3_FORCE_PATH_STYLE: EnvValue.fromValue("true"),
    AWS_REGION: EnvValue.fromValue("us-east-1"),
    // OpenTelemetry → Tempo. The scout-backend tracing.ts bootstrap gates on
    // TELEMETRY_ENABLED.
    TELEMETRY_ENABLED: EnvValue.fromValue("true"),
    TELEMETRY_SERVICE_NAME: EnvValue.fromValue("scout-backend"),
    OTLP_ENDPOINT: EnvValue.fromValue(
      "http://tempo.tempo.svc.cluster.local:4318",
    ),
    TEMPORAL_ADDRESS: EnvValue.fromValue(
      "temporal-temporal-server-service.temporal.svc.cluster.local:7233",
    ),
    ...llmArchiveEnvVars(),
    DISCORD_TOKEN: EnvValue.fromSecretValue({
      secret: Secret.fromSecretName(
        chart,
        "discord-token-secret",
        onePasswordItem.name,
      ),
      key: "DISCORD_TOKEN",
    }),
    RIOT_API_KEY: EnvValue.fromSecretValue({
      secret: Secret.fromSecretName(
        chart,
        "riot-api-key-secret",
        onePasswordItem.name,
      ),
      key: "RIOT_API_KEY",
    }),
    S3_BUCKET_NAME: EnvValue.fromValue(s3BucketName),
    SENTRY_DSN: EnvValue.fromSecretValue({
      secret: Secret.fromSecretName(
        chart,
        "sentry-dsn-secret",
        onePasswordItem.name,
      ),
      key: "SENTRY_DSN",
    }),
    ENVIRONMENT: EnvValue.fromValue(stage),
    // Bootstrap for the flag client — these cannot come from a flag.
    FEATURE_FLAGS_MODE: EnvValue.fromValue("flipt"),
    FLIPT_ENVIRONMENT: EnvValue.fromValue(stage),
    TEMPORAL_NAMESPACE: EnvValue.fromValue("default"),
    FLIPT_URL: EnvValue.fromValue(
      "http://flipt-flipt-service.flipt.svc.cluster.local:8080",
    ),
    POSTHOG_PROJECT_TOKEN: EnvValue.fromValue(analytics.projectToken),
    POSTHOG_API_HOST: EnvValue.fromValue(analytics.apiHost),
    POSTHOG_SITE_KEY: EnvValue.fromValue(analytics.siteKey),
    POSTHOG_SITE_HOSTNAME: EnvValue.fromValue(analytics.siteHostname),
    // The retained legacy SQLite file: read exactly once by the boot-time
    // importer (scripts/import-legacy-sqlite.ts), never written again, and
    // kept as the rollback path for the Postgres migration.
    LEGACY_SQLITE_PATH: EnvValue.fromValue("/data/db.sqlite"),
    // Parquet "report lake" queried by the DuckDB report engine. Disposable
    // derived data on the same PVC as the legacy DB file; rebuilt from S3 by
    // the report-lake compaction crons.
    REPORT_LAKE_DIR: EnvValue.fromValue("/data/report-lake"),
    JWT_SIGNING_SECRET: EnvValue.fromSecretValue({
      secret: Secret.fromSecretName(
        chart,
        "jwt-signing-secret",
        onePasswordItem.name,
      ),
      key: "JWT_SIGNING_SECRET",
    }),
    DISCORD_CLIENT_SECRET: EnvValue.fromSecretValue({
      secret: Secret.fromSecretName(
        chart,
        "discord-client-secret",
        onePasswordItem.name,
      ),
      key: "DISCORD_CLIENT_SECRET",
    }),
    WEB_APP_ORIGIN: EnvValue.fromValue(
      stage === "prod"
        ? "https://scout-for-lol.com"
        : "https://beta.scout-for-lol.com",
    ),
    LLM_HOURLY_TOKEN_BUDGET: EnvValue.fromValue("2000000"),
    LLM_DAILY_TOKEN_BUDGET: EnvValue.fromValue("20000000"),
    OPENROUTER_API_KEY: EnvValue.fromSecretValue({
      secret: Secret.fromSecretName(
        chart,
        "openrouter-api-key-secret",
        onePasswordItem.name,
      ),
      key: "OPENROUTER_API_KEY",
    }),
  };

  // Beta keeps its operator-managed Explore preview allowlist. Production
  // authorizes signed-in users against the bot's live connected-guild set.
  const envVariables =
    stage === "beta"
      ? {
          ...baseEnvVariables,
          WEEKLY_PARLAY_CONTROL_TOKEN: EnvValue.fromSecretValue({
            secret: requiredWeeklyParlaySecret(weeklyParlaySecret),
            key: "token",
          }),
          // Beta's entire access gate: sign in, and belong to one of these
          // Discord servers. An unset or empty list denies everyone, so this
          // must be present for anyone to reach /app/explore in beta.
          EXPLORE_GUILD_ALLOWLIST: EnvValue.fromValue("1337623164146155593"),
        }
      : baseEnvVariables;

  deployment.addContainer(
    withCommonProps({
      image: `ghcr.io/shepherdjerred/scout-for-lol:${imageVersion}`,
      ports: [
        {
          name: "port-3000",
          number: 3000,
          protocol: Protocol.TCP,
        },
      ],
      securityContext: {
        ensureNonRoot: false,
        readOnlyRootFilesystem: false,
      },
      // Stage-specific request-only baselines cover the observed 30d peaks.
      resources: {
        cpu: {
          request: cpuRequest,
        },
        memory: {
          request: memoryRequest,
        },
      },
      startup: Probe.fromHttpGet("/ping", {
        port: 3000,
        periodSeconds: Duration.seconds(10),
        failureThreshold: 240,
      }),
      liveness: Probe.fromHttpGet("/livez", {
        port: 3000,
        periodSeconds: Duration.seconds(30),
        failureThreshold: 3,
      }),
      readiness: Probe.fromHttpGet("/healthz", {
        port: 3000,
        periodSeconds: Duration.seconds(30),
        failureThreshold: 3,
      }),
      volumeMounts: [
        {
          path: "/data",
          volume: Volume.fromPersistentVolumeClaim(
            chart,
            "scout-volume",
            localPathVolume.claim,
          ),
        },
      ],
      envVariables,
    }),
  );

  applyZfsVolumeSelinuxRelabeling(deployment, selinuxLevel);

  setRevisionHistoryLimit(deployment);

  // Create Service to expose metrics port
  new Service(chart, `scout-service-${stage}`, {
    metadata: {
      name: `scout-service-${stage}`,
      labels: {
        app: "scout",
        stage: stage,
      },
    },
    selector: deployment,
    ports: [{ name: "metrics", port: 3000 }],
  });

  // Create ServiceMonitor for Prometheus to scrape Scout metrics
  createServiceMonitor(chart, {
    name: `scout-${stage}`,
    matchLabels: { app: "scout", stage },
  });
}
