Transform: AWS::Serverless-2016-10-31
Resources:
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "com.shepherdjerred.cashly.web"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
