import { describe, expect, test } from "vitest";
import { ConfigExtensionRequestSchema } from "#src/schemas.ts";
import request from "./fixtures/woodpecker-v3.18.1-config-request.json" with { type: "json" };

/**
 * The request Woodpecker v3.18.1's server actually sends.
 *
 * Generated by marshalling the server's own `model.Repo` and `model.Pipeline`
 * types into its `requestStructure` (server/services/config/http.go), so the
 * field names are the server's, not this package's idea of them. The netrc
 * block is dropped: the extension never reads it.
 *
 * A mismatch here is not a lane quietly misbehaving: the extension answers
 * 400 and every pipeline errors before it is created, as the first live
 * request did when the schema expected `link_url`.
 */
describe("Woodpecker v3.18.1 configuration request", () => {
  test("parses with every field the extension reads", () => {
    const parsed = ConfigExtensionRequestSchema.parse(request);
    expect(parsed.repo).toMatchObject({
      id: 1,
      name: "monorepo",
      default_branch: "main",
    });
    expect(parsed.pipeline).toMatchObject({
      event: "pull_request",
      branch: "main",
      author: "shepherdjerred",
      sender: "shepherdjerred",
      forge_url: "https://github.com/shepherdjerred/monorepo/pull/3121",
      changed_files: ["packages/woodpecker-config-extension/src/app.ts"],
    });
  });

  /** `from_fork` is `omitempty` upstream: absent on same-repository PRs. */
  test("reads an absent from_fork as a same-repository change", () => {
    expect(request.pipeline).not.toHaveProperty("from_fork");
    expect(ConfigExtensionRequestSchema.parse(request).pipeline.from_fork).toBe(
      false,
    );
  });
});
