/**
 * `/stream subtitles`'s track picker: a Discord select menu built from the ranked subtitle
 * candidates for the currently-playing source. Lives outside the command handler so the handler
 * stays discord.js-free (matches `pagination.ts`'s own reason for existing outside both
 * `command-handler.ts` and `command-bot.ts`). Unlike pagination's persistent, self-contained,
 * multi-click re-render collector, this is a one-shot value-returning pick — `awaitMessageComponent`
 * is the right primitive here, not `createMessageComponentCollector`.
 */
import {
  ActionRowBuilder,
  ComponentType,
  StringSelectMenuBuilder,
  type ChatInputCommandInteraction,
  type MessageActionRowComponentBuilder,
} from "discord.js";
import {
  SubtitleTrackRefSchema,
  type SubtitleTrackRef,
} from "@shepherdjerred/streambot/sources/source.ts";
import type { SubtitleCandidate } from "@shepherdjerred/streambot/sources/subtitles.ts";
import { getErrorMessage } from "@shepherdjerred/streambot/util/errors.ts";
import { logger } from "@shepherdjerred/streambot/util/logger.ts";

const log = logger.child("subtitle-menu");

// How long the user has to pick before the menu is abandoned.
const MENU_TIMEOUT_MS = 2 * 60 * 1000;
// Discord's hard cap on select-menu options; one slot is reserved for "Off".
const MAX_MENU_OPTIONS = 25;
const MAX_CANDIDATE_OPTIONS = MAX_MENU_OPTIONS - 1;

const OFF_VALUE = "off";
const CUSTOM_ID = "subtitle_track_pick";

/** Encode a track ref as an opaque Discord select-option value (`<=100` chars, well within it). */
export function encodeTrackRef(ref: SubtitleTrackRef): string {
  switch (ref.kind) {
    case "off":
      return OFF_VALUE;
    case "sidecar":
      return `sidecar:${ref.file}`;
    case "embedded":
      return `embedded:${String(ref.subtitleIndex)}:${ref.codec}`;
    case "ytdlp":
      return `ytdlp:${ref.lang}:${ref.autoGenerated ? "auto" : "manual"}`;
  }
}

/** Inverse of {@link encodeTrackRef}. Validated against the schema so a decoding bug fails loudly. */
export function decodeTrackRef(value: string): SubtitleTrackRef {
  const [kind, ...rest] = value.split(":");
  if (kind === undefined) {
    throw new Error(`invalid subtitle track ref value: ${value}`);
  }
  const built = ((): unknown => {
    switch (kind) {
      case "off":
        return { kind: "off" };
      case "sidecar":
        return { kind: "sidecar", file: rest.join(":") };
      case "embedded": {
        const [indexStr, ...codecParts] = rest;
        return {
          kind: "embedded",
          subtitleIndex: Number(indexStr),
          codec: codecParts.join(":"),
        };
      }
      case "ytdlp": {
        const [lang, autoFlag] = rest;
        return {
          kind: "ytdlp",
          lang: lang ?? "",
          autoGenerated: autoFlag === "auto",
        };
      }
      default:
        throw new Error(`invalid subtitle track ref value: ${value}`);
    }
  })();
  return SubtitleTrackRefSchema.parse(built);
}

function candidateToTrackRef(candidate: SubtitleCandidate): SubtitleTrackRef {
  switch (candidate.kind) {
    case "sidecar":
      return { kind: "sidecar", file: candidate.file };
    case "embedded":
      return {
        kind: "embedded",
        subtitleIndex: candidate.subtitleIndex,
        codec: candidate.codec,
      };
    case "ytdlp":
      return {
        kind: "ytdlp",
        lang: candidate.lang,
        autoGenerated: candidate.autoGenerated,
      };
  }
}

/** A short, human label for a candidate's select-menu entry. */
function labelForCandidate(candidate: SubtitleCandidate): string {
  if (candidate.kind === "ytdlp") {
    const name = candidate.name ?? candidate.lang;
    return candidate.autoGenerated ? `${name} (auto-generated)` : name;
  }
  const lang = candidate.lang ?? "unknown language";
  const modifier =
    candidate.modifier === null ? "" : ` (${candidate.modifier})`;
  const source = candidate.kind === "sidecar" ? "sidecar" : "embedded";
  return `${lang}${modifier} — ${source}`;
}

/**
 * Present a subtitle-track picker built from `candidates` (already ranked best-first by the
 * caller) and resolve with the user's pick as an opaque encoded trackRef string, or `null` on
 * timeout/cancel/any error. Truncates to the best {@link MAX_CANDIDATE_OPTIONS} candidates when
 * there are more, surfacing a "(+N more not shown)" note rather than silently dropping tracks.
 * Assumes the interaction has already been deferred (a menu pick can take up to the timeout).
 */
export async function sendSubtitleMenu(
  interaction: ChatInputCommandInteraction,
  candidates: readonly SubtitleCandidate[],
): Promise<string | null> {
  const shown = candidates.slice(0, MAX_CANDIDATE_OPTIONS);
  const hiddenCount = candidates.length - shown.length;

  const menu = new StringSelectMenuBuilder()
    .setCustomId(CUSTOM_ID)
    .setPlaceholder("Choose a subtitle track")
    .addOptions(
      { label: "Off (no subtitles)", value: OFF_VALUE },
      ...shown.map((candidate) => ({
        label: labelForCandidate(candidate).slice(0, 100),
        value: encodeTrackRef(candidateToTrackRef(candidate)),
      })),
    );
  const row =
    new ActionRowBuilder<MessageActionRowComponentBuilder>().addComponents(
      menu,
    );
  const content =
    hiddenCount > 0
      ? `Choose a subtitle track (+${String(hiddenCount)} more not shown):`
      : "Choose a subtitle track:";

  await interaction.editReply({ content, components: [row] });

  try {
    const message = await interaction.fetchReply();
    const picked = await message.awaitMessageComponent({
      componentType: ComponentType.StringSelect,
      filter: (i) => i.user.id === interaction.user.id,
      time: MENU_TIMEOUT_MS,
    });
    const value = picked.values[0] ?? null;
    await picked.update({ components: [] });
    return value;
  } catch (error) {
    log.debug("subtitle menu timed out or failed", {
      error: getErrorMessage(error),
    });
    await clearSubtitleMenu(interaction);
    return null;
  }
}

async function clearSubtitleMenu(
  interaction: ChatInputCommandInteraction,
): Promise<void> {
  try {
    await interaction.editReply({ components: [] });
  } catch (error) {
    log.warn("clearing subtitle menu failed", {
      error: getErrorMessage(error),
    });
  }
}
