import { recommended } from "../eslint-config/local.ts";

export default [
  ...recommended({
    tsconfigRootDir: import.meta.dirname,
    ignores: [
      "**/generated/**/*",
      "**/dist/**/*",
      "**/build/**/*",
      "**/.cache/**/*",
      "**/node_modules/**/*",
      "**/.astro/**/*",
      "**/*.md",
      "**/*.mdx",
      "**/*.mjs",
      "**/*.js",
      "**/*.cjs",
      ".mastra/",
      "data/",
    ],
    naming: false,
    customRules: {
      zod: true,
      bun: false,
      codeOrganization: false,
      typeSafety: false,
      promiseStyle: false,
    },
  }),
  {
    rules: {
      "no-console": "off",
      "no-restricted-imports": "off",
      "max-depth": ["warn", { max: 6 }],
      "max-lines": [
        "error",
        { max: 800, skipBlankLines: false, skipComments: false },
      ],
      "max-params": ["error", { max: 6 }],
      complexity: ["warn", { max: 30 }],
      "unicorn/prefer-number-properties": "off",
      "unicorn/no-useless-undefined": "warn",
      "unicorn/numeric-separators-style": "warn",
      "unicorn/require-module-specifiers": "off",
      "custom-rules/prefer-zod-validation": "off",
      "unicorn/import-style": "off",
      "unicorn/no-array-sort": "off",
      "unicorn/prefer-export-from": "off",
      "unicorn/text-encoding-identifier-case": "off",
      "@typescript-eslint/no-floating-promises": "warn",
      "@typescript-eslint/no-empty-function": "warn",
      "@typescript-eslint/require-await": "warn",
      "@typescript-eslint/prefer-readonly": "warn",
      "max-lines-per-function": [
        "warn",
        { max: 300, skipBlankLines: true, skipComments: true },
      ],
      "eslint-comments/require-description": "warn",
      "eslint-comments/no-restricted-disable": "warn",
    },
  },
];
