import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 8,
  },
  headerAction: {
    width: 76,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  headerButton: { fontSize: 17 },
  saveButton: { fontWeight: "600" },
  title: { fontSize: 17, fontWeight: "600" },
  content: { padding: 20 },
  error: {
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 10,
    padding: 12,
    marginBottom: 18,
    fontSize: 14,
  },
  section: { marginTop: 20 },
  sectionLabel: {
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  nameInput: {
    minHeight: 48,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 14,
    fontSize: 17,
  },
  choiceRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  iconChoice: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: "center",
    justifyContent: "center",
  },
  tintChoice: { width: 44, height: 44, borderRadius: 22 },
  switchRow: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    marginTop: 24,
  },
  switchCopy: { flex: 1, paddingVertical: 10, marginRight: 12 },
  rowTitle: { fontSize: 17 },
  rowSubtitle: { fontSize: 13, lineHeight: 18, marginTop: 2 },
  groupTitle: { fontSize: 20, fontWeight: "700", marginTop: 28 },
  groupSubtitle: {
    fontSize: 14,
    lineHeight: 19,
    marginTop: 4,
    marginBottom: 18,
  },
  segmentedRow: { flexDirection: "row", gap: 8, marginBottom: 22 },
  segment: {
    flex: 1,
    minHeight: 40,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  segmentText: { fontSize: 14, fontWeight: "600" },
  wrapRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  optionChip: {
    minHeight: 40,
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 20,
    paddingHorizontal: 14,
  },
  optionText: { fontSize: 14, fontWeight: "500" },
});
