import type { Chart } from "cdk8s";
import { Duration, Size } from "cdk8s";
import {
  Cpu,
  Deployment,
  DeploymentStrategy,
  EnvValue,
  Probe,
  Secret,
  Service,
  Volume,
} from "cdk8s-plus-31";
import {
  IntOrString,
  KubeNetworkPolicy,
} from "@shepherdjerred/homelab/cdk8s/generated/imports/k8s.ts";
import { OnePasswordItem } from "@shepherdjerred/homelab/cdk8s/generated/imports/onepassword.com.ts";
import { TailscaleIngress } from "@shepherdjerred/homelab/cdk8s/src/misc/tailscale.ts";
import { createCloudflareTunnelBinding } from "@shepherdjerred/homelab/cdk8s/src/misc/cloudflare-tunnel.ts";
import {
  withCommonProps,
  setRevisionHistoryLimit,
} from "@shepherdjerred/homelab/cdk8s/src/misc/common.ts";
import versions from "@shepherdjerred/homelab/cdk8s/src/versions.ts";

// Build the postgres URL from parts. Composed at runtime from string
// concatenation (not a literal) to avoid false-positive "Password in URL"
// detection by `no-secrets/no-secrets` — the inline `$(DB_USER)` /
// `$(DB_PASSWORD)` placeholders are K8s env-var references, not real
// credentials.
function buildPgUrl(): string {
  const protocol = "postgres";
  const userRef = "$(DB_USER)";
  const passRef = "$(DB_" + "PASSWORD)";
  const host = "bugsink-postgresql:5432";
  const db = "bugsink_db";
  return `${protocol}://${userRef}:${passRef}@${host}/${db}`;
}

export function createBugsinkDeployment(chart: Chart) {
  // Bugsink v2.0.7+ runs as non-root user with UID 14237
  const UID = 14_237;
  const GID = 14_237;

  // 1Password secret containing:
  // - SECRET_KEY: Django secret key (64+ chars, use: openssl rand -base64 64)
  // - postgres-password: PostgreSQL password (generated by postgres-operator, copy from k8s secret)
  // - SMTP_USERNAME: Postal SMTP credential username (create in Postal web UI)
  // - SMTP_PASSWORD: Postal SMTP credential password (create in Postal web UI)
  const bugsinkSecrets = new OnePasswordItem(chart, "bugsink-secrets", {
    spec: {
      itemPath: "vaults/v64ocnykdqju4ui6j6pua56xw4/items/bugsink-credentials",
    },
  });
  const secretRef = Secret.fromSecretName(
    chart,
    "bugsink-secrets-ref",
    bugsinkSecrets.name,
  );

  // PostgreSQL credentials secret generated by postgres-operator. Keys:
  //   - username
  //   - password
  // Naming pattern: {username}.{cluster}.credentials.postgresql.acid.zalan.do
  const postgresSecretName =
    "bugsink.bugsink-postgresql.credentials.postgresql.acid.zalan.do";
  const pgSecretRef = Secret.fromSecretName(
    chart,
    "bugsink-pg-secret-ref",
    postgresSecretName,
  );

  // DATABASE_URL is composed via K8s env-var $(VAR) substitution from the
  // postgres-operator secret. Setting it as a real env var (instead of
  // exporting it inline in `args`) means any process the container runs —
  // bugsink-manage at startup, ad-hoc `kubectl exec` sessions, future
  // sidecars — inherits it for free.
  //
  // Order matters: K8s evaluates `$(VAR)` against env vars defined EARLIER
  // in the container's env list, so DB_USER and DB_PASSWORD must precede
  // DATABASE_URL. Object-literal property order is preserved through
  // spread, so spread `...dbEnv` FIRST in any envVariables block.
  const dbEnv = {
    DB_USER: EnvValue.fromSecretValue({
      secret: pgSecretRef,
      key: "username",
    }),
    DB_PASSWORD: EnvValue.fromSecretValue({
      secret: pgSecretRef,
      key: "password",
    }),
    DATABASE_URL: EnvValue.fromValue(buildPgUrl()),
  };

  const deployment = new Deployment(chart, "bugsink", {
    replicas: 1,
    strategy: DeploymentStrategy.recreate(),
    securityContext: {
      fsGroup: GID,
    },
    metadata: {
      annotations: {
        "ignore-check.kube-linter.io/no-read-only-root-fs":
          "Bugsink requires writable filesystem for Django runtime",
      },
    },
    podMetadata: {
      labels: {
        app: "bugsink",
      },
    },
  });

  // Shared /tmp volume for snappea SQLite database (/tmp/snappea.sqlite3)
  // Both main container and snappea worker need access to this.
  const tmpVolume = Volume.fromEmptyDir(
    chart,
    "bugsink-tmp-volume",
    "bugsink-tmp",
  );

  // Init container to run Django migrations
  deployment.addInitContainer(
    withCommonProps({
      name: "migrate",
      image: `bugsink/bugsink:${versions["bugsink/bugsink"]}`,
      command: ["/bin/sh", "-c"],
      args: ["bugsink-manage migrate --noinput"],
      securityContext: {
        user: UID,
        group: GID,
        ensureNonRoot: true,
        allowPrivilegeEscalation: false,
        readOnlyRootFilesystem: false,
      },
      envVariables: {
        ...dbEnv,
        SECRET_KEY: EnvValue.fromSecretValue({
          secret: secretRef,
          key: "SECRET_KEY",
        }),
        DEBUG: EnvValue.fromValue("False"),
      },
    }),
  );

  // Init container to run snappea database migrations
  // Snappea uses a separate SQLite database at /tmp/snappea.sqlite3 which is ephemeral.
  // We must run these migrations on every startup to recreate the tables.
  deployment.addInitContainer(
    withCommonProps({
      name: "migrate-snappea",
      image: `bugsink/bugsink:${versions["bugsink/bugsink"]}`,
      command: ["/bin/sh", "-c"],
      args: ["bugsink-manage migrate --database=snappea --noinput"],
      securityContext: {
        user: UID,
        group: GID,
        ensureNonRoot: true,
        allowPrivilegeEscalation: false,
        readOnlyRootFilesystem: false,
      },
      envVariables: {
        ...dbEnv,
        SECRET_KEY: EnvValue.fromSecretValue({
          secret: secretRef,
          key: "SECRET_KEY",
        }),
        DEBUG: EnvValue.fromValue("False"),
      },
      volumeMounts: [
        {
          path: "/tmp",
          volume: tmpVolume,
        },
      ],
    }),
  );

  deployment.addContainer(
    withCommonProps({
      name: "bugsink",
      image: `bugsink/bugsink:${versions["bugsink/bugsink"]}`,
      command: ["/bin/sh", "-c"],
      args: ["bugsink-manage runserver 0.0.0.0:8000"],
      ports: [{ name: "http", number: 8000 }],
      envVariables: {
        ...dbEnv,
        // Security configuration
        SECRET_KEY: EnvValue.fromSecretValue({
          secret: secretRef,
          key: "SECRET_KEY",
        }),
        DEBUG: EnvValue.fromValue("False"),
        ALLOWED_HOSTS: EnvValue.fromValue(
          "bugsink.shepherdjerred.com,bugsink.sjer.red,bugsink.tailnet-1a49.ts.net,localhost,127.0.0.1",
        ),

        // URL configuration
        BASE_URL: EnvValue.fromValue("https://bugsink.sjer.red"),

        // Proxy configuration
        BEHIND_HTTPS_PROXY: EnvValue.fromValue("True"),

        // Email configuration via Postal SMTP
        // Add SMTP_USERNAME and SMTP_PASSWORD to bugsink-credentials in 1Password
        EMAIL_HOST: EnvValue.fromValue("postal-postal-smtp-service.postal"),
        EMAIL_PORT: EnvValue.fromValue("25"),
        EMAIL_HOST_USER: EnvValue.fromSecretValue({
          secret: secretRef,
          key: "SMTP_USERNAME",
        }),
        EMAIL_HOST_PASSWORD: EnvValue.fromSecretValue({
          secret: secretRef,
          key: "SMTP_PASSWORD",
        }),
        EMAIL_USE_TLS: EnvValue.fromValue("False"),
        EMAIL_USE_SSL: EnvValue.fromValue("False"),
        DEFAULT_FROM_EMAIL: EnvValue.fromValue("Bugsink <bugsink@sjer.red>"),

        // User registration - disable to prevent race condition vulnerability
        USER_REGISTRATION: EnvValue.fromValue("CB_NOBODY"),
      },
      securityContext: {
        user: UID,
        group: GID,
        ensureNonRoot: true,
        allowPrivilegeEscalation: false,
        readOnlyRootFilesystem: false,
      },
      volumeMounts: [
        {
          path: "/tmp",
          volume: tmpVolume,
        },
      ],
      resources: {
        cpu: {
          request: Cpu.millis(100),
          limit: Cpu.millis(750),
        },
        memory: {
          request: Size.mebibytes(256),
          limit: Size.gibibytes(1),
        },
      },
      liveness: Probe.fromTcpSocket({
        port: 8000,
        initialDelaySeconds: Duration.seconds(10),
        periodSeconds: Duration.seconds(30),
      }),
      readiness: Probe.fromTcpSocket({
        port: 8000,
        initialDelaySeconds: Duration.seconds(5),
        periodSeconds: Duration.seconds(10),
      }),
      startup: Probe.fromTcpSocket({
        port: 8000,
        // Django migrations can be slow - allow up to 5 minutes
        failureThreshold: 30,
        periodSeconds: Duration.seconds(10),
      }),
    }),
  );

  // Snappea worker sidecar - processes background tasks from the queue
  // Required because the Docker image hard-codes TASK_ALWAYS_EAGER=False
  deployment.addContainer(
    withCommonProps({
      name: "snappea-worker",
      image: `bugsink/bugsink:${versions["bugsink/bugsink"]}`,
      command: ["/bin/sh", "-c"],
      args: ["bugsink-manage runsnappea"],
      envVariables: {
        ...dbEnv,
        SECRET_KEY: EnvValue.fromSecretValue({
          secret: secretRef,
          key: "SECRET_KEY",
        }),
        DEBUG: EnvValue.fromValue("False"),
        BASE_URL: EnvValue.fromValue("https://bugsink.sjer.red"),

        // Email configuration for background email tasks
        EMAIL_HOST: EnvValue.fromValue("postal-postal-smtp-service.postal"),
        EMAIL_PORT: EnvValue.fromValue("25"),
        EMAIL_HOST_USER: EnvValue.fromSecretValue({
          secret: secretRef,
          key: "SMTP_USERNAME",
        }),
        EMAIL_HOST_PASSWORD: EnvValue.fromSecretValue({
          secret: secretRef,
          key: "SMTP_PASSWORD",
        }),
        EMAIL_USE_TLS: EnvValue.fromValue("False"),
        EMAIL_USE_SSL: EnvValue.fromValue("False"),
        DEFAULT_FROM_EMAIL: EnvValue.fromValue("Bugsink <bugsink@sjer.red>"),
      },
      securityContext: {
        user: UID,
        group: GID,
        ensureNonRoot: true,
        allowPrivilegeEscalation: false,
        readOnlyRootFilesystem: false,
      },
      volumeMounts: [
        {
          path: "/tmp",
          volume: tmpVolume,
        },
      ],
      resources: {
        cpu: {
          request: Cpu.millis(50),
          limit: Cpu.millis(250),
        },
        memory: {
          request: Size.mebibytes(128),
          limit: Size.mebibytes(512),
        },
      },
    }),
  );

  setRevisionHistoryLimit(deployment);

  const service = new Service(chart, "bugsink-service", {
    selector: deployment,
    metadata: {
      labels: { app: "bugsink" },
    },
    ports: [{ port: 8000, name: "http" }],
  });

  // Network Policy - restrict egress to PostgreSQL and DNS only
  new KubeNetworkPolicy(chart, "bugsink-netpol", {
    metadata: { name: "bugsink-netpol" },
    spec: {
      podSelector: { matchLabels: { app: "bugsink" } },
      policyTypes: ["Egress", "Ingress"],
      ingress: [
        {
          // Allow from Tailscale and Cloudflare Tunnel
          from: [
            // Tailscale operator
            {
              namespaceSelector: {
                matchLabels: {
                  "kubernetes.io/metadata.name": "tailscale",
                },
              },
            },
            // Cloudflare tunnel
            {
              namespaceSelector: {
                matchLabels: {
                  "kubernetes.io/metadata.name": "cloudflare-tunnel",
                },
              },
            },
          ],
          ports: [{ port: IntOrString.fromNumber(8000), protocol: "TCP" }],
        },
      ],
      egress: [
        {
          // Allow DNS
          to: [
            {
              namespaceSelector: {},
              podSelector: {
                matchLabels: {
                  "k8s-app": "kube-dns",
                },
              },
            },
          ],
          ports: [
            { port: IntOrString.fromNumber(53), protocol: "UDP" },
            { port: IntOrString.fromNumber(53), protocol: "TCP" },
          ],
        },
        {
          // Allow PostgreSQL within namespace
          to: [
            {
              podSelector: {
                matchLabels: {
                  cluster_name: "bugsink-postgresql",
                },
              },
            },
          ],
          ports: [{ port: IntOrString.fromNumber(5432), protocol: "TCP" }],
        },
        {
          // Allow Postal SMTP in postal namespace
          to: [
            {
              namespaceSelector: {
                matchLabels: {
                  "kubernetes.io/metadata.name": "postal",
                },
              },
              podSelector: {
                matchLabels: {
                  app: "postal-smtp",
                },
              },
            },
          ],
          ports: [{ port: IntOrString.fromNumber(25), protocol: "TCP" }],
        },
      ],
    },
  });

  new TailscaleIngress(chart, "bugsink-tailscale-ingress", {
    service,
    host: "bugsink",
  });

  // Cloudflare Tunnel for public access
  createCloudflareTunnelBinding(chart, "bugsink-cf-tunnel", {
    serviceName: service.name,
    fqdn: "bugsink.sjer.red",
  });

  return { deployment, service, bugsinkSecrets };
}
