/**
 * Riot API Type Mocks for Testing
 *
 * Provides factory functions for creating mock Riot API objects (RawParticipant, etc.)
 * with all required fields populated with sensible defaults.
 */

import type { RawParticipant, RawChallenges } from "@scout-for-lol/data";

const DEFAULT_PERKS = {
  statPerks: { defense: 0, flex: 0, offense: 0 },
  styles: [
    {
      description: "primaryStyle" as const,
      selections: [
        { perk: 8112, var1: 0, var2: 0, var3: 0 },
        { perk: 8126, var1: 0, var2: 0, var3: 0 },
      ],
      style: 8100,
    },
    {
      description: "subStyle" as const,
      selections: [{ perk: 8210, var1: 0, var2: 0, var3: 0 }],
      style: 8200,
    },
  ],
};

const DEFAULT_MISSIONS = {
  playerScore0: 0,
  playerScore1: 0,
  playerScore2: 0,
  playerScore3: 0,
  playerScore4: 0,
  playerScore5: 0,
  playerScore6: 0,
  playerScore7: 0,
  playerScore8: 0,
  playerScore9: 0,
  playerScore10: 0,
  playerScore11: 0,
};

/**
 * Create a mock RawParticipant with all required fields.
 * Pass overrides for fields your test cares about.
 */
export function makeTestParticipant(
  overrides: Partial<RawParticipant> = {},
): RawParticipant {
  return {
    assists: 1,
    baronKills: 0,
    basicPings: 0,
    champExperience: 0,
    champLevel: 18,
    championId: 1,
    championName: "Lux",
    championTransform: 0,
    allInPings: 0,
    assistMePings: 0,
    commandPings: 0,
    visionClearedPings: 0,
    consumablesPurchased: 0,
    damageDealtToBuildings: 0,
    damageDealtToObjectives: 0,
    damageDealtToTurrets: 0,
    damageSelfMitigated: 0,
    dangerPings: 0,
    deaths: 1,
    detectorWardsPlaced: 0,
    doubleKills: 0,
    dragonKills: 0,
    eligibleForProgression: true,
    enemyMissingPings: 0,
    enemyVisionPings: 0,
    firstBloodAssist: false,
    firstBloodKill: false,
    firstTowerAssist: false,
    firstTowerKill: false,
    gameEndedInEarlySurrender: false,
    gameEndedInSurrender: false,
    getBackPings: 0,
    goldEarned: 0,
    goldSpent: 0,
    holdPings: 0,
    individualPosition: "Invalid",
    inhibitorKills: 0,
    inhibitorTakedowns: 0,
    inhibitorsLost: 0,
    item0: 0,
    item1: 0,
    item2: 0,
    item3: 0,
    item4: 0,
    item5: 0,
    item6: 0,
    itemsPurchased: 0,
    killingSprees: 0,
    kills: 1,
    largestCriticalStrike: 0,
    largestKillingSpree: 0,
    largestMultiKill: 0,
    longestTimeSpentLiving: 0,
    magicDamageDealt: 0,
    magicDamageDealtToChampions: 0,
    magicDamageTaken: 0,
    missions: DEFAULT_MISSIONS,
    needVisionPings: 0,
    neutralMinionsKilled: 0,
    nexusKills: 0,
    nexusLost: 0,
    nexusTakedowns: 0,
    objectivesStolen: 0,
    objectivesStolenAssists: 0,
    onMyWayPings: 0,
    participantId: 1,
    pentaKills: 0,
    perks: DEFAULT_PERKS,
    physicalDamageDealt: 0,
    physicalDamageDealtToChampions: 0,
    physicalDamageTaken: 0,
    profileIcon: 0,
    pushPings: 0,
    puuid: crypto.randomUUID(),
    quadraKills: 0,
    riotIdTagline: "NA1",
    sightWardsBoughtInGame: 0,
    spell1Casts: 0,
    spell2Casts: 0,
    spell3Casts: 0,
    spell4Casts: 0,
    summoner1Casts: 0,
    summoner1Id: 4,
    summoner2Casts: 0,
    summoner2Id: 7,
    summonerId: "test-summoner",
    summonerLevel: 30,
    summonerName: "P",
    teamEarlySurrendered: false,
    teamId: 100,
    teamPosition: "UTILITY",
    timeCCingOthers: 0,
    timePlayed: 1800,
    totalAllyJungleMinionsKilled: 0,
    totalDamageDealt: 0,
    totalDamageDealtToChampions: 0,
    totalDamageShieldedOnTeammates: 0,
    totalDamageTaken: 0,
    totalEnemyJungleMinionsKilled: 0,
    totalHeal: 0,
    totalHealsOnTeammates: 0,
    totalMinionsKilled: 0,
    totalTimeCCDealt: 0,
    totalTimeSpentDead: 0,
    totalUnitsHealed: 0,
    tripleKills: 0,
    trueDamageDealt: 0,
    trueDamageDealtToChampions: 0,
    trueDamageTaken: 0,
    turretKills: 0,
    turretTakedowns: 0,
    turretsLost: 0,
    unrealKills: 0,
    visionScore: 0,
    visionWardsBoughtInGame: 0,
    wardsKilled: 0,
    wardsPlaced: 0,
    win: true,
    riotIdGameName: "P#NA1",
    ...overrides,
  } satisfies RawParticipant;
}

/**
 * Create mock RawChallenges with all required fields.
 */
export function makeTestChallenges(
  overrides: Partial<RawChallenges> = {},
): RawChallenges {
  const result = {
    "12AssistStreakCount": 0,
    abilityUses: 0,
    acesBefore15Minutes: 0,
    alliedJungleMonsterKills: 0,
    baronTakedowns: 0,
    blastConeOppositeOpponentCount: 0,
    bountyGold: 0,
    buffsStolen: 0,
    completeSupportQuestInTime: 0,
    controlWardsPlaced: 0,
    damagePerMinute: 0,
    damageTakenOnTeamPercentage: 0,
    dancedWithRiftHerald: 0,
    deathsByEnemyChamps: 0,
    dodgeSkillShotsSmallWindow: 0,
    doubleAces: 0,
    dragonTakedowns: 0,
    earlyLaningPhaseGoldExpAdvantage: 0,
    effectiveHealAndShielding: 0,
    elderDragonKillsWithOpposingSoul: 0,
    elderDragonMultikills: 0,
    enemyChampionImmobilizations: 0,
    enemyJungleMonsterKills: 0,
    epicMonsterKillsNearEnemyJungler: 0,
    epicMonsterKillsWithin30SecondsOfSpawn: 0,
    epicMonsterSteals: 0,
    epicMonsterStolenWithoutSmite: 0,
    firstTurretKilled: 0,
    fistBumpParticipation: 0,
    flawlessAces: 0,
    fullTeamTakedown: 0,
    gameLength: 0,
    getTakedownsInAllLanesEarlyJungleAsLaner: 0,
    goldPerMinute: 0,
    hadOpenNexus: 0,
    immobilizeAndKillWithAlly: 0,
    initialBuffCount: 0,
    initialCrabCount: 0,
    jungleCsBefore10Minutes: 0,
    junglerTakedownsNearDamagedEpicMonster: 0,
    kTurretsDestroyedBeforePlatesFall: 0,
    kda: 0,
    killAfterHiddenWithAlly: 0,
    killParticipation: 0,
    killedChampTookFullTeamDamageSurvived: 0,
    killingSprees: 0,
    killsNearEnemyTurret: 0,
    killsOnOtherLanesEarlyJungleAsLaner: 0,
    killsOnRecentlyHealedByAramPack: 0,
    killsUnderOwnTurret: 0,
    killsWithHelpFromEpicMonster: 0,
    knockEnemyIntoTeamAndKill: 0,
    landSkillShotsEarlyGame: 0,
    laneMinionsFirst10Minutes: 0,
    laningPhaseGoldExpAdvantage: 0,
    legendaryCount: 0,
    legendaryItemUsed: [],
    lostAnInhibitor: 0,
    maxCsAdvantageOnLaneOpponent: 0,
    maxKillDeficit: 0,
    maxLevelLeadLaneOpponent: 0,
    mejaisFullStackInTime: 0,
    moreEnemyJungleThanOpponent: 0,
    multiKillOneSpell: 0,
    multiTurretRiftHeraldCount: 0,
    multikills: 0,
    multikillsAfterAggressiveFlash: 0,
    outerTurretExecutesBefore10Minutes: 0,
    outnumberedKills: 0,
    outnumberedNexusKill: 0,
    perfectDragonSoulsTaken: 0,
    perfectGame: 0,
    pickKillWithAlly: 0,
    poroExplosions: 0,
    quickCleanse: 0,
    quickFirstTurret: 0,
    quickSoloKills: 0,
    riftHeraldTakedowns: 0,
    saveAllyFromDeath: 0,
    scuttleCrabKills: 0,
    skillshotsDodged: 0,
    skillshotsHit: 0,
    snowballsHit: 0,
    soloBaronKills: 0,
    soloKills: 0,
    stealthWardsPlaced: 0,
    survivedSingleDigitHpCount: 0,
    survivedThreeImmobilizesInFight: 0,
    takedownOnFirstTurret: 0,
    takedowns: 0,
    takedownsAfterGainingLevelAdvantage: 0,
    takedownsBeforeJungleMinionSpawn: 0,
    takedownsFirstXMinutes: 0,
    takedownsInAlcove: 0,
    takedownsInEnemyFountain: 0,
    teamBaronKills: 0,
    teamDamagePercentage: 0,
    teamElderDragonKills: 0,
    teamRiftHeraldKills: 0,
    threeWardsOneSweeperCount: 0,
    tookLargeDamageSurvived: 0,
    turretPlatesTaken: 0,
    turretTakedowns: 0,
    turretsTakenWithRiftHerald: 0,
    twentyMinionsIn3SecondsCount: 0,
    twoWardsOneSweeperCount: 0,
    unseenRecalls: 0,
    visionScoreAdvantageLaneOpponent: 0,
    visionScorePerMinute: 0,
    voidMonsterKill: 0,
    wardTakedowns: 0,
    wardTakedownsBefore20M: 0,
    wardsGuarded: 0,
    ...overrides,
  };
  // eslint-disable-next-line custom-rules/no-type-assertions -- test mock with Partial spread requires assertion
  return result as unknown as RawChallenges;
}
