package com.shepherdjerred.thestorm.rwf.domain.lobby;

import com.shepherdjerred.thestorm.rwf.domain.combatant.TeamColor;
import com.shepherdjerred.thestorm.rwf.domain.geometry.BlockPos;
import com.shepherdjerred.thestorm.rwf.domain.geometry.Cuboid;
import com.shepherdjerred.thestorm.rwf.domain.geometry.Spawn;
import com.shepherdjerred.thestorm.rwf.domain.geometry.Vec3;
import com.shepherdjerred.thestorm.rwf.domain.kit.KitBook;
import com.shepherdjerred.thestorm.rwf.domain.kit.KitSpec;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates the shipped lobby: a roofed 31x9x31 stone room east of every map, with a gold spawn pad
 * in the middle, a red side to the north and a blue side to the south, one lit kit alcove per kit
 * along the east wall, the rules wall to the north, the match board to the south, and a raised
 * watch balcony against the west wall under a window that faces the maps. Pure and deterministic:
 * {@link #generate()} always returns the same blocks, so the committed {@code blocks.schem} can be
 * regenerated byte for byte and its hash checked, and {@link #layout()} names the places {@code
 * lobby.yml} must carry.
 *
 * <p>Blocks are written relative to {@link #ORIGIN}, the region's lowest corner, in a Sponge
 * schematic's {@code (y * length + z) * width + x} order. No block entities: the signs and labels
 * are display entities the plugin spawns.
 */
public final class LobbyBuild {

  public static final int WIDTH = 31;
  public static final int HEIGHT = 9;
  public static final int LENGTH = 31;

  /** The region's lowest corner in the rwf world: east of every map, centred on the maps' z. */
  public static final BlockPos ORIGIN = new BlockPos(128, 64, 16);

  static final String AIR = "minecraft:air";
  static final String WALL = "minecraft:stone_bricks";
  static final String FLOOR = "minecraft:polished_andesite";
  static final String RED = "minecraft:red_concrete";
  static final String BLUE = "minecraft:blue_concrete";
  static final String PAD = "minecraft:gold_block";
  static final String LIGHT = "minecraft:glowstone";
  static final String GLASS = "minecraft:glass";
  static final String FRAME = "minecraft:chiseled_stone_bricks";
  static final String PEDESTAL = "minecraft:quartz_block";
  static final String LAMP = "minecraft:sea_lantern";
  static final String DAIS = "minecraft:smooth_stone";

  /** The palette, in index order; {@code AIR} first so most of the room is index 0. */
  public static final List<String> PALETTE =
      List.of(AIR, WALL, FLOOR, RED, BLUE, PAD, LIGHT, GLASS, FRAME, PEDESTAL, LAMP, DAIS);

  /** The z of each alcove's middle, north to south, one per kit in menu order. */
  static final List<Integer> ALCOVES = List.of(6, 12, 18, 24);

  /** The centre column of the room. */
  static final int MIDDLE = 15;

  /** The balcony: a dais against the west wall whose top is this many blocks above the floor. */
  static final int BALCONY_TOP = 4;

  static final int BALCONY_EAST = 5;
  static final int BALCONY_NORTH = 8;
  static final int BALCONY_SOUTH = 22;

  private LobbyBuild() {}

  /** The lobby's blocks; the same every call. */
  public static Blocks generate() {
    if (ALCOVES.size() != KitBook.MILESTONE_ONE.size()) {
      throw new IllegalStateException("the lobby has one alcove per kit in the kit book");
    }
    var room = new Room();
    room.fill(new Cell(0, 0, 0), new Cell(WIDTH - 1, 0, LENGTH - 1), FLOOR);
    room.fill(new Cell(0, HEIGHT - 1, 0), new Cell(WIDTH - 1, HEIGHT - 1, LENGTH - 1), WALL);
    for (var y = 1; y < HEIGHT - 1; y++) {
      room.fill(new Cell(0, y, 0), new Cell(WIDTH - 1, y, 0), WALL);
      room.fill(new Cell(0, y, LENGTH - 1), new Cell(WIDTH - 1, y, LENGTH - 1), WALL);
      room.fill(new Cell(0, y, 0), new Cell(0, y, LENGTH - 1), WALL);
      room.fill(new Cell(WIDTH - 1, y, 0), new Cell(WIDTH - 1, y, LENGTH - 1), WALL);
    }
    for (var x = 5; x < WIDTH - 1; x += 5) {
      for (var z = 5; z < LENGTH - 1; z += 5) {
        room.set(x, HEIGHT - 1, z, LIGHT);
      }
    }
    // The team sides: a red carpet of concrete to the north, a blue one to the south.
    room.fill(new Cell(8, 0, 2), new Cell(24, 0, 10), RED);
    room.fill(new Cell(8, 0, 20), new Cell(24, 0, 28), BLUE);
    room.fill(new Cell(MIDDLE - 1, 0, MIDDLE - 1), new Cell(MIDDLE + 1, 0, MIDDLE + 1), PAD);
    for (var middle : ALCOVES) {
      alcove(room, middle);
    }
    balcony(room);
    return new Blocks(room.indices);
  }

  /** An alcove against the east wall: framed, lit from behind, with a pedestal for the item. */
  private static void alcove(Room room, int middle) {
    var inner = WIDTH - 3;
    var outer = WIDTH - 2;
    room.fill(new Cell(inner, 1, middle - 2), new Cell(outer, 4, middle - 2), FRAME);
    room.fill(new Cell(inner, 1, middle + 2), new Cell(outer, 4, middle + 2), FRAME);
    room.fill(new Cell(inner, 4, middle - 2), new Cell(outer, 4, middle + 2), FRAME);
    room.fill(new Cell(inner, 0, middle - 1), new Cell(outer, 0, middle + 1), PEDESTAL);
    room.set(outer, 1, middle, PEDESTAL);
    room.set(WIDTH - 1, 3, middle, LAMP);
  }

  /** The raised balcony with three steps up its east face and a glass rim, under the window. */
  private static void balcony(Room room) {
    room.fill(
        new Cell(1, 1, BALCONY_NORTH), new Cell(BALCONY_EAST, BALCONY_TOP, BALCONY_SOUTH), DAIS);
    for (var step = 1; step < BALCONY_TOP; step++) {
      var x = BALCONY_EAST + BALCONY_TOP - step;
      room.fill(new Cell(x, 1, MIDDLE - 1), new Cell(x, step, MIDDLE + 1), DAIS);
    }
    var rim = BALCONY_TOP + 1;
    room.fill(
        new Cell(BALCONY_EAST, rim, BALCONY_NORTH), new Cell(BALCONY_EAST, rim, MIDDLE - 2), GLASS);
    room.fill(
        new Cell(BALCONY_EAST, rim, MIDDLE + 2), new Cell(BALCONY_EAST, rim, BALCONY_SOUTH), GLASS);
    room.fill(new Cell(1, rim, BALCONY_NORTH), new Cell(BALCONY_EAST, rim, BALCONY_NORTH), GLASS);
    room.fill(new Cell(1, rim, BALCONY_SOUTH), new Cell(BALCONY_EAST, rim, BALCONY_SOUTH), GLASS);
    room.fill(
        new Cell(0, rim, BALCONY_NORTH + 1), new Cell(0, HEIGHT - 2, BALCONY_SOUTH - 1), GLASS);
  }

  /**
   * The named places of the generated room, in world coordinates: what {@code lobby.yml} carries.
   * The alcoves show the kit book's kits in menu order, north to south.
   */
  public static LobbyLayout layout() {
    var kits = KitBook.MILESTONE_ONE;
    var alcoves = new ArrayList<LobbyLayout.Alcove>();
    for (var i = 0; i < kits.size(); i++) {
      alcoves.add(alcove(kits.get(i), ALCOVES.get(i)));
    }
    return new LobbyLayout(
        "Waiting Room",
        new Cuboid(ORIGIN, ORIGIN.plus(WIDTH - 1, HEIGHT - 1, LENGTH - 1)),
        spawn(MIDDLE + 0.5, 1, MIDDLE + 0.5, 270),
        List.of(
            new LobbyLayout.Side(TeamColor.RED, spawn(MIDDLE + 0.5, 1, 6.5, 0)),
            new LobbyLayout.Side(TeamColor.BLUE, spawn(MIDDLE + 0.5, 1, 24.5, 180))),
        alcoves,
        spawn(MIDDLE + 0.5, 2.5, 1.5, 0),
        spawn(MIDDLE + 0.5, 2.5, LENGTH - 1.5, 180),
        spawn(3.5, BALCONY_TOP + 1, MIDDLE + 0.5, 90));
  }

  private static LobbyLayout.Alcove alcove(KitSpec kit, int middle) {
    return new LobbyLayout.Alcove(
        kit.id(), point(WIDTH - 1.5, 2.25, middle + 0.5), spawn(WIDTH - 4.5, 1, middle + 0.5, 270));
  }

  private static Vec3 point(double x, double y, double z) {
    return new Vec3(ORIGIN.x() + x, ORIGIN.y() + y, ORIGIN.z() + z);
  }

  private static Spawn spawn(double x, double y, double z, float yaw) {
    return new Spawn(point(x, y, z), yaw, 0);
  }

  /** The generated blocks: one palette index per block of the region. */
  public static final class Blocks {

    private final int[] indices;

    private Blocks(int[] indices) {
      this.indices = indices.clone();
    }

    /** One {@link #PALETTE} index per block, {@code (y * LENGTH + z) * WIDTH + x}; a copy. */
    public int[] indices() {
      return indices.clone();
    }

    /** The block state at relative position {@code x, y, z}. */
    public String at(int x, int y, int z) {
      return PALETTE.get(indices[(y * LENGTH + z) * WIDTH + x]);
    }
  }

  /** A position relative to {@link #ORIGIN}. */
  private record Cell(int x, int y, int z) {}

  private static final class Room {

    private final int[] indices = new int[WIDTH * HEIGHT * LENGTH];

    void set(int x, int y, int z, String block) {
      var index = PALETTE.indexOf(block);
      if (index < 0) {
        throw new IllegalArgumentException(block + " is not in the lobby palette");
      }
      indices[(y * LENGTH + z) * WIDTH + x] = index;
    }

    /** Fills the box between two corners, both included. */
    void fill(Cell from, Cell to, String block) {
      for (var y = from.y(); y <= to.y(); y++) {
        for (var z = from.z(); z <= to.z(); z++) {
          for (var x = from.x(); x <= to.x(); x++) {
            set(x, y, z, block);
          }
        }
      }
    }
  }
}
