import type { ErrorEvent, EventHint } from "@sentry/bun";
import { ZodError } from "zod";
import { isExpectedUpstreamError } from "#src/league/api/upstream-errors.ts";

/**
 * Twisted's two error classes for transient Riot upstream conditions. Both
 * set `name` explicitly on the prototype:
 *
 * - `GenericError` (`name = "GenericError"`) — generic 4xx/5xx from Riot,
 *   the source of the 18,963 502 events seen in the 2026-04-27 audit.
 * - `ServiceUnavailable` (`name = "RiotUnavailable"`) — Riot 503.
 *
 * Matching on `name` rather than `instanceof` avoids importing the
 * implementation classes (twisted is bundled inside the backend's deps,
 * not the data package) and avoids dual-class issues if twisted ever
 * gets versioned in two workspaces.
 *
 * Source: `node_modules/twisted/dist/errors/Generic.error.d.ts` and
 * `service-unavailable.error.d.ts`.
 */
const TWISTED_ERROR_NAMES = new Set(["GenericError", "RiotUnavailable"]);

/**
 * Sample rate for twisted upstream 5xx events. We don't drop all of them
 * because a sustained shift in 502/503/504 patterns is itself a signal
 * (Riot region outage, account-flagged auth, etc). 1% gives roughly
 * 15 events/day at the volumes seen in the 2026-04-27 audit (1,460/day),
 * which is enough to spot a trend change without paging on every one.
 *
 * Tunable via the `SCOUT_RIOT_5XX_SAMPLE_RATE` env var if needed; defaults
 * to 0.01. Set to 0 to drop entirely; set to 1 to disable sampling.
 */
const DEFAULT_RIOT_5XX_SAMPLE_RATE = 0.01;

function getRiot5xxSampleRate(): number {
  const raw = Bun.env["SCOUT_RIOT_5XX_SAMPLE_RATE"];
  if (raw === undefined || raw === "") {
    return DEFAULT_RIOT_5XX_SAMPLE_RATE;
  }
  const parsed = Number.parseFloat(raw);
  if (!Number.isFinite(parsed) || parsed < 0 || parsed > 1) {
    return DEFAULT_RIOT_5XX_SAMPLE_RATE;
  }
  return parsed;
}

/**
 * Substring match against a `ZodError`'s message that identifies the
 * boundary validation for user-supplied Riot IDs. These come from Discord
 * slash command input — when the user types something that doesn't match
 * `<game_name>#<tag_line>`, the command handler responds to them with a
 * friendly error. There is no actionable bug for the operator.
 *
 * The string is the literal `message` argument passed to `.regex(...)` in
 * `RiotIdSchema` (see `packages/data/src/model/league-account.ts`).
 */
const RIOT_ID_FORMAT_MESSAGE =
  "Riot ID must be in the format <game_name>#<tag_line>";

function isTwistedUpstreamError(value: unknown): boolean {
  if (!(value instanceof Error)) {
    return false;
  }
  if (!TWISTED_ERROR_NAMES.has(value.name)) {
    return false;
  }
  // Both classes declare `status: number`. Re-check at runtime so a
  // mis-named error from elsewhere can't slip through.
  if (!("status" in value)) {
    return false;
  }
  const status = value.status;
  return typeof status === "number" && isExpectedUpstreamError(status);
}

/**
 * Sentry `beforeSend` filter that thins noise generated by expected
 * conditions in the Scout backend.
 *
 * Behavior:
 * - twisted's `GenericError` / `ServiceUnavailable` with status 502, 503,
 *   or 504 → **sampled** at the rate from `getRiot5xxSampleRate()`. A
 *   sustained shift in upstream-error volume is itself a signal, so we
 *   keep a small fraction. **Only matches twisted's own error classes** —
 *   a 502 from Discord, Bugsink, OpenAI, or anywhere else is unaffected.
 * - boundary `ZodError`s on user-supplied Riot IDs from Discord slash
 *   commands → **dropped entirely**. The user already gets a friendly
 *   reply, and the schema is fixed; volume here is pure user-input
 *   shape, not a Riot signal. Matched by the literal regex message in
 *   `RiotIdSchema`, so a `ZodError` from any other schema is unaffected.
 *
 * Returning `null` from `beforeSend` discards the event entirely.
 *
 * The `random` parameter is dependency-injected for testability; in
 * production it defaults to `Math.random`.
 */
export function filterScoutSentryEvent(
  event: ErrorEvent,
  hint: EventHint,
  random: () => number = Math.random,
): ErrorEvent | null {
  const original = hint.originalException;

  if (isTwistedUpstreamError(original)) {
    // `random() < sampleRate` gives the desired endpoint semantics:
    // sampleRate=0 always drops, sampleRate=1 always keeps (since
    // `Math.random()` returns [0, 1)). Any value in between samples
    // approximately at that rate.
    const sampleRate = getRiot5xxSampleRate();
    return random() < sampleRate ? event : null;
  }

  if (original instanceof ZodError) {
    const matchesRiotIdRegex = original.issues.some((issue) =>
      issue.message.includes(RIOT_ID_FORMAT_MESSAGE),
    );
    if (matchesRiotIdRegex) {
      return null;
    }
  }

  return event;
}
