import type { ErrorEvent, EventHint } from "@sentry/bun";
import { ZodError } from "zod";
import {
  isExpectedUpstreamError,
  RiotHttpError,
} from "#src/league/api/client/errors.ts";

/**
 * Sample rate for Riot API upstream 5xx events. We don't drop all of them
 * because a sustained shift in 502/503/504 patterns is itself a signal
 * (Riot region outage, account-flagged auth, etc). 1% gives roughly
 * 15 events/day at the volumes seen in the audit (1,460/day),
 * which is enough to spot a trend change without paging on every one.
 *
 * Tunable via the `SCOUT_RIOT_5XX_SAMPLE_RATE` env var if needed; defaults
 * to 0.01. Set to 0 to drop entirely; set to 1 to disable sampling.
 */
const DEFAULT_RIOT_5XX_SAMPLE_RATE = 0.01;

function getRiot5xxSampleRate(): number {
  const raw = Bun.env["SCOUT_RIOT_5XX_SAMPLE_RATE"];
  if (raw === undefined || raw === "") {
    return DEFAULT_RIOT_5XX_SAMPLE_RATE;
  }
  const parsed = Number.parseFloat(raw);
  if (!Number.isFinite(parsed) || parsed < 0 || parsed > 1) {
    return DEFAULT_RIOT_5XX_SAMPLE_RATE;
  }
  return parsed;
}

/**
 * Substring match against a `ZodError`'s message that identifies the
 * boundary validation for user-supplied Riot IDs. These come from Discord
 * slash command input — when the user types something that doesn't match
 * `<game_name>#<tag_line>`, the command handler responds to them with a
 * friendly error. There is no actionable bug for the operator.
 *
 * The string is the literal `message` argument passed to `.regex(...)` in
 * `RiotIdSchema` (see `packages/data/src/model/league-account.ts`).
 */
const RIOT_ID_FORMAT_MESSAGE =
  "Riot ID must be in the format <game_name>#<tag_line>";

function isRiotUpstreamError(value: unknown): boolean {
  return (
    value instanceof RiotHttpError && isExpectedUpstreamError(value.status)
  );
}

/**
 * Sentry `beforeSend` filter that thins noise generated by expected
 * conditions in the Scout backend.
 *
 * Behavior:
 * - Riot API upstream HTTP errors with status 502, 503, 504, 520, 522, 524 →
 *   **sampled** at the rate from `getRiot5xxSampleRate()`. Only matches the
 *   native client's `RiotHttpError`, so other upstream APIs remain visible.
 * - boundary `ZodError`s on user-supplied Riot IDs from Discord slash
 *   commands → **dropped entirely**.
 */
export function filterScoutSentryEvent(
  event: ErrorEvent,
  hint: EventHint,
  random: () => number = Math.random,
): ErrorEvent | null {
  const original = hint.originalException;

  if (isRiotUpstreamError(original)) {
    const sampleRate = getRiot5xxSampleRate();
    return random() < sampleRate ? event : null;
  }

  if (original instanceof ZodError) {
    const matchesRiotIdRegex = original.issues.some((issue) =>
      issue.message.includes(RIOT_ID_FORMAT_MESSAGE),
    );
    if (matchesRiotIdRegex) {
      return null;
    }
  }

  return event;
}
