import type { ErrorEvent, EventHint } from "@sentry/bun";
import { ZodError } from "zod";
import {
  isExpectedUpstreamError,
  RiotHttpError,
} from "#src/league/api/client/errors.ts";
import { LlmBudgetExceeded } from "#src/league/review/openai-budget.ts";

/**
 * Sample rate for Riot API upstream 5xx events. We don't drop all of them
 * because a sustained shift in 502/503/504 patterns is itself a signal
 * (Riot region outage, account-flagged auth, etc). 1% gives roughly
 * 15 events/day at the volumes seen in the audit (1,460/day),
 * which is enough to spot a trend change without paging on every one.
 *
 * Tunable via the `SCOUT_RIOT_5XX_SAMPLE_RATE` env var if needed; defaults
 * to 0.01. Set to 0 to drop entirely; set to 1 to disable sampling.
 */
const DEFAULT_RIOT_5XX_SAMPLE_RATE = 0.01;

function getRiot5xxSampleRate(): number {
  const raw = Bun.env["SCOUT_RIOT_5XX_SAMPLE_RATE"];
  if (raw === undefined || raw === "") {
    return DEFAULT_RIOT_5XX_SAMPLE_RATE;
  }
  const parsed = Number.parseFloat(raw);
  return !Number.isFinite(parsed) || parsed < 0 || parsed > 1
    ? DEFAULT_RIOT_5XX_SAMPLE_RATE
    : parsed;
}

/**
 * Substring match against a `ZodError`'s message that identifies the
 * boundary validation for user-supplied Riot IDs. These come from Discord
 * slash command input — when the user types something that doesn't match
 * `<game_name>#<tag_line>`, the command handler responds to them with a
 * friendly error. There is no actionable bug for the operator.
 *
 * The string is the literal `message` argument passed to `.regex(...)` in
 * `RiotIdSchema` (see `packages/data/src/model/riot/league-account.ts`).
 */
const RIOT_ID_FORMAT_MESSAGE =
  "Riot ID must be in the format <game_name>#<tag_line>";

function isRiotUpstreamError(value: unknown): boolean {
  return (
    value instanceof RiotHttpError && isExpectedUpstreamError(value.status)
  );
}

/**
 * `name` set by `DiscordUpstreamError` (`lib/discord-rest.ts`). Matched by
 * name rather than `instanceof` because that module pulls in the Prisma
 * client, which this startup-loaded filter must not drag in.
 */
const DISCORD_UPSTREAM_ERROR_NAME = "DiscordUpstreamError";

/** Bound for walking an `Error.cause` chain; real chains are 1–3 deep. */
const MAX_CAUSE_DEPTH = 10;

function causedByDiscordUpstream(error: unknown): boolean {
  let current: unknown = error;
  for (let depth = 0; depth < MAX_CAUSE_DEPTH; depth += 1) {
    if (!(current instanceof Error)) {
      return false;
    }
    if (current.name === DISCORD_UPSTREAM_ERROR_NAME) {
      return true;
    }
    current = current.cause;
  }
  return false;
}

/**
 * discord.js gateway handshake failures (`Events.Error` / `Events.ShardError`
 * in `discord/bootstrap.ts`). The handlers still log and the shard handler
 * still flips the gateway state — only the Sentry event is noise.
 */
const DISCORD_GATEWAY_NOISE_SOURCES = new Set([
  "discord-client",
  "discord-shard",
]);
const DISCORD_GATEWAY_NOISE_PATTERN = /^WebSocket connection to .* failed/;

function isDiscordGatewayNoise(event: ErrorEvent, original: unknown): boolean {
  const source = event.tags?.["source"];
  return (
    typeof source === "string" &&
    DISCORD_GATEWAY_NOISE_SOURCES.has(source) &&
    original instanceof Error &&
    DISCORD_GATEWAY_NOISE_PATTERN.test(original.message)
  );
}

/**
 * Sentry `beforeSend` filter that thins noise generated by expected
 * conditions in the Scout backend.
 *
 * Behavior:
 * - Riot API upstream HTTP errors with status 502, 503, 504, 520, 522, 524 →
 *   **sampled** at the rate from `getRiot5xxSampleRate()`. Only matches the
 *   native client's `RiotHttpError`, so other upstream APIs remain visible.
 * - boundary `ZodError`s on user-supplied Riot IDs from Discord slash
 *   commands → **dropped entirely**.
 * - `LlmBudgetExceeded` (the designed token-budget throttle, already counted
 *   in Prometheus) → **dropped entirely**.
 * - errors caused by `DiscordUpstreamError`, including the user-facing
 *   `TRPCError` wrapper ("Couldn't reach Discord") → **dropped entirely**.
 *   The discord-upstream module already counts these per reason.
 * - discord.js gateway handshake failures from the `discord-client` /
 *   `discord-shard` handlers → **dropped entirely**. The handlers still log,
 *   and the shard handler still flips the gateway state.
 */
export function filterScoutSentryEvent(
  event: ErrorEvent,
  hint: EventHint,
  random: () => number = Math.random,
): ErrorEvent | null {
  const original = hint.originalException;

  if (isRiotUpstreamError(original)) {
    const sampleRate = getRiot5xxSampleRate();
    return random() < sampleRate ? event : null;
  }

  if (original instanceof ZodError) {
    const matchesRiotIdRegex = original.issues.some((issue) =>
      issue.message.includes(RIOT_ID_FORMAT_MESSAGE),
    );
    if (matchesRiotIdRegex) {
      return null;
    }
  }

  if (original instanceof LlmBudgetExceeded) {
    return null;
  }

  if (causedByDiscordUpstream(original)) {
    return null;
  }

  return isDiscordGatewayNoise(event, original) ? null : event;
}
